teams:
  enhancements-admins:
    description: Contributors with admin access to k/enhancements
    maintainers:
    - idvoretskyi
    members:
    - calebamiles
    - jdumars
    - justaugustus
    - lachie83
    privacy: closed
  enhancements-maintainers:
    description: Contributors with write access to k/enhancements
    maintainers:
    - idvoretskyi
    members:
    - calebamiles
    - jdumars
    - justaugustus
    - lachie83
    previously:
    - features-maintainers
    privacy: closed
  kep-maintainers:
    description: KEP Process Owners
    members:
    - calebamiles
    - jdumars
    - justaugustus
    - lachie83
    previously:
    - enhancement-maintainers
    privacy: closed
  project-board-maintainers:
    description: Contributors with access to groom issues on org-level project boards.
      Groups can opt-in to assistance with grooming by adding this team to their project
      board with admin permissions.
    maintainers:
    - idvoretskyi
    members:
    - jdumars
    - justaugustus
    - lachie83
    - mattfarina
    privacy: closed
  sig-pm:
    description: Members of SIG PM.
    maintainers:
    - idvoretskyi
    members:
    - calebamiles
    - craiglpeters
    - jdumars
    - justaugustus
    - lachie83
    privacy: closed
