teams:
  cluster-capacity-admins:
    description: Admin access to the cluster-capacity repo
    members:
    - ingvagabund
    privacy: closed
  cluster-capacity-maintainers:
    description: Write access to the cluster-capacity repo
    members:
    - ingvagabund
    privacy: closed
  descheduler-admins:
    description: Admin access to the descheduler repo
    members:
    - aveshagarwal
    - damemi
    - k82cn
    - ravisantoshgudimetla
    privacy: closed
  descheduler-maintainers:
    description: Write access to the descheduler repo
    members:
    - aveshagarwal
    - damemi
    - k82cn
    - ravisantoshgudimetla
    privacy: closed
    previously:
    - descehduler-maintainers
  kube-batch-admins:
    description: Admin access to the kube-batch repo
    members:
    - k82cn
    privacy: closed
  kube-batch-maintainers:
    description: Write access to the kube-batch repo
    members:
    - k82cn
    privacy: closed
  kube-scheduler-simulator-admins:
    description: Admin access to the kube-scheduler-simulator
    members:
    - adtac
    - alculquicondor
    - Huang-Wei
    privacy: closed
  kube-scheduler-simulator-maintainers:
    description: Write access to the kube-scheduler-simulator
    members:
    - adtac
    - sanposhiho
    privacy: closed
  poseidon-admins:
    description: Admin access to the poseidon repo
    members:
    - ahg-g
    - deepak-vij
    - k82cn
    privacy: closed
  poseidon-maintainers:
    description: Write access to the poseidon repo
    members:
    - ahg-g
    - deepak-vij
    - k82cn
    privacy: closed
  scheduler-plugins-admins:
    description: Admin access to the scheduler-plugins repo
    members:
    - ahg-g
    - Huang-Wei
    privacy: closed
  scheduler-plugins-maintainers:
    description: Write access to the scheduler-plugins repo
    members:
    - ahg-g
    - Huang-Wei
    privacy: closed
