name: Kubernetes Retired
description: Kubernetes projects that are no longer actively maintained
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- jasonbraganza
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
