teams:
  cli-experimental-admins:
    description: admin access to cli-experimental
    members:
    - KnVerey
    - Liujingfang1
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  cli-experimental-maintainers:
    description: write access to cli-experimental
    members:
    - liggitt
    - Liujingfang1
    - monopole
    privacy: closed
  cli-utils-admins:
    description: admin access to cli-utils
    members:
    - eddiezane
    - knverey
    - seans3
    - soltysh
    privacy: closed
  cli-utils-maintainers:
    description: write access to cli-utils
    members:
    - karlkfi
    - liggitt
    - Liujingfang1
    - mortent
    privacy: closed
  krew-admins:
    description: admin access to krew
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  krew-maintainers:
    description: write access to krew
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  krew-index-admins:
    description: admin access to krew-index
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  krew-index-maintainers:
    description: write access to krew-index
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  krm-functions-registry-admins:
    description: admin access to krm-functions-registry
    members:
    - jeremyrickard
    - KnVerey
    - mengqiy
    privacy: closed
  krm-functions-registry-maintainers:
    description: write access to krm-functions-registry
    members:
    - jeremyrickard
    - KnVerey
    - mengqiy
    - natasha41575
    privacy: closed
  kui-admins:
    description: admin access to kui
    members:
    - myan9
    - starpit
    privacy: closed
  kui-maintainers:
    description: write access to kui
    members:
    - eddiezane
    - mark-nc
    - myan9
    - pwittrock
    - seans3
    - soltysh
    - starpit
    privacy: closed
  kustomize-admins:
    description: ""
    members:
    - knverey
    - natasha41575
    privacy: closed
  kustomize-maintainers:
    description: ""
    members: [] # there are currently no maintainers besides the owners
    privacy: closed
