teams:
  vsphere-csi-driver-admins:
    description: admin access to vsphere-csi-driver
    members:
    - codenrhoden
    - divyenpatel
    - frapposelli
    privacy: closed
  vsphere-csi-driver-maintainers:
    description: write access to vsphere-csi-driver
    members:
    - codenrhoden
    - divyenpatel
    - frapposelli
    - SandeepPissay
    - xing-yang
    privacy: closed
