teams:
  kops-admins:
    description: Admin access to the kops repo
    members:
    - justinsb
    - mikedanese
    - zmerlynn
    privacy: closed
    repos:
      kops: admin
  kops-maintainers:
    description: Write access to the kops repo
    members:
    - hakman
    - johngmyers
    - justinsb
    - mikedanese
    - olemarkus
    - rifelpet
    - zetaab
    privacy: closed
    repos:
      kops: write
  kubeadm-admins:
    description: Admin access to the kubeadm repo
    members:
    - fabriziopandini
    - neolit123
    - pacoxu
    - SataQiu
    privacy: closed
    repos:
      kubeadm: admin
  kubeadm-maintainers:
    description: Write access to the kubeadm repo
    members:
    - fabriziopandini
    - neolit123
    - pacoxu
    - SataQiu
    privacy: closed
    repos:
      kubeadm: write
  minikube-admins:
    description: Admin access to the minikube repo
    members:
    - afbjorklund
    - medyagh
    - spowelljr
    privacy: closed
    repos:
      minikube: admin
  minikube-maintainers:
    description: Write access to the minikube repo
    members:
    - afbjorklund
    - medyagh
    - prezha
    - spowelljr
    privacy: closed
    repos:
      minikube: write
  sig-cluster-lifecycle:
    description: For discussing SIG Cluster Lifecycle topics
    members:
    - cpanato
    - detiber
    - dixudx
    - fabriziopandini
    - kad
    - luxas
    - neolit123
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - yagonobre
    privacy: closed
  system-validators-admins:
    description: Admin access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
    repos:
      system-validators: admin
  system-validators-maintainers:
    description: Write access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
    repos:
      system-validators: write
  sig-cluster-lifecycle-leads:
    members:
    - CecileRobertMichon
    - fabriziopandini
    - justinsb
    - neolit123
    - vincepri
    privacy: closed
