teams:
  kubeadm-admins:
    description: Admin access to the kubeadm repo
    members:
    - luxas
    - timothysc
    privacy: closed
  kubeadm-maintainers:
    description: Write access to the kubeadm repo
    members:
    - detiber
    - fabriziopandini
    - luxas
    - neolit123
    - rosti
    - timothysc
    privacy: closed
  sig-cluster-lifecycle:
    description: Use only if you can't figure out a better category
    members:
    - chuckha
    - detiber
    - dixudx
    - ereslibre
    - fabriziopandini
    - jbeda
    - kad
    - krousey
    - liztio
    - luxas
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - xiangpengzhao
    - yagonobre
    privacy: closed
  sig-cluster-lifecycle-pr-reviews:
    description: ""
    members:
    - chuckha
    - detiber
    - dixudx
    - ereslibre
    - fabriziopandini
    - jbeda
    - kad
    - krousey
    - liztio
    - luxas
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - xiangpengzhao
    - yagonobre
    - zouyee
    privacy: closed
  system-validators-admins:
    description: Admin access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
  system-validators-maintainers:
    description: Write access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
