teams:
  kops-admins:
    description: Admin access to the kops repo
    members:
    - justinsb
    - mikedanese
    - zmerlynn
    privacy: closed
  kops-maintainers:
    description: Write access to the kops repo
    members:
    - geojaz
    - hakman
    - johngmyers
    - justinsb
    - kashifsaadat
    - mikedanese
    - mikesplain
    - olemarkus
    - rdrgmnzs
    - rifelpet
    - zetaab
    privacy: closed
  kubeadm-admins:
    description: Admin access to the kubeadm repo
    members:
    - luxas
    - timothysc
    privacy: closed
  kubeadm-maintainers:
    description: Write access to the kubeadm repo
    members:
    - detiber
    - fabriziopandini
    - luxas
    - neolit123
    - rosti
    - SataQiu
    - timothysc
    privacy: closed
  minikube-admins:
    description: Admin access to the minikube repo
    members:
    - balopat
    - dlorenc
    - tstromberg
    - vishh
    privacy: closed
  minikube-maintainers:
    description: Write access to the minikube repo
    members:
    - afbjorklund
    - balopat
    - ethernetdan
    - jimmidyson
    - sharifelgamal
    - tstromberg
    privacy: closed
  sig-cluster-lifecycle:
    description: For discussing SIG Cluster Lifecycle topics
    members:
    - cpanato
    - detiber
    - dixudx
    - ereslibre
    - fabriziopandini
    - kad
    - luxas
    - neolit123
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - yagonobre
    privacy: closed
  system-validators-admins:
    description: Admin access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
  system-validators-maintainers:
    description: Write access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
