teams:
  sig-cli-leads:
    description: ""
    members:
    - eddiezane
    - KnVerey
    - seans3
    - soltysh
    privacy: closed
  sig-cli-kubectl-maintainers:
    description: ""
    members:
    - brianpursley
    - eddiezane
    - KnVerey
    - seans3
    - soltysh
    privacy: closed
