teams:
  publishing-bot-admins:
    description: Admin access to publishing repositories
    maintainers:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - nikhita
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
  publishing-bot-maintainers:
    description: Write access to publishing repositories
    maintainers:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - nikhita
    - puerco
    - saschagrunert
    - sttts
    members:
    - palnabarun
    - Verolop
    - xmudrii
    privacy: closed
