teams:
  custom-metrics-apiserver-admins:
    description: Admin access to the custom-metrics-apiserver repo
    members:
    - dashpole
    - dgrisonnet
    - pohly
    - RainbowMango
    - rexagod
    - richabanker
    privacy: closed
    repos:
      custom-metrics-apiserver: admin
  custom-metrics-apiserver-maintainers:
    description: Write access to the custom-metrics-apiserver repo
    members:
    - dashpole
    - dgrisonnet
    - pohly
    - RainbowMango
    - rexagod
    - richabanker
    privacy: closed
    repos:
      custom-metrics-apiserver: write
  instrumentation-admins:
    description: Admin access to the instrumentation repo
    members:
    - dashpole
    - dgrisonnet
    - pohly
    - rexagod
    - richabanker
    privacy: closed
    repos:
      instrumentation: admin
  instrumentation-tools-admins:
    description: Admin access to the instrumentation-tools repo
    members:
    - dashpole
    - dgrisonnet
    - pohly
    - rexagod
    - richabanker
    privacy: closed
    repos:
      instrumentation-tools: admin
  instrumentation-tools-maintainers:
    description: Write access to the instrumentation-tools repo
    members:
    - dashpole
    - dgrisonnet
    - pohly
    - rexagod
    - richabanker
    privacy: closed
    repos:
      instrumentation-tools: write
  logtools-admins:
    description: Admin access to the logtools repo
    members:
      - pohly
      - rexagod
      - serathius
    privacy: closed
    repos:
      logtools: admin
  logtools-maintainers:
    description: Write access to the logtools repo
    members:
      - pohly
      - rexagod
      - serathius
    privacy: closed
    repos:
      logtools: write
  metrics-server-admins:
    description: Admin access to the metrics-server repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
    repos:
      metrics-server: admin
  metrics-server-maintainers:
    description: Write access to the metrics-server repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
    repos:
      metrics-server: write
  prometheus-adapter-admins:
    description: Admin access to the prometheus-adapter repo
    members:
    - dgrisonnet
    privacy: closed
    repos:
      prometheus-adapter: admin
  prometheus-adapter-maintainers:
    description: Write access to the prometheus-adapter repo
    members:
    - dgrisonnet
    privacy: closed
    repos:
      prometheus-adapter: write
  resource-state-metrics-admins:
    description: Admin access to the resource-state-metrics repo
    members:
    - dgrisonnet
    - mrueg
    - rexagod
    privacy: closed
    repos:
      resource-state-metrics: admin
  resource-state-metrics-maintainers:
    description: Write access to the resource-state-metrics repo
    members:
    - dgrisonnet
    - mrueg
    - rexagod
    privacy: closed
    repos:
      resource-state-metrics: write
  usage-metrics-collector-admins:
    description: Admin access to the usage-metrics-collector repo
    members:
    - ehashman
    - ndipebot
    - pwittrock
    privacy: closed
    repos:
      usage-metrics-collector: admin
  usage-metrics-collector-maintainers:
    description: Write access to the usage-metrics-collector repo
    members:
    - ehashman
    - ndipebot
    - pwittrock
    privacy: closed
    repos:
      usage-metrics-collector: write
