teams:
  custom-metrics-apiserver-admins:
    description: Admin access to the custom-metrics-apiserver repo
    members:
    - brancz
    - piosz
    privacy: closed
  custom-metrics-apiserver-maintainers:
    description: Write access to the custom-metrics-apiserver repo
    members:
    - dgrisonnet
    - s-urbaniak
    - serathius
    privacy: closed
  instrumentation-tools-admins:
    description: Admin access to the instrumentation-tools repo
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    privacy: closed
  instrumentation-tools-maintainers:
    description: Write access to the instrumentation-tools repo
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    privacy: closed
  metrics-server-admins:
    description: Admin access to the metrics-server repo
    members:
    - brancz
    - piosz
    privacy: closed
  metrics-server-maintainers:
    description: Write access to the metrics-server repo
    members:
    - s-urbaniak
    - serathius
    privacy: closed
  prometheus-adapter-admins:
    description: Admin access to the prometheus-adapter repo
    members:
    - brancz
    - DirectXMan12
    - s-urbaniak
    privacy: closed
  prometheus-adapter-maintainers:
    description: Write access to the prometheus-adapter repo
    members:
    - dgrisonnet
    - s-urbaniak
    privacy: closed
