teams:
  execution-hook-admins:
    description: Admin access to execution-hook repo
    members:
    - kow3ns
    privacy: closed
    repos:
      execution-hook: admin
  execution-hook-maintainers:
    description: Write access to execution-hook repo
    members:
    - jingxu97
    - kow3ns
    - xing-yang
    privacy: closed
    repos:
      execution-hook: write
  jobset-admins:
    description: Admin access to jobset repo
    members:
    - ahg-g
    - danielvegamyhre
    privacy: closed
    repos:
      jobset: admin
  jobset-maintainers:
    description: Write access to jobset repo
    members:
    - ahg-g
    privacy: closed
    repos:
      jobset: write
  kjob-admins:
    description: Admin access to kjob repo
    members:
    - mimowo
    - mwielgus
    privacy: closed
    repos:
      kjob: admin
  kjob-maintainers:
    description: Write access to kjob repo
    members:
    - mimowo
    - mwielgus
    privacy: closed
    repos:
      kjob: write
  lws-admins:
    description: Admin access to lws repo
    members:
    - ahg-g
    - edwinhr716
    privacy: closed
    repos:
      lws: admin
  lws-maintainers:
    description: Write access to lws repo
    members:
    - ahg-g
    - liurupeng
    privacy: closed
    repos:
      lws: write
