teams:
  cel-admission-webhook-admins:
    description: admin access to cel-admission-webhook
    members:
    - cici37
    - jpbetz
    privacy: closed
    repos:
      cel-admission-webhook: admin
  cel-admission-webhook-maintainers:
    description: write access to cel-admission-webhook
    members:
    - cici37
    - jpbetz
    privacy: closed
    repos:
      cel-admission-webhook: write
  sig-api-machinery-api-reviews:
    description: ""
    members:
    - liggitt
    privacy: closed
  sig-api-machinery-bugs:
    description: ""
    members:
    - jpbetz
    privacy: closed
  sig-api-machinery-feature-requests:
    description: ""
    members:
    - jpbetz
    - liggitt
    privacy: closed
  sig-api-machinery-emeritus:
    description: Emeritus members of sig-api-machinery
    members:
    - derekwaynecarr
    privacy: closed
  sig-api-machinery-members:
    description: Members of sig-api-machinery
    maintainers:
    - MadhavJivrajani
    members:
    - alexzielenski
    - andrewsykim
    - aojea
    - apelisse
    - aramase
    - cici37
    - deads2k
    - enj
    - fedebongio
    - Jefftree
    - jpbetz
    - kwiesmueller
    - liggitt
    - munnerz
    - seans3
    - smarterclayton
    - soltysh
    - sttts
    - sxllwx
    - tallclair
    - thockin
    - tkashem
    - yliaog
    - yue9944882
    privacy: closed
  sig-api-machinery-misc:
    description: Use only if you can't figure out a better category
    members:
    - deads2k
    - derekwaynecarr
    - enj
    - jpbetz
    - liggitt
    - smarterclayton
    - soltysh
    - sttts
    - yue9944882
    privacy: closed
  sig-api-machinery-pr-reviews:
    description: ""
    maintainers:
    - MadhavJivrajani
    members:
    - deads2k
    - jpbetz
    - liggitt
    - smarterclayton
    - sttts
    privacy: closed
  sig-api-machinery-proposals:
    description: ""
    members:
    - jpbetz
    - liggitt
    privacy: closed
  sig-api-machinery-test-failures:
    description: ""
    members:
    - jpbetz
    privacy: closed
  sig-api-machinery-leads:
    description: ""
    members:
    - deads2k
    - fedebongio
    - jpbetz
    - sttts
    privacy: closed
