teams:
  cloud-provider-openstack-admins:
    description: Admin access to cloud-provider-openstack repo
    members:
    - adisky
    - chrigl
    - dims
    - lingxiankong
    - ramineni
    privacy: closed
  cloud-provider-openstack-maintainers:
    description: Write access to the cloud-provider-openstack repo
    members:
    - adisky
    - chrigl
    - dims
    - lingxiankong
    - ramineni
    privacy: closed
  cloud-provider-openstack-members:
    description: ""
    members:
    - adisky
    - chrigl
    - dims
    - lingxiankong
    - ramineni
    privacy: closed
  provider-openstack-api-reviews:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-api-reviews
  provider-openstack-bugs:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-bugs
  provider-openstack-feature-requests:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-feature-requests
  provider-openstack-misc:
    description: OpenStack Special Interest Group
    members:
    - adisky
    - anguslees
    - chrigl
    - codevulture
    - dims
    - feiskyer
    - flaper87
    - grahamhayes
    - harlowja
    - hongbin
    - kragniz
    - lingxiankong
    - NickrenREN
    - pigmej
    - ramineni
    - rootfs
    - russellb
    - stevemcquaid
    - xsgordon
    privacy: closed
    previously:
    - sig-openstack-misc
  provider-openstack-pr-reviews:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-pr-reviews
  provider-openstack-proposals:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-proposals
  provider-openstack-test-failures:
    description: ""
    members:
    - adisky
    - chrigl
    - lingxiankong
    - ramineni
    privacy: closed
    previously:
    - sig-openstack-test-failures
