teams:
  sig-docs-blog-owners:
    description: Approvers for blog content
    maintainers:
    - mrbobbytables
    members:
    - nate-double-u
    - onlydole
    - sftim
    - jefftrojan
    privacy: closed
  sig-docs-de-owners:
    description: Approvers for German content
    members:
    - bene2k1
    - rlenferink
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    - rlenferink
    privacy: closed
  sig-docs-en-owners:
    description: Approvers for English content
    members:
    - bradtopol
    - dipesh-rawat  
    - divya-mohan0209
    - katcosgrove
    - kbhawkey
    - mickeyboxell
    - natalisucks
    - nate-double-u
    - onlydole
    - reylejano
    - sftim
    - tengqm
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - bradtopol
    - dipesh-rawat
    - divya-mohan0209
    - kbhawkey
    - mehabhalodiya
    - mengjiao-liu
    - natalisucks
    - nate-double-u
    - onlydole
    - reylejano
    - sftim
    - shannonxtreme
    - tengqm
    - windsonsea
    privacy: closed
  sig-docs-es-owners:
    description: Approvers for Spanish content
    members:
    - electrocucaracha
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - 92nqb
    - electrocucaracha
    - krol3
    - raelga
    - ramrodo
    privacy: closed
  sig-docs-fr-owners:
    description: Approvers for French content
    members:
    - feloy
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - feloy
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-hi-owners:
    description: Approvers for Hindi content
    members:
    - dipesh-rawat
    - divya-mohan0209
    privacy: closed
  sig-docs-hi-reviews:
    description: PR reviews for Hindi content
    members:
    - Babapool
    - bishal7679
    - dipesh-rawat    
    - divya-mohan0209
    privacy: closed
  sig-docs-id-owners:
    description: Approvers for Indonesian content
    members:
    - ariscahyadi
    - girikuncoro
    - habibrosyad
    privacy: closed
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - ariscahyadi
    - girikuncoro
    - habibrosyad
    privacy: closed
  sig-docs-it-owners:
    description: Approvers for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    privacy: closed
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    privacy: closed
  sig-docs-ja-owners:
    description: Approvers for Japanese content
    members:
    - bells17
    - inductor
    - nasa9084
    - Okabe-Junya
    privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - atoato88
    - bells17
    - inductor
    - kakts
    - nasa9084
    - Okabe-Junya
    - t-inu
    privacy: closed
  sig-docs-ko-owners:
    description: Approvers for Korean content
    members:
    - gochist
    - jihoon-seo
    - seokho-son
    - ysyukr
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - gochist
    - jihoon-seo
    - jmyung
    - jongwooo
    - seokho-son
    - ysyukr
    privacy: closed
  sig-docs-leads:
    description: Chairs and tech leads for SIG Docs
    members:
    - divya-mohan0209
    - kbhawkey
    - natalisucks
    - onlydole
    - reylejano
    - sftim
    - tengqm
    privacy: closed
  sig-docs-pl-owners:
    description: Approvers for Polish content
    members:
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-pl-reviews:
    description: Reviews for Polish docs PRs
    members:
    - kpucynski
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-ru-owners:
    description: Approvers for Russian content
    members:
    - Arhell
    - kirkonru
    - shurup
    privacy: closed
  sig-docs-ru-reviews:
    description: Reviews for Russian docs PRs
    members:
    - Arhell
    - kirkonru
    - shurup
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - bradtopol
    - divya-mohan0209
    - gochist
    - kbhawkey
    - natalisucks
    - reylejano
    - tengqm
    privacy: closed
  sig-docs-pt-owners:
    description: Approvers for Portuguese content
    members:
    - devlware
    - edsoncelio
    - femrtnz
    - jcjesus
    - jhonmike
    - stormqueen1990
    - yagonobre
    privacy: closed
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - devlware
    - edsoncelio
    - femrtnz
    - jcjesus
    - jhonmike
    - stormqueen1990
    - yagonobre
    privacy: closed
  sig-docs-zh-owners:
    description: Approvers for Chinese content
    members:
    - chenrui333
    - howieyuen
    - mengjiao-liu
    - my-git9
    - SataQiu
    - Sea-n
    - tanjunchen
    - tengqm
    - windsonsea
    - xichengliudui
    - ydFu
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content
    members:
    - asa3311
    - chenrui333
    - howieyuen
    - kinzhi
    - mengjiao-liu
    - my-git9
    - SataQiu
    - Sea-n
    - tanjunchen
    - tengqm
    - windsonsea
    - xichengliudui
    - ydFu
    privacy: closed
  sig-docs-vi-owners:
    description: Admins for Vietnamese content
    members:
    - huynguyennovem
    - truongnh1992
    privacy: closed
  sig-docs-vi-reviews:
    description: PR reviews for Vietnamese content
    members:
    - huynguyennovem
    - truongnh1992
    privacy: closed
  sig-docs-uk-owners:
    description: Approvers for Ukrainian content
    members:
    - Arhell
    - MaxymVlasov
    privacy: closed
  sig-docs-uk-reviews:
    description: PR reviews for Ukrainian content
    members:
    - Arhell
    - idvoretskyi
    - MaxymVlasov
    privacy: closed
  website-admins:
    description: Admin access to the website repo
    previously:
    - kubernetes-website-admins
    members:
    - divya-mohan0209
    - natalisucks
    - reylejano
    privacy: closed
    repos:
      website: admin
  website-maintainers:
    description: Write access to the website repo
    members:
    - a-mccarthy # Localization subproject owner
    - bells17 # L10n: Japanese
    - bradtopol # L10n: English
    - devlware # L10: Portuguese
    - divya-mohan0209 # L10n: English
    - drewhagen # 1.31 RT Docs Lead temporary access for the release
    - femrtnz # L10n: Portuguese
    - girikuncoro # L10n: Indonesian
    - gochist # L10n: Korean
    - huynguyennovem # L10n: Vietnamese # L10n: Korean
    - inductor # L10n: Japanese
    - jcjesus # L10n: Portuguese
    - jhonmike # L10n: Portuguese
    - katcosgrove # 1.29 RT Docs Lead
    - mfilocha # L10n: Polish
    - mickeyboxell # 1.27 RT Docs lead
    - nasa9084 # L10n: Japanese
    - natalisucks # L10n: English
    - nate-double-u # L10n: English
    - nvtkaszpir # L10n: Polish
    - Okabe-Junya #L10n: Japanese
    - onlydole # L10n: English
    - raelga # L10n: Spanish
    - remyleone # L10n: French
    - reylejano # L10n: English
    - rlenferink # L10n: German
    - SataQiu # L10n: Chinese
    - seokho-son # L10n: Korean
    - sftim # L10n: English
    - shurup # L10n: Russian
    - tengqm # L10n: Chinese
    - truongnh1992 # L10n: Vietnamese
    - xichengliudui # L10n: Chinese
    - yagonobre # L10n: Portuguese
    privacy: closed
    repos:
      website: write
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo
    members:
    - a-mccarthy
    - bene2k1
    - bradtopol
    - divya-mohan0209
    - drewhagen # 1.31 RT Docs Lead temporary access for the release
    - femrtnz
    - girikuncoro
    - gochist
    - huynguyennovem
    - inductor
    - jcjesus
    - mickeyboxell
    - nasa9084
    - natalisucks
    - nate-double-u
    - onlydole
    - perriea
    - Princesso # 1.31 Docs Lead
    - raelga
    - rekcah78
    - remyleone
    - reylejano
    - rlenferink
    - SataQiu
    - seokho-son
    - sftim
    - shurup
    - tanjunchen
    - tengqm
    - truongnh1992
    - xichengliudui
    - ysyukr
    privacy: closed
