teams:
  kubernetes-blog:
    description: Admins for the Kubernetes blog
    members:
    - kbarnard10
    - natekartchner
    - sarahkconway
    privacy: closed
  sig-docs-de-owners: 
    description: Admins for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-en-owners: 
    description: Admins for English content
    members:
    - bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - Bradamant3
    - jaredbhatti
    - jimangel
    - Rajakavitha1
    - stewart-yu
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-es-owners:
    description: Admins for Spanish content
    members:
    - alexbrand
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - alexbrand
    - electrocucaracha
    - glo-pena
    - raelga
    privacy: closed
  sig-docs-fr-owners:
    description: Admins for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-id-owners:
    description: Admins for Indonesian content
    members:
    - girikuncoro
    - irvifa
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - girikuncoro
    - irvifa
    privacy: closed
  sig-docs-it-owners:
    description: Admins for Italian content
    members:
    - micheleberardi
    - rlenferink
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - micheleberardi
    - rlenferink
    privacy: closed
  sig-docs-ja-owners:
     description: Admins for Japanese content
     members:
     - cstoku
     - makocchi-git
     - MasayaAoyama
     - nasa9084
     - tnir
     privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - cstoku
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - tnir
    privacy: closed
  sig-docs-ko-owners:
    description: Admins for Korean content
    members:
    - claudiajkang
    - gochist
    - ianychoi
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - ClaudiaJKang
    - gochist
    - ianychoi
    privacy: closed
  sig-docs-l10n-admins:
    description: Admins for localization projects
    members:
    - alexbrand # Spanish
    - bradamant3 # English
    - ClaudiaJKang # Korean
    - cstoku # Japanese
    - femrtnz # Portuguese
    - girikuncoro # Indonesian
    - gochist # Korean
    - hanjiayao # Chinese
    - irvifa # Indonesian
    - jaredbhatti # English 
    - jcjesus # Portuguese
    - markthink # Chinese
    - micheleberardi # Italian
    - raelga # Spanish
    - remyleone # French
    - rlenferink # Italian
    - tnir # Japanese
    - zacharysarah # English
    - zhangxiaoyu-zidif # Chinese
    privacy: closed
  sig-docs-maintainers:
    description: Website maintainers 
    members:
    - bradamant3
    - chenopis
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - pwittrock
    - steveperry-53
    - tengqm
    - zacharysarah
    - zparnold
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-pt-owners:
    description: Admins for Portuguese content
    members:
    - femrtnz
    - jcjesus
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - femrtnz
    - jcjesus
    privacy: closed
  sig-docs-zh-owners:
    description: Admins for Chinese content
    members:
    - hanjiayao
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content 
    members:
    - chenrui333
    - idealhack
    - pigletfly
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo.
    members:
    - abuisine
    - alexbrand
    - awkif
    - bene2k1
    - bradamant3    
    - bradtopol
    - chenopis
    - claudiajkang
    - cody-clark
    - cstoku
    - femrtnz
    - girikuncoro
    - gochist
    - hanjiayao
    - irvifa
    - jaredbhatti
    - jcjesus
    - jimangel
    - jygastaud
    - kbarnard10
    - lledru
    - micheleberardi
    - mistyhacks
    - nasa9084
    - oussemos
    - perriea
    - raelga
    - rajakavitha1
    - rbenzair
    - rekcah78
    - remyleone
    - rlenferink
    - ryanmcginnis
    - smana
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - tnir
    - xiangpengzhao
    - yastij
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
