teams:
  sig-docs-blog-owners:
    description: Approvers for blog content
    maintainers:
    - mrbobbytables
    members:
    - nate-double-u
    - onlydole
    - sftim
    privacy: closed
  sig-docs-de-owners:
    description: Approvers for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-en-owners:
    description: Approvers for English content
    members:
    - annajung
    - bradtopol
    - divya-mohan0209
    - jimangel
    - kbhawkey
    - krol3
    - natalisucks
    - nate-double-u
    - onlydole
    - reylejano
    - sftim
    - tengqm
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - bradtopol
    - divya-mohan0209
    - jimangel
    - kbhawkey
    - mehabhalodiya
    - natalisucks
    - nate-double-u
    - onlydole
    - reylejano
    - sftim
    - shannonxtreme
    - tengqm
    privacy: closed
  sig-docs-es-owners:
    description: Approvers for Spanish content
    members:
    - electrocucaracha
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - 92nqb
    - electrocucaracha
    - krol3
    - raelga
    - ramrodo
    privacy: closed
  sig-docs-fr-owners:
    description: Approvers for French content
    members:
    - awkif
    - feloy
    - oussemos
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - awkif
    - feloy
    - oussemos
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-hi-owners:
    description: Approvers for Hindi content
    members:
    - anubha-v-ardhan
    - divya-mohan0209
    privacy: closed
  sig-docs-hi-reviews:
    description: PR reviews for Hindi content
    members:
    - anubha-v-ardhan
    - Babapool
    - bishal7679
    - divya-mohan0209
    - Garima-Negi
    - verma-kunal
    privacy: closed
  sig-docs-id-owners:
    description: Approvers for Indonesian content
    members:
    - ariscahyadi
    - danninov
    - girikuncoro
    - habibrosyad
    privacy: closed
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - ariscahyadi
    - danninov
    - girikuncoro
    - habibrosyad
    privacy: closed
  sig-docs-it-owners:
    description: Approvers for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    - micheleberardi
    privacy: closed
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    - micheleberardi
    privacy: closed
  sig-docs-ja-owners:
    description: Approvers for Japanese content
    members:
    - inductor
    - nasa9084
    privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - atoato88
    - bells17
    - inductor
    - kakts
    - nasa9084
    - ptux
    - t-inu
    privacy: closed
  sig-docs-ko-owners:
    description: Approvers for Korean content
    members:
    - gochist
    - ianychoi
    - jihoon-seo
    - seokho-son
    - yoonian
    - ysyukr
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - gochist
    - ianychoi
    - jihoon-seo
    - jmyung
    - seokho-son
    - yoonian
    - ysyukr
    privacy: closed
  sig-docs-leads:
    description: Chairs and tech leads for SIG Docs
    members:
    - divya-mohan0209
    - jimangel
    - kbhawkey
    - natalisucks
    - onlydole
    - reylejano
    - sftim
    - tengqm
    privacy: closed
  sig-docs-pl-owners:
    description: Approvers for Polish content
    members:
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-pl-reviews:
    description: Reviews for Polish docs PRs
    members:
    - kpucynski
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-ru-owners:
    description: Approvers for Russian content
    members:
    - Arhell
    - shurup
    privacy: closed
  sig-docs-ru-reviews:
    description: Reviews for Russian docs PRs
    members:
    - Arhell
    - shurup
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - bradtopol
    - cody-clark
    - gochist
    - jimangel
    - kbhawkey
    - Rajakavitha1
    - stewart-yu
    - tengqm
    - tfogo
    - zparnold
    privacy: closed
  sig-docs-pt-owners:
    description: Approvers for Portuguese content
    members:
    - devlware
    - edsoncelio
    - femrtnz
    - jcjesus
    - jhonmike
    - rikatz
    - stormqueen1990
    - yagonobre
    privacy: closed
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - devlware
    - edsoncelio
    - femrtnz
    - jcjesus
    - jhonmike
    - rikatz
    - stormqueen1990
    - yagonobre
    privacy: closed
  sig-docs-zh-owners:
    description: Approvers for Chinese content
    members:
    - chenrui333
    - howieyuen
    - mengjiao-liu
    - SataQiu
    - Sea-n
    - tanjunchen
    - tengqm
    - xichengliudui
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content
    members:
    - chenrui333
    - chenxuc
    - howieyuen
    - mengjiao-liu
    - my-git9
    - SataQiu
    - Sea-n
    - tanjunchen
    - tengqm
    - windsonsea
    - xichengliudui
    - ydFu
    privacy: closed
  sig-docs-vi-owners:
    description: Admins for Vietnamese content
    members:
    - huynguyennovem
    - truongnh1992
    privacy: closed
  sig-docs-vi-reviews:
    description: PR reviews for Vietnamese content
    members:
    - huynguyennovem
    - truongnh1992
    privacy: closed
  sig-docs-uk-owners:
    description: Approvers for Ukrainian content
    members:
    - Arhell
    - MaxymVlasov
    privacy: closed
  sig-docs-uk-reviews:
    description: PR reviews for Ukrainian content
    maintainers:
    - idvoretskyi
    members:
    - Arhell
    - MaxymVlasov
    - Potapy4
    privacy: closed
  website-admins:
    description: Admin access to the website repo
    previously:
    - kubernetes-website-admins
    members:
    - divya-mohan0209
    - jimangel
    - natalisucks
    - reylejano
    privacy: closed
  website-maintainers:
    description: Write access to the website repo
    members:
    - a-mccarthy # Localization subproject owner
    - bradtopol # L10n: English
    - devlware # L10: Portuguese
    - divya-mohan0209 # L10n: English
    - femrtnz # L10n: Portuguese
    - girikuncoro # L10n: Indonesian
    - gochist # L10n: Korean
    - huynguyennovem # L10n: Vietnamese
    - ianychoi # L10n: Korean
    - inductor # L10n: Japanese
    - jcjesus # L10n: Portuguese
    - jhonmike # L10n: Portuguese
    - jimangel # L10n: English
    - krol3 # 1.26 RT Docs lead
    - mfilocha # L10n: Polish
    - mittalyashu # L10n: Hindi
    - nasa9084 # L10n: Japanese
    - natalisucks # L10n: English
    - nate-double-u # L10n: English
    - nvtkaszpir # L10n: Polish
    - onlydole # L10n: English
    - potapy4 # L10n: Russian
    - raelga # L10n: Spanish
    - remyleone # L10n: French
    - reylejano # L10n: English
    - rikatz # L10n: Portuguese
    - rlenferink # L10n: German
    - SataQiu # L10n: Chinese
    - seokho-son # L10n: Korean
    - sftim # L10n: English
    - shurup # L10n: Russian
    - tengqm # L10n: Chinese
    - truongnh1992 # L10n: Vietnamese
    - xichengliudui # L10n: Chinese
    - yagonobre # L10n: Portuguese
    privacy: closed
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo
    members:
    - a-mccarthy
    - annajung
    - awkif
    - bene2k1
    - bradtopol
    - celestehorgan
    - divya-mohan0209
    - femrtnz
    - girikuncoro
    - gochist
    - huynguyennovem
    - inductor
    - jcjesus
    - jimangel
    - krol3 # 1.26 RT Docs lead
    - nasa9084
    - natalisucks
    - nate-double-u
    - onlydole
    - oussemos
    - perriea
    - potapy4
    - raelga
    - Rajakavitha1
    - rekcah78
    - remyleone
    - reylejano
    - rlenferink
    - SataQiu
    - savitharaghunathan
    - seokho-son
    - sftim
    - shurup
    - tanjunchen
    - tengqm
    - tfogo
    - truongnh1992
    - xichengliudui
    - ysyukr
    - zparnold
    privacy: closed
