teams:
  sig-docs-de-owners:
    description: Approvers for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-en-owners:
    description: Approvers for English content
    members:
    - annajung
    - bradtopol
    - celestehorgan
    - irvifa
    - jimangel
    - kbarnard10
    - kbhawkey
    - onlydole
    - pi-victor
    - reylejano
    - savitharaghunathan
    - sftim
    - tengqm
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - bradtopol
    - celestehorgan
    - daminisatya
    - jimangel
    - kbarnard10
    - kbhawkey
    - onlydole
    - rajeshdeshpande02
    - sftim
    - tengqm
    privacy: closed
  sig-docs-es-owners:
    description: Approvers for Spanish content
    members:
    - electrocucaracha
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - electrocucaracha
    - emedina
    - glo-pena
    - raelga
    privacy: closed
  sig-docs-fr-owners:
    description: Approvers for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-hi-owners:
    description: Owners for Hindi content
    members:
    - daminisatya
    - mittalyashu
    - Rajakavitha1
    privacy: closed
  sig-docs-hi-reviews:
    description: PR reviews for Hindi content
    members:
    - daminisatya
    - mittalyashu
    - Rajakavitha1
    privacy: closed
  sig-docs-id-owners:
    description: Approvers for Indonesian content
    members:
    - girikuncoro
    - irvifa
    privacy: closed
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - danninov
    - girikuncoro
    - habibrosyad
    - irvifa
    - phanama
    - wahyuoi
    privacy: closed
  sig-docs-it-owners:
    description: Approvers for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    - micheleberardi
    privacy: closed
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    - micheleberardi
    privacy: closed
  sig-docs-ja-owners:
    description: Approvers for Japanese content
    members:
    - inductor
    - nasa9084
    privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - bells17
    - inductor
    - kakts
    - makocchi-git
    - nasa9084
    privacy: closed
  sig-docs-ko-owners:
    description: Approvers for Korean content
    members:
    - claudiajkang
    - gochist
    - ianychoi
    - seokho-son
    - ysyukr
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - ClaudiaJKang
    - gochist
    - ianychoi
    - jihoon-seo
    - jmyung
    - pjhwa
    - seokho-son
    - yoonian
    - ysyukr
    privacy: closed
  sig-docs-leads:
    description: Chairs and tech leads for SIG Docs
    members:
    - irvifa
    - jimangel
    - kbarnard10
    - kbhawkey
    - onlydole
    - sftim
    privacy: closed
  sig-docs-pl-owners:
    description: Approvers for Polish content
    members:
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-pl-reviews:
    description: Reviews for Polish docs PRs
    members:
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-ru-owners:
    description: Approvers for Russian content
    members:
    - aisonaku
    - dianaabv
    - msheldyakov
    - potapy4
    privacy: closed
  sig-docs-ru-reviews:
    description: Reviews for Russian docs PRs
    members:
    - aisonaku
    - dianaabv
    - msheldyakov
    - potapy4
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - bradtopol
    - cody-clark
    - gochist
    - irvifa
    - jimangel
    - kbarnard10
    - kbhawkey
    - Rajakavitha1
    - stewart-yu
    - tengqm
    - tfogo
    - zparnold
    privacy: closed
  sig-docs-pt-owners:
    description: Approvers for Portuguese content
    members:
    - devlware
    - femrtnz
    - jailton
    - jcjesus
    - jhonmike
    - rikatz
    - yagonobre
    privacy: closed
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - devlware
    - femrtnz
    - jailton
    - jcjesus
    - jhonmike
    - rikatz
    - yagonobre
    privacy: closed
  sig-docs-zh-owners:
    description: Approvers for Chinese content
    members:
    - SataQiu
    - tanjunchen
    - tengqm
    - xichengliudui
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content
    members:
    - chenrui333
    - chenxuc
    - idealhack
    - mengjiao-liu
    - pigletfly
    - SataQiu
    - tanjunchen
    - tengqm
    - xichengliudui
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-vi-owners:
    description: Admins for Vietnamese content
    members:
    - huynguyennovem
    - ngtuna
    - truongnh1992
    privacy: closed
  sig-docs-vi-reviews:
    description: PR reviews for Vietnamese content
    members:
    - huynguyennovem
    - ngtuna
    - truongnh1992
    privacy: closed
  sig-docs-uk-owners:
    description: Approvers for Ukrainian content
    members:
    - anastyakulyk
    - butuzov
    - MaxymVlasov
    privacy: closed
  sig-docs-uk-reviews:
    description: PR reviews for Ukrainian content
    members:
    - anastyakulyk
    - Arhell
    - butuzov
    - MaxymVlasov
    - Potapy4
    privacy: closed
  website-admins:
    description: Admin access to the website repo
    previously:
    - kubernetes-website-admins
    members:
    - irvifa
    - jimangel
    - kbarnard10
    privacy: closed
  website-maintainers:
    description: Write access to the website repo
    members:
    - aisonaku # L10n: Russian
    - Bradamant3 # L10n: English
    - bradtopol # L10n: English
    - ClaudiaJKang # L10n: Korean
    - cstoku # L10n: Japanese
    - devlware # L10: Portuguese
    - dianaabv # L10n: Russian
    - femrtnz # L10n: Portuguese
    - girikuncoro # L10n: Indonesian
    - gochist # L10n: Korean
    - huynguyennovem # L10n: Vietnamese
    - ianychoi # L10n: Korean
    - inductor # L10n: Japanese
    - irvifa # L10n: Indonesian
    - jailton # L10n: Portuguese
    - jcjesus # L10n: Portuguese
    - jhonmike # L10n: Portuguese
    - jimangel # L10n: English
    - kbarnard10 # L10n: English
    - mfilocha # L10n: Polish
    - mittalyashu # L10n: Hindi
    - msheldyakov # L10n: Russian
    - nasa9084 # L10n: Japanese
    - ngtuna # L10n: Vietnamese
    - nvtkaszpir # L10n: Polish
    - pi-victor # 1.22 RT Docs lead temporary access for the release
    - potapy4 # L10n: Russian
    - raelga # L10n: Spanish
    - remyleone # L10n: French
    - rikatz # L10n: Portuguese
    - rlenferink # L10n: German
    - SataQiu # L10n: Chinese
    - seokho-son # L10n: Korean
    - sftim # L10n: English
    - truongnh1992 # L10n: Vietnamese
    - xichengliudui # L10n: Chinese
    - yagonobre # L10n: Portuguese
    - zhangxiaoyu-zidif # L10n: Chinese
    privacy: closed
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo
    members:
    - abuisine
    - aisonaku
    - annajung
    - ashnehete # 1.22 RT Docs Shadow
    - awkif
    - bene2k1
    - bradtopol
    - carlisia # 1.22 RT Docs Shadow
    - celestehorgan
    - chrisnegus # 1.22 RT Docs Shadow
    - claudiajkang
    - cstoku
    - dianaabv
    - femrtnz
    - girikuncoro
    - gochist
    - huynguyennovem
    - inductor
    - irvifa
    - jcjesus
    - jimangel
    - juandiegopalomino
    - jygastaud
    - kbarnard10
    - lledru
    - msheldyakov
    - nasa9084
    - ngtuna
    - onlydole
    - oussemos
    - perriea
    - pi-victor # 1.22 RT Docs Lead
    - potapy4
    - raelga
    - Rajakavitha1
    - rbenzair
    - rekcah78
    - remyleone
    - reylejano
    - ritpanjw # 1.22 RT Docs Shadow
    - rlenferink
    - SataQiu
    - savitharaghunathan
    - seokho-son
    - sftim
    - smana
    - tanjunchen
    - tengqm
    - tfogo
    - truongnh1992
    - vineethreddy02
    - xichengliudui
    - yastij
    - ysyukr
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
