teams:
  sig-docs-blog-owners:
    description: Approvers for blog content
    maintainers:
    - mrbobbytables
    members:
    - Gauravpadam
    - graz-dev
    - lmktfy
    - natalisucks
    - nate-double-u
    privacy: closed
  sig-docs-de-owners:
    description: Approvers for German content
    members:
    - bene2k1
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    privacy: closed
  sig-docs-en-owners:
    description: Approvers for English content
    members:
    - dipesh-rawat  
    - divya-mohan0209
    - katcosgrove
    - lmktfy
    - natalisucks
    - nate-double-u
    - onlydole
    - reylejano
    - salaxander
    - SayakMukhopadhyay
    - tengqm
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - dipesh-rawat
    - divya-mohan0209
    - lmktfy
    - mengjiao-liu
    - natalisucks
    - nate-double-u
    - reylejano
    - salaxander
    - SayakMukhopadhyay
    - shannonxtreme
    - tengqm
    - windsonsea
    privacy: closed
  sig-docs-es-owners:
    description: Approvers for Spanish content
    members:
    - electrocucaracha
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - electrocucaracha
    - krol3
    - raelga
    - ramrodo
    privacy: closed
  sig-docs-fr-owners:
    description: Approvers for French content
    members:
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - perriea
    - rekcah78
    - remyleone
    privacy: closed
  sig-docs-hi-owners:
    description: Approvers for Hindi content
    members:
    - dipesh-rawat
    - divya-mohan0209
    privacy: closed
  sig-docs-hi-reviews:
    description: PR reviews for Hindi content
    members:
    - bishal7679
    - dipesh-rawat    
    - divya-mohan0209
    - jayeshmahajan
    - niranjandarshann
    privacy: closed
  sig-docs-id-owners:
    description: Approvers for Indonesian content
    members:
    - ariscahyadi
    - girikuncoro
    - habibrosyad
    - za
    privacy: closed
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - ariscahyadi
    - girikuncoro
    - habibrosyad
    - za
    privacy: closed
  sig-docs-it-owners:
    description: Approvers for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    privacy: closed
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - fabriziopandini
    - Fale
    - mattiaperi
    privacy: closed
  sig-docs-ja-owners:
    description: Approvers for Japanese content
    members:
    - bells17
    - inductor
    - nasa9084
    - Okabe-Junya
    - t-inu
    privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - atoato88
    - b1gb4by
    - bells17
    - inductor
    - kakts
    - kfess
    - nasa9084
    - Okabe-Junya
    - t-inu
    privacy: closed
  sig-docs-ko-owners:
    description: Approvers for Korean content
    members:
    - ianychoi
    - jihoon-seo
    - jongwooo
    - seokho-son
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - ianychoi
    - jihoon-seo
    - jongwooo
    - seokho-son
    privacy: closed
  sig-docs-leads:
    description: Chairs and tech leads for SIG Docs
    members:
    - divya-mohan0209
    - katcosgrove
    - natalisucks
    - reylejano
    - salaxander
    - tengqm
    privacy: closed
  sig-docs-pl-owners:
    description: Approvers for Polish content
    members:
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-pl-reviews:
    description: Reviews for Polish docs PRs
    members:
    - kpucynski
    - mfilocha
    - nvtkaszpir
    privacy: closed
  sig-docs-ru-owners:
    description: Approvers for Russian content
    members:
    - Arhell
    - kirkonru
    - shurup
    privacy: closed
  sig-docs-ru-reviews:
    description: Reviews for Russian docs PRs
    members:
    - Arhell
    - kirkonru
    - shurup
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - divya-mohan0209
    - katcosgrove
    - natalisucks
    - reylejano
    - salaxander
    - tengqm
    privacy: closed
  sig-docs-pt-owners:
    description: Approvers for Portuguese content
    members:
    - edsoncelio
    - jcjesus
    - stormqueen1990
    privacy: closed
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - edsoncelio
    - jcjesus
    - mrerlison
    - stormqueen1990
    privacy: closed
  sig-docs-zh-owners:
    description: Approvers for Chinese content
    members:
    - chenrui333
    - howieyuen
    - mengjiao-liu
    - my-git9
    - SataQiu
    - tengqm
    - windsonsea
    - xichengliudui
    - ydFu
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content
    members:
    - asa3311
    - chenrui333
    - howieyuen
    - mengjiao-liu
    - my-git9
    - SataQiu
    - Sea-n
    - tengqm
    - windsonsea
    - xichengliudui
    - ydFu
    privacy: closed
  sig-docs-vi-owners:
    description: Admins for Vietnamese content
    members:
    - khanhtc1202
    - ntheanh201
    - truongnh1992
    privacy: closed
  sig-docs-vi-reviews:
    description: PR reviews for Vietnamese content
    members:
    - khanhtc1202
    - ntheanh201
    - truongnh1992
    privacy: closed
  sig-docs-uk-owners:
    description: Approvers for Ukrainian content
    members:
    - Andygol
    - Arhell
    - MaxymVlasov
    privacy: closed
  sig-docs-uk-reviews:
    description: PR reviews for Ukrainian content
    members:
    - Andygol
    - Arhell
    - idvoretskyi
    - MaxymVlasov
    privacy: closed
  website-admins:
    description: Admin access to the website repo
    previously:
    - kubernetes-website-admins
    members:
    - divya-mohan0209
    - natalisucks
    - reylejano
    privacy: closed
    repos:
      website: admin
  website-maintainers:
    description: Write access to the website repo
    members:
    - a-mccarthy # Localization subproject owner
    - bells17 # L10n: Japanese
    - divya-mohan0209 # L10n: English
    - girikuncoro # L10n: Indonesian
    - huynguyennovem # L10n: Vietnamese # L10n: Korean
    - inductor # L10n: Japanese
    - jcjesus # L10n: Portuguese
    - katcosgrove # L10n: English
    - lmktfy # Emeritus tech lead
    - mfilocha # L10n: Polish
    - nasa9084 # L10n: Japanese
    - natalisucks # L10n: English
    - nate-double-u # L10n: English
    - nvtkaszpir # L10n: Polish
    - Okabe-Junya #L10n: Japanese
    - raelga # L10n: Spanish
    - remyleone # L10n: French
    - reylejano # L10n: English
    - salaxander # L10n: English
    - SataQiu # L10n: Chinese
    - seokho-son # L10n: Korean
    - shurup # L10n: Russian
    - t-inu # L10n: Japanese
    - tengqm # L10n: Chinese
    - truongnh1992 # L10n: Vietnamese
    - xichengliudui # L10n: Chinese
    - yagonobre # L10n: Portuguese
    privacy: closed
    repos:
      website: write
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo
    members:
    - a-mccarthy
    - AnshumanTripathi
    - ArvindParekh
    - bene2k1
    - divya-mohan0209
    - girikuncoro
    - huynguyennovem
    - inductor
    - jcjesus
    - Jimmykhangnguyen
    - kernel-kun
    - lmktfy
    - michellengnx
    - nasa9084
    - natalisucks
    - nate-double-u
    - onlydole
    - OrlinVasilev
    - perriea
    - raelga
    - rashansmith
    - rekcah78
    - remyleone
    - reylejano
    - ryan-su-12
    - salaxander
    - SataQiu
    - sayanchowdhury
    - seokho-son
    - shurup
    - tengqm
    - truongnh1992
    - Urvashi0109
    - xichengliudui
    - yujen77300
    privacy: closed
