teams:
  sig-docs-en-owners: 
    description: English content admins 
    maintainers:
    - bradamant3
    - jaredbhatti
    - zacharysarah
    members:
    - Bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jimangel
    - kbarnard10
    - mistyhacks
    - rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    maintainers:
    - Bradamant3
    - jaredbhatti
    - zacharysarah
    members:
    - jimangel
    - Rajakavitha1
    - stewart-yu
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-fr-owners:
    description: Admins for French content
    maintainers:
    - lledru
    - sieben
    - zacharysarah
    members:
    - perriea
    - rekcah78
    - yastij
    - smana
    - rbenzair
    - abuisine
    - erickhun
    - jygastaud
    - awkif
    - oussemos
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    maintainers:
    - zacharysarah
    - sieben
    - lledru
    members:
    - perriea
    - rekcah78
    - yastij
    - smana
    - rbenzair
    - abuisine
    - erickhun
    - jygastaud
    - awkif
    - oussemos
    privacy: closed
  sig-docs-it-owners:
    description: Admins for Italian content
    maintainers:
    - zacharysarah
    - rlenferink
    members:
    - lledru
    - micheleberardi
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    maintainers:
    - zacharysarah
    - rlenferink
    members:
    - lledru
    - micheleberardi
    privacy: closed
  sig-docs-ja-owners:
     description: Admins for Japanese content
     maintainers:
     - cstoku
     - nasa9084
     - tnir
     - zacharysarah
     privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    maintainers:
    - cstoku
    - nasa9084
    - tnir
    members:
    - cstoku
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - tnir
    privacy: closed
  sig-docs-ko-owners:
    description: Admins for Korean content
    maintainers:
    - claudiajkang
    - gochist
    - zacharysarah
    members:
    - ianychoi
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    maintainers:
    - ClaudiaJKang
    - gochist
    members:
    - ianychoi
    privacy: closed
  sig-docs-l10n-admins:
    description: Admins for localization projects
    maintainers:
    - bradamant3
    - jaredbhatti
    - zacharysarah
    members:
    - ClaudiaJKang # Korean
    - cstoku # Japanese
    - gochist # Korean
    - hanjiayao # Chinese
    - lledru # French
    - markthink # Chinese
    - micheleberardi # Italian
    - rlenferink # Italian
    - sieben # French
    - tnir # Japanese
    - zhangxiaoyu-zidif # Chinese
    privacy: closed
  sig-docs-maintainers:
    description: Docs maintainers team
    maintainers:
    - bradamant3
    - jaredbhatti
    - pwittrock
    - steveperry-53
    - zacharysarah
    members:
    - chenopis
    - jimangel
    - kbarnard10
    - mistyhacks
    - tengqm
    - zparnold
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    maintainers:
    - bradamant3
    - jaredbhatti
    - zacharysarah
    members:
    - Bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jimangel
    - kbarnard10
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-zh-owners:
    description: Admins for Chinese content
    maintainers:
    - hanjiayao
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content 
    maintainers:
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    members:
    - chenrui333
    - idealhack
    - pigletfly
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo. Defined in https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml.
    maintainers:
    - bradamant3
    - jaredbhatti
    - zacharysarah
    members:
    - sig-docs-en-owners
    - sig-docs-fr-owners
    - sig-docs-it-owners
    - sig-docs-ja-owners
    - sig-docs-ko-owners
    - sig-docs-zh-owners
    privacy: closed