teams:
  sig-docs-en-owners:
    description: ""
    maintainers:
    - Bradamant3
    - chenopis
    - zacharysarah
    members:
    - bradtopol
    - cody-clark
    - jaredbhatti
    - kbarnard10
    - mistyhacks
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - zparnold
    privacy: closed
  sig-docs-en-reviews:
    description: Review PRs for English content
    maintainers:
    - zacharysarah
    members:
    - jimangel
    - Rajakavitha1
    - stewart-yu
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-ja-owners:
    description: sig-docs-ja-owners
    maintainers:
    - cstoku
    members:
    - chenopis
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - tnir
    privacy: closed
  sig-docs-ja-reviews:
    description: ""
    maintainers:
    - cstoku
    - nasa9084
    - tnir
    members:
    - makocchi-git
    - MasayaAoyama
    privacy: closed
  sig-docs-ko-owners:
    description: sig-docs-ko-owners
    maintainers:
    - gochist
    members:
    - ClaudiaJKang
    - ianychoi
    privacy: closed
    teams:
      sig-docs-ko-reviews:
        description: Reviews for Korean docs PRs
        maintainers:
        - ClaudiaJKang
        - gochist
        members:
        - ianychoi
        privacy: closed
  sig-docs-l10n-admins:
    description: Admins for l10n projects
    maintainers:
    - Bradamant3
    - chenopis
    - zacharysarah
    members:
    - ClaudiaJKang
    - cstoku
    - gochist
    - hanjiayao
    - markthink
    - tnir
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-maintainers:
    description: Docs maintainers team.
    maintainers:
    - chenopis
    - jaredbhatti
    - pwittrock
    - steveperry-53
    - zacharysarah
    members:
    - Bradamant3
    - bradtopol
    - jimangel
    - kbarnard10
    - mistyhacks
    - ryanmcginnis
    - tengqm
    - tfogo
    - xiangpengzhao
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-pr-reviews:
    description: Users authorized to review docs PRs
    maintainers:
    - Bradamant3
    - chenopis
    - zacharysarah
    members:
    - bradtopol
    - cody-clark
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - xiangpengzhao
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-zh-owners:
    description: ""
    maintainers:
    - hanjiayao
    - tengqm
    members:
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: Reviews for Chinese docs PRs
    maintainers:
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    members:
    - chenrui333
    - idealhack
    - pigletfly
    privacy: closed
