teams:
  sig-docs-de-owners:
    description: Approvers for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-de-reviews:
    description: PR reviews for German content
    members:
    - bene2k1
    - mkorbi
    - rlenferink
    privacy: closed
  sig-docs-en-owners:
    description: Approvers for English content
    members:
    - bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - gochist
    - jaredbhatti
    - jimangel
    - kbarnard10
    - kbhawkey
    - makoscafee
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - simplytunde
    - steveperry-53
    - stewart-yu
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zparnold
    privacy: closed
  sig-docs-en-reviews:
    description: PR reviews for English content
    members:
    - Rajakavitha1
    - sftim
    - stewart-yu
    privacy: closed
  sig-docs-es-owners:
    description: Approvers for Spanish content
    members:
    - alexbrand
    - raelga
    privacy: closed
  sig-docs-es-reviews:
    description: PR reviews for Spanish content
    members:
    - alexbrand
    - electrocucaracha
    - glo-pena
    - raelga
    privacy: closed
  sig-docs-fr-owners:
    description: Approvers for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-fr-reviews:
    description: PR reviews for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - remyleone
    - smana
    - yastij
    privacy: closed
  sig-docs-hi-owners:
    description: Owners for Hindi content
    members:
    - daminisatya
    - mittalyashu
    - Rajakavitha1
    privacy: closed
  sig-docs-hi-reviews:
    description: PR reviews for Hindi content
    members:
    - daminisatya
    - mittalyashu
    - Rajakavitha1
    privacy: closed
  sig-docs-id-owners:
    description: Approvers for Indonesian content
    members:
    - girikuncoro
    - irvifa
    privacy: closed
  sig-docs-id-reviews:
    description: PR reviews for Indonesian content
    members:
    - danninov
    - girikuncoro
    - irvifa
    - phanama
    privacy: closed
  sig-docs-it-owners:
    description: Approvers for Italian content
    members:
    - mattiaperi
    - rlenferink
  sig-docs-it-reviews:
    description: PR reviews for Italian content
    members:
    - mattiaperi
    - micheleberardi
    - rlenferink
    privacy: closed
  sig-docs-ja-owners:
    description: Approvers for Japanese content
    members:
    - cstoku
    - inductor
    - nasa9084
    privacy: closed
  sig-docs-ja-reviews:
    description: PR reviews for Japanese content
    members:
    - cstoku
    - inductor
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - oke-py
    privacy: closed
  sig-docs-ko-owners:
    description: Approvers for Korean content
    members:
    - claudiajkang
    - gochist
    - ianychoi
    - seokho-son
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - ClaudiaJKang
    - gochist
    - ianychoi
    - seokho-son
    privacy: closed
  sig-docs-ru-owners:
    description: Approvers for Russian content
    members:
    - aisonaku
    - dianaabv
    - msheldyakov
    - potapy4
    privacy: closed
  sig-docs-ru-reviews:
    description: Reviews for Russian docs PRs
    members:
    - aisonaku
    - dianaabv
    - msheldyakov
    - potapy4
    privacy: closed
  sig-docs-pr-reviews:
    description: PR reviews for docs-related issues
    members:
    - bradamant3
    - bradtopol
    - cody-clark
    - gochist
    - jimangel
    - kbarnard10
    - kbhawkey
    - makoscafee
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - simplytunde
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zparnold
    privacy: closed
  sig-docs-pt-owners:
    description: Approvers for Portuguese content
    members:
    - femrtnz
    - jcjesus
    privacy: closed
  sig-docs-pt-reviews:
    description: PR reviews for Portuguese content
    members:
    - femrtnz
    - jcjesus
    privacy: closed
  sig-docs-zh-owners:
    description: Approvers for Chinese content
    members:
    - hanjiayao
    - SataQiu
    - xiangpengzhao
    - xichengliudui
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: PR reviews for Chinese content
    members:
    - chenrui333
    - idealhack
    - pigletfly
    - SataQiu
    - tengqm
    - xiangpengzhao
    - xichengliudui
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-vi-owners:
    description: Admins for Vietnamese content
    members:
    - huynguyennovem
    - ngtuna
    - truongnh1992
    privacy: closed
  sig-docs-vi-reviews:
    description: PR reviews for Vietnamese content
    members:
    - huynguyennovem
    - ngtuna
    - truongnh1992
    privacy: closed
  website-admins:
    description: Admin access to the website repo
    previously:
    - kubernetes-website-admins
    members:
    - Bradamant3
    - jimangel
    - zacharysarah
    privacy: closed
  website-maintainers:
    description: Write access to the website repo
    members:
    - aisonaku # L10n: Russian
    - alexbrand # L10n: Spanish
    - Bradamant3 # L10n: English
    - ClaudiaJKang # L10n: Korean
    - cstoku # L10n: Japanese
    - daminisatya # Release lead 1.17
    - dianaabv # L10n: Russian
    - femrtnz # L10n: Portuguese
    - girikuncoro # L10n: Indonesian
    - gochist # L10n: Korean
    - hanjiayao # L10n: Chinese
    - huynguyennovem # L10n: Vietnamese
    - ianychoi # L10n: Korean
    - inductor # L10n: Japanese
    - irvifa # L10n: Indonesian
    - jcjesus # L10n: Portuguese
    - jimangel # L10n: English
    - mittalyashu # L10n: Hindi
    - msheldyakov # L10n: Russian
    - nasa9084 # L10n: Japanese
    - ngtuna # L10n: Vietnamese
    - potapy4 # L10n: Russian
    - raelga # L10n: Spanish
    - remyleone # L10n: French
    - rlenferink # L10n: Italian
    - SataQiu # L10n: Chinese
    - seokho-son # L10n: Korean
    - truongnh1992 # L10n: Vietnamese
    - xichengliudui # L10n: Chinese
    - zacharysarah # L10n: English
    - zhangxiaoyu-zidif # L10n: Chinese
    privacy: closed
  website-milestone-maintainers:
    description: Contributors who can use `/milestone` in the website repo
    members:
    - abuisine
    - aisonaku
    - alexbrand
    - awkif
    - bene2k1
    - bradamant3
    - bradtopol
    - claudiajkang
    - cstoku
    - daminisatya
    - dianaabv
    - femrtnz
    - girikuncoro
    - gochist
    - hanjiayao
    - huynguyennovem
    - inductor
    - irvifa
    - jaredbhatti
    - jcjesus
    - jimangel
    - juandiegopalomino
    - jygastaud
    - kbarnard10
    - lledru
    - MAKOSCAFEE
    - msheldyakov
    - nasa9084
    - ngtuna
    - oussemos
    - perriea
    - potapy4
    - raelga
    - Rajakavitha1
    - rbenzair
    - rekcah78
    - remyleone
    - rlenferink
    - ryanmcginnis
    - SataQiu
    - simplytunde
    - smana
    - steveperry-53
    - stewart-yu
    - tfogo
    - truongnh1992
    - xiangpengzhao
    - xichengliudui
    - yastij
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
    
