teams:
  cluster-proportional-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-autoscaler-maintainers:
    description: Write access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-vertical-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  cluster-proportional-vertical-autoscaler-maintainers:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
  ip-masq-agent-admins:
    description: Admin access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - admins-ip-masq-agent
  ip-masq-agent-maintainers:
    description: Write access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - maintainers-ip-masq-agent
  external-dns-admins:
    description: Admin access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
    previously:
    - admins-external-dns
  external-dns-maintainers:
    description: Write access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
    previously:
    - maintainers-external-dns
  ingress-controller-conformance-admins:
    description: Admin access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - admins-ingress-controller-conformance
  ingress-controller-conformance-maintainers:
    description: Write access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - maintainers-ingress-controller-conformance
  iptables-wrappers-admins:
    description: Admin access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
  iptables-wrappers-maintainers:
    description: Write access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
  service-apis-admins:
    description: Admin access to the service-apis repo
    members:
    - bowei
    - thockin
    privacy: closed
  service-apis-maintainers:
    description: Write access to the service-apis repo
    members:
    - bowei
    - thockin
    privacy: closed
    previously:
    - service-apis-amintainers
