teams:
  admins-ip-masq-agent:
    description: Admin access to the ip-masq-agent repo
    members:
    - bowei
    - dnardo
    - MrHohn
    privacy: closed
  maintainers-ip-masq-agent:
    description: Write access to the ip-masq-agent repo
    members:
    - bowei
    - dnardo
    - MrHohn
    privacy: closed
  admins-external-dns:
    description: Admin access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
  maintainers-external-dns:
    description: Write access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
  admins-ingress-controller-conformance:
    description: Admin access to the ingress-controller-conformance repo
    members:
    - bowei
    - thockin
    privacy: closed
  maintainers-ingress-controller-conformance:
    description: Write access to the ingress-controller-conformance repo
    members:
    - bowei
    - thockin
    privacy: closed
