teams:
  cluster-proportional-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-autoscaler: admin
  cluster-proportional-autoscaler-maintainers:
    description: Write access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-autoscaler: write
  cluster-proportional-vertical-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-vertical-autoscaler: admin
  cluster-proportional-vertical-autoscaler-maintainers:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-vertical-autoscaler: write
  cni-dra-driver-admins:
    description: Admin access to the cni-dra-driver repo
    members:
    - aojea
    - LionelJouin
    - MikeZappa87
    privacy: closed
    repos:
      cni-dra-driver: admin
  cni-dra-driver-maintainers:
    description: Admin access to the cni-dra-driver epo
    members:
    - aojea
    - LionelJouin
    - MikeZappa87
    privacy: closed
    repos:
      cni-dra-driver: write
  gwctl-admins:
    description: Admin access to the gwctl repo
    members:
    - gauravkghildiyal
    - robscott
    - shaneutt
    - snorwin
    - youngnick
    privacy: closed
    repos:
      gwctl: admin
  gwctl-maintainers:
    description: Write access to the gwctl repo
    members:
    - gauravkghildiyal
    - robscott
    - shaneutt
    - snorwin
    - youngnick
    privacy: closed
    repos:
      gwctl: write
  ip-masq-agent-admins:
    description: Admin access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - admins-ip-masq-agent
    repos:
      ip-masq-agent: admin
  ip-masq-agent-maintainers:
    description: Write access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - maintainers-ip-masq-agent
    repos:
      ip-masq-agent: write
  external-dns-admins:
    description: Admin access to the external-dns repo
    members:
    - mloiseleur
    - Raffo
    - szuecs
    privacy: closed
    previously:
    - admins-external-dns
    repos:
      external-dns: admin
  external-dns-maintainers:
    description: Write access to the external-dns repo
    members:
    - mloiseleur
    - Raffo
    - szuecs
    privacy: closed
    previously:
    - maintainers-external-dns
    repos:
      external-dns: write
  ingate-admins:
    description: Admin access to the ingate repo
    members:
    - Gacko
    - strongjz
    privacy: closed
    repos:
      ingate: admin
  ingate-maintainers:
    description: Write access to the ingate repo
    members:
    - Gacko
    - strongjz
    - tao12345666333
    privacy: closed
    repos:
      ingate: write
  ingress2gateway-admins:
    description: Admin access to the ingress2gateway repo
    members:
    - LiorLieberman
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
    repos:
      ingress2gateway: admin
  ingress2gateway-maintainers:
    description: Write access to the ingress2gateway repo
    members:
    - LiorLieberman
    - robscott
    - youngnick
    privacy: closed
    repos:
      ingress2gateway: write
  ingress-controller-conformance-admins:
    description: Admin access to the ingress-controller-conformance repo
    members:
    - bowei
    - thockin
    privacy: closed
    previously:
    - admins-ingress-controller-conformance
    repos:
      ingress-controller-conformance: admin
  ingress-controller-conformance-maintainers:
    description: Write access to the ingress-controller-conformance repo
    members:
    - bowei
    - thockin
    privacy: closed
    previously:
    - maintainers-ingress-controller-conformance
    repos:
      ingress-controller-conformance: write
  iptables-wrappers-admins:
    description: Admin access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - thockin
    privacy: closed
    repos:
      iptables-wrappers: admin
  iptables-wrappers-maintainers:
    description: Write access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - thockin
    privacy: closed
    repos:
      iptables-wrappers: write
  gateway-api-inference-extension-admins:
    description: Admin access to gateway-api-inference-extension
    members:
    - ahg-g
    - danehans
    - kfswain
    - nirrozenbaum
    privacy: closed
    repos:
      gateway-api-inference-extension: admin
  gateway-api-inference-extension-milestone-maintainers:
    description: Milestone maintainers for gateway-api-inference-extension
    members:
    - elevran
    - kaushikmitr
    - rahulgurnani
    privacy: closed
  gateway-api-admins:
    description: Admin access to the gateway-api repo
    members:
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
    previously:
    - service-apis-admins
    repos:
      gateway-api: admin
  gateway-api-maintainers:
    description: Gateway API Maintainers
    members:
    - robscott
    - shaneutt
    - youngnick
    privacy: closed
    previously:
    - service-apis-maintainers
    - service-apis-amintainers
    repos:
      gateway-api: write
  gateway-api-release-team:
    description: Gateway API Release Team
    members:
    - bexxmodd
    - kflynn
    privacy: closed
    repos:
      gateway-api: write
  gateway-api-mesh-leads:
    description: Gateway API Mesh Leads
    members:
    - howardjohn
    - keithmattix
    - LiorLieberman
    - mikemorris
    privacy: closed
  kubernetes-network-drivers-admins:
    description: Admin access to the kubernetes-network-drivers repo
    members:
    - aojea
    - bowei
    - danwinship
    - thockin
    privacy: closed
    repos:
      kubernetes-network-drivers: admin
  kubernetes-network-drivers-maintainers:
    description: Write access to the kubernetes-network-drivers repo
    members:
    - aojea
    - bentheelder
    - danwinship
    - thockin
    privacy: closed
    repos:
      kubernetes-network-drivers: write
  kindnet-admins:
    description: Admin access to the kindnet repo
    members:
    - aojea
    - bentheelder
    - danwinship
    - thockin
    privacy: closed
    repos:
      kindnet: admin
  kindnet-maintainers:
    description: Write access to the kindnet repo
    members:
    - aojea
    - bentheelder
    - danwinship
    - thockin
    privacy: closed
    repos:
      kindnet: write
  knftables-admins:
    description: Admin access to the knftables repo
    members:
    - aojea
    - danwinship
    - shaneutt
    - thockin
    privacy: closed
    repos:
      knftables: admin
  kube-agentic-networking-admins:
    description: Admin access to the kube-agentic-networking repo
    members:
    - guicassolato
    - LiorLieberman
    privacy: closed
    repos:
      kube-agentic-networking: admin
  kube-agentic-networking-maintainers:
    description: Write access to the kube-agentic-networking repo
    members:
    - guicassolato
    - LiorLieberman
    privacy: closed
    repos:
      kube-agentic-networking: write
  kube-network-policies-admins:
    description: Admin access to the kube-network-policies repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      kube-network-policies: admin
  kube-network-policies-maintainers:
    description: Write access to the kube-network-policies repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      kube-network-policies: write
  multi-network:
    description: admin access to multi-network repo
    members:
    - aojea
    - LionelJouin
    - mskrocki
    privacy: closed
    repos:
      multi-network: admin
  multi-network-api:
    description: admin access to multi-network-api repo
    members:
    - aojea
    - LionelJouin
    - mskrocki
    privacy: closed
    repos:
      multi-network-api: admin
  nat64-admins:
    description: Admin access to the nat64 repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      nat64: admin
  nat64-maintainers:
    description: Write access to the nat64 repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      nat64: write
  network-policy-api-admins:
    description: Admin access to the network-policy-api repo
    members:
    - aojea
    - danwinship
    - Dyanngg
    - npinaeva
    - tssurya
    privacy: closed
    repos:
      network-policy-api: admin
  network-policy-finalizer-admins:
    description: Admin access to the network-policy-finalizer repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      network-policy-finalizer: admin
  network-policy-finalizer-maintainers:
    description: Write access to the network-policy-finalizer repo
    members:
    - aojea
    - danwinship
    - thockin
    privacy: closed
    repos:
      network-policy-finalizer: write
  node-ipam-controller-admins:
    description: Admin access to the node-ipam-controller repo
    members:
    - ameukam
    - aojea
    - danwinship
    - mneverov
    - sarveshr7
    - shaneutt
    - thockin
    privacy: closed
    repos:
      node-ipam-controller: admin
  node-ipam-controller-maintainers:
    description: Write access to the node-ipam-controller repo
    members:
    - ameukam
    - aojea
    - danwinship
    - mneverov
    - sarveshr7
    - shaneutt
    - thockin
    privacy: closed
    repos:
      node-ipam-controller: write
  wg-ai-gateway-admins:
    description: Admin access to the wg-ai-gateway repo
    members:
    - keithmattix
    - kflynn
    - kfswain
    - nirrozenbaum
    - shaneutt
    - xunzhuo
    privacy: closed
    repos:
      wg-ai-gateway: admin
  wg-ai-gateway-maintainers:
    description: Write access to the wg-ai-gateway repo
    members:
    - keithmattix
    - kflynn
    - kfswain
    - nirrozenbaum
    - shaneutt
    - xunzhuo
    privacy: closed
    repos:
      wg-ai-gateway: write
