teams:
  sig-security:
    description: SIG Security
    members:
    - IanColdwater
    - tabbysable
    privacy: closed
    teams:
      sig-security-leads:
        description: SIG Security Leads
        members:
        - IanColdwater
        - tabbysable
        privacy: closed
      sig-security-pr-reviews:
        description: SIG Security PR review notifications
        members:
        - IanColdwater
        - tabbysable
        privacy: closed
  sig-security-admins:
    description: Admin access to sig-security repo
    members:
    - IanColdwater
    - tabbysable
    privacy: closed
  sig-security-maintainers:
    description: Write access to sig-security repo
    members:
    - IanColdwater
    - tabbysable
    privacy: closed
