teams:
  apiserver-builder-alpha-admins:
    description: admin access to apiserver-builder-alpha
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
  apiserver-builder-alpha-maintainers:
    description: write access to apiserver-builder-alpha
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
  apiserver-runtime-admins:
    description: admin access to apiserver-runtime
    members:
    - DirectXMan12
    - gabbifish
    - pwittrock
    - yue9944882
    privacy: closed
  apiserver-runtime-maintainers:
    description: write access to apiserver-runtime
    members:
    - DirectXMan12
    - gabbifish
    - pwittrock
    - yue9944882
    privacy: closed
  clientgofix-admins:
    description: admin access to clientgofix
    members:
    - liggitt
    - mikedanese
    privacy: closed
  clientgofix-maintainers:
    description: write access to clientgofix
    members:
    - liggitt
    - mikedanese
    privacy: closed
  controller-runtime-admins:
    description: admin access to controller-runtime
    members:
    - DirectXMan12
    - droot
    - pwittrock
    privacy: closed
  controller-runtime-contributors:
    description: read access to controller-runtime
    members:
    - lichuqiang
    - pwittrock
    privacy: closed
  controller-runtime-maintainers:
    description: write access to controller-runtime
    members:
    - alvaroaleman
    - camilamacedo86
    - gabbifish
    - Liujingfang1
    - mengqiy
    - pwittrock
    - seans3
    - vincepri
    privacy: closed
  controller-tools-admins:
    description: admin access to controller-tools
    members:
    - DirectXMan12
    - droot
    - pwittrock
    - seans3
    privacy: closed
  controller-tools-contributors:
    description: read access to controller-tools
    members:
    - Birdrock
    - pwittrock
    privacy: closed
  controller-tools-maintainers:
    description: write access to controller-tools
    members:
    - camilamacedo86
    - droot
    - gabbifish
    - mengqiy
    - pwittrock
    - seans3
    - vincepri
    privacy: closed
  kubebuilder-admins:
    description: admin access to kubebuilder
    members:
    - DirectXMan12
    - droot
    - estroz
    - grodrigues3
    - Liujingfang1
    - mengqiy
    - monopole
    - pmorie
    - pwittrock
    privacy: closed
  kubebuilder-contributors:
    description: read access to kubebuilder
    members:
    - DirectXMan12
    - lichuqiang
    - pwittrock
    privacy: closed
  kubebuilder-declarative-pattern-admins:
    description: admin access to kubebuilder-declarative-pattern
    members:
    - johnsonj
    - justinsb
    privacy: closed
  kubebuilder-declarative-pattern-maintainers:
    description: write access to kubebuilder-declarative-pattern
    members:
    - johnsonj
    - justinsb
    privacy: closed
  kubebuilder-maintainers:
    description: write access to kubebuilder
    members:
    - Adirio
    - apelisse
    - camilamacedo86
    - DirectXMan12
    - droot
    - gabbifish
    - mengqiy
    - monopole
    - pmorie
    - pwittrock
    - seans3
    privacy: closed
  kubebuilder-release-tools-admins:
    description: Admin access to kubebuilder-release-tools
    members:
    - DirectXMan12
    - droot
    - mengqiy
    - vincepri
    privacy: closed
  kubebuilder-release-tools-maintainers:
    description: Write access to kubebuilder-release-tools
    members:
    - Adirio
    - DirectXMan12
    - droot
    - mengqiy
    - vincepri
    privacy: closed
  kubectl-check-ownerreferences-admins:
    description: Admin access to kubectl-check-ownerreferences
    members:
    - caesarxuchao
    - deads2k
    - liggitt
    privacy: closed
  kubernetes/sig-api-machinery:
    description: Parent team for all SIG API Machinery subteams (approvers, reviewers,
      admins)
    members:
    - deads2k
    - lavalamp
    privacy: closed
    teams:
      kubernetes/sig-api-machinery-admins:
        description: Admin rights over all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
      kubernetes/sig-api-machinery-approvers:
        description: write access to all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
      kubernetes/sig-api-machinery-reviewers:
        description: read access to all repositories owned by SIG API Machinery
        members:
        - deads2k
        - lavalamp
        privacy: closed
  structured-merge-diff-admins:
    description: admin access to structured-merge-diff
    members:
    - apelisse
    - lavalamp
    privacy: closed
  structured-merge-diff-maintainers:
    description: write access to structured-merge-diff
    members:
    - apelisse
    - jpbetz
    - lavalamp
    # emeritus
    # - jennybuckley
    privacy: closed
  yaml-admins:
    description: ""
    members:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
  yaml-maintainers:
    description: ""
    members:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
