teams:
  apiserver-builder-alpha-admins:
    description: admin access to apiserver-builder-alpha
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
    repos:
      apiserver-builder-alpha: admin
  apiserver-builder-alpha-maintainers:
    description: write access to apiserver-builder-alpha
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
    repos:
      apiserver-builder-alpha: write
  apiserver-runtime-admins:
    description: admin access to apiserver-runtime
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
    repos:
      apiserver-runtime: admin
  apiserver-runtime-maintainers:
    description: write access to apiserver-runtime
    members:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
    repos:
      apiserver-runtime: write
  clientgofix-admins:
    description: admin access to clientgofix
    members:
    - liggitt
    - mikedanese
    privacy: closed
    repos:
      clientgofix: admin
  clientgofix-maintainers:
    description: write access to clientgofix
    members:
    - liggitt
    - mikedanese
    privacy: closed
    repos:
      clientgofix: write
  controller-runtime-admins:
    description: admin access to controller-runtime
    members:
    - joelanford
    - vincepri
    privacy: closed
    repos:
      controller-runtime: admin
  controller-runtime-maintainers:
    description: write access to controller-runtime
    members:
    - alvaroaleman
    - fillzpp
    - joelanford
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      controller-runtime: write
  controller-tools-admins:
    description: admin access to controller-tools
    members:
    - joelanford
    - vincepri
    privacy: closed
    repos:
      controller-tools: admin
  controller-tools-maintainers:
    description: write access to controller-tools
    members:
    - alvaroaleman
    - joelanford
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      controller-tools: write
  json-admins:
    description: Admin access to the json repo
    members:
    - deads2k
    - lavalamp
    - liggitt
    privacy: closed
    repos:
      json: admin
  kubebuilder-admins:
    description: admin access to kubebuilder
    members:
    - camilamacedo86
    - DirectXMan12
    - jmrodri
    - mengqiy
    - pmorie
    - pwittrock
    - varshaprasad96
    privacy: closed
    repos:
      kubebuilder: admin
      kubebuilder-declarative-pattern: admin
  kubebuilder-contributors:
    description: read access to kubebuilder
    members:
    - DirectXMan12
    - pwittrock
    privacy: closed
    repos:
      kubebuilder: read
  kubebuilder-declarative-pattern-admins:
    description: admin access to kubebuilder-declarative-pattern
    members:
    - justinsb
    privacy: closed
    repos:
      kubebuilder-declarative-pattern: admin
  kubebuilder-declarative-pattern-maintainers:
    description: write access to kubebuilder-declarative-pattern
    members:
    - justinsb
    privacy: closed
    repos:
      kubebuilder-declarative-pattern: write
  kubebuilder-maintainers:
    description: write access to kubebuilder
    members:
    - apelisse
    - camilamacedo86
    - DirectXMan12
    - mengqiy
    - pmorie
    - pwittrock
    - seans3
    privacy: closed
    repos:
      kubebuilder: write
  kubebuilder-release-tools-admins:
    description: Admin access to kubebuilder-release-tools
    members:
    - DirectXMan12
    - mengqiy
    - vincepri
    privacy: closed
    repos:
      kubebuilder-release-tools: admin
  kubebuilder-release-tools-maintainers:
    description: Write access to kubebuilder-release-tools
    members:
    - camilamacedo86
    - DirectXMan12
    - mengqiy
    - vincepri
    privacy: closed
    repos:
      kubebuilder-release-tools: write
  kubectl-check-ownerreferences-admins:
    description: Admin access to kubectl-check-ownerreferences
    members:
    - caesarxuchao
    - deads2k
    - liggitt
    privacy: closed
    repos:
      kubectl-check-ownerreferences: admin
  kubernetes/sig-api-machinery:
    description: Parent team for all SIG API Machinery subteams (approvers, reviewers,
      admins)
    members:
    - deads2k
    - lavalamp
    privacy: closed
    teams:
      kubernetes/sig-api-machinery-admins:
        description: Admin rights over all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
        repos:
          kube-storage-version-migrator: admin
      kubernetes/sig-api-machinery-approvers:
        description: write access to all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
        repos:
          kube-storage-version-migrator: write
      kubernetes/sig-api-machinery-reviewers:
        description: read access to all repositories owned by SIG API Machinery
        members:
        - deads2k
        - lavalamp
        privacy: closed
        repos:
          kube-storage-version-migrator: read
  structured-merge-diff-admins:
    description: admin access to structured-merge-diff
    members:
    - apelisse
    - lavalamp
    privacy: closed
    repos:
      structured-merge-diff: admin
  structured-merge-diff-maintainers:
    description: write access to structured-merge-diff
    members:
    - apelisse
    - jiahuif
    - jpbetz
    - lavalamp
    # emeritus
    # - jennybuckley
    privacy: closed
    repos:
      structured-merge-diff: write
  yaml-admins:
    description: ""
    members:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
    repos:
      yaml: admin
  yaml-maintainers:
    description: ""
    members:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
    repos:
      yaml: write
