teams:
  container-object-storage-interface-api-admins:
    description: Admin access to container-object-storage-interface-api
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  container-object-storage-interface-api-maintainers:
    description: Write access to container-object-storage-interface-api
    members:
    - brahmaroutu
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  container-object-storage-interface-controller-admins:
    description: Admin access to container-object-storage-interface-controller
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  container-object-storage-interface-controller-maintainers:
    description: Write access to container-object-storage-interface-controller
    members:
    - brahmaroutu
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  container-object-storage-interface-csi-adapter-admins:
    description: Admin access to container-object-storage-interface-csi-adapter
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  container-object-storage-interface-csi-adapter-maintainers:
    description: Write access to container-object-storage-interface-csi-adapter
    members:
    - brahmaroutu
    - copejon
    - jsafrane
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  container-object-storage-interface-provisioner-sidecar-admins:
    description: Admin access to container-object-storage-interface-provisioner-sidecar
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  container-object-storage-interface-provisioner-sidecar-maintainers:
    description: Write access to container-object-storage-interface-provisioner-sidecar
    members:
    - brahmaroutu
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  container-object-storage-interface-spec-admins:
    description: Admin access to container-object-storage-interface-spec
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  container-object-storage-interface-spec-maintainers:
    description: Write access to container-object-storage-interface-spec
    members:
    - brahmaroutu
    - copejon
    - jsafrane
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  cosi-driver-sample-admins:
    description: Admin access to cosi-driver-sample
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  cosi-driver-sample-maintainers:
    description: Write access to cosi-driver-sample
    members:
    - jsafrane
    - krishchow
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
  gluster-block-external-provisioner-admins:
    description: Admin access to gluster-block-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  gluster-file-external-provisioner-admins:
    description: Admin access to gluster-file-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  nfs-subdir-external-provisioner-admins:
    description: Admin access to nfs-subdir-external-provisioner
    members:
    - jsafrane
    - kmova
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  nfs-ganesha-server-and-external-provisioner-admins:
    description: Admin access to nfs-ganesha-server-and-external-provisioner
    members:
    - jsafrane
    - kmova
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
