teams:
  container-object-storage-interface-admins:
    description: Admin access to container-object-storage-interface
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface: admin
  container-object-storage-interface-maintainers:
    description: Write access to container-object-storage-interface
    members:
    - BlaineEXE
    - jsafrane
    - msau42
    - saad-ali
    - shanduur
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface: write
  cosi-driver-sample-admins:
    description: Admin access to cosi-driver-sample
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      cosi-driver-sample: admin
  cosi-driver-sample-maintainers:
    description: Write access to cosi-driver-sample
    members:
    - BlaineEXE
    - jsafrane
    - msau42
    - saad-ali
    - shanduur
    - xing-yang
    privacy: closed
    repos:
      cosi-driver-sample: write
  gcp-compute-persistent-disk-csi-driver-admins:
    description: Admin access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - dannawang0221
    - hime
    - juliankatz
    - leiyiz
    - mattcary
    - msau42
    - pwschuurman
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tonyzhc
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: admin
  gcp-compute-persistent-disk-csi-driver-maintainers:
    description: Write access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - cemakd
    - dannawang0221    
    - hime
    - juliankatz
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - sneha-at
    - songjiaxun
    - sunnylovestiramisu
    - tonyzhc
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: write
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - dannawang0221
    - hime
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: admin
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - amacaskill
    - dannawang0221
    - hime
    - leiyiz
    - mattcary
    - msau42
    - pwschuurman
    - saad-ali
    - saikat-royc
    - sneha-at
    - songjiaxun
    - sunnylovestiramisu
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: write      
  gluster-block-external-provisioner-admins:
    description: Admin access to gluster-block-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      gluster-block-external-provisioner: admin
  gluster-file-external-provisioner-admins:
    description: Admin access to gluster-file-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      gluster-file-external-provisioner: admin
  nfs-subdir-external-provisioner-admins:
    description: Admin access to nfs-subdir-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      nfs-subdir-external-provisioner: admin
  nfs-ganesha-server-and-external-provisioner-admins:
    description: Admin access to nfs-ganesha-server-and-external-provisioner
    members:
    - jsafrane
    - kvaps
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      nfs-ganesha-server-and-external-provisioner: admin
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: admin
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: write
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: admin
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: write
