teams:
  container-object-storage-interface-api-admins:
    description: Admin access to container-object-storage-interface-api
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-api: admin
  container-object-storage-interface-api-maintainers:
    description: Write access to container-object-storage-interface-api
    members:
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-api: write
  container-object-storage-interface-controller-admins:
    description: Admin access to container-object-storage-interface-controller
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-controller: admin
  container-object-storage-interface-controller-maintainers:
    description: Write access to container-object-storage-interface-controller
    members:
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-controller: write
  container-object-storage-interface-csi-adapter-admins:
    description: Admin access to container-object-storage-interface-csi-adapter
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-csi-adapter: admin
  container-object-storage-interface-csi-adapter-maintainers:
    description: Write access to container-object-storage-interface-csi-adapter
    members:
    - copejon
    - jsafrane
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-csi-adapter: write
  container-object-storage-interface-provisioner-sidecar-admins:
    description: Admin access to container-object-storage-interface-provisioner-sidecar
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-provisioner-sidecar: admin
  container-object-storage-interface-provisioner-sidecar-maintainers:
    description: Write access to container-object-storage-interface-provisioner-sidecar
    members:
    - jsafrane
    - msau42
    - rrati
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-provisioner-sidecar: write
  container-object-storage-interface-spec-admins:
    description: Admin access to container-object-storage-interface-spec
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-spec: admin
  container-object-storage-interface-spec-maintainers:
    description: Write access to container-object-storage-interface-spec
    members:
    - copejon
    - jsafrane
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      container-object-storage-interface-spec: write
  cosi-driver-sample-admins:
    description: Admin access to cosi-driver-sample
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      cosi-driver-sample: admin
  cosi-driver-sample-maintainers:
    description: Write access to cosi-driver-sample
    members:
    - jsafrane
    - krishchow
    - msau42
    - saad-ali
    - wlan0
    - xing-yang
    privacy: closed
    repos:
      cosi-driver-sample: write
  gluster-block-external-provisioner-admins:
    description: Admin access to gluster-block-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      gluster-block-external-provisioner: admin
  gluster-file-external-provisioner-admins:
    description: Admin access to gluster-file-external-provisioner
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      gluster-file-external-provisioner: admin
  nfs-subdir-external-provisioner-admins:
    description: Admin access to nfs-subdir-external-provisioner
    members:
    - jsafrane
    - kmova
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      nfs-subdir-external-provisioner: admin
  nfs-ganesha-server-and-external-provisioner-admins:
    description: Admin access to nfs-ganesha-server-and-external-provisioner
    members:
    - jsafrane
    - kmova
    - kvaps
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      nfs-ganesha-server-and-external-provisioner: admin
