teams:
  sig-storage-api-reviews:
    description: API Reviews for Kubernetes Storage Special-Interest-Group
    members:
    - davidopp
    - jsafrane
    - msau42
    - rootfs
    - saad-ali
    - thockin
    - wattsteve
    - xing-yang
    privacy: closed
  sig-storage-bugs:
    description: Bugs for Kubernetes Storage Special-Interest-Group
    members:
    - gnufied
    - jeffvance
    - jingxu97
    - jsafrane
    - msau42
    - NickrenREN
    - rootfs
    - saad-ali
    - wattsteve
    - xing-yang
    privacy: closed
  sig-storage-feature-requests:
    description: Feature Requests for Kubernetes Storage Special-Interest-Group
    members:
    - davidopp
    - jingxu97
    - jsafrane
    - msau42
    - NickrenREN
    - rootfs
    - saad-ali
    - smarterclayton
    - thockin
    - wattsteve
    - xing-yang
    privacy: closed
  sig-storage-misc:
    description: Miscellaneous Discussions for Kubernetes Storage Special-Interest-Group.
      Ideally @kubernetes/sig-storage-misc should be seldom used, in lieu of more
      appropriate channels (sig-storage-bugs, sig-storage-proposals, sig-storage-pr-reviews,
      etc.)
    members:
    - davidopp
    - gnufied
    - jeffvance
    - jingxu97
    - jsafrane
    - msau42
    - NickrenREN
    - rootfs
    - saad-ali
    - smarterclayton
    - thockin
    - wattsteve
    - xing-yang
    privacy: closed
  sig-storage-pr-reviews:
    description: PR Reviews for Kubernetes Storage Special-Interest-Group
    members:
    - jsafrane
    - msau42
    - rootfs
    - saad-ali
    - xing-yang
    privacy: closed
  sig-storage-proposals:
    description: Proposals for Kubernetes Storage Special-Interest-Group
    members:
    - davidopp
    - jingxu97
    - jsafrane
    - msau42
    - rootfs
    - saad-ali
    - smarterclayton
    - thockin
    - vishh
    - wattsteve
    - xing-yang
    privacy: closed
  sig-storage-test-failures:
    description: Test Failures for Kubernetes Storage Special-Interest-Group
    members:
    - jeffvance
    - jingxu97
    - jsafrane
    - msau42
    - rootfs
    - saad-ali
    - xing-yang
    privacy: closed
