teams:
  windows-gmsa-admins:
    description: Admin access to windows-gmsa repo
    members:
    - ddebroy
    - marosset
    - michmike
    privacy: closed
  windows-gmsa-maintainers:
    description: Write access to windows-gmsa repo
    members:
    - ddebroy
    - marosset
    - michmike
    privacy: closed
  sig-windows-samples-admins:
    description: Admin access to sig-windows-samples repo
    members:
    - marosset
    - michmike
    privacy: closed
    previously:
    - sig-windows-examples-admins
  sig-windows-samples-maintainers:
    description: Write access to sig-windows-samples repo
    members:
    - jsturtevant
    - marosset
    - michmike
    privacy: closed
    previously:
    - sig-windows-examples-maintainers
  sig-windows-tools-admins:
    description: Admin access to sig-windows-tools repo
    members:
    - benmoss
    - marosset
    - michmike
    privacy: closed
  sig-windows-tools-maintainers:
    description: Write access to sig-windows-tools repo
    members:
    - benmoss
    - jsturtevant
    - marosset
    - michmike
    privacy: closed
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - adelina-t
    - marosset
    - michmike
    privacy: closed
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - adelina-t
    - jsturtevant
    - marosset
    - michmike
    privacy: closed
