teams:
  windows-gmsa-admins:
    description: Admin access to windows-gmsa repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-gmsa: admin
  windows-gmsa-maintainers:
    description: Write access to windows-gmsa repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-gmsa: write
  sig-windows-samples-admins:
    description: Admin access to sig-windows-samples repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    previously:
    - sig-windows-examples-admins
    repos:
      sig-windows-samples: admin
  sig-windows-samples-maintainers:
    description: Write access to sig-windows-samples repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    previously:
    - sig-windows-examples-maintainers
    repos:
      sig-windows-samples: write
  sig-windows-dev-tools-admins:
    description: Admin access to sig-windows-dev-tools repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      sig-windows-dev-tools: admin
      windows-service-proxy: admin
  sig-windows-tools-admins:
    description: Admin access to sig-windows-tools repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      sig-windows-tools: admin
  sig-windows-tools-maintainers:
    description: Write access to sig-windows-tools repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      sig-windows-tools: write
  windows-operational-readiness-admins:
    description: Admin access to the windows-operational-readiness repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-operational-readiness: admin
  windows-operational-readiness-maintainers:
    description: Write access to the windows-operational-readiness repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-operational-readiness: write
  windows-service-proxy-admins:
    description: Admin access to the windows-service-proxy repo
    members:
    - aravindhp
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-service-proxy: admin
  windows-service-proxy-maintainers:
    description: Write access to the windows-service-proxy repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-service-proxy: write
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-testing: admin
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - aravindhp
    - claudiubelu
    - marosset
    - zylxjtu
    privacy: closed
    repos:
      windows-testing: write
