teams:
  windows-gmsa-admins:
    description: Admin access to windows-gmsa repo
    members:
    - ddebroy
    - michmike
    - PatrickLang
    privacy: closed
  windows-gmsa-maintainers:
    description: Write access to windows-gmsa repo
    members:
    - ddebroy
    - michmike
    - PatrickLang
    privacy: closed
  sig-windows-samples-admins:
    description: Admin access to sig-windows-samples repo
    members:
    - marosset
    - michmike
    privacy: closed
    previously:
    - sig-windows-examples-admins
  sig-windows-samples-maintainers:
    description: Write access to sig-windows-samples repo
    members:
    - marosset
    - michmike
    privacy: closed
    previously:
    - sig-windows-examples-maintainers
  sig-windows-tools-admins:
    description: Admin access to sig-windows-tools repo
    members:
    - benmoss
    - michmike
    - PatrickLang
    privacy: closed
  sig-windows-tools-maintainers:
    description: Write access to sig-windows-tools repo
    members:
    - benmoss
    - michmike
    - PatrickLang
    privacy: closed
