teams:
  community-admins:
    description: ""
    maintainers:
    - calebamiles
    - cblecker
    - idvoretskyi
    - nikhita
    members:
    - bgrant0607
    - castrojo
    - grodrigues3
    - jdumars
    - parispittman
    - Phillels
    - sarahnovotny
    - thockin
    privacy: closed
  community-maintainers:
    description: ""
    maintainers:
    - cblecker
    - nikhita
    members:
    - parispittman
    - Phillels
    - thockin
    privacy: closed
  sig-contributor-experience-bugs:
    description: Bugs relating to contributor-experience infrastructure, such as the
      PR bot, etc.
    maintainers:
    - cblecker
    - nikhita
    members:
    - grodrigues3
    - idealhack
    - rmmh
    privacy: closed
  sig-contributor-experience-feature-requests:
    description: Requests for features in contributor-experience infrastructure, such
      as the PR bot, etc.
    maintainers:
    - cblecker
    - idvoretskyi
    - nikhita
    members:
    - grodrigues3
    - idealhack
    - rmmh
    privacy: closed
  sig-contributor-experience-misc-use-only-as-a-last-resort:
    description: Improve contributor productivity
    maintainers:
    - cblecker
    - idvoretskyi
    - nikhita
    members:
    - dims
    - eparis
    - foxish
    - grodrigues3
    - hongchaodeng
    - idealhack
    - jessfraz
    - Kashomon
    - lavalamp
    - monopole
    - philips
    - pigmej
    - pwittrock
    - rmmh
    - thockin
    - xiang90
    privacy: closed
  sig-contributor-experience-pr-reviews:
    description: PR reviews for contributor-experience infrastructure, such as the
      PR bot, etc.
    maintainers:
    - cblecker
    - idvoretskyi
    - nikhita
    members:
    - grodrigues3
    - idealhack
    - rmmh
    privacy: closed
  sig-contributor-experience-proposals:
    description: Design proposals for new contributor-experience infrastructure, such
      as bots, monitoring dashboards, portals, etc.
    maintainers:
    - cblecker
    - nikhita
    members:
    - grodrigues3
    - idealhack
    privacy: closed
  sig-contributor-experience-test-failures:
    description: List to triage test failures for contributor-experience infrastructure,
      such as the PR bot, etc.
    maintainers:
    - cblecker
    - nikhita
    members:
    - grodrigues3
    - idealhack
    privacy: closed
