teams:
  sig-auth-api-reviews:
    description: ""
    members:
    - davidopp
    - deads2k
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - tallclair
    privacy: closed
  sig-auth-bugs:
    description: ""
    members:
    - davidopp
    - deads2k
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - tallclair
    privacy: closed
  sig-auth-feature-requests:
    description: ""
    members:
    - davidopp
    - deads2k
    - destijl
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - smarterclayton
    - tallclair
    privacy: closed
  sig-auth-misc:
    description: ""
    members:
    - alex-mohr
    - cjcullen
    - davidopp
    - deads2k
    - destijl
    - enj
    - erictune
    - liggitt
    - mattmoyer
    - mikedanese
    - pmorie
    - smarterclayton
    - tallclair
    privacy: closed
  sig-auth-pr-reviews:
    description: ""
    members:
    - davidopp
    - deads2k
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - tallclair
    privacy: closed
  sig-auth-proposals:
    description: ""
    members:
    - davidopp
    - deads2k
    - destijl
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - smarterclayton
    - tallclair
    privacy: closed
  sig-auth-test-failures:
    description: ""
    members:
    - davidopp
    - deads2k
    - enj
    - liggitt
    - mattmoyer
    - mikedanese
    - tallclair
    privacy: closed
