teams:
  sig-architecture:
    description: SIG Architecture
    members:
    - derekwaynecarr
    - dims
    - johnbelamaric
    - liggitt
    - smarterclayton
    - thockin
    privacy: closed
    teams:
      sig-architecture-leads:
        description: SIG Architecture Chairs and Technical Leads
        members:
        - derekwaynecarr
        - dims
        - johnbelamaric
        privacy: closed
      sig-architecture-pr-reviews:
        description: SIG Architecture PR review notifications
        members:
        - derekwaynecarr
        - dims
        - johnbelamaric
        - liggitt
        - smarterclayton
        - thockin
        privacy: closed
  code-organization-project-admins:
    description: admin access to code organization subproject board
    members:
    - dims
    privacy: closed
  enhancements:
    description: Enhancements subproject members (includes subproject owners
      and the active Release Team's Enhancements subteam)
    maintainers:
    - mrbobbytables # subproject owner
    members:
    - annajung # 1.21 Enhancements Lead
    - arunmk # 1.21 Enhancements Shadow
    - jameslaverack # 1.21 Enhancements Shadow
    - jeremyrickard # subproject owner
    - johnbelamaric # subproject owner
    - jrsapi # 1.21 Enhancements Shadow
    - justaugustus # subproject owner
    - kendallroden # 1.21 Enhancements Shadow
    - kikisdeliveryservice # 1.20 Enhancements Lead
    - LappleApple # subproject owner
    - palnabarun
    privacy: closed
    teams:
      enhancements-admins:
        description: Contributors with admin access to k/enhancements
        maintainers:
        - mrbobbytables # subproject owner
        members:
        - jeremyrickard # subproject owner
        - johnbelamaric # subproject owner
        - justaugustus # subproject owner
        - LappleApple # subproject owner
        privacy: closed
      enhancements-maintainers:
        description: Contributors with write access to k/enhancements
        maintainers:
        - mrbobbytables # subproject owner
        members:
        - jeremyrickard # subproject owner
        - johnbelamaric # subproject owner
        - justaugustus # subproject owner
        - LappleApple # subproject owner
        previously:
        - features-maintainers
        privacy: closed
