teams:
  sig-architecture:
    description: SIG Architecture
    members:
    - derekwaynecarr
    - dims
    - johnbelamaric
    - liggitt
    - smarterclayton
    - thockin
    privacy: closed
    teams:
      sig-architecture-leads:
        description: SIG Architecture Chairs and Technical Leads
        members:
        - derekwaynecarr
        - dims
        - johnbelamaric
        privacy: closed
        repos:
          design-proposals-archive: admin
      sig-architecture-pr-reviews:
        description: SIG Architecture PR review notifications
        members:
        - derekwaynecarr
        - dims
        - johnbelamaric
        - liggitt
        - smarterclayton
        - thockin
        privacy: closed
  code-organization-project-admins:
    description: admin access to code organization subproject board
    members:
    - dims
    privacy: closed
  enhancements:
    description: Enhancements subproject members (includes subproject owners
      and the active Release Team's Enhancements subteam)
    maintainers:
    - mrbobbytables # subproject owner
    members:
    - aibarbetta # 1.35 Enhancements Shadow
    - Atharva-Shinde # 1.28 RT Enhancements Lead
    - chanieljdan # 1.35 Enhancements Shadow
    - fykaa # 1.35 Enhancements Shadow
    - jenshu # 1.34 Enhancements Lead
    - jeremyrickard # subproject owner
    - jmickey # 1.35 Enhancements Shadow
    - johnbelamaric # subproject owner
    - justaugustus # subproject owner
    - kikisdeliveryservice # subproject owner
    - rayandas # 1.35 Enhancements Lead
    - salehsedghpour # 1.30 RT Enhancements Lead
    - whtssub # 1.35 Enhancements Shadow
    privacy: closed
    teams:
      enhancements-admins:
        description: Contributors with admin access to k/enhancements
        maintainers:
        - mrbobbytables # subproject owner
        members:
        - jeremyrickard # subproject owner
        - johnbelamaric # subproject owner
        - justaugustus # subproject owner
        - kikisdeliveryservice # subproject owner
        privacy: closed
        repos:
          enhancements: admin
      enhancements-maintainers:
        description: Contributors with write access to k/enhancements
        maintainers:
        - mrbobbytables # subproject owner
        members:
        - jeremyrickard # subproject owner
        - johnbelamaric # subproject owner
        - justaugustus # subproject owner
        - kikisdeliveryservice # subproject owner
        previously:
        - features-maintainers
        privacy: closed
        repos:
          enhancements: write
  production-readiness:
    description: Production Readiness Review Team
    members:
    - deads2k
    - johnbelamaric
    - jpbetz
    - kannon92
    - soltysh
    - wojtek-t
    privacy: closed
    teams:
      prod-readiness-reviewers:
        description: Production Readiness Reviewers
        members:
        - aramase       # shadow
        - deads2k       # approver
        - johnbelamaric # approver
        - jpbetz        # approver
        - kannon92      # approver
        - sohankunkerkar # shadow
        - soltysh       # approver
        - stlaz         # shadow
        - wojtek-t      # approver
        privacy: closed
