teams:
  wg-structured-logging-leads:
    description: ""
    members:
      - serathius
      - shubheksha
    privacy: closed
  wg-structured-logging-members:
    description: ""
    members:
      - MadhavJivrajani
      - Priyankasaggu11929
      - serathius
      - shubheksha
      - yangjunmyfm192085
    privacy: closed
  wg-structured-logging-reviews:
    description: ""
    members:
      - serathius
      - shubheksha
      - yangjunmyfm192085
    privacy: closed
