teams:
  wg-structured-logging-leads:
    description: ""
    members:
      - pohly
      - serathius
    privacy: closed
  wg-structured-logging-members:
    description: ""
    members:
      - MadhavJivrajani
      - mengjiao-liu
      - navidshaikh
      - pohly
      - Priyankasaggu11929
      - serathius
      - shivanshu1333
      - yangjunmyfm192085
      - yuzhiquan
    privacy: closed
  wg-structured-logging-reviews:
    description: ""
    members:
      - mengjiao-liu
      - navidshaikh
      - pohly
      - serathius
      - shivanshu1333
      - yangjunmyfm192085
      - yuzhiquan
    privacy: closed
