teams:
  dra-driver-cpu-admins:
    description: Admin access to dra-driver-cpu repo
    members:
    - johnbelamaric
    - klueska
    - pohly
    privacy: closed
    repos:
      dra-driver-cpu: admin
  dra-driver-cpu-maintainers:
    description: Write access to dra-driver-cpu repo
    members:
    - johnbelamaric
    - klueska
    - pohly
    privacy: closed
    repos:
      dra-driver-cpu: write
  dra-example-driver-admins:
    description: Admin access to dra-example-driver repo
    members:
    - klueska
    - pohly
    privacy: closed
    repos:
      dra-example-driver: admin
  dra-example-driver-maintainers:
    description: Write access to dra-example-driver repo
    members:
    - bart0sh
    privacy: closed
    repos:
      dra-example-driver: write
  node-feature-discovery-operator-admins:
    description: Admin access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
    repos:
      node-feature-discovery-operator: admin
  node-feature-discovery-operator-maintainers:
    description: Write access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
    repos:
      node-feature-discovery-operator: write
  node-readiness-controller-admins:
    description: Admin access to node-readiness-controller repo
    members:
    - ajaysundark
    - dchen1107
    - haircommander
    - mrunalp
    - SergeyKanzhelev
    privacy: closed
    repos:
      node-readiness-controller: admin
  node-readiness-controller-maintainers:
    description: Write access to node-readiness-controller repo
    members:
    - ajaysundark
    - dchen1107
    - haircommander
    - mrunalp
    - SergeyKanzhelev
    - tallclair
    privacy: closed
    repos:
      node-readiness-controller: write
  noderesourcetopology-api-admins:
    description: Admin access to noderesourcetopology-api repo
    members:
    - ffromani
    - swatisehgal
    privacy: closed
    repos:
      noderesourcetopology-api: admin
  noderesourcetopology-api-maintainers:
    description: Write access to noderesourcetopology-api repo
    members:
    - marquiz
    privacy: closed
    repos:
      noderesourcetopology-api: write
  security-profiles-operator-admins:
    description: Admin access to security-profiles-operator repo
    members:
    - ccojocar
    - JAORMX
    - saschagrunert
    privacy: closed
    previously:
    - seccomp-operator-admins
    repos:
      security-profiles-operator: admin
  security-profiles-operator-maintainers:
    description: Write access to security-profiles-operator repo
    members:
    - ccojocar
    - JAORMX
    - ngopalak-redhat
    - saschagrunert
    - Vincent056
    privacy: closed
    previously:
    - seccomp-operator-maintainers
    repos:
      security-profiles-operator: write
  kernel-module-management-admins:
    description: Admin access to kernel-module-management repo
    members:
    - qbarrand
    - ybettan
    - yevgeny-shnaidman
    privacy: closed
    previously:
    - special-resource-operator-admins
    repos:
      kernel-module-management: admin
  kernel-module-management-maintainers:
    description: Write access to kernel-module-management repo
    members:
    - qbarrand
    - ybettan
    - yevgeny-shnaidman
    privacy: closed
    previously:
    - special-resource-operator-maintainers
    repos:
      kernel-module-management: write
