teams:
  node-feature-discovery-operator-admins:
    description: Admin access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
  node-feature-discovery-operator-maintainers:
    description: Write access to node-feature-discovery-operator repo
    members:
    - ArangoGutierrez
    - marquiz
    - zvonkok
    privacy: closed
  security-profiles-operator-admins:
    description: Admin access to security-profiles-operator repo
    members:
    - hasheddan
    - pjbgf
    - saschagrunert
    privacy: closed
    previously:
    - seccomp-operator-admins
  security-profiles-operator-maintainers:
    description: Write access to security-profiles-operator repo
    members:
    - hasheddan
    - pjbgf
    - saschagrunert
    privacy: closed
    previously:
    - seccomp-operator-maintainers
