teams:
  cloud-provider-openstack-admins:
    description: Admin access to cloud-provider-openstack repo
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: admin
  cloud-provider-openstack-maintainers:
    description: Write access to the cloud-provider-openstack repo
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: write
  cloud-provider-openstack-members:
    description: ""
    members:
    - dulek
    - kayrus
    - mdbooth
    - zetaab
    privacy: closed
    repos:
      cloud-provider-openstack: read

  # NOTE(mdbooth): The purpose of the teams below is not clear. Membership is
  # not actively maintained.
  provider-openstack-api-reviews:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-api-reviews
  provider-openstack-bugs:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-bugs
  provider-openstack-feature-requests:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-feature-requests
  provider-openstack-misc:
    description: OpenStack Special Interest Group
    members:
    - anguslees
    - dims
    - dulek
    - feiskyer
    - kayrus
    - kragniz
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-misc
  provider-openstack-pr-reviews:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-pr-reviews
  provider-openstack-proposals:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-proposals
  provider-openstack-test-failures:
    description: ""
    members:
    - dulek
    - kayrus
    - zetaab
    privacy: closed
    previously:
    - sig-openstack-test-failures
