teams:
  autoscaler-admins:
    description: Admin access to the autoscaler repo
    members:
    - bigdarkclown
    - gjtempleton
    - maciekpytel
    - towca
    - x13n
    privacy: closed
    repos:
      autoscaler: admin
  autoscaler-maintainers:
    description: "Maintainers of sub-projects in the autoscaler repo"
    members:
    - bigdarkclown
    - gjtempleton
    - maciekpytel
    - raywainman
    - towca
    - x13n
    privacy: closed
    repos:
      autoscaler: write
  autoscaler-reviewers:
    description: "Reviewers of PRs in the autoscaler repo"
    members:
    - bigdarkclown
    - feiskyer
    - gjtempleton
    - maciekpytel
    - raywainman
    - x13n
    privacy: closed
    repos:
      autoscaler: read
  sig-autoscaling-api-reviews:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    - mwielgus
    privacy: closed
  sig-autoscaling-bugs:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-feature-requests:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-misc:
    description: ""
    members:
    - bigdarkclown
    - gjtempleton
    - maciekpytel
    - towca
    - x13n
    privacy: closed
  sig-autoscaling-pr-reviews:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-proposals:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-test-failures:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-leads:
    description: ""
    members:
    - gjtempleton
    - maciekpytel
    privacy: closed
  sig-autoscaling-milestone-maintainers:
    description: Contributors who can use `/milestone` in the autoscaling repo
    members:
    - adrianmoisey
    - kwiesmueller
    - omerap12
    - raywainman
    - voelzmo
    privacy: closed
