name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- aaroniscode
- aaronlevy
- adelina-t
- Adirio
- adohe
- adrianludwin
- ahg-g
- ahmetb
- ainmosni
- akutz
- alculquicondor
- aledbf
- alejandrox1
- alenkacz
- alexeldeib
- alexgervais
- alijahnas
- alisondy
- alvaroaleman
- ameukam
- amwat
- amy
- andrewrynhard
- andrewsykim
- andyzhangx
- anfernee
- animeshsingh
- ant31
- aojea
- apelisse
- aramase
- ArangoGutierrez
- ashish-amarnath
- ashishranjan738
- atoato88
- Atoms
- aveshagarwal
- awesomenix
- b01901143
- balajismaniam
- BaluDontu
- barney-s
- bartsmykla
- benmoss
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- bmelbourne
- bowei
- bozzo
- Bradamant3
- bradtopol
- brahmaroutu
- brancz
- brianpursley
- bzub
- caesarxuchao
- calebamiles
- camilamacedo86
- carolynvs
- cartyc
- caseydavenport
- castrojo
- CecileRobertMichon
- celestehorgan
- chadswen
- chaosaffe
- charleszheng44
- cheftako
- chendotjs
- chenopis
- chewong
- childsb
- chizhg
- chrigl
- chris-short
- chriskim06
- christopherhein
- chuckha
- clarketm
- clarklee92
- claudiubelu
- clyang82
- cmluciano
- codenrhoden
- cofyc
- copejon
- corneliusweig
- cpanato
- craiglpeters
- cwdsuzhou
- d-nishi
- DahuK
- damemi
- danehans
- danielqsj
- danielSbastos
- danwinship
- dashpole
- davidewatson
- davidopp
- davidz627
- dberkov
- dcbw
- ddebroy
- deads2k
- deepak-vij
- deitch
- denkensk
- derekwaynecarr
- detiber
- devigned
- dhellmann
- dholbach
- dims
- DirectXMan12
- displague
- Divya063
- divyenpatel
- djzager
- dkoshkin
- dlipovetsky
- dmatch01
- dougm
- draveness
- droot
- dstrebel
- dvonthenen
- easeway
- eddiezane
- ehashman
- EleanorRigby
- elmiko
- entro-pi
- enxebre
- EppO
- ericavonb
- estroz
- Ethyling
- f0rmiga
- fabriziopandini
- fanzhangio
- Fei-Guo
- feiskyer
- figo
- flaper87
- floreks
- floryut
- font
- frankfarzan
- frapposelli
- fredkan
- frobware
- gab-satchi
- gabbifish
- gerred
- gianarb
- GinnyJI
- girikuncoro
- giuseppe
- gnufied
- grodrigues3
- guineveresaenger
- gyliu513
- gyuho
- haiyanmeng
- hakman
- hannibalhuang
- hantaowang
- haosdent
- haoshuwei
- hardikdr
- hasbro17
- hasheddan
- hbagdi
- hchenxa
- hectorj2f
- hello2mao
- hex108
- hh
- hickeyma
- hidekazuna
- hjacobs
- hoegaarden
- holmsten
- hpandeycodeit
- Huang-Wei
- humblec
- hwdef
- hzxuzhonghu
- iamemilio
- IanColdwater
- ibzib
- idealhack
- ingvagabund
- interma
- irfanurrehman
- irvifa
- ixdy
- jackielii
- jacobsmith928
- JamesLaverack
- janetkuo
- javier-b-perez
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jdumars
- jeefy
- jefftree
- jeffvance
- jeffwan
- jennybuckley
- JeremyOT
- jeremyrickard
- jhvhs
- jiatongw
- Jiawei0227
- jichenjc
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jinzhejz
- joelanford
- JoelSpeed
- johnharris85
- johnsonj
- joncwong
- joonas
- jpbetz
- jpeach
- jqmichael
- jsafrane
- jsturtevant
- juan-lee
- juanvallejo
- justaugustus
- justinsb
- k-toyoda-pi
- k82cn
- kad
- kaslin
- Katharine
- kawych
- kbarnard10
- kbhawkey
- kendallnelson
- kensipe
- kevin-wangzefeng
- kfox1111
- khenidak
- kkmsft
- kmova
- knight42
- KnVerey
- kow3ns
- kris-nova
- krmayankk
- krousey
- krzyzacy
- ksubrmnn
- kvaps
- kwiesmueller
- lachie83
- lafh
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- linki
- Lion-Wei
- listx
- Liujingfang1
- lixiang233
- liyinan926
- liztio
- loburm
- logicalhan
- LuckySB
- luxas
- m00nf1sh
- m1093782566
- maciaszczykm
- maisem
- mariantalla
- markyjackson-taulia
- marosset
- marpaia
- marquiz
- mars1024
- marun
- marwanad
- mattcary
- mattfarina
- mattymo
- mauilion
- mbbroberg
- mboersma
- mcrute
- mengqiy
- MHBauer
- micahhausler
- michaelbeaumont
- michaelgugino
- michaelmdresser
- michelleN
- michmike
- mikedanese
- miouge1
- mirwan
- misterikkit
- mkimuram
- mkorbi
- mkumatag
- Monkeyanator
- monopole
- mook-as
- MorrisLaw
- mortent
- morvencao
- moshloop
- mowangdk
- MrHohn
- mrmrcoleman
- mrunalp
- msau42
- mszostok
- mtaufen
- munnerz
- MushuEE
- mylesagray
- mytunguyen
- nader-ziada
- nan-yu
- ncdc
- nckturner
- neolit123
- nicolehanjing
- NicoleYson
- nikopen
- nilo19
- njuettner
- noamran
- nzoueidi
- odinuge
- onlydole
- onyiny-ang
- oomichi
- palnabarun
- parispittman
- PatrickLang
- pbnj
- phanimarupaka
- phenixblue
- philips
- phoenixking25
- phyber
- piosz
- piotrmiskiewicz
- pjbgf
- pjh
- Pluies
- pmorie
- pohly
- prachirp
- prankul88
- prksu
- prydonius
- ps882
- puerco
- puja108
- pwittrock
- quinton-hoole
- qvicksilver
- raelga
- Raffo
- RainbowMango
- Rajakavitha1
- rajansandeep
- rajula96reddy
- Random-Liu
- randomvariable
- RaunakShah
- ravisantoshgudimetla
- rbitia
- resouer
- rhatdan
- richardcase
- rifelpet
- rikatz
- ritazh
- riverzhang
- rjbez17
- rlenferink
- rmenn
- roberthbailey
- robinpercy
- robscott
- roycaihw
- rrati
- rsmitty
- rudoi
- runcom
- runyontr
- s-ito-ts
- s-urbaniak
- saad-ali
- saikat-royc
- salaxander
- sallyom
- samudralavamshi54
- sanchezl
- SandeepPissay
- saschagrunert
- SataQiu
- savitharaghunathan
- sboeuf
- sbueringer
- screeley44
- seanmalloy
- seans3
- sedefsavas
- serathius
- serbrech
- SergeyKanzhelev
- sethmccombs
- sethp-nr
- sethpollack
- sflxn
- sftim
- sfzylad
- Sh4d1
- shashidharatd
- shawn-hurley
- sheerun
- Shell32-Natsu
- shivi28
- shu-mutou
- sidharthsurana
- smarterclayton
- soggiest
- sohankunkerkar
- soltysh
- SomtochiAma
- soniasingla
- sophieliu15
- spurin
- srampal
- srm09
- stealthybox
- stevekuznetsov
- steveperry-53
- sttts
- syjabri
- tabbysable
- tahsinrahman
- tanjacky
- tanjunchen
- tao12345666333
- taragu
- tariq1890
- tashimi
- tengqm
- thandayuthapani
- thebsdbox
- thockin
- timothysc
- timyinshi
- tizhou86
- tlereste
- tomassedovic
- TommyLike
- tpepper
- truongnh1992
- trutx
- umohnani8
- Verolop
- verult
- vikaschoudhary16
- vincepri
- vinny-sabatini
- vishakhanihore
- vjdhama
- vllry
- voor
- wawa0210
- wfernandes
- wk8
- wlan0
- wongma7
- woopstar
- x13n
- xiangpengzhao
- xianlubird
- xichengliudui
- xing-yang
- xmudrii
- xrmzju
- xunpan
- yagonobre
- yastij
- yiqigao217
- ykakarap
- yliaog
- yodahekinsew
- youngnick
- ytsarev
- yuanchen8911
- yuanying
- yue9944882
- yujuhong
- yujunz
- zacharysarah
- ZeroMagic
- zhuangqh
- zhucan
- zimmertr
- zouyee
- ZP-AlwaysWin
- zparnold
- zulandar
- zvonkok
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mattfarina
    - mortent
    - nan-yu
    - prydonius
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - balajismaniam
    privacy: closed
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - balajismaniam
    - marquiz
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
