name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- grodrigues3
- idvoretskyi
- k8s-ci-robot
- spiffxp
- thelinuxfoundation
members:
- ant31
- apelisse
- bgrant0607
- Birdrock
- carolynvs
- castrojo
- christopherhein
- chuckha
- davidewatson
- davidz627
- deads2k
- derekwaynecarr
- detiber
- dims
- DirectXMan12
- droot
- fanzhangio
- feiskyer
- font
- frapposelli
- guineveresaenger
- gyliu513
- hoegaarden
- ingvagabund
- irfanurrehman
- jbeda
- jberkus
- jdumars
- jeremyrickard
- justinsb
- kow3ns
- krmayankk
- lavalamp
- lichuqiang
- Liujingfang1
- liztio
- marun
- mattfarina
- mengqiy
- michelleN
- monopole
- mrbobbytables
- mrunalp
- msau42
- onyiny-ang
- parispittman
- philips
- pmorie
- prydonius
- pwittrock
- quinton-hoole
- Random-Liu
- roberthbailey
- robinpercy
- runcom
- saad-ali
- seans3
- shashidharatd
- smarterclayton
- thockin
- timothysc
- totherme
- verult
