name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- nikhita
- spiffxp
- thelinuxfoundation
members:
- adelina-t
- adohe
- ahmetb
- ainmosni
- akutz
- alejandrox1
- alvaroaleman
- ameukam
- amwat
- andrewsykim
- andyzhangx
- anfernee
- animeshsingh
- ant31
- aojea
- apelisse
- ashish-amarnath
- atoato88
- Atoms
- awesomenix
- balajismaniam
- bclau
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- Bradamant3
- brancz
- bryk
- caesarxuchao
- carolynvs
- castrojo
- chadswen
- chaosaffe
- cheftako
- chenopis
- childsb
- chrigl
- christopherhein
- chuckha
- codenrhoden
- cofyc
- d-nishi
- danehans
- danielqsj
- dashpole
- davidewatson
- davidopp
- davidz627
- ddebroy
- deads2k
- denkensk
- derekwaynecarr
- detiber
- dholbach
- dims
- DirectXMan12
- dkoshkin
- dlipovetsky
- dmatch01
- dougm
- droot
- dstrebel
- dvonthenen
- easeway
- Ethyling
- fabianofranz
- fabriziopandini
- fanzhangio
- feiskyer
- figo
- flaper87
- floreks
- font
- frapposelli
- giuseppe
- grodrigues3
- guineveresaenger
- gyliu513
- gyuho
- hardikdr
- hchenxa
- hello2mao
- hex108
- hh
- hidekazuna
- hoegaarden
- holmsten
- hzxuzhonghu
- iamemilio
- ibzib
- idealhack
- ingvagabund
- interma
- irfanurrehman
- janetkuo
- javier-b-perez
- jbeda
- jberkus
- jdumars
- jeefy
- jeffwan
- jennybuckley
- jeremyrickard
- jichenjc
- jingxu97
- jinzhejz
- JoelSpeed
- johnsonj
- jsafrane
- juan-lee
- juanvallejo
- justaugustus
- justinsb
- k82cn
- kad
- Katharine
- kow3ns
- kris-nova
- krmayankk
- krousey
- krzyzacy
- kwiesmueller
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- Lion-Wei
- listx
- Liujingfang1
- liyinan926
- liztio
- luxas
- m00nf1sh
- m1093782566
- maciaszczykm
- maisem
- mariantalla
- marpaia
- marquiz
- marun
- marwanad
- mattfarina
- mattymo
- mauilion
- mcrute
- mengqiy
- michelleN
- michmike
- miouge1
- mirwan
- mkumatag
- Monkeyanator
- monopole
- morvencao
- mrbobbytables
- mrunalp
- msau42
- mtaufen
- munnerz
- ncdc
- neolit123
- nikopen
- onyiny-ang
- parispittman
- PatrickLang
- philips
- phyber
- piosz
- pmorie
- prydonius
- puja108
- pwittrock
- quinton-hoole
- Random-Liu
- randomvariable
- rhatdan
- ritazh
- riverzhang
- rlenferink
- roberthbailey
- robinpercy
- runcom
- saad-ali
- saschagrunert
- sboeuf
- seans3
- serbrech
- sflxn
- sfzylad
- shashidharatd
- shawn-hurley
- shu-mutou
- sidharthsurana
- smarterclayton
- soggiest
- sohankunkerkar
- soltysh
- srampal
- sttts
- suleisl2000
- syjabri
- tahsinrahman
- tao12345666333
- taragu
- tariq1890
- tashimi
- thockin
- timothysc
- tizhou86
- tomassedovic
- TommyLike
- totherme
- tpepper
- umohnani8
- verult
- vikaschoudhary16
- vincepri
- wk8
- wongma7
- woopstar
- xiangpengzhao
- xmudrii
- xunpan
- yagonobre
- yastij
- yliaog
- yujuhong
- zacharysarah
- zouyee
- zvonkok
teams:
  application-admins:
    description: admin access to application
    members:
    - kow3ns
    - mattfarina
    - prydonius
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cluster-api-provider-vsphere-admins:
    description: admin access to cluster-api-provider-vsphere-admins
    maintainers:
    - spiffxp
    members:
    - frapposelli
    - sflxn
    privacy: closed
  cluster-api-provider-vsphere-maintainers:
    description: write access to cluster-api-provider-vsphere
    maintainers:
    - spiffxp
    members:
    - figo
    - frapposelli
    - sflxn
    - sidharthsurana
    privacy: closed
  cri-tools-admins:
    description: admin access to cri-tools
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: write access to cri-tools
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: admin access to dashboard-metrics-scraper
    members:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: write access to dashboard-metrics-scraper
    members:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  etcdadm-admins:
    description: admin access to etcdadm
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  etcdadm-maintainers:
    description: write access to etcdadm
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: ""
    members:
    - msau42
    - saad-ali
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: ""
    members:
    - msau42
    - saad-ali
    privacy: closed
  kind-admins:
    description: ""
    members:
    - BenTheElder
    - munnerz
    privacy: closed
  kind-maintainers:
    description: ""
    members:
    - BenTheElder
    - munnerz
    privacy: closed
  kube-batch-admins:
    description: admin access to kube-batch
    maintainers:
    - calebamiles
    - spiffxp
    members:
    - k82cn
    - timothysc
    privacy: closed
  kube-batch-maintainers:
    description: write access to kube-batch
    maintainers:
    - calebamiles
    - spiffxp
    members:
    - k82cn
    - timothysc
    privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  kubespray-admins:
    description: ""
    members:
    - ant31
    - chadswen
    - mattymo
    privacy: closed
  kubespray-maintainers:
    description: ""
    members:
    - ant31
    - Atoms
    - chadswen
    - mattymo
    - miouge1
    - mirwan
    - riverzhang
    - woopstar
    privacy: closed
  mutating-trace-admission-controller:
    description: ""
    maintainers:
    - calebamiles
    privacy: closed
    teams:
      mutating-trace-admission-controller-admins:
        description: admin access to mutating-trace-admission-controller
        maintainers:
        - calebamiles
        privacy: closed
      mutating-trace-admission-controller-maintainers:
        description: write access to mutating-trace-admission-controller
        maintainers:
        - calebamiles
        privacy: closed
  node-feature-discovery-admins:
    description: ""
    members:
    - balajismaniam
    privacy: closed
  node-feature-discovery-maintainers:
    description: ""
    members:
    - balajismaniam
    - marquiz
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: admin access to sig-storage-lib-external-provisioner
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: write access to sig-storage-lib-external-provisioner
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: ""
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: ""
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  testing_frameworks-admins:
    description: admin access for testing_frameworks
    members:
    - hoegaarden
    - totherme
    privacy: closed
  testing_frameworks-maintainers:
    description: write access to testing_frameworks
    members:
    - liztio
    - marun
    privacy: closed
  windows-testing-admins:
    description: ""
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
  windows-testing-maintainers:
    description: ""
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
