admins:
- ameukam
- cblecker
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- palnabarun
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 196Ikuchil
- "249043822"
- a7i
- aaroniscode
- aaronlevy
- aartij17
- abhiraut
- abhisheksinghbaghel
- Abirdcfly
- adelina-t
- Adirio
- adohe
- adrianchiris
- adrianludwin
- adtac
- agradouski
- ahg-g
- ahmetb
- ainmosni
- AkihiroSuda
- akutz
- aladewberry
- alculquicondor
- aledbf
- alejandrox1
- alenkacz
- alexander-demichev
- alexeldeib
- alexgervais
- alexzielenski
- alijahnas
- alisondy
- AlmogBaku
- alvaroaleman
- amacaskill
- ambiknai
- Amulyam24
- amwat
- amy
- andrewrynhard
- andrewsykim
- AndyXiangLi
- andyzhangx
- anfernee
- animeshsingh
- Ankitasw
- ant31
- anusha94
- aojea
- apelisse
- apricote
- arahamad-zz
- aramase
- ArangoGutierrez
- aravindhp
- arghya88
- Arhell
- ArkaSaha30
- arthurdm
- aryan9600
- ash2k
- ashish-amarnath
- ashishranjan738
- Ashley-wenyizha
- astoycos
- Atharva-Shinde
- atoato88
- Atoms
- aveshagarwal
- AvineshTripathi
- awesomenix
- ayberk
- b01901143
- BaluDontu
- barney-s
- bartsmykla
- benmoss
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- BinacsLee
- Birdrock
- bishal7679
- bmelbourne
- BobyMCbobs
- boddumanohar
- bowei
- bozzo
- Bradamant3
- bradmccoydev
- bradtopol
- brahmaroutu
- brancz
- brianpursley
- bridgetkromhout
- bswartz
- bzub
- caesarxuchao
- cailynse
- calebamiles
- camilamacedo86
- carlisia
- carolynvs
- cartyc
- caseydavenport
- castrojo
- CatherineF-dev
- cchengleo
- CecileRobertMichon
- celanthe
- celestehorgan
- chadswen
- champtar
- chaodaiG
- chaosaffe
- charleszheng44
- chases2
- cheftako
- chendotjs
- chetak123
- chethanv28
- chewong
- childsb
- chizhg
- chrigl
- chris-short
- chrischdi
- chrishenzie
- chriskim06
- chrismetz09
- christopherhein
- chuckha
- chymy
- cici37
- CIPHERTron
- cjwagner
- clarketm
- clarklee92
- claudiubelu
- clyang82
- cmluciano
- cmurphy
- codenrhoden
- coderanger
- coffeepac
- cofyc
- copejon
- corneliusweig
- cpanato
- cprivitere
- craiglpeters
- cristicalin
- csantanapr
- cwdsuzhou
- cyclinder
- d-nishi
- DahuK
- damemi
- danehans
- danielqsj
- danielSbastos
- Danil-Grigorev
- danwinship
- dashpole
- davidewatson
- davidjumani
- davidopp
- davidvossel
- davidz627
- dberkov
- dcantah
- dcbw
- ddebroy
- deads2k
- Debanitrkl
- deejross
- deepak-vij
- deepakkinni
- deitch
- denkensk
- derekwaynecarr
- detiber
- devigned
- dgrisonnet
- dharmjit
- dhellmann
- dholbach
- dims
- DiptoChakrabarty
- DirectXMan12
- displague
- divya-mohan0209
- Divya063
- divyenpatel
- djzager
- dkoshkin
- dlipovetsky
- dobsonj
- dongsupark
- doshyt
- dougm
- dougsland
- dpasiukevich
- draveness
- drmorr0
- droot
- dstrebel
- dthorsen
- dvonthenen
- easeway
- eddiezane
- edreed
- ehashman
- EleanorRigby
- electrocucaracha
- elmiko
- encodeflush
- endocrimes
- entro-pi
- enxebre
- EppO
- erain
- ericavonb
- erikgb
- ErikJiang
- estroz
- Ethyling
- evansheng
- everettraven
- everpeace
- f0rmiga
- fabriziopandini
- Fedosin
- Fei-Guo
- feiskyer
- fejta
- feloy
- figo
- FillZpp
- flaper87
- floreks
- floryut
- font
- fpetkovski
- frankfarzan
- frapposelli
- fredkan
- FriedrichWilken
- frobware
- fsmunoz
- furkatgofurov7
- gab-satchi
- gabbifish
- Garima-Negi
- gavinfish
- geetikabatra
- geoffcline
- gerred
- gianarb
- GinnyJI
- girikuncoro
- giuseppe
- gjkim42
- gkarthiks
- gnoam
- gnufied
- gohilankit
- grodrigues3
- gtxu
- guineveresaenger
- gyliu513
- gyuho
- haiyanmeng
- hakman
- hanamantagoudvk
- hanlins
- hannibalhuang
- hantaowang
- haosdent
- hardikdr
- hasbro17
- hasheddan
- hbagdi
- hchenxa
- hectorj2f
- hello2mao
- hex108
- hh
- hickeyma
- hidekazuna
- hjacobs
- hoegaarden
- holmsten
- howardjohn
- hpandeycodeit
- Huang-Wei
- humblec
- hwdef
- hzxuzhonghu
- iamemilio
- IanColdwater
- ibabou
- ibzib
- idealhack
- ingvagabund
- interma
- invidian
- irfanurrehman
- irvifa
- isaacdorfman
- ixdy
- iXinqi
- jackfrancis
- jackielii
- jacobsmith928
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- jasonbraganza
- javadoors
- javier-b-perez
- jayesh-srivastava
- jayonlau
- jaypipes
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jdumars
- jeefy
- jefftree
- jeffvance
- jeffwan
- jennybuckley
- jeremyje
- JeremyOT
- jeremyrickard
- jhrozek
- jhvhs
- jiahuif
- JiaoDean
- jiatongw
- Jiawei0227
- jichenjc
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jinsongo
- jkh52
- jlsong01
- jmrodri
- jmwurst
- joekr
- joelanford
- JoelSpeed
- johananl
- johannesfrey
- johngmyers
- johnharris85
- johnSchnake
- johnsonj
- JohnTitor
- joncwong
- Jont828
- jonyhy96
- joonas
- josh-ferrell
- jpbetz
- jpeach
- jqmichael
- jsafrane
- jsturtevant
- juan-lee
- juanvallejo
- justaugustus
- justin-chizer
- justinsb
- jweite-amazon
- jwtty
- jyotimahapatra
- k-toyoda-pi
- k82cn
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- karlkfi
- Karthik-K-N
- kaslin
- Katharine
- kavyashree-r
- kawych
- kbarnard10
- kbasv
- kbhawkey
- keithmattix
- kendallnelson
- kensipe
- kerthcet
- kevin-wangzefeng
- kevindelgado
- kfox1111
- khenidak
- killianmuldoon
- kishorj
- kkeshavamurthy
- kkmsft
- kmova
- knabben
- knelasevero
- knight42
- KnVerey
- koba1t
- kow3ns
- kris-nova
- krishchow
- krmayankk
- krol3
- krousey
- krzyzacy
- ksubrmnn
- kundan2707
- kvaps
- kwiesmueller
- lachie83
- lafh
- landreasyan
- lauralorenz
- lavalamp
- leakingtapan
- leiyiz
- leonardpahlke
- lianghao208
- lichuqiang
- liggitt
- linki
- Lion-Wei
- lipingxue
- listx
- Liujingfang1
- liupeng0518
- lixiang233
- liyinan926
- lizhuqi
- liztio
- loburm
- LochanRn
- logicalhan
- longwuyuan
- lou-lan
- lubronzhan
- LuckySB
- luxas
- lzhecheng
- m-Bilal
- m-messiah
- m00nf1sh
- macaptain
- maciaszczykm
- Madhan-SWE
- MadhavJivrajani
- Madhur97
- maelvls
- makkes
- maplain
- MarcelMue
- MarcusNoble
- mariantalla
- mark-nc
- markmc
- markyjackson-taulia
- marosset
- marquiz
- mars1024
- MartinForReal
- marun
- marwanad
- mattcary
- mattfarina
- mattymo
- mauilion
- mauriciopoppe
- maxdrib
- MaxRenaud
- MaxRink
- mayankshah1607
- mbbroberg
- mboersma
- mcluseau
- mcrute
- mdbooth
- meghanajangi
- mehabhalodiya
- mengqiy
- MHBauer
- micahhausler
- michaelbeaumont
- michaelgugino
- michaelmdresser
- michelle192837
- michelleN
- michmike
- mikedanese
- mikemorris
- mikeshng
- mimowo
- minbaev
- miouge1
- mirwan
- misterikkit
- mkimuram
- mkorbi
- mkumatag
- Monkeyanator
- monopole
- monotek
- mook-as
- morengab
- MorrisLaw
- mortent
- morvencao
- moshloop
- mowangdk
- mpherman2
- mrajashree
- MrHohn
- mritunjaysharma394
- mrmrcoleman
- mrog
- mrunalp
- msau42
- mszostok
- mtaufen
- mukhoakash
- munnerz
- MushuEE
- myan9
- mylesagray
- mytunguyen
- mzaian
- n3wscott
- nader-ziada
- nak3
- Namanl2001
- nan-yu
- natalisucks
- natasha41575
- navidshaikh
- ncdc
- nckturner
- nearora-msft
- nebhale
- necatican
- nehaLohia27
- neolit123
- nicolehanjing
- NicoleYson
- NikhilSharmaWe
- nikopen
- nilekhc
- nilo19
- nirarg
- nirmalaagash
- njuettner
- noamran
- nprokopic
- nunnatsa
- nzoueidi
- odinuge
- olemarkus
- olivierlemasle
- onlydole
- onyiny-ang
- oomichi
- oprinmarius
- orsenthil
- oscr
- pacoxu
- parispittman
- pasqualet
- PatrickLang
- pbnj
- Pensu
- perithompson
- petr-muller
- phanimarupaka
- phenixblue
- philips
- phillipsj
- phoenixking25
- phyber
- piosz
- piotrmiskiewicz
- pjbgf
- pjh
- Pluies
- pmorie
- pohly
- prachirp
- prafull01
- Prajyot-Parab
- prankul88
- prankulmahajan
- pravarag
- Priyankasaggu11929
- prksu
- Promaethius
- prydonius
- ps882
- psschwei
- puerco
- puja108
- PurneswarPrasad
- PushkarJ
- pwittrock
- pydctw
- qabpea
- qbarrand
- qiujian16
- qiutongs
- quinton-hoole
- qvicksilver
- raelga
- Raffo
- RainbowMango
- Rajakavitha1
- Rajalakshmi-Girish
- rajansandeep
- rajula96reddy
- ramrodo
- Random-Liu
- randomvariable
- rashmigottipati
- RaunakShah
- ravisantoshgudimetla
- rbitia
- rdpsin
- rejoshed
- relyt0925
- resouer
- reylejano
- rficcaglia
- rhatdan
- riaankl
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- riverzhang
- rjbez17
- rlenferink
- rmenn
- rmohr
- roberthbailey
- robinpercy
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- roycaihw
- rrati
- rsmitty
- rtsp
- rudoi
- runyontr
- s-ito-ts
- s-kawamura-w664
- s-urbaniak
- s04
- saad-ali
- sahilvv
- saikat-royc
- salaxander
- sallyom
- samos123
- samudralavamshi54
- sanchezl
- SandeepPissay
- sandipanpanda
- SanikaGawhane
- sanposhiho
- sanwishe
- SaranBalaji90
- sarazqy
- saschagrunert
- sashrith
- SataQiu
- savitharaghunathan
- sayantani11
- sboeuf
- sbose78
- sbueringer
- schrej
- scothis
- screeley44
- seanmalloy
- seans3
- seanschneeweiss
- sedefsavas
- serathius
- serbrech
- SergeyKanzhelev
- sethmccombs
- sethp-nr
- sethpollack
- sftim
- sfzylad
- Sh4d1
- shalini-b
- shaneutt
- shashidharatd
- shawn-hurley
- sheerun
- Shell32-Natsu
- ShivamTyagi12345
- shivanshu1333
- shivi28
- shu-mutou
- shuaijinchao
- ShwethaKumbla
- shyamradhakrishnan
- shysank
- sidharthsurana
- simrangupta234
- Skarlso
- skriss
- sladyn98
- smarterclayton
- soggiest
- sohankunkerkar
- soltysh
- SomtochiAma
- sonasingh46
- soniasingla
- sophieliu15
- spiffxp
- spurin
- spzala
- srampal
- srm09
- starpit
- stealthybox
- stevehipwell
- stevekuznetsov
- steveperry-53
- stmcginnis
- strongjz
- sttts
- sunpa93
- swatisehgal
- SyamSundarKirubakaran
- szuecs
- t-inu
- tabbysable
- tahsinrahman
- tallclair
- tam7t
- tanjacky
- tanjunchen
- tao12345666333
- taragu
- tariq1890
- tashimi
- tengqm
- thandayuthapani
- thebsdbox
- thejoycekung
- thockin
- timoreimann
- timothysc
- timyinshi
- tizhou86
- tkashem
- tlereste
- tobiasgiese
- tokt
- tomassedovic
- TommyLike
- torredil
- tpepper
- truongnh1992
- trutx
- tssurya
- twilight0620
- tylerferrara
- umangachapagain
- umohnani8
- upodroid
- varshaprasad96
- vdhanan
- Verolop
- verult
- vikaschoudhary16
- vincepri
- vinny-sabatini
- vishakhanihore
- VivekThrivikraman-est
- vjdhama
- vladimirvivien
- vllry
- voor
- vrabbi
- wangchen615
- wawa0210
- weiling61
- wentao-zh
- wfernandes
- wilsonehusin
- wk8
- wlan0
- wongma7
- wongni
- woopstar
- wzshiming
- x13n
- Xenwar
- xiangpengzhao
- xianlubird
- xichengliudui
- xing-yang
- xinydev
- xmudrii
- xrmzju
- xunpan
- Xunzhuo
- yagonobre
- yangjunmyfm192085
- yankay
- yastij
- ybettan
- yevgeny-shnaidman
- yibozhuang
- yiqigao217
- ykakarap
- yliaog
- yodahekinsew
- yonatankahana
- youngnick
- YoyinZyc
- ytsarev
- yuanchen8911
- yuanying
- yue9944882
- YuikoTakada
- yujuhong
- yujunz
- yuwenma
- zacharysarah
- ZeroMagic
- zhangxyjlu
- zhengtianbao
- zhuangqh
- zhucan
- zimmertr
- ziyi-xie
- zmalik
- zouyee
- ZP-AlwaysWin
- zparnold
- zqzten
- zshihang
- zulandar
- zvonkok
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mattfarina
    - mortent
    - nan-yu
    - prydonius
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  gcp-compute-persistent-disk-csi-driver-admins:
    description: Admin access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-compute-persistent-disk-csi-driver-maintainers:
    description: Write access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    privacy: closed
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - marquiz
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    privacy: closed
