admins:
- cblecker
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 196Ikuchil
- "249043822"
- 92nqb
- a7i
- aaroniscode
- aaronlevy
- aartij17
- abhay-krishna
- abhiraut
- abhisheksinghbaghel
- Abirdcfly
- achernevskii
- adelina-t
- adikul30
- adilGhaffarDev
- Adirio
- adohe
- adriananeci
- adrianchiris
- adrianludwin
- adtac
- afirth
- agradouski
- ahg-g
- AhmedGrati
- ahmetb
- ainmosni
- airbornepony
- aj11anuj
- akankshakumari393
- akankshapanse
- AkihiroSuda
- akutz
- aladewberry
- AlbeeSo
- alculquicondor
- aledbf
- alejandrox1
- alenkacz
- alexander-demicev
- alexeldeib
- alexgervais
- AlexNPavel
- alexzielenski
- alijahnas
- alisondy
- AlmogBaku
- alvaroaleman
- amacaskill
- ambiknai
- ameukam
- amolmote
- Amulyam24
- amwat
- amy
- AnaMMedina21
- AndiDog
- andrewrynhard
- AndrewSirenko
- andrewsykim
- AndyXiangLi
- andyzhangx
- anfernee
- animeshsingh
- aniruddha2000
- Ankitasw
- annasong20
- ant31
- anusha94
- aojea
- apelisse
- apricote
- arahamad
- aramase
- ArangoGutierrez
- aravindhp
- arghya88
- ArkaSaha30
- arkodg
- aroradaman
- arthurdm
- aryan9600
- asa3311
- ash2k
- ashish-amarnath
- ashishranjan738
- Ashley-wenyizha
- asim-reza
- astoycos
- Atharva-Shinde
- atoato88
- Atoms
- AverageMarcus
- aveshagarwal
- AvineshTripathi
- awesomenix
- ayberk
- b01901143
- BaluDontu
- barney-s
- bart0sh
- bartsmykla
- bells17
- benmoss
- BenTheElder
- bertinatto
- bg-chun
- bgrant0607
- bigkraig
- binacs
- Birdrock
- bishal7679
- BlaineEXE
- bmelbourne
- BobyMCbobs
- boddumanohar
- bowei
- bozzo
- Bradamant3
- bradmccoydev
- bradtopol
- brahmaroutu
- brancz
- brianpursley
- bridgetkromhout
- Bryce-Soghigian
- bswartz
- bugoverdose
- bwagner5
- byako
- bzub
- caesarxuchao
- cahillsf
- cailynse
- calebamiles
- camilamacedo86
- campoy
- candita
- carlisia
- carlory
- carolynvs
- cartermckinnon
- cartyc
- caseydavenport
- castrojo
- CatherineF-dev
- cchengleo
- ccojocar
- CecileRobertMichon
- celanthe
- celestehorgan
- chadswen
- champtar
- chaodaiG
- chaosaffe
- charles-chenzz
- charleszheng44
- chases2
- cheftako
- chendave
- chendotjs
- chengxiangdong
- chetak123
- chethanv28
- chewong
- childsb
- chiukapoor
- chizhg
- chrigl
- chris-short
- chrischdi
- chrisdoherty4
- chrishenzie
- chriskim06
- chrismetz09
- christopherhein
- chuckha
- chymy
- cici37
- CIPHERTron
- cjwagner
- clarketm
- clarklee92
- claudiubelu
- clyang82
- cmluciano
- cmurphy
- cnmcavoy
- codefromthecrypt
- codenrhoden
- coderanger
- coffeepac
- cofyc
- ConnorJC3
- copejon
- corneliusweig
- cpanato
- cprivitere
- craiglpeters
- cristicalin
- csantanapr
- cvvz
- cwdsuzhou
- cyclinder
- d-nishi
- DahuK
- damdo
- damemi
- danehans
- danielqsj
- danielSbastos
- danielvegamyhre
- Danil-Grigorev
- dannawang0221
- danwinship
- dashpole
- davidewatson
- davidjumani
- davidopp
- davidvossel
- davidz627
- dberkov
- dbonfigli
- dcantah
- dcbw
- ddebroy
- deads2k
- Debanitrkl
- deejross
- deepak-vij
- deepakkinni
- deitch
- denkensk
- derekwaynecarr
- detiber
- devigned
- dgrisonnet
- dharaneeshvrd
- dharmjit
- dhellmann
- dholbach
- DimpleRajaVamsi
- dims
- dipankardas011
- DiptoChakrabarty
- DirectXMan12
- displague
- divya-mohan0209
- Divya063
- divyenpatel
- dixudx
- djzager
- dkoshkin
- dlipovetsky
- dntosas
- dobsonj
- dongsupark
- doshyt
- dougm
- dougsland
- dpasiukevich
- dprotaso
- draveness
- drew-viles
- drewhagen
- drmorr0
- droot
- droslean
- dstrebel
- dthorsen
- dtzar
- dulek
- dvonthenen
- Dyanngg
- easeway
- eddiezane
- eddycharly
- edreed
- ehashman
- Eileen-Yu
- EleanorRigby
- electrocucaracha
- elezar
- ellistarn
- elmiko
- EmilienM
- endocrimes
- engedaam
- enj
- entro-pi
- enxebre
- EppO
- erain
- ericavonb
- erikgb
- ErikJiang
- esigo
- estroz
- evansheng
- everettraven
- everpeace
- ezzoueidi
- f0rmiga
- fabi200123
- fabriziopandini
- faiq
- Fedosin
- Fei-Guo
- feiskyer
- fejta
- feloy
- fengshunli
- ffromani
- figo
- FillZpp
- Fish-pro
- fiunchinho
- flaper87
- floreks
- floryut
- fmuyassarov
- font
- fpetkovski
- frankbu
- frankfarzan
- frapposelli
- freddie400
- fredkan
- FriedrichWilken
- frobware
- fsmunoz
- furkatgofurov7
- fuxiuyin
- fykaa
- g-gaston
- gab-satchi
- gabbifish
- Garima-Negi
- Garrybest
- gauravkghildiyal
- Gauravpadam
- gavinfish
- gcs278
- geetikabatra
- Gekko0114
- geoffcline
- gerred
- gianarb
- GinnyJI
- girikuncoro
- giuseppe
- gjkim42
- gjtempleton
- gkarthiks
- gnoam
- gnufied
- gohilankit
- gomesjason
- gottwald
- grodrigues3
- gtxu
- guineveresaenger
- gyliu513
- gyohuangxin
- gyuho
- hackeramitkumar
- hailkomputer
- haircommander
- haiyanmeng
- hakman
- hanamantagoudvk
- hangscer8
- hanlins
- hannibalhuang
- hantaowang
- hanyuel
- haosdent
- hardikdr
- harshanarayana
- hasbro17
- hasheddan
- hbagdi
- hchenxa
- hectorj2f
- helen-frank
- hello2mao
- hex108
- hh
- hickeyma
- hidekazuna
- Hii-Arpit
- HirazawaUi
- hjacobs
- hoegaarden
- holmsten
- hosseinsalahi
- howardjohn
- hpandeycodeit
- hrak
- Huang-Wei
- hughdanliu
- humblec
- huntergregory
- hwdef
- hzxuzhonghu
- iamemilio
- IanColdwater
- ibabou
- ibzib
- idealhack
- idvoretskyi
- imnmo
- ingvagabund
- inteon
- interma
- intUnderflow
- invidian
- ipochi
- irfanurrehman
- irvifa
- isaacdorfman
- ixdy
- iXinqi
- jackfrancis
- jackielii
- jacobsmith928
- jacobwolfaws
- jaehnri
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- jasonbraganza
- javadoors
- javier-b-perez
- jayesh-srivastava
- jayonlau
- jaypipes
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jbpratt
- jdumars
- jeefy
- Jefftree
- jeffvance
- jeffwan
- jennybuckley
- jeremyje
- JeremyOT
- jeremyrickard
- jhrozek
- jhvhs
- jiahuif
- JiaoDean
- jiatongw
- Jiawei0227
- jichenjc
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jinsongo
- jjacobelli
- jkh52
- jklaw90
- jlamillan
- jlsong01
- jmdeal
- jmguzik
- jmhbnz
- jmrodri
- jmwurst
- joe-atzinger
- joekr
- joelanford
- JoelSpeed
- johananl
- johannesfrey
- johngmyers
- johnharris85
- johnSchnake
- johnsonj
- JohnTitor
- jonathan-innis
- joncwong
- Jont828
- jonyhy96
- joonas
- josh-ferrell
- jpbetz
- jpeach
- jpmcb
- jqmichael
- jrsapi
- jsafrane
- jsturtevant
- juan-lee
- juanvallejo
- judemars
- justaugustus
- justin-chizer
- justinsb
- jweite-amazon
- jwtty
- jyotimahapatra
- k-toyoda-pi
- k82cn
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- kaisoz
- kannon92
- karlkfi
- Karthik-K-N
- Kasambx
- kaslin
- Katharine
- Kavinjsir
- kavyashree-r
- kawych
- kbarnard10
- kbasv
- kbhawkey
- keithmattix
- kendallnelson
- kensipe
- kerthcet
- kevin-wangzefeng
- kevindelgado
- kflynn
- kfox1111
- khareyash05
- khenidak
- khoang98
- kiashok
- killianmuldoon
- kishorj
- kkeshavamurthy
- kkkkun
- kkmsft
- KKtheGhost
- klueska
- KlwntSingh
- kmova
- knabben
- knee-berts
- knelasevero
- knight42
- KnVerey
- koba1t
- kow3ns
- krishchow
- krisnova
- krmayankk
- krol3
- krousey
- krzyzacy
- ksubrmnn
- kundan2707
- kvaps
- kwiesmueller
- lachie83
- lafh
- landreasyan
- laozc
- lauralorenz
- lavalamp
- laxmikantbpandhare
- leakingtapan
- leiyiz
- lentzi90
- leonardpahlke
- levikobi
- lianghao208
- lichuqiang
- liggitt
- LingyanYin
- linki
- Lion-Wei
- LiorLieberman
- lipingxue
- listx
- Liujingfang1
- liupeng0518
- lixiang233
- liyinan926
- lizhuqi
- liztio
- loburm
- lobziik
- LochanRn
- logicalhan
- longwuyuan
- lou-lan
- louiscryan
- lubronzhan
- LuckySB
- luthermonson
- luxas
- lzhecheng
- m-Bilal
- m-messiah
- m00nf1sh
- macaptain
- maciaszczykm
- maciekpytel
- Madhan-SWE
- Madhur97
- maelvls
- makkes
- mandre
- maplain
- MarcelMue
- MarcusNoble
- mariantalla
- mark-nc
- markmc
- marosset
- marquiz
- mars1024
- MartinForReal
- marun
- marwanad
- MaryamTavakkoli
- mashby2022
- mateiidavid
- matrus2
- mattcary
- mattfarina
- mattfenwick
- matthyx
- mattymo
- mauilion
- mauriciopoppe
- maxdrib
- MaxRenaud
- MaxRink
- mayankshah1607
- MaysaMacedo
- mbbroberg
- mboersma
- mboukhalfa
- mcbenjemaa
- mcluseau
- mcrute
- mdbooth
- medyagh
- meghanajangi
- mehabhalodiya
- mengjiao-liu
- mengqiy
- mfahlandt
- MHBauer
- micahhausler
- michaelbeaumont
- michaelfromyeg
- michaelgugino
- michaelmdresser
- michelle192837
- Michelle951
- michelleN
- michmike
- mikedanese
- mikemorris
- mikeshng
- mimowo
- minbaev
- Miouge1
- mirwan
- misterikkit
- mjlshen
- mjudeikis
- mkimuram
- mkorbi
- mkumatag
- mlavacca
- mloiseleur
- mmerkes
- mnaser
- mneverov
- moadqassem
- mochizuki875
- moficodes
- Monkeyanator
- monopole
- monotek
- mook-as
- morengab
- MorrisLaw
- mortent
- morvencao
- moshloop
- mowangdk
- mpatlasov
- mpherman2
- mrajashree
- mresvanis
- MrFreezeex
- MrHohn
- mritunjaysharma394
- mrmrcoleman
- mrog
- mrueg
- mrunalp
- msau42
- mskanth972
- mszostok
- mtaufen
- mtougeron
- muddapu
- mukhoakash
- munnerz
- musaprg
- MushuEE
- mwielgus
- my-git9
- myan9
- mylesagray
- mytunguyen
- mzaian
- n3wscott
- nader-ziada
- nak3
- Namanl2001
- nan-yu
- natalisucks
- natasha41575
- navidshaikh
- nawazkh
- nayihz
- ncapps
- ncdc
- nckturner
- ndipebot
- nearora-msft
- nebhale
- necatican
- nehaLohia27
- neolit123
- nicolehanjing
- NicoleYson
- NikhilSharmaWe
- nikopen
- nilekhc
- nilo19
- nirarg
- nirmalaagash
- nitishfy
- niuzhenguo
- njtran
- njuettner
- nnmin-aws
- noamran
- NoicFank
- nojnhuh
- npinaeva
- npintaux
- npolshakova
- nprokopic
- nrb
- nunnatsa
- odinuge
- olemarkus
- olivercodes
- oliviassss
- olivierlemasle
- onlydole
- onyiny-ang
- oomichi
- oprinmarius
- orsenthil
- oscr
- pacoxu
- parispittman
- pasqualet
- PatrickLang
- pbnj
- pegasas
- Pensu
- perithompson
- petr-muller
- phanimarupaka
- phenixblue
- philips
- phillipsj
- phoenixking25
- phyber
- pierreprinetti
- piosz
- piotrmiskiewicz
- PiotrProkop
- pjbgf
- pjh
- pkprzekwas
- Pluies
- pmorie
- pohly
- poonam-lamba
- prachirp
- Pradumnasaraf
- prafull01
- Prajyot-Parab
- pramitagautam
- prankul88
- prankulmahajan
- prateekgogia
- pravarag
- prksu
- Promaethius
- prydonius
- ps882
- psschwei
- puerco
- puja108
- PurneswarPrasad
- PushkarJ
- pwittrock
- pwschuurman
- pydctw
- qabpea
- qbarrand
- qingwave
- qinqon
- qiujian16
- qiutongs
- qlijin
- qnetter
- quinton-hoole
- qvicksilver
- raelga
- Raffo
- RainbowMango
- Rajakavitha1
- Rajalakshmi-Girish
- rajansandeep
- rajaskakodkar
- rajula96reddy
- ramrodo
- Random-Liu
- randomvariable
- rashansmith
- rashmigottipati
- RaunakShah
- ravisantoshgudimetla
- rayandas
- rayowang
- rbitia
- rdpsin
- rejoshed
- relyt0925
- resouer
- rexagod
- reylejano
- rficcaglia
- rhatdan
- Riaankl
- Richabanker
- richackard
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- riverzhang
- rjbez17
- rjsadow
- rlenferink
- rmenn
- rmohr
- roberthbailey
- robinpercy
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- roycaihw
- rrati
- rsmitty
- rtsp
- rudoi
- runyontr
- rvanderp3
- s-ito-ts
- s-kawamura-w664
- s-urbaniak
- s04
- saad-ali
- sadath-12
- sahilvv
- saikat-royc
- sairameshv
- Sajiyah-Salat
- salaxander
- salehsedghpour
- sallyom
- saltbo
- samos123
- samudralavamshi54
- sanchezl
- sanchita-07
- SandeepPissay
- sandipanpanda
- SanikaGawhane
- sanposhiho
- sanwishe
- sarab97
- SaranBalaji90
- sarazqy
- saschagrunert
- sashrith
- SataQiu
- saurav-agarwalla
- savitharaghunathan
- sayantani11
- sboeuf
- sbose78
- sbs2001
- sbueringer
- schrej
- scothis
- screeley44
- SD-13
- sdmodi
- sdodson
- seanmalloy
- seans3
- seanschneeweiss
- seanzatzdev-amazon
- sedefsavas
- serathius
- serbrech
- SergeyKanzhelev
- sethmccombs
- sethp-nr
- sethpollack
- sftim
- sfzylad
- Sh4d1
- shalini-b
- shaneutt
- shashidharatd
- shatoboar
- shawn-hurley
- sheerun
- Shell32-Natsu
- ShivamTyagi12345
- shivanshu1333
- shivi28
- shu-mutou
- shuaijinchao
- ShwethaKumbla
- shyamjvs
- shyamradhakrishnan
- shysank
- sidharthsurana
- simrangupta234
- Skarlso
- skitt
- skriss
- sladyn98
- smarterclayton
- smg247
- Sneha-at
- soggiest
- sohankunkerkar
- soltysh
- SomtochiAma
- sonasingh46
- songjiaxun
- Songjoy
- soniasingla
- sophieliu15
- spencerhance
- spiffxp
- spowelljr
- spurin
- spzala
- srampal
- sreeram-venkitesh
- srm09
- SRodi
- starpit
- stealthybox
- stephenfin
- stevehipwell
- stevekuznetsov
- steveperry-53
- stmcginnis
- stormqueen1990
- strongjz
- sttts
- stuton
- SubhasmitaSw
- sudermanjr
- sunjayBhatia
- sunnylovestiramisu
- sunpa93
- swatisehgal
- SyamSundarKirubakaran
- szuecs
- t-inu
- tabbysable
- tahsinrahman
- Tal-or
- tallaxes
- tallclair
- tam7t
- taniaduggal
- tanjacky
- tanjunchen
- tao12345666333
- taragu
- tariq1890
- tashimi
- tengqm
- tenzen-y
- TerryHowe
- thandayuthapani
- thebsdbox
- thejoycekung
- thockin
- timoreimann
- timothysc
- timwangmusic
- timyinshi
- tizhou86
- tkashem
- tlereste
- tobiasgiese
- tokt
- tomassedovic
- TommyLike
- tormath1
- torredil
- tpepper
- trasc
- troy0820
- truongnh1992
- trutx
- tssurya
- tu1h
- tukwila
- tuxtof
- twilight0620
- tydra-wang
- tylerferrara
- tyuchn
- tzifudzi
- tzneal
- umangachapagain
- umohnani8
- upodroid
- utam0k
- vadasambar
- VannTen
- varshaprasad96
- vdhanan
- Verolop
- verult
- VibhorChinda
- vikaschoudhary16
- vikash-8090-Yadav
- Vincent056
- vincepri
- vinli-cn
- vinny-sabatini
- vishakhanihore
- vishalanarase
- vishesh92
- VivekThrivikraman-est
- vjdhama
- vladimirvivien
- vllry
- voor
- vrabbi
- Vyom-Yadav
- wangchen615
- wawa0210
- weilaaa
- weiling61
- weizhouapache
- wentao-zh
- wfernandes
- willie-yao
- wilsonehusin
- wilsonwu
- windsonsea
- wk8
- wlan0
- wlp1153468871
- wondywang
- wongma7
- wongni
- woopstar
- wwentland
- wyike
- wzshiming
- x13n
- XDRAGON2002
- xdu31
- Xenwar
- xiangpengzhao
- xianlubird
- xichengliudui
- xing-yang
- xinydev
- xmcqueen
- xmudrii
- xrmzju
- xunpan
- Xunzhuo
- yagonobre
- yanggangtony
- yanghesong
- yangjunmyfm192085
- yankay
- yaroslava-serdiuk
- yashsingh74
- yastij
- ybettan
- ydFu
- yevgeny-shnaidman
- yibozhuang
- yiqigao217
- ykakarap
- yliaog
- yodahekinsew
- yonatankahana
- youngnick
- YoyinZyc
- yrs147
- ytsarev
- yuanchen8911
- yuanying
- yue9944882
- YuikoTakada
- yujuhong
- yujunz
- yulng
- yussufsh
- yuwenma
- yyy1000
- z1cheng
- zacharysarah
- zelenushechka
- ZeroMagic
- zhanggbj
- zhangxyjlu
- zhengtianbao
- zhuangqh
- zhucan
- Zhuzhenghao
- zimmertr
- ziyi-xie
- zmalik
- zouyee
- ZP-AlwaysWin
- zparnold
- zqzten
- zshihang
- zulandar
- zvonkok
- zwpaper
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mattfarina
    - mortent
    - nan-yu
    - prydonius
    privacy: closed
    repos:
      application: admin
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
    repos:
      cri-tools: admin
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - haircommander
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
    repos:
      cri-tools: write
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: admin
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: write
  gcp-compute-persistent-disk-csi-driver-admins:
    description: Admin access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: admin
  gcp-compute-persistent-disk-csi-driver-maintainers:
    description: Write access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - sunnylovestiramisu
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: write
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: admin
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - sunnylovestiramisu
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: write
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: admin
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: write
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: admin
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: write
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: admin
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: write
