name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- adelina-t
- adohe
- adrianludwin
- ahmetb
- ainmosni
- akutz
- alejandrox1
- alexeldeib
- alvaroaleman
- ameukam
- amwat
- amy
- andrewsykim
- andyzhangx
- anfernee
- animeshsingh
- ant31
- aojea
- apelisse
- ashish-amarnath
- atoato88
- Atoms
- aveshagarwal
- awesomenix
- balajismaniam
- BaluDontu
- bclau
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- bowei
- Bradamant3
- bradtopol
- brancz
- bryk
- caesarxuchao
- calebamiles
- camilamacedo86
- carolynvs
- castrojo
- CecileRobertMichon
- chadswen
- chaosaffe
- cheftako
- chenopis
- childsb
- chrigl
- christopherhein
- chuckha
- clyang82
- codenrhoden
- cofyc
- corneliusweig
- d-nishi
- DahuK
- damemi
- danehans
- danielqsj
- danielSbastos
- dashpole
- davidewatson
- davidopp
- davidz627
- ddebroy
- deads2k
- denkensk
- derekwaynecarr
- detiber
- dhellmann
- dholbach
- dims
- DirectXMan12
- divyenpatel
- dkoshkin
- dlipovetsky
- dmatch01
- dnardo
- dougm
- draveness
- droot
- dstrebel
- dvonthenen
- easeway
- entro-pi
- ericzhang08
- Ethyling
- f0rmiga
- fabianofranz
- fabriziopandini
- fanzhangio
- Fei-Guo
- feiskyer
- figo
- flaper87
- floreks
- font
- frapposelli
- fredkan
- gerred
- giuseppe
- grayluck
- grodrigues3
- guineveresaenger
- gyliu513
- gyuho
- hantaowang
- haoshuwei
- hardikdr
- hchenxa
- hello2mao
- hex108
- hh
- hidekazuna
- hoegaarden
- holmsten
- hpandeycodeit
- hzxuzhonghu
- iamemilio
- ibzib
- idealhack
- ingvagabund
- interma
- irfanurrehman
- janetkuo
- javier-b-perez
- jbeda
- jberkhahn
- jberkus
- jdumars
- jeefy
- jeffvance
- jeffwan
- jennybuckley
- jeremyrickard
- jichenjc
- jimangel
- jingxu97
- jinzhejz
- JoelSpeed
- johnsonj
- joonas
- jsafrane
- juan-lee
- juanvallejo
- justaugustus
- justinsb
- k-toyoda-pi
- k82cn
- kad
- Katharine
- kbarnard10
- kbhawkey
- kfox1111
- kow3ns
- kris-nova
- krmayankk
- krousey
- krzyzacy
- ksubrmnn
- kwiesmueller
- lafh
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- Lion-Wei
- listx
- Liujingfang1
- liyinan926
- liztio
- luxas
- m00nf1sh
- m1093782566
- maciaszczykm
- maisem
- mariantalla
- marpaia
- marquiz
- mars1024
- marun
- marwanad
- mattfarina
- mattymo
- mauilion
- mcrute
- mengqiy
- MHBauer
- micahhausler
- michaelgugino
- michelleN
- michmike
- miouge1
- mirwan
- mkimuram
- mkumatag
- Monkeyanator
- monopole
- mook-as
- morvencao
- moshloop
- MrHohn
- mrunalp
- msau42
- mszostok
- mtaufen
- munnerz
- mylesagray
- ncdc
- neolit123
- nikopen
- nzoueidi
- odinuge
- onyiny-ang
- oomichi
- openstacker
- parispittman
- PatrickLang
- phenixblue
- philips
- phyber
- piosz
- piotrmiskiewicz
- pmorie
- prydonius
- ps882
- puja108
- pwittrock
- quinton-hoole
- raelga
- Rajakavitha1
- Random-Liu
- randomvariable
- ravisantoshgudimetla
- resouer
- rhatdan
- ritazh
- riverzhang
- rjbez17
- rlenferink
- roberthbailey
- robinpercy
- rudoi
- runcom
- runyontr
- s-ito-ts
- saad-ali
- sallyom
- SandeepPissay
- saschagrunert
- SataQiu
- sboeuf
- sbueringer
- screeley44
- seans3
- serbrech
- sethp-nr
- sethpollack
- sflxn
- sfzylad
- shashidharatd
- shawn-hurley
- shivi28
- shu-mutou
- sidharthsurana
- smarterclayton
- soggiest
- sohankunkerkar
- soltysh
- srampal
- stealthybox
- steveperry-53
- sttts
- suleisl2000
- syjabri
- tahsinrahman
- tao12345666333
- taragu
- tariq1890
- tashimi
- tengqm
- thandayuthapani
- thockin
- timothysc
- tizhou86
- tomassedovic
- TommyLike
- totherme
- tpepper
- umohnani8
- verult
- vikaschoudhary16
- vincepri
- vjdhama
- vllry
- wk8
- wongma7
- woopstar
- xiangpengzhao
- xianlubird
- xichengliudui
- xing-yang
- xmudrii
- xunpan
- yagonobre
- yastij
- yiqigao217
- yliaog
- yue9944882
- yujuhong
- zacharysarah
- zouyee
- ZP-AlwaysWin
- zparnold
- zulandar
- zvonkok
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - kow3ns
    - mattfarina
    - prydonius
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cluster-api-provider-vsphere-admins:
    description: Admin access to the cluster-api-provider-vsphere repo
    maintainers:
    - spiffxp
    members:
    - akutz
    - andrewsykim
    - frapposelli
    - sflxn
    privacy: closed
  cluster-api-provider-vsphere-maintainers:
    description: Write access to the cluster-api-provider-vsphere repo
    maintainers:
    - spiffxp
    members:
    - akutz
    - andrewsykim
    - figo
    - frapposelli
    - sflxn
    - sidharthsurana
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  descheduler-admins:
    description: Admin access to the descheduler repo
    members:
    - aveshagarwal
    - k82cn
    - ravisantoshgudimetla
    privacy: closed
  descehduler-maintainers:
    description: Write access to the descheduler repo
    members:
    - aveshagarwal
    - k82cn
    - ravisantoshgudimetla
    privacy: closed
  etcdadm-admins:
    description: Admin access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  etcdadm-maintainers:
    description: Write access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  kind-admins:
    description: Admin access to the kind rpeo
    members:
    - BenTheElder
    - munnerz
    privacy: closed
  kind-maintainers:
    description: Write access to the kind repo
    members:
    - BenTheElder
    - munnerz
    privacy: closed
  kube-batch-admins:
    description: Admin access to the kube-batch repo
    maintainers:
    - spiffxp
    members:
    - calebamiles
    - k82cn
    - timothysc
    privacy: closed
  kube-batch-maintainers:
    description: Write access to the kube-batch repo
    maintainers:
    - spiffxp
    members:
    - calebamiles
    - k82cn
    - timothysc
    privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  kubespray-admins:
    description: Admin access to the kubespray repo
    members:
    - ant31
    - chadswen
    - mattymo
    privacy: closed
  kubespray-maintainers:
    description: Write access to the kubespray repo
    members:
    - ant31
    - Atoms
    - chadswen
    - mattymo
    - miouge1
    - mirwan
    - riverzhang
    - woopstar
    privacy: closed
  mutating-trace-admission-controller:
    description: Parent team for mutating-trace-admission-controller repo (maintainers, admins)
    members:
    - calebamiles
    privacy: closed
    teams:
      mutating-trace-admission-controller-admins:
        description: Admin access to the mutating-trace-admission-controller repo
        members:
        - calebamiles
        privacy: closed
      mutating-trace-admission-controller-maintainers:
        description: Write access to the mutating-trace-admission-controller repo
        members:
        - calebamiles
        privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - balajismaniam
    privacy: closed
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - balajismaniam
    - marquiz
    privacy: closed
  reference-docs-admins:
    description: Admin access to the reference-docs repo
    members:
    - bradamant3
    - jimangel
    - zacharysarah
    privacy: closed
  reference-docs-maintainers:
    description: Write access to the reference-docs repo
    members:
    - kbhawkey
    - tengqm
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - cofyc
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  testing_frameworks-admins:
    description: Admin access to the testing_frameworks repo
    members:
    - hoegaarden
    - totherme
    privacy: closed
  testing_frameworks-maintainers:
    description: Write access to the testing_frameworks repo
    members:
    - liztio
    - marun
    privacy: closed
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - adelina-t
    - michmike
    - PatrickLang
    privacy: closed
