name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- nikhita
- spiffxp
- thelinuxfoundation
members:
- adelina-t
- ainmosni
- akutz
- alejandrox1
- alvaroaleman
- ameukam
- amwat
- andrewsykim
- animeshsingh
- ant31
- apelisse
- Atoms
- balajismaniam
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- Bradamant3
- brancz
- bryk
- caesarxuchao
- carolynvs
- castrojo
- chadswen
- chaosaffe
- chenopis
- childsb
- chrigl
- christopherhein
- chuckha
- cofyc
- d-nishi
- danehans
- danielqsj
- dashpole
- davidewatson
- davidz627
- deads2k
- derekwaynecarr
- detiber
- dims
- DirectXMan12
- dkoshkin
- dlipovetsky
- dmatch01
- dougm
- droot
- dstrebel
- fabriziopandini
- fanzhangio
- feiskyer
- flaper87
- floreks
- font
- frapposelli
- giuseppe
- grodrigues3
- guineveresaenger
- gyliu513
- gyuho
- hardikdr
- hoegaarden
- iamemilio
- ibzib
- idealhack
- ingvagabund
- interma
- irfanurrehman
- jbeda
- jberkus
- jdumars
- jeefy
- jeffwan
- jennybuckley
- jeremyrickard
- jichenjc
- jingxu97
- jinzhejz
- jsafrane
- justaugustus
- justinsb
- k82cn
- kow3ns
- kris-nova
- krmayankk
- krousey
- krzyzacy
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- Lion-Wei
- Liujingfang1
- liyinan926
- liztio
- m00nf1sh
- m1093782566
- maciaszczykm
- maisem
- mariantalla
- marquiz
- marun
- marwanad
- mattfarina
- mattymo
- mcrute
- mengqiy
- michelleN
- michmike
- miouge1
- mirwan
- Monkeyanator
- monopole
- mrbobbytables
- mrunalp
- msau42
- munnerz
- neolit123
- nikopen
- onyiny-ang
- parispittman
- PatrickLang
- philips
- phyber
- piosz
- pmorie
- prydonius
- puja108
- pwittrock
- quinton-hoole
- quinton-hoole-2
- Random-Liu
- randomvariable
- rhatdan
- riverzhang
- rlenferink
- roberthbailey
- robinpercy
- runcom
- saad-ali
- sboeuf
- seans3
- shashidharatd
- sidharthsurana
- smarterclayton
- soggiest
- sohankunkerkar
- suleisl2000
- syjabri
- taragu
- tariq1890
- thockin
- timothysc
- tizhou86
- tomassedovic
- totherme
- verult
- vincepri
- wongma7
- woopstar
- xiangpengzhao
- xmudrii
- xunpan
- yagonobre
- yastij
- yliaog
- yujuhong
- zacharysarah
- zouyee
teams:
  application-admins:
    description: admin access to application
    maintainers:
    - kow3ns
    members:
    - mattfarina
    - prydonius
    privacy: closed
  architecture-tracking-admins:
    description: admin permission for architecture-tracking
    maintainers:
    - bgrant0607
    - jdumars
    privacy: closed
  architecture-tracking-maintainers:
    description: write permission for architecture-tracking
    maintainers:
    - bgrant0607
    - jdumars
    - spiffxp
    members:
    - dims
    - liggitt
    - mattfarina
    - timothysc
    privacy: closed
  aws-ebs-csi-driver-admins:
    description: ""
    maintainers:
    - d-nishi
    members:
    - leakingtapan
    privacy: closed
  aws-ebs-csi-driver-maintainers:
    description: ""
    maintainers:
    - d-nishi
    members:
    - bertinatto
    - jsafrane
    - leakingtapan
    privacy: closed
  aws-encryption-provider-admins:
    description: admin access to aws_encryption-provider repo
    maintainers:
    - justinsb
    - robinpercy
    privacy: closed
  aws-encryption-provider-maintainers:
    description: write access to aws_encryption-provider
    maintainers:
    - justinsb
    - robinpercy
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - thelinuxfoundation
    privacy: closed
  cluster-api-admins:
    description: ""
    maintainers:
    - timothysc
    members:
    - kris-nova
    - krousey
    - roberthbailey
    privacy: closed
  cluster-api-maintainers:
    description: ""
    maintainers:
    - timothysc
    members:
    - davidewatson
    - detiber
    privacy: closed
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    maintainers:
    - detiber
    privacy: closed
  cluster-api-provider-aws-maintainers:
    description: write access to cluster-api-provider-aws
    maintainers:
    - detiber
    members:
    - chuckha
    - davidewatson
    - ingvagabund
    - timothysc
    privacy: closed
  cluster-api-provider-digitalocean-admins:
    description: ""
    maintainers:
    - roberthbailey
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-digitalocean-maintainers:
    description: ""
    maintainers:
    - alvaroaleman
    - nikhita
    - roberthbailey
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    maintainers:
    - roberthbailey
    privacy: closed
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    maintainers:
    - roberthbailey
    members:
    - justinsb
    privacy: closed
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    maintainers:
    - dims
    members:
    - chaosaffe
    privacy: closed
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    maintainers:
    - dims
    members:
    - chaosaffe
    privacy: closed
  cluster-api-provider-vsphere-admins:
    description: admin access to cluster-api-provider-vsphere-admins
    maintainers:
    - spiffxp
    members:
    - frapposelli
    privacy: closed
  cluster-api-provider-vsphere-maintainers:
    description: write access to cluster-api-provider-vsphere
    maintainers:
    - spiffxp
    members:
    - frapposelli
    privacy: closed
  contributor-site-admins:
    description: admin access to contributor-site
    maintainers:
    - castrojo
    members:
    - mrbobbytables
    privacy: closed
  contributor-site-maintainers:
    description: write access to contributor-site
    maintainers:
    - castrojo
    members:
    - mrbobbytables
    privacy: closed
  controller-runtime-admins:
    description: ""
    members:
    - DirectXMan12
    - droot
    - pwittrock
    privacy: closed
  controller-runtime-contributors:
    description: ""
    members:
    - fanzhangio
    - lichuqiang
    - pwittrock
    privacy: closed
  controller-runtime-maintainers:
    description: ""
    members:
    - Liujingfang1
    - mengqiy
    - pwittrock
    - seans3
    privacy: closed
  controller-tools-admins:
    description: ""
    members:
    - DirectXMan12
    - droot
    - pwittrock
    - seans3
    privacy: closed
  controller-tools-contributors:
    description: ""
    members:
    - Birdrock
    - pwittrock
    privacy: closed
  controller-tools-maintainers:
    description: ""
    members:
    - droot
    - mengqiy
    - pwittrock
    - seans3
    privacy: closed
  cri-o-admins:
    description: admin access to cri-o
    maintainers:
    - mrunalp
    members:
    - runcom
    privacy: closed
  cri-o-maintainers:
    description: write access to cri-o
    maintainers:
    - mrunalp
    members:
    - giuseppe
    - runcom
    privacy: closed
  cri-tools-admins:
    description: admin access to cri-tools
    maintainers:
    - feiskyer
    - mrunalp
    members:
    - Random-Liu
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: write access to cri-tools
    maintainers:
    - feiskyer
    - mrunalp
    members:
    - Random-Liu
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: admin access to dashboard-metrics-scraper
    maintainers:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: write access to dashboard-metrics-scraper
    maintainers:
    - bryk
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  etcdadm-admins:
    description: admin access to etcdadm
    maintainers:
    - justinsb
    privacy: closed
  etcdadm-maintainers:
    description: write access to etcdadm
    maintainers:
    - justinsb
    privacy: closed
  federation-v2-admins:
    description: admin access for the federation-v2 repo
    maintainers:
    - spiffxp
    members:
    - font
    - irfanurrehman
    - marun
    - pmorie
    - shashidharatd
    privacy: closed
  federation-v2-maintainers:
    description: write access to the fededation-v2 repo
    maintainers:
    - marun
    members:
    - font
    - irfanurrehman
    - shashidharatd
    privacy: closed
  federation-wg:
    description: Individuals who are part of sig-multicluster and working as federation
      workgroup.
    maintainers:
    - irfanurrehman
    members:
    - font
    - gyliu513
    - marun
    - onyiny-ang
    - pmorie
    - quinton-hoole
    - quinton-hoole-2
    - shashidharatd
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: ""
    maintainers:
    - msau42
    - saad-ali
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: ""
    maintainers:
    - msau42
    - saad-ali
    privacy: closed
  kind-admins:
    description: ""
    maintainers:
    - BenTheElder
    members:
    - munnerz
    privacy: closed
  kind-maintainers:
    description: ""
    maintainers:
    - BenTheElder
    members:
    - munnerz
    privacy: closed
  kube-batch-admins:
    description: admin access to kube-batch
    maintainers:
    - calebamiles
    - spiffxp
    members:
    - k82cn
    - timothysc
    privacy: closed
  kube-batch-maintainers:
    description: write access to kube-batch
    maintainers:
    - calebamiles
    - spiffxp
    members:
    - k82cn
    - timothysc
    privacy: closed
  kubebuilder-admins:
    description: Administrators of the repo
    maintainers:
    - grodrigues3
    members:
    - DirectXMan12
    - droot
    - Liujingfang1
    - mengqiy
    - monopole
    - pmorie
    - pwittrock
    privacy: closed
  kubebuilder-contributors:
    description: ""
    members:
    - DirectXMan12
    - fanzhangio
    - lichuqiang
    - pwittrock
    privacy: closed
  kubebuilder-maintainers:
    description: Maintainers of the project
    members:
    - apelisse
    - DirectXMan12
    - droot
    - mengqiy
    - monopole
    - pmorie
    - pwittrock
    - seans3
    privacy: closed
  kubernetes/sig-api-machinery:
    description: Parent team for all SIG API Machinery subteams (approvers, reviewers,
      admins)
    members:
    - deads2k
    - lavalamp
    privacy: closed
    teams:
      kubernetes/sig-api-machinery-admins:
        description: Admin rights over all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
      kubernetes/sig-api-machinery-approvers:
        description: write access to all SIG API Machinery managed repositories
        members:
        - deads2k
        - lavalamp
        privacy: closed
      kubernetes/sig-api-machinery-reviewers:
        description: read access to all repositories owned by SIG API Machinery
        members:
        - deads2k
        - lavalamp
        privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  kubespray-admins:
    description: ""
    maintainers:
    - ant31
    members:
    - chadswen
    - mattymo
    privacy: closed
  kubespray-maintainers:
    description: ""
    maintainers:
    - ant31
    members:
    - Atoms
    - chadswen
    - mattymo
    - mirwan
    - riverzhang
    - woopstar
    privacy: closed
  kustomize-admins:
    description: ""
    members:
    - droot
    - monopole
    - pwittrock
    privacy: closed
  kustomize-contributors:
    description: ""
    members:
    - pwittrock
    privacy: closed
  kustomize-maintainers:
    description: ""
    members:
    - pwittrock
    privacy: closed
  mutating-trace-admission-controller:
    description: ""
    maintainers:
    - calebamiles
    privacy: closed
    teams:
      mutating-trace-admission-controller-admins:
        description: admin access to mutating-trace-admission-controller
        maintainers:
        - calebamiles
        privacy: closed
      mutating-trace-admission-controller-maintainers:
        description: write access to mutating-trace-admission-controller
        maintainers:
        - calebamiles
        privacy: closed
  node-feature-discovery-admins:
    description: ""
    members:
    - balajismaniam
    privacy: closed
  node-feature-discovery-maintainers:
    description: ""
    members:
    - balajismaniam
    - marquiz
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: admin access to sig-storage-lib-external-provisioner
    maintainers:
    - wongma7
    members:
    - childsb
    - jsafrane
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: write access to sig-storage-lib-external-provisioner
    maintainers:
    - wongma7
    members:
    - childsb
    - jsafrane
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: ""
    maintainers:
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: ""
    maintainers:
    - jsafrane
    - msau42
    - saad-ali
    privacy: closed
  structured-merge-diff-admins:
    description: admin access to structured-merge-diff
    maintainers:
    - apelisse
    - lavalamp
    privacy: closed
  structured-merge-diff-maintainers:
    description: write access to structured-merge-diff
    maintainers:
    - apelisse
    - lavalamp
    members:
    - jennybuckley
    privacy: closed
  testing_frameworks-admins:
    description: admin access for testing_frameworks
    maintainers:
    - hoegaarden
    members:
    - totherme
    privacy: closed
  testing_frameworks-maintainers:
    description: write access to testing_frameworks
    maintainers:
    - liztio
    members:
    - marun
    privacy: closed
  website-metadata-admins:
    description: ""
    maintainers:
    - Bradamant3
    - zacharysarah
    members:
    - chenopis
    privacy: closed
  website-metadata-maintainers:
    description: ""
    maintainers:
    - Bradamant3
    - zacharysarah
    members:
    - chenopis
    privacy: closed
  windows-testing-admins:
    description: ""
    maintainers:
    - michmike
    - PatrickLang
    members:
    - adelina-t
    privacy: closed
  windows-testing-maintainers:
    description: ""
    maintainers:
    - michmike
    - PatrickLang
    members:
    - adelina-t
    privacy: closed
  yaml-admins:
    description: ""
    maintainers:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
  yaml-maintainers:
    description: ""
    maintainers:
    - deads2k
    - dims
    - lavalamp
    - liggitt
    privacy: closed
