admins:
- ameukam
- cblecker
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- palnabarun
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 196Ikuchil
- "249043822"
- a7i
- aaroniscode
- aaronlevy
- aartij17
- abhiraut
- abhisheksinghbaghel
- Abirdcfly
- adelina-t
- Adirio
- adohe
- adrianchiris
- adrianludwin
- adtac
- agradouski
- ahg-g
- ahmetb
- ainmosni
- akankshakumari393
- AkihiroSuda
- akutz
- aladewberry
- alculquicondor
- aledbf
- alejandrox1
- alenkacz
- alexander-demicev
- alexeldeib
- alexgervais
- alexzielenski
- alijahnas
- alisondy
- AlmogBaku
- alvaroaleman
- amacaskill
- ambiknai
- amolmote
- Amulyam24
- amwat
- amy
- AnaMMedina21
- andrewrynhard
- andrewsykim
- AndyXiangLi
- andyzhangx
- anfernee
- animeshsingh
- aniruddha2000
- Ankitasw
- annasong20
- ant31
- anusha94
- aojea
- apelisse
- apricote
- arahamad
- aramase
- ArangoGutierrez
- aravindhp
- arghya88
- Arhell
- ArkaSaha30
- arthurdm
- aryan9600
- ash2k
- ashish-amarnath
- ashishranjan738
- Ashley-wenyizha
- asim-reza
- astoycos
- Atharva-Shinde
- atoato88
- Atoms
- AverageMarcus
- aveshagarwal
- AvineshTripathi
- awesomenix
- ayberk
- b01901143
- BaluDontu
- barney-s
- bart0sh
- bartsmykla
- benmoss
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- BinacsLee
- Birdrock
- bishal7679
- bmelbourne
- BobyMCbobs
- boddumanohar
- bowei
- bozzo
- Bradamant3
- bradmccoydev
- bradtopol
- brahmaroutu
- brancz
- brianpursley
- bridgetkromhout
- bswartz
- bzub
- caesarxuchao
- cailynse
- calebamiles
- camilamacedo86
- carlisia
- carlory
- carolynvs
- cartyc
- caseydavenport
- castrojo
- CatherineF-dev
- cchengleo
- ccojocar
- CecileRobertMichon
- celanthe
- celestehorgan
- chadswen
- champtar
- chaodaiG
- chaosaffe
- charleszheng44
- chases2
- cheftako
- chendotjs
- chengxiangdong
- chetak123
- chethanv28
- chewong
- childsb
- chiukapoor
- chizhg
- chrigl
- chris-short
- chrischdi
- chrishenzie
- chriskim06
- chrismetz09
- christopherhein
- chuckha
- chymy
- cici37
- CIPHERTron
- cjwagner
- clarketm
- clarklee92
- claudiubelu
- clyang82
- cmluciano
- cmurphy
- codenrhoden
- coderanger
- coffeepac
- cofyc
- ConnorJC3
- copejon
- corneliusweig
- cpanato
- cprivitere
- craiglpeters
- cristicalin
- csantanapr
- cwdsuzhou
- cyclinder
- d-nishi
- DahuK
- damemi
- danehans
- danielqsj
- danielSbastos
- Danil-Grigorev
- danwinship
- dashpole
- davidewatson
- davidjumani
- davidopp
- davidvossel
- davidz627
- dberkov
- dcantah
- dcbw
- ddebroy
- deads2k
- Debanitrkl
- deejross
- deepak-vij
- deepakkinni
- deitch
- denkensk
- derekwaynecarr
- detiber
- devigned
- dgrisonnet
- dharmjit
- dhellmann
- dholbach
- dims
- DiptoChakrabarty
- DirectXMan12
- displague
- divya-mohan0209
- Divya063
- divyenpatel
- djzager
- dkoshkin
- dlipovetsky
- dntosas
- dobsonj
- dongsupark
- doshyt
- dougm
- dougsland
- dpasiukevich
- dprotaso
- draveness
- drmorr0
- droot
- dstrebel
- dthorsen
- dulek
- dvonthenen
- Dyanngg
- easeway
- eddiezane
- edreed
- ehashman
- EleanorRigby
- electrocucaracha
- elmiko
- endocrimes
- enj
- entro-pi
- enxebre
- EppO
- erain
- ericavonb
- erikgb
- ErikJiang
- esigo
- estroz
- Ethyling
- evansheng
- everettraven
- everpeace
- f0rmiga
- fabi200123
- fabriziopandini
- Fedosin
- Fei-Guo
- feiskyer
- fejta
- feloy
- fengshunli
- ffromani
- figo
- FillZpp
- Fish-pro
- flaper87
- floreks
- floryut
- fmuyassarov
- font
- fpetkovski
- frankfarzan
- frapposelli
- fredkan
- FriedrichWilken
- frobware
- fsmunoz
- furkatgofurov7
- fuxiuyin
- gab-satchi
- gabbifish
- Garima-Negi
- Garrybest
- gavinfish
- geetikabatra
- geoffcline
- gerred
- gianarb
- GinnyJI
- girikuncoro
- giuseppe
- gjkim42
- gkarthiks
- gnoam
- gnufied
- gohilankit
- gottwald
- grodrigues3
- gtxu
- guineveresaenger
- gyliu513
- gyohuangxin
- gyuho
- hackeramitkumar
- haircommander
- haiyanmeng
- hakman
- hanamantagoudvk
- hanlins
- hannibalhuang
- hantaowang
- haosdent
- hardikdr
- harshanarayana
- hasbro17
- hasheddan
- hbagdi
- hchenxa
- hectorj2f
- hello2mao
- hex108
- hh
- hickeyma
- hidekazuna
- hjacobs
- hoegaarden
- holmsten
- hosseinsalahi
- howardjohn
- hpandeycodeit
- Huang-Wei
- humblec
- hwdef
- hzxuzhonghu
- iamemilio
- IanColdwater
- ibabou
- ibzib
- idealhack
- imnmo
- ingvagabund
- interma
- invidian
- irfanurrehman
- irvifa
- isaacdorfman
- ixdy
- iXinqi
- jackfrancis
- jackielii
- jacobsmith928
- jacobwolfaws
- jaehnri
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- jasonbraganza
- javadoors
- javier-b-perez
- jayesh-srivastava
- jayonlau
- jaypipes
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jdumars
- jeefy
- jefftree
- jeffvance
- jeffwan
- jennybuckley
- jeremyje
- JeremyOT
- jeremyrickard
- jhrozek
- jhvhs
- jiahuif
- JiaoDean
- jiatongw
- Jiawei0227
- jichenjc
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jinsongo
- jkh52
- jlamillan
- jlsong01
- jmrodri
- jmwurst
- joekr
- joelanford
- JoelSpeed
- johananl
- johannesfrey
- johngmyers
- johnharris85
- johnSchnake
- johnsonj
- JohnTitor
- joncwong
- Jont828
- jonyhy96
- joonas
- josh-ferrell
- jpbetz
- jpeach
- jpmcb
- jqmichael
- jrsapi
- jsafrane
- jsturtevant
- juan-lee
- juanvallejo
- judemars
- justaugustus
- justin-chizer
- justinsb
- jweite-amazon
- jwtty
- jyotimahapatra
- k-toyoda-pi
- k82cn
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- kannon92
- karlkfi
- Karthik-K-N
- kaslin
- Katharine
- Kavinjsir
- kavyashree-r
- kawych
- kbarnard10
- kbasv
- kbhawkey
- keithmattix
- kendallnelson
- kensipe
- kerthcet
- kevin-wangzefeng
- kevindelgado
- kflynn
- kfox1111
- khenidak
- khoang98
- killianmuldoon
- kishorj
- kkeshavamurthy
- kkmsft
- klueska
- kmova
- knabben
- knelasevero
- knight42
- KnVerey
- koba1t
- kow3ns
- krishchow
- krisnova
- krmayankk
- krol3
- krousey
- krzyzacy
- ksubrmnn
- kundan2707
- kvaps
- kwiesmueller
- lachie83
- lafh
- landreasyan
- lauralorenz
- lavalamp
- laxmikantbpandhare
- leakingtapan
- leiyiz
- lentzi90
- leonardpahlke
- lianghao208
- lichuqiang
- liggitt
- linki
- Lion-Wei
- LiorLieberman
- lipingxue
- listx
- Liujingfang1
- liupeng0518
- lixiang233
- liyinan926
- lizhuqi
- liztio
- loburm
- lobziik
- LochanRn
- logicalhan
- longwuyuan
- lou-lan
- lubronzhan
- LuckySB
- luthermonson
- luxas
- lzhecheng
- m-Bilal
- m-messiah
- m00nf1sh
- macaptain
- maciaszczykm
- Madhan-SWE
- MadhavJivrajani
- Madhur97
- maelvls
- makkes
- maplain
- MarcelMue
- MarcusNoble
- mariantalla
- mark-nc
- markmc
- markyjackson-taulia
- marosset
- marquiz
- mars1024
- MartinForReal
- marun
- marwanad
- mattcary
- mattfarina
- mattfenwick
- mattymo
- mauilion
- mauriciopoppe
- maxdrib
- MaxRenaud
- MaxRink
- mayankshah1607
- mbbroberg
- mboersma
- mcluseau
- mcrute
- mdbooth
- medyagh
- meghanajangi
- mehabhalodiya
- mengqiy
- MHBauer
- micahhausler
- michaelbeaumont
- michaelgugino
- michaelmdresser
- michelle192837
- Michelle951
- michelleN
- michmike
- mikedanese
- mikemorris
- mikeshng
- mimowo
- minbaev
- miouge1
- mirwan
- misterikkit
- mkimuram
- mkorbi
- mkumatag
- mlavacca
- moadqassem
- Monkeyanator
- monopole
- monotek
- mook-as
- morengab
- MorrisLaw
- mortent
- morvencao
- moshloop
- mowangdk
- mpherman2
- mrajashree
- MrHohn
- mritunjaysharma394
- mrmrcoleman
- mrog
- mrunalp
- msau42
- mszostok
- mtaufen
- mtougeron
- mukhoakash
- munnerz
- MushuEE
- mwielgus
- my-git9
- myan9
- mylesagray
- mytunguyen
- mzaian
- n3wscott
- nader-ziada
- nak3
- Namanl2001
- nan-yu
- natalisucks
- natasha41575
- navidshaikh
- nawazkh
- ncdc
- nckturner
- nearora-msft
- nebhale
- necatican
- nehaLohia27
- neolit123
- nicolehanjing
- NicoleYson
- NikhilSharmaWe
- nikopen
- nilekhc
- nilo19
- nirarg
- nirmalaagash
- niuzhenguo
- njuettner
- nnmin-aws
- noamran
- NoicFank
- nojnhuh
- npintaux
- npolshakova
- nprokopic
- nunnatsa
- nzoueidi
- odinuge
- olemarkus
- olivercodes
- olivierlemasle
- onlydole
- onyiny-ang
- oomichi
- oprinmarius
- orsenthil
- oscr
- pacoxu
- parispittman
- pasqualet
- PatrickLang
- pbnj
- Pensu
- perithompson
- petr-muller
- phanimarupaka
- phenixblue
- philips
- phillipsj
- phoenixking25
- phyber
- piosz
- piotrmiskiewicz
- pjbgf
- pjh
- Pluies
- pmorie
- pohly
- prachirp
- Pradumnasaraf
- prafull01
- Prajyot-Parab
- prankul88
- prankulmahajan
- pravarag
- Priyankasaggu11929
- prksu
- Promaethius
- prydonius
- ps882
- psschwei
- puerco
- puja108
- PurneswarPrasad
- PushkarJ
- pwittrock
- pwschuurman
- pydctw
- qabpea
- qbarrand
- qingwave
- qinqon
- qiujian16
- qiutongs
- qnetter
- quinton-hoole
- qvicksilver
- raelga
- Raffo
- RainbowMango
- Rajakavitha1
- Rajalakshmi-Girish
- rajansandeep
- rajaskakodkar
- rajula96reddy
- ramrodo
- Random-Liu
- randomvariable
- rashmigottipati
- RaunakShah
- ravisantoshgudimetla
- rbitia
- rdpsin
- rejoshed
- relyt0925
- resouer
- rexagod
- reylejano
- rficcaglia
- rhatdan
- riaankl
- Richabanker
- richackard
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- riverzhang
- rjbez17
- rjsadow
- rlenferink
- rmenn
- rmohr
- roberthbailey
- robinpercy
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- roycaihw
- rrati
- rsmitty
- rtsp
- rudoi
- runyontr
- s-ito-ts
- s-kawamura-w664
- s-urbaniak
- s04
- saad-ali
- sahilvv
- saikat-royc
- salaxander
- sallyom
- samos123
- samudralavamshi54
- sanchezl
- sanchita-07
- SandeepPissay
- sandipanpanda
- SanikaGawhane
- sanposhiho
- sanwishe
- SaranBalaji90
- sarazqy
- saschagrunert
- sashrith
- SataQiu
- savitharaghunathan
- sayantani11
- sboeuf
- sbose78
- sbs2001
- sbueringer
- schrej
- scothis
- screeley44
- seanmalloy
- seans3
- seanschneeweiss
- sedefsavas
- serathius
- serbrech
- SergeyKanzhelev
- sethmccombs
- sethp-nr
- sethpollack
- sftim
- sfzylad
- Sh4d1
- shalini-b
- shaneutt
- shashidharatd
- shatoboar
- shawn-hurley
- sheerun
- Shell32-Natsu
- ShivamTyagi12345
- shivanshu1333
- shivi28
- shu-mutou
- shuaijinchao
- ShwethaKumbla
- shyamradhakrishnan
- shysank
- sidharthsurana
- simrangupta234
- Skarlso
- skriss
- sladyn98
- smarterclayton
- soggiest
- sohankunkerkar
- soltysh
- SomtochiAma
- sonasingh46
- soniasingla
- sophieliu15
- spiffxp
- spowelljr
- spurin
- spzala
- srampal
- srm09
- starpit
- stealthybox
- stevehipwell
- stevekuznetsov
- steveperry-53
- stmcginnis
- strongjz
- sttts
- SubhasmitaSw
- sunjayBhatia
- sunnylovestiramisu
- sunpa93
- swatisehgal
- SyamSundarKirubakaran
- szuecs
- t-inu
- tabbysable
- tahsinrahman
- tallclair
- tam7t
- taniaduggal
- tanjacky
- tanjunchen
- tao12345666333
- taragu
- tariq1890
- tashimi
- tengqm
- tenzen-y
- thandayuthapani
- thebsdbox
- thejoycekung
- thockin
- timoreimann
- timothysc
- timyinshi
- tizhou86
- tkashem
- tlereste
- tobiasgiese
- tokt
- tomassedovic
- TommyLike
- torredil
- tpepper
- truongnh1992
- trutx
- tssurya
- tuxtof
- twilight0620
- tylerferrara
- tyuchn
- umangachapagain
- umohnani8
- upodroid
- varshaprasad96
- vdhanan
- Verolop
- verult
- VibhorChinda
- vikaschoudhary16
- Vincent056
- vincepri
- vinli-cn
- vinny-sabatini
- vishakhanihore
- VivekThrivikraman-est
- vjdhama
- vladimirvivien
- vllry
- voor
- vrabbi
- wangchen615
- wanyufe
- wawa0210
- weilaaa
- weiling61
- wentao-zh
- wfernandes
- willie-yao
- wilsonehusin
- wilsonwu
- wk8
- wlan0
- wlp1153468871
- wondywang
- wongma7
- wongni
- woopstar
- wzshiming
- x13n
- Xenwar
- xiangpengzhao
- xianlubird
- xichengliudui
- xing-yang
- xinydev
- xmcqueen
- xmudrii
- xrmzju
- xunpan
- Xunzhuo
- yagonobre
- yanghesong
- yangjunmyfm192085
- yankay
- yastij
- ybettan
- yevgeny-shnaidman
- yibozhuang
- yiqigao217
- ykakarap
- yliaog
- yodahekinsew
- yonatankahana
- youngnick
- YoyinZyc
- yrs147
- ytsarev
- yuanchen8911
- yuanying
- yue9944882
- YuikoTakada
- yujuhong
- yujunz
- yuwenma
- zacharysarah
- ZeroMagic
- zhangxyjlu
- zhengtianbao
- zhuangqh
- zhucan
- zimmertr
- ziyi-xie
- zmalik
- zouyee
- ZP-AlwaysWin
- zparnold
- zqzten
- zshihang
- zulandar
- zvonkok
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mattfarina
    - mortent
    - nan-yu
    - prydonius
    privacy: closed
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - haircommander
    - mrunalp
    - Random-Liu
    - saschagrunert
    - yujuhong
    privacy: closed
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
  gcp-compute-persistent-disk-csi-driver-admins:
    description: Admin access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-compute-persistent-disk-csi-driver-maintainers:
    description: Write access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    privacy: closed
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    - prydonius
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - marquiz
    privacy: closed
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - marquiz
    privacy: closed
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - childsb
    - jsafrane
    - wongma7
    privacy: closed
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    privacy: closed
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    privacy: closed
