name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- grodrigues3
- idvoretskyi
- k8s-ci-robot
- spiffxp
- thelinuxfoundation
members:
- akutz
- alvaroaleman
- ameukam
- amwat
- andrewsykim
- ant31
- apelisse
- atoms
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- caesarxuchao
- carolynvs
- castrojo
- chadswen
- chaosaffe
- childsb
- christopherhein
- chuckha
- d-nishi
- danehans
- davidewatson
- davidz627
- deads2k
- derekwaynecarr
- detiber
- dims
- DirectXMan12
- dmatch01
- dougm
- droot
- dstrebel
- fanzhangio
- feiskyer
- flaper87
- font
- frapposelli
- giuseppe
- guineveresaenger
- gyliu513
- gyuho
- hoegaarden
- iamemilio
- ingvagabund
- irfanurrehman
- jbeda
- jberkus
- jdumars
- jennybuckley
- jeremyrickard
- jingxu97
- jinzhejz
- jsafrane
- justaugustus
- justinsb
- k82cn
- kow3ns
- krmayankk
- krzyzacy
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- Lion-Wei
- Liujingfang1
- liyinan926
- liztio
- m00nf1sh
- m1093782566
- mariantalla
- marquiz
- marun
- mattfarina
- mattymo
- mcrute
- mengqiy
- michelleN
- mirwan
- monopole
- mrbobbytables
- mrunalp
- msau42
- munnerz
- nikhita
- nikopen
- onyiny-ang
- parispittman
- philips
- phyber
- pmorie
- prydonius
- pwittrock
- quinton-hoole
- quinton-hoole-2
- Random-Liu
- randomvariable
- rhatdan
- riverzhang
- roberthbailey
- robinpercy
- runcom
- saad-ali
- seans3
- shashidharatd
- smarterclayton
- suleisl2000
- thockin
- timothysc
- tizhou86
- totherme
- verult
- vincepri
- wongma7
- woopstar
- xmudrii
- yliaog
- yujuhong
