admins:
- cblecker
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 196Ikuchil
- "249043822"
- 92nqb
- a7i
- aaroniscode
- abhay-krishna
- abhiraut
- Abirdcfly
- achernevskii
- adelina-t
- adikul30
- adilGhaffarDev
- adityabhatia
- adriananeci
- adrianchiris
- adrianludwin
- adtac
- afirth
- agradouski
- ahg-g
- AhmedGrati
- ahmetb
- airbornepony
- aj11anuj
- akankshakumari393
- akankshapanse
- AkihiroSuda
- akutz
- aladewberry
- AlbeeSo
- alculquicondor
- aledbf
- alexander-demicev
- alexeldeib
- AlexNPavel
- alexzielenski
- AlmogBaku
- alvaroaleman
- amacaskill
- ambiknai
- ameukam
- amolmote
- Amulyam24
- AnaMMedina21
- AndiDog
- AndrewSirenko
- andrewsykim
- andyzhangx
- anfernee
- aniruddha2000
- Ankitasw
- annasong20
- ant31
- antoooks
- anusha94
- aojea
- apelisse
- apricote
- arahamad
- aramase
- ArangoGutierrez
- aravindhp
- ArkaSaha30
- arkodg
- aroradaman
- aryan9600
- asa3311
- ash2k
- ashishranjan738
- Ashley-wenyizha
- astefanutti
- astoycos
- Atharva-Shinde
- atoato88
- Atoms
- AverageMarcus
- aveshagarwal
- AvineshTripathi
- B1F030
- barney-s
- bart0sh
- bells17
- benmoss
- BenTheElder
- bertinatto
- bg-chun
- bgrant0607
- binacs
- bishal7679
- BlaineEXE
- BobyMCbobs
- bowei
- bozzo
- bradmccoydev
- bradtopol
- brancz
- brianpursley
- bridgetkromhout
- Bryce-Soghigian
- bswartz
- bugoverdose
- bwagner5
- byako
- bzub
- caesarxuchao
- cahillsf
- cailynse
- camilamacedo86
- campoy
- candita
- carlory
- cartermckinnon
- caseydavenport
- castrojo
- CatherineF-dev
- cchengleo
- ccojocar
- CecileRobertMichon
- celestehorgan
- chadswen
- champtar
- chansuke
- chaodaiG
- charles-chenzz
- chases2
- cheftako
- chendave
- chengxiangdong
- chetak123
- chethanv28
- chewong
- chiukapoor
- chizhg
- chris-short
- chrischdi
- chrisdoherty4
- chrishenzie
- chriskim06
- chrismetz09
- christopherhein
- chymy
- cici37
- CIPHERTron
- cjwagner
- claudiubelu
- cmurphy
- cnmcavoy
- codefromthecrypt
- coderanger
- cofyc
- ConnorJC3
- cooldracula
- cpanato
- cprivitere
- craiglpeters
- cristicalin
- csantanapr
- cvvz
- cwdsuzhou
- cyclinder
- d-nishi
- dabradley
- DahuK
- damdo
- damemi
- danehans
- danielvegamyhre
- DanielXiao
- Danil-Grigorev
- dannawang0221
- danwinship
- dashpole
- davidjumani
- davidopp
- davidvossel
- dberkov
- dbonfigli
- dcantah
- dcbw
- ddebroy
- deads2k
- Debanitrkl
- deepakkinni
- deitch
- denkensk
- derekwaynecarr
- detiber
- devigned
- dgrisonnet
- dharaneeshvrd
- dharmjit
- dhellmann
- dholbach
- DimpleRajaVamsi
- dims
- dipankardas011
- DiptoChakrabarty
- DirectXMan12
- displague
- divya-mohan0209
- Divya063
- divyenpatel
- dixudx
- dkoshkin
- dlipovetsky
- dntosas
- dobsonj
- dongsupark
- dougm
- dougsland
- dpasiukevich
- dprotaso
- drew-viles
- drewhagen
- drmorr0
- droslean
- dthorsen
- dtzar
- dulek
- Dyanngg
- easeway
- eddiezane
- eddycharly
- edreed
- ehashman
- Eileen-Yu
- electrocucaracha
- elezar
- ellistarn
- elmiko
- EmilienM
- endocrimes
- engedaam
- enj
- enxebre
- erikgb
- ErikJiang
- esigo
- everettraven
- everpeace
- ezzoueidi
- fabi200123
- fabriziopandini
- faiq
- Fedosin
- Fei-Guo
- feiskyer
- feloy
- ffromani
- FillZpp
- Fish-pro
- fiunchinho
- floreks
- floryut
- fmuyassarov
- fpetkovski
- frankbu
- frapposelli
- freddie400
- fredkan
- FriedrichWilken
- fsmunoz
- furkatgofurov7
- fuxiuyin
- fykaa
- g-gaston
- gab-satchi
- Garrybest
- gauravkghildiyal
- Gauravpadam
- gcs278
- geetikabatra
- Gekko0114
- geoffcline
- girikuncoro
- giuseppe
- gjkim42
- gjtempleton
- gnufied
- gohilankit
- gomesjason
- gottwald
- guineveresaenger
- gyohuangxin
- gyuho
- hackeramitkumar
- hailkomputer
- haircommander
- hakman
- hangscer8
- hanlins
- hannibalhuang
- hanyuel
- haosdent
- hardikdr
- harshanarayana
- hectorj2f
- helen-frank
- heyste
- hh
- Hii-Arpit
- HirazawaUi
- howardjohn
- hrak
- Huang-Wei
- hughdanliu
- humblec
- huntergregory
- huxcrux
- hwdef
- hzxuzhonghu
- IanColdwater
- ibabou
- idealhack
- idvoretskyi
- imnmo
- ingvagabund
- inteon
- intUnderflow
- invidian
- ipochi
- irvifa
- ixdy
- jackfrancis
- jackielii
- jacobwolfaws
- jaehnri
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- jasonbraganza
- javadoors
- jayesh-srivastava
- jayonlau
- jaypipes
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jbpratt
- jdumars
- jeefy
- Jefftree
- jeffwan
- jeremyje
- JeremyOT
- jeremyrickard
- jhrozek
- jiahuif
- JiaoDean
- Jiawei0227
- jichenjc
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jjacobelli
- jkh52
- jklaw90
- jlamillan
- jlsong01
- jmdeal
- jmguzik
- jmhbnz
- jmrodri
- joe-atzinger
- joekr
- joelanford
- JoelSpeed
- johananl
- johannesfrey
- johngmyers
- jonathan-innis
- jongwooo
- Jont828
- jonyhy96
- josh-ferrell
- jpbetz
- jpmcb
- jrsapi
- jsafrane
- jsturtevant
- judemars
- justaugustus
- justinsb
- jweite-amazon
- jwtty
- jyotimahapatra
- k82cn
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- kaisoz
- kannon92
- karlkfi
- Karthik-K-N
- Kasambx
- kaslin
- Katharine
- Kavinjsir
- kavyashree-r
- kawych
- kbhawkey
- keithmattix
- kendallnelson
- kerthcet
- kevin-wangzefeng
- kevindelgado
- kflynn
- kfox1111
- khareyash05
- khenidak
- khoang98
- kiashok
- killianmuldoon
- kishorj
- kkeshavamurthy
- kkkkun
- KKtheGhost
- klueska
- KlwntSingh
- kmova
- knabben
- knee-berts
- knelasevero
- knight42
- KnVerey
- koba1t
- koksay
- kow3ns
- krmayankk
- krol3
- krzyzacy
- kundan2707
- kvaps
- kwiesmueller
- lachie83
- landreasyan
- laozc
- lauralorenz
- lavalamp
- laxmikantbpandhare
- leakingtapan
- leiyiz
- lentzi90
- leonardpahlke
- levikobi
- lianghao208
- liggitt
- LingyanYin
- linki
- LiorLieberman
- lipingxue
- listx
- liupeng0518
- lizhuqi
- lobziik
- LochanRn
- logicalhan
- longwuyuan
- lou-lan
- louiscryan
- lubronzhan
- luthermonson
- luxas
- lzhecheng
- m-Bilal
- m-messiah
- m00nf1sh
- maciaszczykm
- maciekpytel
- Madhan-SWE
- Madhur97
- maelvls
- makkes
- mandre
- MarcelMue
- markmc
- marosset
- marquiz
- mars1024
- MartinForReal
- marwanad
- MaryamTavakkoli
- mateiidavid
- matrus2
- mattcary
- mattfenwick
- matthyx
- mauriciopoppe
- MaxRink
- MaysaMacedo
- mboersma
- mboukhalfa
- mcbenjemaa
- mcluseau
- mdbooth
- medyagh
- meghanajangi
- mehabhalodiya
- mengjiao-liu
- mengqiy
- mfahlandt
- micahhausler
- michaelbeaumont
- michaelfromyeg
- michaelgugino
- michelle192837
- Michelle951
- mikedanese
- mikemorris
- mikeshng
- mimowo
- misterikkit
- mjlshen
- mjudeikis
- mkimuram
- mkumatag
- mlavacca
- mloiseleur
- mloskot
- mmerkes
- mnaser
- mneverov
- moadqassem
- mochizuki875
- moficodes
- monotek
- MorrisLaw
- mortent
- mowangdk
- mpatlasov
- mpherman2
- mresvanis
- MrFreezeex
- MrHohn
- mrog
- mrueg
- mrunalp
- msau42
- mskanth972
- mtaufen
- mtougeron
- muddapu
- mukhoakash
- munnerz
- muraee
- musaprg
- MushuEE
- mwielgus
- my-git9
- mylesagray
- mzaian
- nak3
- Namanl2001
- nan-yu
- nasa9084
- natalisucks
- natasha41575
- navidshaikh
- nawazkh
- nayihz
- ncapps
- ncdc
- nckturner
- ndipebot
- nearora-msft
- neolit123
- nicolehanjing
- NikhilSharmaWe
- nilekhc
- nilo19
- nitishfy
- niuzhenguo
- njtran
- njuettner
- nnmin-aws
- NoicFank
- nojnhuh
- npinaeva
- npintaux
- npolshakova
- nprokopic
- nrb
- nunnatsa
- odinuge
- olemarkus
- olivercodes
- oliviassss
- olivierlemasle
- onlydole
- oomichi
- oprinmarius
- OrlinVasilev
- orsenthil
- oscr
- pacoxu
- parispittman
- pegasas
- petr-muller
- phenixblue
- phillipsj
- pierreprinetti
- piosz
- piotrmiskiewicz
- PiotrProkop
- pjbgf
- pjh
- pkprzekwas
- Pluies
- pmorie
- pohly
- poonam-lamba
- Pradumnasaraf
- Prajyot-Parab
- pramitagautam
- prankulmahajan
- prateekgogia
- pravarag
- psschwei
- puerco
- puja108
- PushkarJ
- pwittrock
- pwschuurman
- qabpea
- qbarrand
- qingwave
- qinqon
- qiujian16
- qiutongs
- qlijin
- quinton-hoole
- raelga
- Raffo
- RainbowMango
- Rajalakshmi-Girish
- rajaskakodkar
- rajula96reddy
- rakshitgondwal
- ramrodo
- Random-Liu
- randomvariable
- rashansmith
- rashmigottipati
- RaunakShah
- ravisantoshgudimetla
- rayandas
- rayowang
- rdpsin
- reetasingh
- relyt0925
- rexagod
- reylejano
- rficcaglia
- rhatdan
- Riaankl
- Richabanker
- richackard
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- rjbez17
- rjsadow
- rlenferink
- rmohr
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- roycaihw
- rsmitty
- rtsp
- rvanderp3
- s-kawamura-w664
- s-urbaniak
- saad-ali
- sadath-12
- saikat-royc
- sairameshv
- Sajiyah-Salat
- salaxander
- salehsedghpour
- sallyom
- saltbo
- samos123
- sanchezl
- sanchita-07
- SandeepPissay
- sandipanpanda
- SanikaGawhane
- sanposhiho
- sarab97
- SaranBalaji90
- sarazqy
- sarveshr7
- saschagrunert
- sashrith
- SataQiu
- saurav-agarwalla
- savitharaghunathan
- sayantani11
- sbs2001
- sbueringer
- schrej
- scothis
- SD-13
- sdmodi
- sdodson
- seanmalloy
- seans3
- seanschneeweiss
- seanzatzdev-amazon
- serathius
- serbrech
- SergeyKanzhelev
- sftim
- Sh4d1
- shalini-b
- shanduur
- shaneutt
- shatoboar
- ShivamTyagi12345
- shivanshu1333
- shraddhabang
- shu-mutou
- ShwethaKumbla
- shyamjvs
- shyamradhakrishnan
- Skarlso
- skitt
- skriss
- sladyn98
- smarterclayton
- smg247
- Sneha-at
- sohankunkerkar
- soltysh
- SomtochiAma
- sonasingh46
- songjiaxun
- Songjoy
- sophieliu15
- spencerhance
- spiffxp
- spowelljr
- spurin
- spzala
- sreeram-venkitesh
- srm09
- SRodi
- starpit
- stealthybox
- stephenfin
- stevehipwell
- stevekuznetsov
- stmcginnis
- stormqueen1990
- strongjz
- sttts
- stuton
- SubhasmitaSw
- sudermanjr
- sunjayBhatia
- sunnylovestiramisu
- sunpa93
- swatisehgal
- szuecs
- t-inu
- tabbysable
- Tal-or
- tallaxes
- tallclair
- tam7t
- taniaduggal
- tanjunchen
- tao12345666333
- tariq1890
- tashimi
- tengqm
- tenzen-y
- TerryHowe
- thebsdbox
- thockin
- timoreimann
- timothysc
- timwangmusic
- tizhou86
- tkashem
- tobiasgiese
- tokt
- tormath1
- torredil
- tpepper
- trasc
- troy0820
- truongnh1992
- tssurya
- tu1h
- tukwila
- tuxtof
- twilight0620
- tydra-wang
- tyuchn
- tzifudzi
- tzneal
- uablrek
- umangachapagain
- upodroid
- utam0k
- vadasambar
- VannTen
- varshaprasad96
- Verolop
- VibhorChinda
- vikash-8090-Yadav
- Vincent056
- vincepri
- vinli-cn
- vishalanarase
- vishesh92
- vladimirvivien
- voor
- vrabbi
- Vyom-Yadav
- wangchen615
- weilaaa
- weiling61
- weizhouapache
- wentao-zh
- willie-yao
- wilsonwu
- windsonsea
- wlan0
- wlp1153468871
- wondywang
- wongma7
- woopstar
- wwentland
- wyike
- wzshiming
- x13n
- XDRAGON2002
- xdu31
- xichengliudui
- xing-yang
- xinydev
- xmcqueen
- xmudrii
- xrmzju
- Xunzhuo
- yagonobre
- yanggangtony
- yanghesong
- yangjunmyfm192085
- yankay
- yaroslava-serdiuk
- yashsingh74
- yastij
- ybettan
- ydFu
- yevgeny-shnaidman
- yibozhuang
- yiqigao217
- ykakarap
- yliaog
- yonatankahana
- youngnick
- YoyinZyc
- yrs147
- ytsarev
- yuanchen8911
- yue9944882
- YuikoTakada
- yujunz
- yulng
- yussufsh
- yuwenma
- yyy1000
- z1cheng
- zacharysarah
- zelenushechka
- ZeroMagic
- zhanggbj
- zhangxyjlu
- zhengtianbao
- zhucan
- Zhuzhenghao
- zimmertr
- ziyi-xie
- zmalik
- zouyee
- zparnold
- zqzten
- zshihang
- zvonkok
- zwpaper
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mortent
    - nan-yu
    privacy: closed
    repos:
      application: admin
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: admin
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - haircommander
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: write
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: admin
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: write
  gcp-compute-persistent-disk-csi-driver-admins:
    description: Admin access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - pwschuurman
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: admin
  gcp-compute-persistent-disk-csi-driver-maintainers:
    description: Write access to the gcp-compute-persistent-disk-csi-driver repo
    members:
    - amacaskill
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - sunnylovestiramisu
    - tyuchn
    privacy: closed
    repos:
      gcp-compute-persistent-disk-csi-driver: write
  gcp-filestore-csi-driver-admins:
    description: Admin access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - saad-ali
    - saikat-royc
    - songjiaxun
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: admin
  gcp-filestore-csi-driver-maintainers:
    description: Write access to the gcp-filestore-csi-driver repo
    members:
    - leiyiz
    - mattcary
    - msau42
    - pwschuurman
    - saad-ali
    - saikat-royc
    - songjiaxun
    - sunnylovestiramisu
    - tyuchn
    privacy: closed
    repos:
      gcp-filestore-csi-driver: write
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: admin
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: write
  sig-storage-lib-external-provisioner-admins:
    description: Admin access to the sig-storage-lib-external-provisioner repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: admin
  sig-storage-lib-external-provisioner-maintainers:
    description: Write access to the sig-storage-lib-external-provisioner repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - wongma7
    - xing-yang
    privacy: closed
    repos:
      sig-storage-lib-external-provisioner: write
  sig-storage-local-static-provisioner-admins:
    description: Admin access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: admin
  sig-storage-local-static-provisioner-maintainers:
    description: Write access to the sig-storage-local-static-provisioner repo
    members:
    - andyzhangx
    - cofyc
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      sig-storage-local-static-provisioner: write
