name: Kubernetes SIGs
description: Org for Kubernetes SIG-related work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- grodrigues3
- idvoretskyi
- k8s-ci-robot
- spiffxp
- thelinuxfoundation
members:
- adelina-t
- ainmosni
- akutz
- alvaroaleman
- ameukam
- amwat
- andrewsykim
- animeshsingh
- ant31
- apelisse
- atoms
- balajismaniam
- BenTheElder
- bertinatto
- bgrant0607
- bigkraig
- Birdrock
- Bradamant3
- brancz
- caesarxuchao
- carolynvs
- castrojo
- chadswen
- chaosaffe
- chenopis
- childsb
- chrigl
- christopherhein
- chuckha
- cofyc
- d-nishi
- danehans
- danielqsj
- dashpole
- davidewatson
- davidz627
- deads2k
- derekwaynecarr
- detiber
- dims
- DirectXMan12
- dmatch01
- dougm
- droot
- dstrebel
- fabriziopandini
- fanzhangio
- feiskyer
- flaper87
- font
- frapposelli
- giuseppe
- guineveresaenger
- gyliu513
- gyuho
- hardikdr
- hoegaarden
- iamemilio
- ibzib
- idealhack
- ingvagabund
- irfanurrehman
- jbeda
- jberkus
- jdumars
- jennybuckley
- jeremyrickard
- jingxu97
- jinzhejz
- jsafrane
- justaugustus
- justinsb
- k82cn
- kow3ns
- kris-nova
- krmayankk
- krousey
- krzyzacy
- lavalamp
- leakingtapan
- lichuqiang
- liggitt
- Lion-Wei
- Liujingfang1
- liyinan926
- liztio
- m00nf1sh
- m1093782566
- mariantalla
- marquiz
- marun
- mattfarina
- mattymo
- mcrute
- mengqiy
- michelleN
- michmike
- mirwan
- Monkeyanator
- monopole
- mrbobbytables
- mrunalp
- msau42
- munnerz
- neolit123
- nikhita
- nikopen
- onyiny-ang
- parispittman
- PatrickLang
- philips
- phyber
- piosz
- pmorie
- prydonius
- puja108
- pwittrock
- quinton-hoole
- quinton-hoole-2
- Random-Liu
- randomvariable
- rhatdan
- riverzhang
- roberthbailey
- robinpercy
- runcom
- saad-ali
- seans3
- shashidharatd
- sidharthsurana
- smarterclayton
- soggiest
- suleisl2000
- syjabri
- thockin
- timothysc
- tizhou86
- totherme
- verult
- vincepri
- wongma7
- woopstar
- xiangpengzhao
- xmudrii
- yagonobre
- yastij
- yliaog
- yujuhong
- zacharysarah
- zouyee
