admins:
- cblecker
- jasonbraganza
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 0ekk
- 196Ikuchil
- "249043822"
- 4rivappa
- a-hilaly
- a7i
- aakankshabhende
- aaroniscode
- abhay-krishna
- Abirdcfly
- abursavich
- achandrasekar
- adikul30
- adilGhaffarDev
- adowair
- adriananeci
- adrianchiris
- adrianmoisey
- afirth
- afzal442
- agradouski
- ahg-g
- ahmetb
- ahrtr
- aibarbetta
- aj11anuj
- ajaysundark
- akankshapanse
- akhilerm
- AkihiroSuda
- akram
- akutz
- alaypatel07
- AlbeeSo
- alculquicondor
- aledbf
- alexander-demicev
- alexeldeib
- AlexNPavel
- alexzielenski
- alimaazamat
- alvaroaleman
- amacaskill
- aman4433
- ambiknai
- ameukam
- Amulyam24
- amy
- AnaMMedina21
- AndiDog
- AndrewCharlesHay
- AndrewSirenko
- andrewsykim
- andreyvelich
- andyxning
- andyzhangx
- ania-borowiec
- aniruddha2000
- Ankitasw
- annasong20
- anshuman-agarwala
- ant31
- antoooks
- anusha94
- aojea
- apelisse
- apricote
- arahamad
- aramase
- ArangoGutierrez
- aravindhp
- ardaguclu
- ArkaSaha30
- arkodg
- aroradaman
- arshadd-b
- ArvindParekh
- aryan9600
- asa3311
- asem-hamid
- ash2k
- ashishranjan738
- ashu8912
- astefanutti
- astoycos
- Atharva-Shinde
- atiratree
- atoato88
- Atoms
- AverageMarcus
- avni-mahajan
- azaynul10
- B1F030
- ballista01
- barney-s
- bart0sh
- bells17
- benjaminapetersen
- BenjaminBraunDev
- benluddy
- benmoss
- BenTheElder
- bertinatto
- bexxmodd
- bg-chun
- bgrant0607
- Bharadwajshivam28
- binacs
- bishal7679
- BlaineEXE
- bnallapeta
- BobyMCbobs
- bouaouda-achraf
- bowei
- bradmccoydev
- brancz
- brianpursley
- bridgetkromhout
- bryan-cox
- bryantbiggs
- Bryce-Soghigian
- Bslabe123
- bswartz
- bwagner5
- byako
- cahillsf
- cailyn-codes
- camilamacedo86
- candita
- capri-xiyue
- carlory
- cartermckinnon
- caseydavenport
- castrojo
- CatherineF-dev
- ccojocar
- CecileRobertMichon
- cemakd
- chadswen
- champtar
- chandankumar4
- chansuke
- chases2
- cheftako
- chen-keinan
- chendave
- chengxiangdong
- chetak123
- chethanv28
- chewong
- chiukapoor
- chris-short
- chrischdi
- chrishenzie
- chriskim06
- christopherhein
- chymy
- cici37
- CIPHERTron
- cjwagner
- claudiubelu
- cloudmelon
- cnmcavoy
- codefromthecrypt
- coderanger
- cofyc
- ComradeProgrammer
- comtalyst
- ConnorJC3
- cooldracula
- corentone
- cpanato
- cprivitere
- craigbox
- csantanapr
- cvvz
- cwdsuzhou
- cyclinder
- dabradley
- damdo
- damemi
- danehans
- danielvegamyhre
- DanielXiao
- Danil-Grigorev
- danilo-gemoli
- dankova22
- dannawang0221
- danwinship
- darshansreenivas
- dashpole
- david-martin
- davidjumani
- davidvossel
- DavidXU12345
- dbonfigli
- dchen1107
- deads2k
- Debanitrkl
- deepakkinni
- deitch
- denkensk
- DerekFrank
- derekwaynecarr
- deszhou
- devigned
- devikrishnamk0123
- dgrisonnet
- dgrove-oss
- DhairyaMajmudar
- dharaneeshvrd
- dims
- dipesh-rawat
- displague
- divya-mohan0209
- divyenpatel
- dixudx
- dkoshkin
- dlipovetsky
- dmvolod
- dntosas
- dobsonj
- dom4ha
- dongjiang1989
- dougm
- dprotaso
- drew-viles
- drewhagen
- drmorr0
- droslean
- dtzar
- dulek
- Dyanngg
- EandrewJones
- eddiezane
- eddycharly
- edreed
- Edwinhr716
- ehashman
- electrocucaracha
- Electronic-Waste
- elevran
- elezar
- elieserr
- ElijahQuinones
- ellistarn
- elmiko
- embik
- EmilienM
- endocrimes
- engedaam
- enj
- enxebre
- ericsmalling
- erikgb
- ErikJiang
- esigo
- everettraven
- everpeace
- EyalPazz
- fabi200123
- fabriziopandini
- faermanj
- faiq
- fanhaouu
- farazkhawaja
- fasaxc
- Fedosin
- Fei-Guo
- feiskyer
- feloy
- fengshunli
- ffromani
- FillZpp
- fiunchinho
- floreks
- floryut
- fmuyassarov
- fpetkovski
- Frapschen
- fsmunoz
- furkatgofurov7
- fykaa
- g-gaston
- gab-satchi
- gabesaba
- Gacko
- Garrybest
- gauravkghildiyal
- Gauravpadam
- gcs278
- gdasson
- Gekko0114
- GenPage
- girikuncoro
- giuseppe
- GiuseppeTT
- gjkim42
- gjtempleton
- GnatorX
- gnufied
- gohilankit
- gomesjason
- googs1025
- gottwald
- guicassolato
- gujingit
- GunaKKIBM
- gyuho
- hackeramitkumar
- hailkomputer
- haircommander
- hajiler
- hakman
- hakuna-matatah
- halimsam
- haoranleo
- haosdent
- hardikdr
- harshanarayana
- hectorj2f
- helen-frank
- Henrywu573
- heyste
- highpon
- Hii-Arpit
- hime
- HirazawaUi
- HoKim98
- howardjohn
- hrak
- Huang-Wei
- hughdanliu
- humblec
- hungnguyen243
- huntergregory
- huww98
- huxcrux
- hwdef
- hzxuzhonghu
- IanColdwater
- ichekrygin
- idvoretskyi
- illume
- iltyty
- inductor
- ingvagabund
- inteon
- intUnderflow
- ipochi
- irvifa
- IrvingMg
- ivankatliarchuk
- ivanvc
- izturn
- jackfrancis
- jackielii
- jaehnri
- jakobmoellerdev
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- javadoors
- jayesh-srivastava
- jaypipes
- jayunit100
- jberkus
- jbpratt
- jeefy
- JeffLuoo
- Jefftree
- jefftrojan
- jeffwan
- jenshu
- JeremyOT
- jeremyrickard
- jichenjc
- jigisha620
- jihoon-seo
- jimangel
- JimBugwadia
- jimmidyson
- Jimmykhangnguyen
- jingxu97
- jjacobelli
- jjk-g
- jkh52
- jklaw90
- jlamillan
- jlbutler
- jm-franc
- jmdeal
- jmguzik
- jmhbnz
- joaquimrocha
- joelanford
- JoelSpeed
- johananl
- johnbelamaric
- johnchobroadcom
- johngmyers
- jonathan-innis
- jongwooo
- Jont828
- josh-ferrell
- jpbetz
- jpmcb
- Jpsassine
- jrsapi
- jsafrane
- jsturtevant
- julianKatz
- justaugustus
- justinsb
- jwtty
- jyotimahapatra
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- kahirokunn
- kaisoz
- kamarabbas99
- kanlkan
- kannon92
- karenhchu
- karlkfi
- Karthik-K-N
- kaslin
- katcosgrove
- Katharine
- kaushikmitr
- Kavinjsir
- kavyashree-r
- kawych
- keithmattix
- kendallnelson
- kernel-kun
- kerthcet
- kfess
- kflynn
- kfox1111
- kfswain
- khoang98
- kiashok
- killianmuldoon
- kishen-v
- kkeshavamurthy
- kkkkun
- KKtheGhost
- kl52752
- klueska
- KlwntSingh
- kmala
- knabben
- knee-berts
- knelasevero
- knight42
- knqyf263
- knrt10
- koba1t
- koksay
- kolluria
- kow3ns
- krmayankk
- krol3
- krzyzacy
- kuba-wolf
- kundan2707
- KunWuLuan
- kvaps
- kwiesmueller
- kwilczynski
- landreasyan
- laoj2
- laozc
- lauralorenz
- LaurentGoderre
- lavishpal
- lchrzaszcz
- learner0810
- leiyiz
- lentzi90
- levikobi
- lianghao208
- liggitt
- LionelJouin
- LiorLieberman
- listx
- liu-cong
- liupeng0518
- liurupeng
- lmktfy
- LochanRn
- logicalhan
- longwuyuan
- lowang-bh
- ls-2018
- lubronzhan
- luthermonson
- luxas
- lzhecheng
- m-messiah
- M00nF1sh
- maciaszczykm
- maciekpytel
- macsko
- maelvls
- mainred
- makkes
- mandre
- manzil-infinity180
- markmc
- marosset
- marquiz
- MartinForReal
- MaryamTavakkoli
- matrus2
- mattcary
- mattfenwick
- matthchr
- matthyx
- mauriciopoppe
- maxcao13
- MaxRink
- MaysaMacedo
- mbianchidev
- mbobrovskyi
- mboersma
- mboukhalfa
- mcbenjemaa
- mcluseau
- mdbooth
- mdzraf
- medyagh
- mehabhalodiya
- mengjiao-liu
- mengqiy
- mfahlandt
- micahhausler
- michelle192837
- michellengnx
- mikedanese
- mikemorris
- mikeshng
- MikeZappa87
- mimowo
- misterikkit
- mjlshen
- mjudeikis
- mkimuram
- mkumatag
- mlavacca
- mloiseleur
- mloskot
- mmerkes
- mnaser
- mneverov
- mochizuki875
- moficodes
- monotek
- MorrisLaw
- mortent
- mowangdk
- mpatlasov
- mpinchover
- mresvanis
- MrFreezeex
- MrHohn
- mrueg
- mrunalp
- msau42
- mskanth972
- mskrocki
- mszadkow
- mtardy
- mtaufen
- mtulio
- munnerz
- muraee
- musaprg
- MushuEE
- mwielgus
- mwysokin
- my-git9
- mykysha
- mzaian
- nan-yu
- nasa9084
- natalisucks
- natasha41575
- nawazkh
- nayihz
- ncdc
- nckturner
- ndipebot
- nearora-msft
- neolit123
- ngopalak-redhat
- nicslatts
- nilekhc
- nilo19
- nirrozenbaum
- nirs
- nitishfy
- niuzhenguo
- njtran
- njuettner
- nnmin-aws
- NoicFank
- nojnhuh
- npinaeva
- npolshakova
- nprokopic
- nrb
- ntnn
- nunnatsa
- odinuge
- Okabe-Junya
- olekzabl
- olemarkus
- olivercodes
- oliviassss
- omerap12
- onlydole
- oomichi
- OrlinVasilev
- orsenthil
- pacoxu
- pajakd
- parispittman
- PBundyra
- pegasas
- petr-muller
- pfeifferj
- Phaow
- pierreprinetti
- piosz
- PiotrProkop
- pjbgf
- Pluies
- pmalek
- pohly
- poonam-lamba
- Pradumnasaraf
- Prajyot-Parab
- prankulmahajan
- prateekgogia
- pravarag
- pravk03
- prianna
- priyaaakansha
- priyanshuraj400
- Prucek
- psschwei
- puerco
- PushkarJ
- pwittrock
- pwschuurman
- qbarrand
- qingwave
- qinqon
- qiujian16
- qiutongs
- qlijin
- Qqkyu
- raelga
- Raffo
- rahulgurnani
- RainbowMango
- Rajalakshmi-Girish
- rajaskakodkar
- rakshitgondwal
- ramrodo
- Random-Liu
- randomvariable
- rashansmith
- RaunakShah
- ravisantoshgudimetla
- rayandas
- raywainman
- rdalbuquerque
- rdpsin
- reetasingh
- remyleone
- rexagod
- reylejano
- riaankleinhans
- ricardoapl
- ricardomaraschini
- richabanker
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- riteshghorse
- ritikaguptams
- rjbez17
- rjsadow
- rlenferink
- rmohr
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- rostislavbobo
- roycaihw
- rschalo
- rushmash91
- rvanderp3
- ryan-su-12
- ryanzhang-oss
- rytswd
- s-urbaniak
- saad-ali
- SachinVarghese
- saikat-royc
- sairameshv
- sajibAdhi
- salasberryfin
- salaxander
- salehsedghpour
- sallyom
- sameshai
- samos123
- samuelkarp
- samzong
- sanchezl
- sanchita-07
- SandeepPissay
- sandipanpanda
- sanposhiho
- sarab97
- SaranBalaji90
- sarthaksarthak9
- sarveshr7
- saschagrunert
- sashrith
- SataQiu
- satyampsoni
- saurav-agarwalla
- savitharaghunathan
- sawsa307
- SayakMukhopadhyay
- sayanchowdhury
- sayantani11
- sbueringer
- schrej
- SD-13
- sdodson
- sdowell
- seanmalloy
- seans3
- seanschneeweiss
- seanzatzdev-amazon
- seifrajhi
- serathius
- serbrech
- SergeyKanzhelev
- serngawy
- shalini-b
- shanduur
- shaneutt
- shecodesmagic
- shmuelk
- shraddhabang
- shu-mutou
- shuqz
- ShwethaKumbla
- shyamjvs
- shyamradhakrishnan
- siddhant-khisty
- sipriyaa
- sivchari
- siwiutki
- Skarlso
- skitt
- skoeva
- skriss
- slashpai
- smarterclayton
- smg247
- smileusd
- smoshiur1237
- sn3hay
- Sneha-at
- snehachhabria
- sniok
- snorwin
- sohankunkerkar
- soltysh
- songjiaxun
- spencerhance
- spowelljr
- spurin
- spzala
- sreeram-venkitesh
- srm09
- SRodi
- stealthybox
- stephenfin
- stevehipwell
- stevekuznetsov
- stlaz
- stmcginnis
- stormqueen1990
- strongjz
- sttts
- sudermanjr
- sunjayBhatia
- Sunnatillo
- sunnylovestiramisu
- sunpa93
- sunya-ch
- SwathiR03
- swatisehgal
- szuecs
- t-inu
- t-mialve
- tabbysable
- Tal-or
- tallaxes
- tallclair
- tao12345666333
- tariq1890
- tasdikrahman
- tengqm
- tenzen-y
- TerryHowe
- terrytangyuan
- TessaIO
- theobarberbany
- thockin
- tico88612
- timoreimann
- timwangmusic
- tkashem
- tmurakam
- tnqn
- tobiasgiese
- tokt
- tomasaschan
- TomerNewman
- tonyzhc
- torredil
- towca
- tpantelis
- trasc
- troy0820
- truongnh1992
- tssurya
- tsuzu
- tuminoid
- tuxtof
- tydra-wang
- tyuchn
- tzifudzi
- tzneal
- uablrek
- Udi-Hofesh
- upodroid
- Urvashi0109
- utam0k
- vadasambar
- VannTen
- varshaprasad96
- vasartori
- vdkotkar
- Verolop
- vflaux
- vignesh-goutham
- vinayakankugoyal
- Vincent056
- vincepri
- vishalanarase
- vishesh92
- vladikkuzn
- vladimirvivien
- vrabbi
- vrutkovs
- vyncent-t
- Vyom-Yadav
- wangchen615
- wangzhen127
- weilaaa
- weizhouapache
- wendy-ha18
- wenjiaswe
- whtssub
- willie-yao
- wilsonwu
- windsonsea
- wongma7
- wrkode
- wweiwei-li
- wyike
- wzshiming
- x13n
- xcarolan
- xdu31
- xichengliudui
- xigang
- xing-yang
- xmudrii
- xrstf
- xtineskim
- Xunzhuo
- yagonobre
- YamasouA
- yangjunmyfm192085
- yankay
- yaroslava-serdiuk
- yashsingh74
- yastij
- ybettan
- ydFu
- yevgeny-shnaidman
- yibozhuang
- ykakarap
- yliaog
- ylink-lfs
- yolossn
- yongruilin
- youngnick
- yuanchen8911
- yuanwang04
- yue9944882
- YuikoTakada
- yujen77300
- yujunz
- yussufsh
- yuwenma
- z1cheng
- zac-nixon
- zetxqx
- zhanggbj
- zhangxyjlu
- zhifei92
- zhucan
- zirain
- ziyi-xie
- zmalik
- zouyee
- zqzten
- zshihang
- zvonkok
- zwpaper
- zylxjtu
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mortent
    - nan-yu
    privacy: closed
    repos:
      application: admin
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: admin
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - haircommander
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: write
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - joaquimrocha
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: admin
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - joaquimrocha
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: write
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - macsko
    - sanposhiho
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: admin
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: write
