admins:
- cblecker
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Org for Kubernetes SIG-related work
has_organization_projects: true
has_repository_projects: true
members:
- 0ekk
- 196Ikuchil
- "249043822"
- 92nqb
- a7i
- aakankshabhende
- aaroniscode
- AbdullahAlShaad
- abhay-krishna
- abhiraut
- Abirdcfly
- abursavich
- achandrasekar
- achernevskii
- adelina-t
- adikul30
- adilGhaffarDev
- adityabhatia
- adowair
- adriananeci
- adrianchiris
- adrianludwin
- adtac
- afirth
- agradouski
- ahg-g
- ahmetb
- ahrtr
- aibarbetta
- airbornepony
- aj11anuj
- akankshakumari393
- akankshapanse
- AkihiroSuda
- akram
- akutz
- aladewberry
- AlbeeSo
- alculquicondor
- aledbf
- alexander-demicev
- alexeldeib
- AlexNPavel
- alexzielenski
- AlmogBaku
- alvaroaleman
- amacaskill
- ambiknai
- ameukam
- amolmote
- Amulyam24
- AnaMMedina21
- AndiDog
- AndrewSirenko
- andrewsykim
- andreyvelich
- andyzhangx
- anfernee
- aniruddha2000
- Ankitasw
- annasong20
- ant31
- antoooks
- anusha94
- aojea
- apelisse
- apricote
- arahamad
- aramase
- ArangoGutierrez
- aravindhp
- ardaguclu
- ArkaSaha30
- arkodg
- aroradaman
- aryan9600
- asa3311
- asem-hamid
- ash2k
- ashishranjan738
- Ashley-wenyizha
- ashu8912
- astefanutti
- astoycos
- Atharva-Shinde
- atiratree
- atoato88
- Atoms
- AverageMarcus
- aveshagarwal
- AvineshTripathi
- azaynul10
- B1F030
- barney-s
- bart0sh
- bells17
- benluddy
- benmoss
- BenTheElder
- bertinatto
- bg-chun
- bgrant0607
- Bharadwajshivam28
- binacs
- bishal7679
- BlaineEXE
- BobyMCbobs
- bouaouda-achraf
- bowei
- bozzo
- bradmccoydev
- bradtopol
- brancz
- brianpursley
- bridgetkromhout
- bryan-cox
- bryantbiggs
- Bryce-Soghigian
- bswartz
- bugoverdose
- bwagner5
- byako
- bzub
- caesarxuchao
- cahillsf
- cailyn-codes
- camilamacedo86
- campoy
- candita
- carlory
- cartermckinnon
- caseydavenport
- castrojo
- CatherineF-dev
- cchengleo
- ccojocar
- CecileRobertMichon
- celestehorgan
- chadswen
- champtar
- chandankumar4
- chansuke
- chaodaiG
- charles-chenzz
- chases2
- cheftako
- chen-keinan
- chendave
- chengxiangdong
- chetak123
- chethanv28
- chewong
- chiukapoor
- chizhg
- chris-short
- chrischdi
- chrisdoherty4
- chrishenzie
- chriskim06
- chrismetz09
- christopherhein
- chymy
- cici37
- CIPHERTron
- cjwagner
- claudiubelu
- cloudmelon
- cmurphy
- cnmcavoy
- codefromthecrypt
- coderanger
- cofyc
- ComradeProgrammer
- comtalyst
- ConnorJC3
- cooldracula
- cpanato
- cprivitere
- craigbox
- craiglpeters
- cristicalin
- csantanapr
- cvvz
- cwdsuzhou
- cyclinder
- d-nishi
- dabradley
- DahuK
- damdo
- damemi
- danehans
- danielvegamyhre
- DanielXiao
- Danil-Grigorev
- danilo-gemoli
- dankova22
- dannawang0221
- danwinship
- dashpole
- davidjumani
- davidopp
- davidvossel
- dberkov
- dbonfigli
- dcantah
- dcbw
- ddebroy
- deads2k
- Debanitrkl
- deepakkinni
- deitch
- denkensk
- derekwaynecarr
- deszhou
- detiber
- devigned
- dgrisonnet
- dgrove-oss
- dharaneeshvrd
- dharmjit
- dhellmann
- dholbach
- DimpleRajaVamsi
- dims
- dipankardas011
- dipesh-rawat
- DiptoChakrabarty
- DirectXMan12
- displague
- divya-mohan0209
- Divya063
- divyenpatel
- dixudx
- dkoshkin
- dlipovetsky
- dmvolod
- dntosas
- dobsonj
- dongsupark
- dougm
- dougsland
- dpasiukevich
- dprotaso
- drew-viles
- drewhagen
- drmorr0
- droslean
- dthorsen
- dtzar
- dulek
- Dyanngg
- EandrewJones
- easeway
- eddiezane
- eddycharly
- edreed
- Edwinhr716
- ehashman
- Eileen-Yu
- electrocucaracha
- elezar
- elieser1101
- ElijahQuinones
- ellistarn
- elmiko
- embik
- EmilienM
- endocrimes
- engedaam
- enj
- enxebre
- ericsmalling
- erikgb
- ErikJiang
- esigo
- everettraven
- everpeace
- EyalPazz
- ezzoueidi
- fabi200123
- fabriziopandini
- faermanj
- faiq
- fanhaouu
- Fedosin
- Fei-Guo
- feiskyer
- feloy
- fengshunli
- ffromani
- FillZpp
- Fish-pro
- fiunchinho
- floreks
- floryut
- fmuyassarov
- fpetkovski
- frankbu
- frapposelli
- freddie400
- fredkan
- FriedrichWilken
- fsmunoz
- furkatgofurov7
- fuxiuyin
- fykaa
- g-gaston
- gab-satchi
- gabesaba
- Gacko
- Garrybest
- gauravkghildiyal
- Gauravpadam
- gcs278
- gdasson
- geetikabatra
- Gekko0114
- geoffcline
- girikuncoro
- giuseppe
- gjkim42
- gjtempleton
- GnatorX
- gnufied
- gohilankit
- gomesjason
- googs1025
- gottwald
- gryf
- guicassolato
- guineveresaenger
- gujingit
- gyohuangxin
- gyuho
- hackeramitkumar
- hailkomputer
- haircommander
- hakman
- hakuna-matatah
- halimsam
- hangscer8
- hanlins
- hannibalhuang
- hanyuel
- haosdent
- hardikdr
- harshanarayana
- hectorj2f
- helen-frank
- Henrywu573
- heyste
- hh
- highpon
- Hii-Arpit
- hime
- HirazawaUi
- HoKim98
- hongkailiu
- howardjohn
- hrak
- Huang-Wei
- hughdanliu
- humblec
- hungnguyen243
- huntergregory
- huww98
- huxcrux
- hwdef
- hzxuzhonghu
- IanColdwater
- ibabou
- idealhack
- idvoretskyi
- illume
- imnmo
- inductor
- ingvagabund
- inteon
- intUnderflow
- invidian
- ipochi
- irvifa
- IrvingMg
- ivankatliarchuk
- ivanvc
- ixdy
- jackfrancis
- jackielii
- jaehnri
- JamesLaverack
- JaneLiuL
- janetkuo
- JAORMX
- jasonbraganza
- javadoors
- jayesh-srivastava
- jayonlau
- jaypipes
- jayunit100
- jbeda
- jberkhahn
- jberkus
- jbpratt
- jdumars
- jeefy
- JeffLuoo
- Jefftree
- jefftrojan
- jeffwan
- jenshu
- jeremyje
- JeremyOT
- jeremyrickard
- jhrozek
- jiahuif
- JiaoDean
- Jiawei0227
- jichenjc
- jihoon-seo
- jimangel
- JimBugwadia
- jimmidyson
- jingxu97
- jjacobelli
- jjk-g
- jkh52
- jklaw90
- jlamillan
- jlsong01
- jmdeal
- jmguzik
- jmhbnz
- jmrodri
- joaquimrocha
- joe-atzinger
- joekr
- joelanford
- JoelSpeed
- johananl
- johannesfrey
- johnbelamaric
- johngmyers
- jonathan-innis
- jongwooo
- Jont828
- jonyhy96
- josh-ferrell
- jpbetz
- jpmcb
- jrsapi
- jsafrane
- jsturtevant
- judemars
- justaugustus
- justinsb
- jweite-amazon
- jwtty
- jyotimahapatra
- k82cn
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kad
- kahirokunn
- kaisoz
- kannon92
- karenhchu
- karlkfi
- Karthik-K-N
- Kasambx
- kaslin
- katcosgrove
- Katharine
- Kavinjsir
- kavyashree-r
- kawych
- kbhawkey
- keithmattix
- kendallnelson
- kerthcet
- kevin-wangzefeng
- kevindelgado
- kflynn
- kfox1111
- kfswain
- khareyash05
- khenidak
- khoang98
- kiashok
- killianmuldoon
- kishen-v
- kishorj
- kkeshavamurthy
- kkkkun
- KKtheGhost
- klueska
- KlwntSingh
- kmala
- kmova
- knabben
- knee-berts
- knelasevero
- knight42
- knqyf263
- knrt10
- KnVerey
- koba1t
- koksay
- kow3ns
- krmayankk
- krol3
- krzyzacy
- kuba-wolf
- kundan2707
- KunWuLuan
- kvaps
- kwiesmueller
- kwilczynski
- lachie83
- landreasyan
- laozc
- lauralorenz
- LaurentGoderre
- lavalamp
- lavishpal
- laxmikantbpandhare
- leakingtapan
- leiyiz
- lentzi90
- leonardpahlke
- levikobi
- lianghao208
- liggitt
- LingyanYin
- linki
- LionelJouin
- LiorLieberman
- lipingxue
- listx
- liu-cong
- liupeng0518
- liurupeng
- lizhuqi
- lmktfy
- lobziik
- LochanRn
- logicalhan
- longwuyuan
- lou-lan
- louiscryan
- lowang-bh
- lubronzhan
- luthermonson
- luxas
- lzhecheng
- m-Bilal
- m-messiah
- m00nf1sh
- maciaszczykm
- maciekpytel
- macsko
- Madhan-SWE
- Madhur97
- maelvls
- mainred
- makkes
- mandre
- MarcelMue
- markmc
- marosset
- marquiz
- mars1024
- MartinForReal
- marwanad
- MaryamTavakkoli
- mateiidavid
- matrus2
- mattcary
- mattfenwick
- matthyx
- mauriciopoppe
- MaxRink
- MaysaMacedo
- mbianchidev
- mbobrovskyi
- mboersma
- mboukhalfa
- mcbenjemaa
- mcluseau
- mdbooth
- medyagh
- meghanajangi
- mehabhalodiya
- mengjiao-liu
- mengqiy
- mfahlandt
- micahhausler
- michaelbeaumont
- michaelfromyeg
- michaelgugino
- michelle192837
- Michelle951
- michellengnx
- mikedanese
- mikemorris
- mikeshng
- MikeZappa87
- mimowo
- misterikkit
- mjlshen
- mjudeikis
- mkimuram
- mkumatag
- mlavacca
- mloiseleur
- mloskot
- mmerkes
- mnaser
- mneverov
- moadqassem
- mochizuki875
- moficodes
- monotek
- MorrisLaw
- mortent
- mowangdk
- mpatlasov
- mpherman2
- mresvanis
- MrFreezeex
- MrHohn
- mrog
- mrueg
- mrunalp
- msau42
- mskanth972
- mskrocki
- mszadkow
- mtardy
- mtaufen
- mtougeron
- mtulio
- muddapu
- mukhoakash
- munnerz
- muraee
- musaprg
- MushuEE
- mwielgus
- my-git9
- mykysha
- mylesagray
- mzaian
- nak3
- Namanl2001
- nan-yu
- nasa9084
- natalisucks
- natasha41575
- navidshaikh
- nawazkh
- nayihz
- ncapps
- ncdc
- nckturner
- ndipebot
- nearora-msft
- neolit123
- nicolehanjing
- NikhilSharmaWe
- nilekhc
- nilo19
- nirrozenbaum
- nitishfy
- niuzhenguo
- njtran
- njuettner
- nnmin-aws
- NoicFank
- nojnhuh
- npinaeva
- npintaux
- npolshakova
- nprokopic
- nrb
- nunnatsa
- odinuge
- Okabe-Junya
- olemarkus
- olivercodes
- oliviassss
- olivierlemasle
- omerap12
- onlydole
- oomichi
- oprinmarius
- OrlinVasilev
- orsenthil
- oscr
- pacoxu
- parispittman
- PBundyra
- pegasas
- petr-muller
- phenixblue
- phillipsj
- pierreprinetti
- piosz
- piotrmiskiewicz
- PiotrProkop
- pjbgf
- pjh
- pkprzekwas
- Pluies
- pmalek
- pmorie
- pohly
- poonam-lamba
- Pradumnasaraf
- Prajyot-Parab
- pramitagautam
- prankulmahajan
- prateekgogia
- pravarag
- prianna
- priyaaakansha
- priyanshuraj400
- Prucek
- psschwei
- puerco
- puja108
- PushkarJ
- pwittrock
- pwschuurman
- qabpea
- qbarrand
- qingwave
- qinqon
- qiujian16
- qiutongs
- qlijin
- quinton-hoole
- raelga
- Raffo
- RainbowMango
- Rajalakshmi-Girish
- rajaskakodkar
- rajula96reddy
- rakshitgondwal
- ramrodo
- Random-Liu
- randomvariable
- rashansmith
- rashmigottipati
- RaunakShah
- ravisantoshgudimetla
- rayandas
- rayowang
- raywainman
- rdalbuquerque
- rdpsin
- reetasingh
- relyt0925
- rexagod
- reylejano
- rficcaglia
- rhatdan
- riaankleinhans
- ricardoapl
- ricardomaraschini
- richabanker
- richackard
- richardcase
- rifelpet
- riita10069
- rikatz
- RinkiyaKeDad
- ritazh
- riteshghorse
- ritikaguptams
- rjbez17
- rjsadow
- rlenferink
- rmohr
- robscott
- rohityadavcloud
- rolfedh
- RomanBednar
- roycaihw
- rschalo
- rsmitty
- rtsp
- rvanderp3
- ryanzhang-oss
- rytswd
- s-kawamura-w664
- s-urbaniak
- saad-ali
- SachinVarghese
- sadath-12
- saikat-royc
- sairameshv
- sajibAdhi
- Sajiyah-Salat
- salasberryfin
- salaxander
- salehsedghpour
- sallyom
- saltbo
- sameshai
- samos123
- samuelkarp
- sanchezl
- sanchita-07
- SandeepPissay
- sandipanpanda
- SanikaGawhane
- sanposhiho
- sarab97
- SaranBalaji90
- sarazqy
- sarthaksarthak9
- sarveshr7
- saschagrunert
- sashrith
- SataQiu
- satyampsoni
- saurav-agarwalla
- savitharaghunathan
- sawsa307
- SayakMukhopadhyay
- sayantani11
- sbs2001
- sbueringer
- schrej
- scothis
- SD-13
- sdmodi
- sdodson
- seanmalloy
- seans3
- seanschneeweiss
- seanzatzdev-amazon
- seifrajhi
- serathius
- serbrech
- SergeyKanzhelev
- serngawy
- Sh4d1
- shalini-b
- shanduur
- shaneutt
- shatoboar
- shecodesmagic
- shijinye
- ShivamTyagi12345
- shraddhabang
- shu-mutou
- ShwethaKumbla
- shyamjvs
- shyamradhakrishnan
- sipriyaa
- sivchari
- siwiutki
- Skarlso
- skitt
- skoeva
- skriss
- sladyn98
- smarterclayton
- smg247
- smileusd
- sn3hay
- Sneha-at
- snehachhabria
- sniok
- sohankunkerkar
- soltysh
- SomtochiAma
- sonasingh46
- songjiaxun
- Songjoy
- sophieliu15
- spencerhance
- spiffxp
- spowelljr
- spurin
- spzala
- sreeram-venkitesh
- srm09
- SRodi
- starpit
- stealthybox
- stephenfin
- steve-hardman
- stevehipwell
- stevekuznetsov
- stmcginnis
- stormqueen1990
- strongjz
- sttts
- stuton
- SubhasmitaSw
- sudermanjr
- sunjayBhatia
- Sunnatillo
- sunnylovestiramisu
- sunpa93
- swatisehgal
- szuecs
- t-inu
- t-mialve
- tabbysable
- Tal-or
- tallaxes
- tallclair
- tam7t
- taniaduggal
- tanjunchen
- tao12345666333
- tariq1890
- tasdikrahman
- tashimi
- tengqm
- tenzen-y
- TerryHowe
- terrytangyuan
- TessaIO
- thebsdbox
- theobarberbany
- thockin
- tico88612
- timoreimann
- timothysc
- timwangmusic
- tizhou86
- tkashem
- tnqn
- tobiasgiese
- tokt
- tomasaschan
- tonyzhc
- tormath1
- torredil
- tpantelis
- tpepper
- trasc
- troy0820
- truongnh1992
- tssurya
- tsuzu
- tukwila
- tuminoid
- tuxtof
- tydra-wang
- tyuchn
- tzifudzi
- tzneal
- uablrek
- Udi-Hofesh
- umangachapagain
- upodroid
- Urvashi0109
- utam0k
- vadasambar
- VannTen
- varshaprasad96
- vasartori
- Verolop
- VibhorChinda
- vignesh-goutham
- vikash-8090-Yadav
- Vincent056
- vincepri
- vinli-cn
- vishalanarase
- vishesh92
- vladikkuzn
- vladimirvivien
- voor
- vrabbi
- vyncent-t
- Vyom-Yadav
- wangchen615
- weilaaa
- weiling61
- weizhouapache
- wendy-ha18
- wenjiaswe
- wentao-zh
- willie-yao
- wilsonwu
- windsonsea
- wlan0
- wlp1153468871
- wondywang
- wongma7
- woopstar
- wrkode
- wweiwei-li
- wwentland
- wyike
- wzshiming
- x13n
- xcarolan
- XDRAGON2002
- xdu31
- xichengliudui
- xing-yang
- xinydev
- xmcqueen
- xmudrii
- xrmzju
- xrstf
- xtineskim
- Xunzhuo
- yagonobre
- yanggangtony
- yanghesong
- yangjunmyfm192085
- yankay
- yaroslava-serdiuk
- yashsingh74
- yastij
- ybettan
- ydFu
- yevgeny-shnaidman
- yibozhuang
- yiqigao217
- ykakarap
- yliaog
- yolossn
- yonatankahana
- yongruilin
- youngnick
- YoyinZyc
- yrs147
- ytsarev
- yuanchen8911
- yue9944882
- YuikoTakada
- yujunz
- yulng
- yussufsh
- yuwenma
- yyy1000
- z1cheng
- zac-nixon
- zacharysarah
- zelenushechka
- ZeroMagic
- zhanggbj
- zhangxyjlu
- zhengtianbao
- zhifei92
- zhucan
- Zhuzhenghao
- zimmertr
- ziyi-xie
- zmalik
- zouyee
- zparnold
- zqzten
- zshihang
- zvonkok
- zwpaper
- zylxjtu
members_can_create_repositories: false
name: Kubernetes SIGs
teams:
  application-admins:
    description: Admin access to the application repo
    members:
    - barney-s
    - janetkuo
    - kow3ns
    - mortent
    - nan-yu
    privacy: closed
    repos:
      application: admin
  bots:
    description: Bot Service Accounts in the Kubernetes-SIGs org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    privacy: closed
  cri-tools-admins:
    description: Admin access to the cri-tools repo
    members:
    - feiskyer
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: admin
  cri-tools-maintainers:
    description: Write access to the cri-tools repo
    members:
    - feiskyer
    - haircommander
    - mrunalp
    - Random-Liu
    - saschagrunert
    privacy: closed
    repos:
      cri-tools: write
  dashboard-metrics-scraper-admins:
    description: Admin access to the dashboard-metrics-scraper repo
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: admin
  dashboard-metrics-scraper-maintainers:
    description: Write access to the dashboard-metrics-scraper
    members:
    - floreks
    - jeefy
    - maciaszczykm
    privacy: closed
    repos:
      dashboard-metrics-scraper: write
  kubernetes/sig-apps:
    description: Parent team for all SIG Apps subteams (approvers, reviewers, admins)
    members:
    - kow3ns
    privacy: closed
    teams:
      kubernetes/sig-apps-admins:
        description: Admin access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-approvers:
        description: Write access to all repositories managed by SIG Apps
        privacy: closed
      kubernetes/sig-apps-reviewers:
        description: 'Read access to all repositories managed by SIG Apps '
        privacy: closed
  kubernetes/sig-scheduling:
    description: Team responsible for sig-scheduling related projects
    members:
    - timothysc
    privacy: closed
  node-feature-discovery-admins:
    description: Admin access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: admin
  node-feature-discovery-maintainers:
    description: Write access to the node-feature-discovery repo
    members:
    - ArangoGutierrez
    - marquiz
    privacy: closed
    repos:
      node-feature-discovery: write
