teams:
  sig-multicluster-api-reviews:
    description: ""
    members:
    - davidopp
    - mwielgus
    - quinton-hoole
    - shashidharatd
    privacy: closed
  sig-multicluster-bugs:
    description: ""
    members:
    - irfanurrehman
    - mwielgus
    - quinton-hoole
    - shashidharatd
    privacy: closed
  sig-multicluster-feature-requests:
    description: ""
    members:
    - davidopp
    - derekwaynecarr
    - mwielgus
    - quinton-hoole
    - shashidharatd
    - smarterclayton
    privacy: closed
  sig-multicluster-misc:
    description: 'SIG for multi cluster: https://groups.google.com/forum/#!forum/kubernetes-sig-multicluster'
    members:
    - davidopp
    - derekwaynecarr
    - huangyuqi
    - irfanurrehman
    - liggitt
    - mwielgus
    - quinton-hoole
    - shashidharatd
    - smarterclayton
    privacy: closed
  sig-multicluster-pr-reviews:
    description: ""
    members:
    - mwielgus
    - quinton-hoole
    - shashidharatd
    privacy: closed
  sig-multicluster-proposals:
    description: ""
    members:
    - davidopp
    - derekwaynecarr
    - liggitt
    - mwielgus
    - quinton-hoole
    - shashidharatd
    - smarterclayton
    previously:
    - sig-mutlicluster-proposals
    privacy: closed
  sig-multicluster-test-failures:
    description: ""
    members:
    - irfanurrehman
    - quinton-hoole
    - shashidharatd
    privacy: closed
