teams:
  sig-instrumentation-api-reviews:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-bugs:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-feature-requests:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    privacy: closed
  sig-instrumentation-misc:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    privacy: closed
  sig-instrumentation-pr-reviews:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-proposals:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    privacy: closed
  sig-instrumentation-test-failures:
    description: ""
    members:
    - andyxning
    - brancz
    - danielqsj
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - s-urbaniak
    - serathius
    - x13n
    privacy: closed
