teams:
  sig-instrumentation-leads:
    description: ""
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    privacy: closed
  sig-instrumentation-approvers:
    description: ""
    members:
    - brancz
    - dashpole
    - dgrisonnet
    - ehashman
    - logicalhan
    - RainbowMango
    - serathius
    privacy: closed
  sig-instrumentation-members:
    description: ""
    members:
    - brancz
    - CatherineF-dev
    - dashpole
    - dgrisonnet
    - dims
    - ehashman
    - erain
    - lilic
    - logicalhan
    - mrueg
    - olivierlemasle
    - pohly
    - RainbowMango
    - rexagod
    - RichaBanker
    - s-urbaniak
    - serathius
    - tariq1890
    - yangjunmyfm192085
    - YoyinZyc
    - yuzhiquan
    privacy: closed
  kube-state-metrics-admins:
    description: Admin access to the kube-state-metrics repo
    members:
    - dashpole
    - dgrisonnet
    - ehashman
    - fpetkovski
    - logicalhan
    - mrueg
    - rexagod
    privacy: closed
    repos:
      kube-state-metrics: admin
  kube-state-metrics-maintainers:
    description: Write access to the kube-state-metrics repo
    members:
    - dgrisonnet
    - fpetkovski
    - mrueg
    - rexagod
    privacy: closed
    repos:
      kube-state-metrics: write
  klog-admins:
    description: Admin access to the klog repo
    members:
    - dims
    - serathius
    - thockin
    privacy: closed
    repos:
      klog: admin
  klog-maintainers:
    description: Write access to the klog repo
    members:
    - dims
    - serathius
    - thockin
    privacy: closed
    repos:
      klog: write
  metrics-admins:
    description: Admin access to the metrics repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
    repos:
      metrics: admin
  metrics-maintainers:
    description: Write access to the metrics repo
    members:
    - dgrisonnet
    - serathius
    privacy: closed
    repos:
      metrics: write
