teams:
  sig-instrumentation-leads:
    description: ""
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    privacy: closed
  sig-instrumentation-approvers:
    description: ""
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    - RainbowMango
    - serathius
    privacy: closed
  sig-instrumentation-members:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - coffeepac
    - dashpole
    - DirectXMan12
    - ehashman
    - lilic
    - logicalhan
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    privacy: closed
