teams:
  community-images-admins:
    description: admins access to community-images
    members:
      - ameukam
      - dims
      - GenPage
      - hakman
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      community-images: admin
  community-images-writers:
    description: write access to community-images
    members:
      - ameukam
      - dims
      - GenPage
      - hakman
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      community-images: write
  community-images-maintainers:
    description: write access to community-images
    members:
      - ameukam
      - dims
      - GenPage
      - hakman
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      community-images: write
  porche-admins:
    description: admins access to porche
    members:
      - ameukam
      - GenPage
      - hakman
      - justinsb
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      porche: admin
  porche-writers:
    description: write access to porche
    members:
      - ameukam
      - GenPage
      - hakman
      - justinsb
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      porche: write
  porche-maintainers:
    description: write access to porche
    members:
      - ameukam
      - GenPage
      - hakman
      - justinsb
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      porche: write
