teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with access to
      publish packages (debs/rpms) on behalf of the Kubernetes project. This team is a
      notification-only group, which includes the SIG Release Chairs for continuity.
    members:
    - aleksandra-malinowska
    - calebamiles
    - justaugustus
    - listx
    - ps882
    - sumitranr
    - tpepper
    privacy: closed
  ci-signal:
    description: Members of the CI Signal team for the current release cycle.
    members:
      - alenkacz # 1.17 CI Signal Lead
      - droslean # 1.17 CI Signal shadow
      - epk # 1.17 CI Signal shadow
      - hasheddan # 1.17 CI Signal shadow
      - verolop # 1.17 CI Signal shadow
    privacy: closed
  licensing:
    description: Members of the Licensing subproject.
    maintainers:
    - nikhita # subproject owner
    members:
    - dims # subproject owner
    - justaugustus # subproject owner
    - swinslow # subproject owner
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on issues/PRs.
      This team also grants write access to the kubernetes/enhancements repo to allow
      editing of descriptions for Enhancement tracking issues.
    maintainers:
    - cblecker # ContribEx
    - fejta # Testing
    - mrbobbytables # 1.17 Enhancements Lead
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # 1.17 RT Lead Shadow
    - aleksandra-malinowska # Patch Release Team
    - alenkacz # 1.17 RT CI Signal lead
    - andrewsykim # Cloud Provider
    - annajung # 1.17 RT Enhancements shadow
    - benmoss # Windows
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - bubblemelon # Branch Manager
    - calebamiles # Release / PM
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - childsb # Storage
    - chrigl # OpenStack
    - cpanato # Branch Manager
    - craiglpeters # Azure
    - d-nishi # AWS
    - daminisatya #1.17 Docs Lead
    - danielromlein # UI
    - dcbw # Network
    - dchen1107 # Node
    - ddebroy # Windows
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dims # Architecture / Release
    - dougm # Patch Release Team
    - droslean # 1.17 CI Signal Shadow
    - enj # Auth
    - evillgenius75 # 1.17 Release Notes Shadow
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - guineveresaenger # 1.17 Release Lead
    - hasheddan # 1.17 CI Signal Shadow
    - hoegaarden # Patch Release Team
    - hpandeycodeit # Usability
    - idealhack # Patch Release Team
    - janetkuo # Apps
    - jberkhahn # Service Catalog
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeefy # UI
    - jeremyrickard # 1.17 RT Enhancements shadow
    - jimangel # Docs
    - josiahbjorgaard # 1.17 Bug Triage Lead
    - justaugustus # Azure / PM / Release
    - justinsb # AWS / Cluster Lifecycle
    - k82cn # Scheduling
    - k8s-release-robot # Release
    - kcmartin # 1.17 RT Enhancements shadow
    - khenidak # Azure
    - kikisdeliveryservice # 1.17 Bug Triage Shadow
    - kow3ns # Apps
    - kris-nova # AWS
    - lachie83 # PM
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - mariantalla # 1.17 RT Lead Shadow
    - markyjackson-taulia # 1.17 Bug Triage shadow
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - michmike # Windows
    - mikedanese # Auth
    - mm4tt # Scalability
    - mszostok # Service Catalog
    - mwielgus # Autoscaling
    - neolit123 # Cluster Lifecycle
    - oxddr # Scalability
    - palnabarun # 1.17 RT Enhancements shadow
    - parispittman # ContribEx
    - patricklang # Windows
    - phillels # ContribEx
    - piosz # Instrumentation
    - pmorie # Multicluster
    - prydonius # Apps
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - saad-ali # Storage
    - saschagrunert # Branch Manager
    - seans3 # CLI
    - shyamjvs # Scalability
    - smourapina # 1.17 Bug Triage shadow
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - tashimi # Usability
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - tpepper # Release
    - ttousai # 1.17 Bug Triage shadow
    - vllry # Usability
    - wojtek-t # Scalability
    - zacharysarah # Docs
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  patch-release-team:
    description: People managing patch releases of prior k8s minor release
      branches. This team is used for notifications for all active patch
      managers, but does not give permissions.
    members:
    - aleksandra-malinowska
    - dougm
    - feiskyer
    - hoegaarden
    - idealhack
    - tpepper
    privacy: closed
  publishing-bot-reviewers:
    description: Reviews for publishing-bot
    maintainers:
    - nikhita
    members:
    - caesarxuchao
    - dims
    - mfojtik
    - sttts
    privacy: closed
  release-engineering:
    description: Members of the Release Engineering subproject, including Build Admins,
      Patch Release Team, Branch Managers, and Release Manager Associates.
    maintainers:
    - nikhita # Release Manager Associate
    members:
    - aleksandra-malinowska # subproject owner / Build Admin / Patch Release Team
    - alexeldeib # Release Manager Associate
    - bubblemelon # Branch Manager
    - calebamiles # subproject owner
    - cpanato # Branch Manager
    - dougm # Patch Release Team
    - feiskyer # Patch Release Team
    - girikuncoro # Release Manager Associate
    - hoegaarden # subproject owner / Patch Release Team
    - idealhack # Patch Release Team
    - imkin # Release Manager Associate
    - javier-b-perez # Release Manager Associate
    - jimangel # Release Manager Associate
    - justaugustus # subproject owner / Branch Manager / Build Admin
    - kacole2 # Release Manager Associate
    - listx # Build Admin
    - onlydole # Release Manager Associate
    - paulbouwer # Release Manager Associate
    - ps882 # Build Admin
    - pswica # Release Manager Associate
    - saschagrunert # Branch Manager
    - sethmccombs # Release Manager Associate
    - slicknik # Release Manager Associate
    - sumitranr # Build Admin
    - tpepper # subproject owner / Build Admin / Patch Release Team
    - xmudrii # Release Manager Associate
    privacy: closed
  release-managers:
    description: People actively pushing k8s releases. Gives admin access to
      repos where branches must be created, etc., and write access to ones where
      label/PR management is needed. Remove users who are not actively doing
      this job.
    members:
    - aleksandra-malinowska # Patch Release Team
    - bubblemelon # Branch Manager
    - cpanato # Branch Manager
    - dougm # Patch Release Team
    - feiskyer # Patch Release Team
    - hoegaarden # Patch Release Team
    - idealhack # Patch Release Team
    - justaugustus # Branch Manager
    - k8s-release-robot
    - saschagrunert # Branch Manager
    - tpepper # Patch Release Team
    privacy: closed
    previously:
    - kubernetes-release-managers
  release-team:
    description: Members of the current Release Team and subproject owners.
    maintainers:
    - mrbobbytables # 1.17 Enhancements Lead
    - spiffxp # subproject owner
    members:
    - aishsundar # subproject owner
    - alejandrox1 # 1.17 RT Lead Shadow
    - alenkacz # 1.17 CI Signal Lead
    - bubblemelon # Branch Manager
    - cartyc # 1.17 Release Notes Lead
    - claurence # subproject owner
    - cpanato # Branch Manager
    - daminisatya # 1.17 Docs Lead
    - evillgenius75 # 1.17 Release Notes Shadow
    - guineveresaenger # 1.17 RT Lead
    - idealhack # Branch Manager
    - jberkus # subproject owner
    - jeefy # 1.17 RT Lead Shadow
    - josiahbjorgaard # 1.17 Bug Triage Lead
    - justaugustus # subproject owner
    - kacole2 # 1.16 Enhancements Lead
    - lachie83 # subproject owner
    - mariantalla # 1.17 RT Lead Shadow
    - nikopen # 1.16 RT Lead Shadow
    - onlydole # 1.16 Communications Lead
    - onyiny-ang # 1.16 Release Notes Shadow
    - rawkode # 1.17 Communications Lead
    - rbitia # 1.16 Enhancements Shadow
    - saschagrunert # 1.16 Release Notes Lead
    - simplytunde # 1.16 Docs Lead
    - soggiest # 1.16 CI Signal Shadow
    - tpepper # subproject owner
    - xmudrii # 1.16 Bug Triage Lead
    privacy: closed
    teams:
      release-team-leads:
        description: Release Team Leads for the current Kubernetes release cycle.
           Grants write access to kubernetes/kubernetes, kubernetes/release, and kubernetes/sig-release,
           and can be used as a notification group.
          Remove org members who are not current Release Team Leads.
        members:
        - alejandrox1 # 1.17 RT Lead Shadow
        - guineveresaenger # 1.17 RT Lead
        - jeefy # 1.17 RT Lead Shadow
        - mariantalla # 1.17 RT Lead Shadow
        privacy: closed
  sig-release:
    description: SIG Release Members
    maintainers:
    - mrbobbytables
    - nikhita
    - spiffxp
    members:
    - abgworrall
    - AishSundar
    - alejandrox1
    - aleksandra-malinowska
    - alenkacz
    - alexeldeib
    - amwat
    - BenTheElder
    - Bradamant3
    - bubblemelon
    - caesarxuchao
    - calebamiles
    - cartyc
    - castrojo
    - chenopis
    - chrisz100
    - cjwagner
    - claurence
    - cpanato
    - craiglpeters
    - daminisatya
    - dashpole
    - dchen1107
    - dims
    - dougm
    - dstrebel
    - enisoc
    - ethernetdan
    - evillgenius75
    - feiskyer
    - foxish
    - girikuncoro
    - guineveresaenger
    - hoegaarden
    - idealhack
    - imkin
    - ixdy
    - javier-b-perez
    - jberkus
    - jdumars
    - jeefy
    - jimangel
    - josiahbjorgaard
    - jpbetz
    - justaugustus
    - k82cn
    - kacole2
    - Katharine
    - kbarnard10
    - krzyzacy
    - lachie83
    - liggitt
    - listx
    - MaciekPytel
    - MAKOSCAFEE
    - mariantalla
    - marpaia
    - marun
    - mbohlool
    - mcrute
    - mistyhacks
    - mohammedzee1000
    - monopole
    - nickchase
    - nikopen
    - nwoods3
    - onlydole
    - onyiny-ang
    - ps882
    - pswica
    - pwittrock
    - radhikapc
    - rawkode
    - rbitia
    - saad-ali
    - saschagrunert
    - shyamjvs
    - simplytunde
    - slicknik
    - soggiest
    - steveperry-53
    - sumitranr
    - tfogo
    - tpepper
    - wojtek-t
    - xmudrii
    - zacharysarah
    - zparnold
    privacy: closed
    teams:
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - calebamiles
        - justaugustus
        - tpepper
        privacy: closed
