teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    members:
    - BenjaminKazemi
    - cpanato
    - justaugustus
    - MushuEE
    - puerco
    - saschagrunert
    - spiffxp
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - ameukam # Release Manager Associate
    - cblecker # ContribEx
    - mrbobbytables # ContribEx
    - nikhita # ContribEx
    - palnabarun # Release Manager
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # Testing
    - andrewsykim # Cloud Provider
    - aojea # Testing / Network
    - Atharva-Shinde # 1.27 Enhancements Shadow
    - BenTheElder # Testing
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - chrigl # OpenStack
    - cici37 # Release Manager Associate
    - claudiubelu # Windows
    - cpanato # Release Manager
    - craiglpeters # Azure
    - csantanapr # 1.27 Bug Triage Shadow
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dgrisonnet # Instrumentation
    - dims # Architecture / Release
    - eddiezane # CLI
    - ehashman # Instrumentation
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - fejta # Testing
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - fsmunoz # 1.27 Enhancements Shadow
    - furkatgofurov7 # 1.27 Bug Triage Shadow
    - gracenng # Release Manager Associate
    - harshanarayana # 1.27 Release Notes Lead
    - harshitasao # 1.27 Comms Lead
    - helayoty # 1.27 Lead Shadow
    - hosseinsalahi # 1.27 Lead Shadow
    - hpandeycodeit # Usability
    - Huang-Wei # Scheduling
    - jameslaverack # 1.27 Emeritus Advisor
    - janetkuo # Apps
    - jayunit100 # Windows
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeremyrickard # Release
    - jhvhs # Service Catalog
    - jimangel # Docs / Release Manager Associate
    - johnbelamaric # Architecture
    - jrsapi # Release Manager Associate
    - jsafrane # Storage
    - jsturtevant # Windows
    - justaugustus # Release
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - katcosgrove # 1.27 RT Lead Shadow
    - khenidak # Azure
    - KnVerey # CLI
    - kow3ns # Apps
    - krol3 # 1.26 Docs Lead
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - marosset # Windows
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - mikedanese # Auth
    - mm4tt # Scalability
    - mrunalp # Node
    - msau42 # Storage
    - mwielgus # Autoscaling
    - nckturner # AWS
    - neoaggelos # 1.27 Bug Triage Lead
    - neolit123 # Cluster Lifecycle
    - npolshakova # 1.27 Enhancements Shadow
    - oxddr # Scalability
    - parispittman # ContribEx
    - phillels # ContribEx
    - pmorie # Multicluster
    - Priyankasaggu11929 # 1.27 RT Lead Shadow
    - prydonius # Apps
    - puerco # Release Manager
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - ramrodo # Release Manager Associate
    - ritazh # Auth
    - saad-ali # Storage
    - salaxander # Release Manager Associate
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - seans3 # CLI
    - serathius # Instrumentation
    - SergeyKanzhelev # Node
    - shatoboar # 1.27 Enhancements Shadow
    - shu-mutou # UI
    - shyamjvs # Scalability
    - soltysh # CLI
    - sowmyav27 # 1.27 Bug Triage Shadow
    - spiffxp # Testing
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - tashimi # Usability
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - valaparthvi # 1.27 Bug Triage Shadow
    - Verolop # Release Manager
    - vllry # Usability
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  publishing-bot-admins:
    description: Admin access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
  publishing-bot-maintainers:
    description: Write access to the publishing-bot repo
    maintainers:
    - nikhita
    - palnabarun
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    - Verolop
    - xmudrii
    privacy: closed
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - fejta
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    privacy: closed
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - fejta
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    - Verolop
    - xmudrii
    privacy: closed
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - palnabarun
    members:
    - alenkacz
    - BenTheElder
    - castrojo
    - cici37
    - cpanato # Technical Lead
    - dims
    - ixdy
    - JamesLaverack
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - leonardpahlke
    - liggitt
    - mariantalla
    - nikopen
    - onyiny-ang
    - puerco # Technical Lead
    - rawkode
    - reylejano
    - salaxander
    - saschagrunert # Chair
    - savitharaghunathan
    - soggiest
    - spiffxp
    - tpepper
    privacy: closed
    teams:
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        maintainers:
        - ameukam # Release Manager Associate
        - palnabarun # Release Manager
        members:
        - cici37 # Release Manager Associate
        - cpanato # subproject owner / Release Manager
        - gracenng # Release Manager Associate
        - jeremyrickard # subproject owner / Release Manager
        - jimangel # Release Manager Associate
        - jrsapi # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - puerco # subproject owner / Release Manager
        - ramrodo # Release Manager Associate
        - salaxander # Release Manager Associate
        - saschagrunert # subproject owner / Release Manager
        - Verolop # subproject owner / Release Manager
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            maintainers:
            - palnabarun
            members:
            - cpanato
            - jeremyrickard
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - Verolop
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
      release-team:
        description: Members of the current Release Team and subproject owners.
        maintainers:
        - palnabarun # subproject owner (1.21 RT Lead)
        members:
        - Atharva-Shinde # 1.27 Enhancements Shadow
        - cici37 # subproject owner (1.25 RT Lead)
        - cpanato # subproject owner / Technical Lead
        - csantanapr # 1.27 Bug Triage Shadow
        - fsmunoz # 1.27 Enhancements Shadow
        - furkatgofurov7 # 1.27 Bug Triage Shadow
        - harshanarayana # 1.27 Release Notes Lead
        - harshitasao # 1.27 Comms Lead
        - helayoty # 1.27 RT Lead Shadow
        - hosseinsalahi # 1.27 RT Lead Shadow
        - jameslaverack # subproject owner (1.24 RT Lead)
        - jeremyrickard # subproject owner / Technical Lead
        - justaugustus # subproject owner / Chair
        - katcosgrove # 1.27 RT Lead Shadow
        - lauralorenz # 1.27 CI Signal Lead
        - leonardpahlke # subproject owner (1.26 RT Lead)
        - marosset # 1.27 Enhancements Lead
        - mickeyboxell # 1.27 Docs Lead
        - neoaggelos # 1.27 Bug Triage Lead
        - npolshakova # 1.27 Enhancements Shadow
        - Priyankasaggu11929 # 1.27 RT Lead Shadow
        - puerco # subproject owner / Technical Lead
        - reylejano # subproject owner (1.23 RT Lead)
        - salaxander # subproject owner (1.27 RT Lead)
        - saschagrunert # subproject owner / Chair
        - savitharaghunathan # subproject owner (1.22 RT Lead)
        - shatoboar # 1.27 Enhancements Shadow
        - sowmyav27 # 1.27 Bug Triage Shadow
        - valaparthvi # 1.27 Bug Triage Shadow
        - Verolop # Release Manager
        - xmudrii # Release Manager
        privacy: closed
        teams:
          ci-signal:
            description: Members of the CI Signal team for the current release
              cycle.
            members:
            - drewhagen # 1.27 CI Signal Shadow
            - gracenng # 1.27 CI Signal Shadow
            - lauralorenz # 1.27 CI Signal Lead
            - mehabhalodiya # 1.27 CI Signal Shadow
            - Vyom-Yadav # 1.27 CI Signal Shadow
            privacy: closed
          release-team-docs:
            description: Members of the Docs team for the current release cycle.
            members:
            - mickeyboxell # 1.27 Docs Lead
            privacy: closed
          release-team-bug-triage:
            description: Members of the Bug Triage team for the current release cycle.
            members:
            - csantanapr # 1.27 Bug Triage Shadow
            - furkatgofurov7 # 1.27 Bug Triage Shadow
            - neoaggelos # 1.27 Bug Triage Lead
            - sowmyav27 # 1.27 Bug Triage Shadow
            - valaparthvi # 1.27 Bug Triage Shadow
            privacy: closed
          release-team-comms:
            description: Members of the Comms team for the current release cycle.
            members:
            - bradmccoydev # 1.27 Comms Shadow 
            - harshitasao # 1.27 Comms Lead
            - jaehnri # 1.27 Comms Shadow
            - Nancy-Chauhan # 1.27 Comms Shadow
            - sfotony # 1.27 Comms Shadow
            privacy: closed
          release-team-enhancements:
            description: Members of the Enhancments team for the current release
              cycle.
            members:
            - Atharva-Shinde # 1.27 Enhancements Shadow
            - fsmunoz # 1.27 Enhancements Shadow
            - marosset # 1.27 Enhancements Lead
            - npolshakova # 1.27 Enhancements Shadow
            - shatoboar # 1.27 Enhancements Shadow
            privacy: closed
          release-team-release-notes:
            description: Members of the Release Notes team for the current release
              cycle.
            members:
            - AnaMMedina21 # 1.27 Release Notes Shadow
            - harshanarayana # 1.27 Release Notes Lead
            - rjsadow # 1.27 Release Notes Shadow
            - sanchita-07 # 1.27 Release Notes Shadow
            - yrs147 # 1.27 Release Notes Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            members:
            - helayoty # 1.27 RT Lead Shadow
            - hosseinsalahi # 1.27 RT Lead Shadow
            - jameslaverack # 1.27 Emeritus Advisor
            - katcosgrove # 1.26 RT Lead Shadow
            - Priyankasaggu11929 # 1.26 RT Lead Shadow
            - salaxander # 1.27 RT Lead
            privacy: closed
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
