teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    - justaugustus
    - MushuEE
    - saschagrunert
    - tpepper
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs. This team also grants write access to the
      kubernetes/enhancements repo to allow editing of descriptions for
      Enhancement tracking issues.
    maintainers:
    - cblecker # ContribEx
    - fejta # Testing
    - mrbobbytables # ContribEx
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # Testing
    - ameukam # Release Manager Associate
    - andrewsykim # Cloud Provider
    - annajung # 1.20 Docs Lead
    - bai # 1.20 Bug Triage Lead
    - benmoss # Windows
    - BenTheElder # Testing
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - chrigl # OpenStack
    - cpanato # Release Manager
    - craiglpeters # Azure
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - ddebroy # Windows
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dims # Architecture / Release
    - dougm # Release Manager
    - droslean # 1.20 Bug Triage Shadow
    - ehashman # Instrumentation
    - enj # Auth
    - erismaster # 1.20 Bug Triage Shadow
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - gianarb # Release Manager Associate
    - hasheddan # Release Manager / 1.20 RT Lead Shadow
    - hoegaarden # Release Manager
    - hpandeycodeit # Usability
    - Huang-Wei # Scheduling
    - idealhack # Release Manager
    - jameslaverack # 1.20 Release Notes Lead
    - janetkuo # Apps
    - jberkhahn # Service Catalog
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeefy # UI
    - jeremyrickard # 1.20 RT Lead
    - jimangel # Docs / Release Manager Associate
    - johnbelamaric # Architecture
    - jrsapi # 1.20 Communications Lead
    - jsafrane # Storage
    - justaugustus # Azure / PM / Release
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - khenidak # Azure
    - kikisdeliveryservice # 1.20 Enhancements Lead
    - kow3ns # Apps
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - markyjackson-taulia # Release Manager Associate
    - marosset # Windows
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - michmike # Windows
    - mikedanese # Auth
    - mkorbi # Release Manager Associate
    - mm4tt # Scalability
    - msau42 # Storage
    - mszostok # Service Catalog
    - mwielgus # Autoscaling
    - nckturner # AWS
    - neolit123 # Cluster Lifecycle
    - onlydole # Release Manager Associate
    - oxddr # Scalability
    - palnabarun # 1.20 RT Lead Shadow
    - parispittman # ContribEx
    - phillels # ContribEx
    - pmorie # Multicluster
    - prydonius # Apps
    - puerco # Release Manager
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - robertkielty # 1.20 CI Signal Lead
    - saad-ali # Storage
    - saschagrunert # Release Manager
    - savitharaghunathan # 1.20 RT Lead Shadow
    - sayanchowdhury # 1.20 Bug Triage Shadow
    - seans3 # CLI
    - serathius # Instrumentation
    - sethmccombs # Release Manager Associate
    - shyamjvs # Scalability
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - tashimi # Usability
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - tpepper # Release
    - verolop # Release Manager Associate
    - vllry # Usability
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager
    - zacharysarah # Docs
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  publishing-bot-reviewers:
    description: Reviews for publishing-bot
    maintainers:
    - nikhita
    members:
    - caesarxuchao
    - dims
    - mfojtik
    - sttts
    privacy: closed
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - spiffxp
    members:
    - alejandrox1 # Technical Lead
    - alenkacz
    - BenTheElder
    - castrojo
    - dims
    - ixdy
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard
    - justaugustus # Chair
    - LappleApple # Program Manager
    - liggitt
    - mariantalla
    - nikopen
    - onyiny-ang
    - palnabarun
    - rawkode
    - saschagrunert # Technical Lead
    - savitharaghunathan
    - soggiest
    - tpepper # Chair
    privacy: closed
    teams:
      licensing:
        description: Members of the Licensing subproject.
        maintainers:
        - nikhita # subproject owner
        members:
        - dims # subproject owner
        - justaugustus # subproject owner
        - swinslow # subproject owner
        privacy: closed
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        members:
        - ameukam # Release Manager Associate
        - cpanato # Release Manager
        - dougm # Release Manager
        - feiskyer # Release Manager
        - gianarb # Release Manager Associate
        - hasheddan # Release Manager
        - hoegaarden # Release Manager
        - idealhack # Release Manager
        - jimangel # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - markyjackson-taulia # Release Manager Associate
        - mkorbi # Release Manager Associate
        - onlydole # Release Manager Associate
        - puerco # Release Manager
        - saschagrunert # subproject owner / Release Manager
        - sethmccombs # Release Manager Associate
        - tpepper # subproject owner / Release Manager
        - Verolop # Release Manager Associate
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            members:
            - cpanato
            - dougm
            - feiskyer
            - hasheddan
            - hoegaarden
            - idealhack
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - tpepper
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
      release-team:
        description: Members of the current Release Team and subproject owners.
        members:
        - alejandrox1 # subproject owner
        - annajung # 1.20 Docs Lead
        - bai # 1.20 Bug Triage Lead
        - celestehorgan # 1.20 Release Notes Shadow
        - chris-short # 1.20 Communications Shadow 
        - cpanato # Release Manager
        - divya-mohan0209 # 1.20 Communications Shadow
        - droslean # 1.20 Bug Triage Shadow
        - eagleusb # 1.20 Docs Shadow
        - eddiezane # 1.20 CI Signal Shadow
        - erismaster # 1.20 Bug Triage Shadow
        - guineveresaenger # subproject owner
        - hasheddan # Release Manager / 1.20 RT Lead Shadow
        - hkamel # 1.20 CI Signal Shadow
        - jameslaverack # 1.20 Release Notes Lead
        - jeremyrickard # 1.20 RT Lead
        - jrsapi # 1.20 Communications Lead
        - justaugustus # subproject owner
        - kcmartin # 1.20 Docs Shadow
        - kendallroden # 1.20 Enhancements Shadow
        - kikisdeliveryservice # 1.20 Enhancements Lead
        - kinarashah # 1.20 Enhancements Shadow
        - lachie83 # subproject owner / 1.20 Emeritus Adviser
        - mikejoh # 1.20 Enhancements Shadow
        - mkorbi # 1.20 Bug Triage Shadow
        - monzelmasry # 1.20 Bug Triage Shadow
        - morrislaw # 1.20 Enhancements Shadow
        - onlydole # subproject owner
        - palnabarun # 1.20 RT Lead Shadow
        - puerco # Release Manager
        - reylejano-rxm # 1.20 Docs Shadow
        - robertkielty # 1.20 CI Signal Lead
        - salaxander # 1.20 Communications Shadow
        - saschagrunert # Release Manager
        - savitharaghunathan # 1.20 RT Lead Shadow
        - sayanchowdhury # 1.20 Bug Triage Shadow
        - scrapcodes # 1.20 CI Signal Shadow
        - sfotony # 1.20 Communications Shadow
        - somtochiama # 1.20 Docs Shadow
        - soniasingla # 1.20 Release Notes Shadow
        - tanjacky # 1.20 Release Notes Shadow
        - thejoycekung # 1.20 CI Signal Shadow
        - tpepper # subproject owner / Release Manager
        - wilsonehusin # 1.20 Release Notes Shadow
        - xmudrii # Release Manager
        privacy: closed
        teams:
          ci-signal:
            description: Members of the CI Signal team for the current release
              cycle.
            members:
            - eddiezane # 1.20 CI Signal Shadow
            - hkamel # 1.20 CI Signal Shadow
            - robertkielty # 1.20 CI Signal Lead
            - ScrapCodes # 1.20 CI Signal Shadow
            - thejoycekung # 1.20 CI Signal Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            members:
            - hasheddan #  1.20 RT Lead Shadow
            - jeremyrickard # 1.20 RT Lead
            - lachie83 # 1.20 Emeritus Adviser
            - palnabarun # 1.20 RT Lead Shadow
            - savitharaghunathan # 1.20 RT Lead Shadow
            privacy: closed
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - alejandrox1 # Technical Lead
        - justaugustus # Chair
        - saschagrunert # Technical Lead
        - tpepper # Chair
        privacy: closed
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - alejandrox1 # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - saschagrunert # Technical Lead
        - tpepper # Chair
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - alejandrox1 # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - saschagrunert # Technical Lead
        - tpepper # Chair
        privacy: closed
