teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    - hasheddan
    - justaugustus
    - MushuEE
    - saschagrunert
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - cblecker # ContribEx
    - fejta # Testing
    - mrbobbytables # ContribEx
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # Testing
    - ameukam # Release Manager Associate
    - andrewsykim # Cloud Provider
    - annajung # 1.22 RT Lead Shadow
    - BenTheElder # Testing
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - chrigl # OpenStack
    - cpanato # Release Manager
    - craiglpeters # Azure
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - ddebroy # Windows
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dims # Architecture / Release
    - divya-mohan0209 # 1.22 RT Lead Shadow
    - eddiezane # CLI
    - ehashman # Instrumentation
    - enj # Auth
    - erismaster # 1.22 RT Lead Shadow
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - gracenng # 1.22 Enhancements Shadow
    - guineveresaenger # 1.22 Emeritus Advisor
    - hasheddan # Release
    - hpandeycodeit # Usability
    - Huang-Wei # Scheduling
    - jameslaverack # 1.22 Enhancements Lead
    - janetkuo # Apps
    - jayunit100 # Windows
    - jberkhahn # Service Catalog
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeefy # UI
    - jeremyrickard # Release
    - jgavinray # 1.22 Bug Triage Shadow
    - jimangel # Docs / Release Manager Associate
    - jlbutler # 1.22 Release Comms Shadow
    - johnbelamaric # Architecture
    - jrsapi # 1.22 Enhancements Shadow
    - jsafrane # Storage
    - jsturtevant # Windows
    - justaugustus # Azure / PM / Release
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - khenidak # Azure
    - kikisdeliveryservice # 1.22 RT Lead Shadow
    - KnVerey # CLI - Kustomize
    - kow3ns # Apps
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - marosset # Windows
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - mikedanese # Auth
    - mkorbi # Release Manager Associate / 1.22 CI Signal Lead
    - mm4tt # Scalability
    - monzelmasry # 1.22 Bug Triage Lead
    - msau42 # Storage
    - mszostok # Service Catalog
    - mwielgus # Autoscaling
    - nckturner # AWS
    - neolit123 # Cluster Lifecycle
    - notchairmk # 1.22 Bug Triage Shadow
    - onlydole # Release Manager Associate / 1.21 Emeritus Advisor
    - oxddr # Scalability
    - palnabarun # 1.21 RT Lead
    - parispittman # ContribEx
    - Pensu # 1.22 Release Comms Lead
    - phillels # ContribEx
    - PI-Victor # 1.22 Docs Lead
    - pmmalinov01 # 1.22 Release Notes Lead
    - pmorie # Multicluster
    - prydonius # Apps
    - puerco # Release Manager
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - reylejano # 1.22 Enhancements Shadow
    - saad-ali # Storage
    - salaxander # 1.22 Enhancements Shadow
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - savitharaghunathan # 1.22 RT Lead
    - seans3 # CLI
    - serathius # Instrumentation
    - sethmccombs # Release Manager Associate
    - sfotony # 1.22 Bug Triage Shadow
    - shyamjvs # Scalability
    - simcard0000 # 1.22 Release Notes Shadow
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - supriya-premkumar # 1.22 Enhancements Shadow
    - tallclair # Auth
    - tashimi # Usability
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - verolop # Release Manager Associate
    - vllry # Usability
    - voigt # 1.22 Bug Triage Shadow
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  publishing-bot-reviewers:
    description: Reviews for publishing-bot
    maintainers:
    - nikhita
    members:
    - caesarxuchao
    - dims
    - mfojtik
    - sttts
    privacy: closed
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - spiffxp
    members:
    - alejandrox1 # Technical Lead
    - alenkacz
    - BenTheElder
    - castrojo
    - dims
    - hasheddan # Technical Lead
    - ixdy
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - LappleApple # Program Manager
    - liggitt
    - mariantalla
    - nikopen
    - onyiny-ang
    - palnabarun
    - rawkode
    - saschagrunert # Chair
    - savitharaghunathan
    - soggiest
    - tpepper
    privacy: closed
    teams:
      licensing:
        description: Members of the Licensing subproject.
        maintainers:
        - nikhita # subproject owner
        members:
        - dims # subproject owner
        - justaugustus # subproject owner
        - swinslow # subproject owner
        privacy: closed
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        members:
        - ameukam # Release Manager Associate
        - cpanato # Release Manager
        - hasheddan # subproject owner / Release Manager
        - jimangel # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - mkorbi # Release Manager Associate
        - onlydole # Release Manager Associate
        - puerco # Release Manager
        - saschagrunert # subproject owner / Release Manager
        - sethmccombs # Release Manager Associate
        - Verolop # Release Manager Associate
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            members:
            - cpanato
            - hasheddan
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
      release-team:
        description: Members of the current Release Team and subproject owners.
        members:
        - alejandrox1 # subproject owner
        - annajung # 1.22 RT Lead Shadow
        - ashnehete # 1.22 Release Docs Shadow
        - carlisia # 1.22 Release Docs Shadow
        - chrisnegus # 1.22 Release Docs Shadow
        - cici37 # 1.22 Release Notes Shadow
        - cpanato # Release Manager
        - Damans227 # 1.22 Release Notes Shadow
        - divya-mohan0209 # 1.22 RT Lead Shadow
        - encodeflush # 1.22 CI Signal Shadow
        - erismaster # 1.22 RT Lead Shadow
        - gracenng # 1.22 Enhancements Shadow
        - guineveresaenger # subproject owner / 1.22 EA
        - hasheddan # subproject owner
        - jameslaverack # 1.22 Enhancements Lead
        - jeremyrickard # Tech Lead
        - jgavinray # 1.22 Bug Triage Shadow
        - jlbutler # 1.22 Release Comms Shadow
        - jrsapi # 1.22 Enhancements Shadow
        - justaugustus # subproject owner
        - kikisdeliveryservice # 1.22 RT Lead Shadow
        - kunal-kushwaha # 1.22 Release Comms Shadow
        - lachie83 # subproject owner / 1.20 Emeritus Advisor
        - lambdanis # 1.22 CI Signal Shadow
        - mkorbi # 1.22 CI Signal Lead
        - monzelmasry # 1.22 Bug Triage Lead
        - notchairmk # 1.22 Bug Triage Shadow
        - onlydole # subproject owner
        - palnabarun # subproject owner
        - Pensu # 1.22 Release Comms Lead
        - PI-Victor # 1.22 Docs Lead
        - pmmalinov01 # 1.22 Release Notes Lead
        - puerco # Release Manager
        - rajula96reddy # 1.22 Release Comms Shadow
        - ramrodo # 1.22 CI Signal Shadow
        - reylejano # 1.22 Enhancements Shadow
        - ritpanjw # 1.22 Release Docs Shadow
        - salaxander # 1.22 Enhancements Shadow
        - saschagrunert # subproject owner
        - savitharaghunathan # 1.22 RT Lead
        - sfotony # 1.22 Bug Triage Shadow
        - simcard0000 # 1.22 Release Notes Shadow
        - skrishna-unix # 1.22 Release Comms Shadow
        - sladyn98 # 1.22 Release Notes Shadow
        - soniasingla # 1.22 CI Signal Shadow
        - supriya-premkumar # 1.22 Enhancements Shadow
        - thejoycekung # 1.22 Branch Manager Shadow
        - verolop # 1.22 Branch Manager Shadow
        - voigt # 1.22 Bug Triage Shadow
        - xmudrii # Release Manager
        privacy: closed
        teams:
          ci-signal:
            description: Members of the CI Signal team for the current release
              cycle.
            members:
            - encodeflush # 1.22 CI Signal Shadow
            - lambdanis # 1.22 CI Signal Shadow
            - mkorbi # 1.22 CI Signal Lead
            - ramrodo # 1.22 CI Signal Shadow
            - soniasingla # 1.22 CI Signal Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            members:
            - annajung # 1.22 RT Lead Shadow
            - divya-mohan0209 # 1.22 RT Lead Shadow
            - erismaster # 1.22 RT Lead Shadow
            - guineveresaenger # 1.22 Emeritus Advisor
            - kikisdeliveryservice # 1.22 RT Lead Shadow
            - savitharaghunathan # 1.22 RT Lead
            privacy: closed
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - alejandrox1 # Technical Lead
        - hasheddan # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - saschagrunert # Chair
        privacy: closed
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - alejandrox1 # Technical Lead
        - hasheddan # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - saschagrunert # Chair
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - alejandrox1 # Technical Lead
        - hasheddan # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - LappleApple # Program Manager
        - saschagrunert # Chair
        privacy: closed
