teams:
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - MadhavJivrajani # ContribEx
    - palnabarun # Release Manager
    - Priyankasaggu11929 # ContribEx
    members:
    - aakankshabhende # 1.35 Comms Shadow
    - adrianmoisey # Autoscaling
    - aibarbetta # 1.36 Release Lead Shadow
    - ameukam # Release Manager Associate / K8s Infra
    - aojea # Testing / Network
    - aramase # Auth
    - aravindhp # Windows
    - ardaguclu # CLI
    - arujjval # 1.35 Comms Shadow
    - BenTheElder # Testing / K8s Infra
    - bgrant0607 # Architecture
    - bowei # Network
    - brancz # Instrumentation
    - bridgetkromhout # Cloud Provider
    - caseydavenport # Network
    - chadmcrowell # 1.36 Comms Lead
    - chanieljdan # 1.35 Enhancements Shadow
    - cheftako # Cloud Provider
    - cici37 # Release Manager
    - claudiubelu # Windows
    - cpanato # Release Manager
    - danwinship # Network
    - dashpole # Instrumentation
    - dchen1107 # Node
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dgrisonnet # Instrumentation
    - dims # Architecture / K8s Infra
    - dipesh-rawat # 1.36 Release Lead Shadow
    - dom4ha # Scheduling
    - drewhagen # 1.35 Release Lead
    - eddiezane # CLI
    - ehashman # Instrumentation
    - elmiko # Cloud Provider
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - fsmunoz # 1.34 EA
    - fykaa # 1.35 Enhancements Shadow
    - GenPage # K8s Infra
    - gjtempleton # Autoscaling
    - gracenng # Release Manager Associate / 1.30 RT EA
    - graz-dev # 1.35 Comms Lead
    - haircommander # Node
    - hakman # K8s Infra
    - jackfrancis # Autoscaling
    - janetkuo # Apps
    - jberkus # Release
    - jbpratt # Testing
    - jenshu # 1.36 Release Lead Shadow
    - jeremyrickard # Release
    - jimangel # Docs / Release Manager Associate / 1.32 Release Branch Manager
    - jmickey # 1.36 Enhancements Lead
    - joaquimrocha # UI
    - joelspeed # Cloud Provider
    - johnbelamaric # Architecture
    - jpbetz # API Machinery
    - jrsapi # Release Manager Associate
    - jsafrane # Storage
    - justaugustus # Release
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - kannon92 # wg-batch organizer
    - katcosgrove # v1.32 EA
    - kow3ns # Apps
    - liggitt # Auth / Release
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - macsko # Scheduling
    - marosset # Windows
    - mbianchidev # v1.34 Branch Manager
    - mborsz # Scalability
    - mengqiy # Scalability
    - micahhausler # Auth
    - michelle192837 # Testing
    - michellengnx # 1.34 Docs Lead
    - mickeyboxell # 1.32 Release Manager Shadow
    - mikezappa87 # Network
    - mm4tt # Scalability
    - mpuckett159 # CLI
    - mrunalp # Node
    - msau42 # Storage
    - neoaggelos # v1.34 Branch Management Shadow
    - neolit123 # Cluster Lifecycle
    - npolshakova # 1.33 Release Lead
    - pacoxu # Cluster Lifecycle
    - pohly # SIG Testing, Instrumentation, Node
    - puerco # Release Manager
    - RainbowMango # Instrumentation
    - Rajalakshmi-Girish # v1.35 Release Lead Shadow
    - rayandas # 1.36 Release Lead Shadow
    - rexagod # Instrumentation
    - richabanker # Instrumentation
    - ritazh # Auth
    - rytswd # 1.36 Release Lead
    - saad-ali # Storage
    - salaxander # Release Manager Associate / 1.29 RT EA
    - salehsedghpour # 1.32 Release Lead Shadow
    - sanposhiho # Scheduling
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - satyampsoni # v1.34 Branch Management Shadow
    - serathius # Instrumentation
    - SergeyKanzhelev # Node
    - shaneutt # Network
    - shu-mutou # UI
    - shyamjvs # Scalability
    - soltysh # CLI
    - spzala # IBM Cloud
    - sreeram-venkitesh # 1.34 Release Lead Shadow
    - stmcginnis # 1.34 Enhancements Shadow
    - sttts # API Machinery
    - SwathiR03 # 1.35 Comms Shadow
    - tallclair # Auth
    - thockin # Network
    - tico88612 # 1.35 Release Signal Lead
    - towca # Autoscaling
    - upodroid # K8s Infra
    - Verolop # Release Manager
    - whtssub # 1.35 Enhancements Shadow
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager / K8s Infra
    - zylxjtu # Windows
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
    repos:
      enhancements: write
  publishing-bot-admins:
    description: Admin access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
    repos:
      publishing-bot: admin
  publishing-bot-maintainers:
    description: Write access to the publishing-bot repo
    maintainers:
    - nikhita
    - palnabarun
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    - Verolop
    - xmudrii
    privacy: closed
    repos:
      publishing-bot: write
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    members:
    - BenTheElder
    - cpanato
    - justaugustus
    - puerco
    - saschagrunert
    privacy: closed
    repos:
      repo-infra: admin
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    members:
    - BenTheElder
    - cpanato
    - justaugustus
    - puerco
    - saschagrunert
    - Verolop
    - xmudrii
    privacy: closed
    repos:
      repo-infra: write
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - palnabarun
    - Priyankasaggu11929
    members:
    - BenTheElder
    - castrojo
    - cici37
    - cpanato # Technical Lead
    - dims
    - gracenng
    - JamesLaverack
    - jberkus
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - katcosgrove
    - liggitt
    - puerco # Technical Lead
    - reylejano
    - salaxander
    - saschagrunert # Chair
    - savitharaghunathan
    privacy: closed
    teams:
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        maintainers:
        - palnabarun # Release Manager
        members:
        - ameukam # Release Manager Associate
        - cici37 # Release Manager
        - cpanato # subproject owner / Release Manager
        - gracenng # Release Manager Associate
        - jeremyrickard # subproject owner / Release Manager
        - jimangel # Release Manager Associate / 1.32 Release Manager
        - jrsapi # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - marosset # Release Manager Associate
        - mehabhalodiya # Release Manager Associate
        - mickeyboxell # 1.32 Release Manager Shadow
        - puerco # subproject owner / Release Manager
        - ramrodo # Release Manager Associate
        - salaxander # Release Manager Associate
        - saschagrunert # subproject owner / Release Manager
        - Verolop # subproject owner / Release Manager
        - xmudrii # Release Manager
        privacy: closed
        repos:
          release: triage
          sig-release: triage
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            maintainers:
            - palnabarun
            members:
            - cici37
            - cpanato
            - jeremyrickard
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - Verolop
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
            repos:
              kubernetes: admin
              release: write
              sig-release: write
      release-team:
        description: Members of the current Release Team and subproject owners.
        maintainers:
        - palnabarun # subproject owner (1.21 RT Lead)
        - Priyankasaggu11929 # subproject owner (1.29 RT Lead)
        members:
        - aibarbetta # 1.35 Enhancements Shadow
        - chanieljdan # 1.35 Enhancements Shadow
        - cpanato # subproject owner / Technical Lead
        - drewhagen # 1.35 Release Lead
        - fykaa # 1.35 Enhancements Shadow
        - gracenng # subproject owner (1.28 RT Lead)
        - jameslaverack # subproject owner (1.24 RT Lead)
        - jenshu # 1.34 Enhancements Lead
        - jeremyrickard # subproject owner / Technical Lead
        - jimangel # 1.32 RT Branch Manager
        - jmickey # 1.35 Enhancements Shadow
        - justaugustus # subproject owner / Chair
        - katcosgrove # 1.30 Lead / 1.32 EA
        - mickeyboxell # 1.32 Release Manager Shadow
        - puerco # subproject owner / Technical Lead
        - rayandas # 1.34 Enhancements Shadow
        - reylejano # subproject owner (1.23 RT Lead)
        - salaxander # subproject owner (1.27 RT Lead)
        - saschagrunert # subproject owner / Chair
        - savitharaghunathan # subproject owner (1.22 RT Lead)
        - stmcginnis # 1.34 Enhancements Shadow
        - Verolop # Release Manager
        - whtssub # 1.35 Enhancements Shadow
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-team-release-signal:
            description: Members of the Release Signal team for the current release
              cycle.
            members:
            - adilGhaffarDev # 1.35 Release Signal Shadow
            - benjaminapetersen # 1.35 Release Signal Shadow
            - kei01234kei # 1.35 Release Signal Shadow
            - knabben # 1.35 Release Signal Shadow
            - Prajyot-Parab # 1.35 Release Signal Shadow
            - tico88612 # 1.35 Release Signal Lead
            - yunchi0921 # v1.35 Release Signal Shadow
            privacy: closed
          release-team-docs:
            description: Members of the Docs team for the current release cycle.
            members:
            - AnshumanTripathi # 1.35 Docs Shadow
            - Jimmykhangnguyen # 1.35 Docs Shadow
            - kernel-kun # 1.35 Docs Shadow
            - OrlinVasilev # 1.35 Docs Lead
            - sayanchowdhury # 1.35 Docs Shadow
            - Urvashi0109 # 1.35 Docs Lead
            privacy: closed
          release-team-comms:
            description: Members of the Comms team for the current release cycle.
            members:
            - aakankshabhende # 1.35 Comms Shadow
            - arujjval # 1.35 Comms Shadow
            - chadmcrowell # 1.35 Comms Shadow
            - graz-dev # 1.35 Comms Lead
            - SwathiR03 # 1.35 Comms Shadow
            privacy: closed
          release-team-enhancements:
            description: Members of the Enhancements team for the current release
              cycle.
            members:
            - aibarbetta # 1.35 Enhancements Shadow
            - chanieljdan # 1.35 Enhancements Shadow
            - fykaa # 1.35 Enhancements Shadow
            - jmickey # 1.35 Enhancements Shadow
            - rayandas # 1.35 Enhancements Lead
            - whtssub # 1.35 Enhancements Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            maintainers:
            - Priyankasaggu11929 # 1.31 Release EA
            members:
            - aibarbetta # 1.36 Release Lead
            - dipesh-rawat # 1.36 Release Lead Shadow
            - jenshu # 1.36 Release Lead Shadow
            - jimangel # 1.32 Release Branch Manager
            - katcosgrove # subproject owner / 1.32 Release EA
            - rayandas # v1.36 Release Lead Shadow
            - rytswd # 1.36 Release Lead
            privacy: closed
            repos:
              kubernetes: write
              release: triage
              sig-release: write
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
        repos:
          release: admin
          sig-release: admin
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
        repos:
          release: triage
          sig-release: maintain
