teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    members:
    - BenjaminKazemi
    - cpanato
    - justaugustus
    - MushuEE
    - puerco
    - saschagrunert
    - spiffxp
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - MadhavJivrajani # ContribEx
    - palnabarun # Release Manager
    - Priyankasaggu11929 # ContribEx
    members:
    - a-mccarthy # 1.31 Communications Lead
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alculquicondor # Scheduling
    - ameukam # Release Manager Associate / K8s Infra
    - andrewsykim # Cloud Provider
    - aojea # Testing / Network
    - aravindhp # Windows
    - ardaguclu # CLI
    - BenTheElder # Testing / K8s Infra
    - bgrant0607 # Architecture
    - brancz # Instrumentation
    - bridgetkromhout # Cloud Provider
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - cici37 # Release Manager
    - claudiubelu # Windows
    - cpanato # Release Manager
    - craiglpeters # Azure
    - danwinship # Network
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dgrisonnet # Instrumentation
    - dims # Architecture / K8s Infra
    - drewhagen # 1.31 Release Lead Shadow
    - eddiezane # CLI
    - ehashman # Instrumentation
    - elmiko # Cloud Provider
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - frapposelli # VMware
    - fsmunoz # 1.31 Release Lead Shadow
    - gjtempleton # Autoscaling
    - gracenng # Release Manager Associate / 1.30 RT EA
    - Huang-Wei # Scheduling
    - janetkuo # Apps
    - jayunit100 # Windows
    - jberkus # Release
    - jbpratt # Testing
    - jdumars # Architecture / PM
    - jeremyrickard # Release
    - jimangel # Docs / Release Manager Associate
    - johnbelamaric # Architecture
    - jpbetz # API Machinery
    - jrsapi # Release Manager Associate
    - jsafrane # Storage
    - jsturtevant # Windows
    - justaugustus # Release
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - katcosgrove # v1.30 RT Lead
    - khenidak # Azure
    - kow3ns # Apps
    - lavalamp # API Machinery
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - maciekpytel # Autoscaling
    - marosset # Windows
    - mborsz # Scalability
    - michelle192837 # Testing
    - mikedanese # Auth
    - mikezappa87 # Network
    - mm4tt # Scalability
    - mpuckett159 # CLI
    - mrunalp # Node
    - msau42 # Storage
    - nckturner # AWS
    - neoaggelos # 1.31 Release Lead
    - neolit123 # Cluster Lifecycle
    - npolshakova # 1.31 Release Notes Lead
    - pacoxu # Cluster Lifecycle
    - pmorie # Multicluster
    - pohly # SIG Testing, Instrumentation, Node
    - Princesso # 1.31 Docs Lead
    - puerco # Release Manager
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - ritazh # Auth
    - saad-ali # Storage
    - salaxander # Release Manager Associate / 1.29 RT EA
    - salehsedghpour # 1.31 Release Lead Shadow
    - sanchita-07 # 1.31 Release Lead Shadow
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - serathius # Instrumentation
    - SergeyKanzhelev # Node
    - shaneutt # Network
    - shu-mutou # UI
    - shyamjvs # Scalability
    - soltysh # CLI
    - spzala # IBM Cloud
    - sreeram-venkitesh # 1.31 Enhancements Lead
    - sttts # API Machinery
    - tallclair # Auth
    - tashimi # Usability
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - upodroid # K8s Infra
    - Verolop # Release Manager
    - Vyom-Yadav # 1.31 Release Signal Lead
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmcqueen # Testing
    - xmudrii # Release Manager
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
    repos:
      enhancements: write
  publishing-bot-admins:
    description: Admin access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
    repos:
      publishing-bot: admin
  publishing-bot-maintainers:
    description: Write access to the publishing-bot repo
    maintainers:
    - nikhita
    - palnabarun
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    - Verolop
    - xmudrii
    privacy: closed
    repos:
      publishing-bot: write
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    members:
    - BenTheElder
    - cpanato
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    privacy: closed
    repos:
      repo-infra: admin
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    members:
    - BenTheElder
    - cpanato
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    - Verolop
    - xmudrii
    privacy: closed
    repos:
      repo-infra: write
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - palnabarun
    - Priyankasaggu11929
    members:
    - BenTheElder
    - castrojo
    - cici37
    - cpanato # Technical Lead
    - dims
    - gracenng
    - ixdy
    - JamesLaverack
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - katcosgrove
    - leonardpahlke
    - liggitt
    - puerco # Technical Lead
    - reylejano
    - salaxander
    - saschagrunert # Chair
    - savitharaghunathan
    - spiffxp
    - tpepper
    privacy: closed
    teams:
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        maintainers:
        - palnabarun # Release Manager
        members:
        - ameukam # Release Manager Associate
        - cici37 # Release Manager
        - cpanato # subproject owner / Release Manager
        - gracenng # Release Manager Associate
        - jeremyrickard # subproject owner / Release Manager
        - jimangel # Release Manager Associate
        - jrsapi # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - marosset # Release Manager Associate
        - puerco # subproject owner / Release Manager
        - ramrodo # Release Manager Associate
        - salaxander # Release Manager Associate
        - saschagrunert # subproject owner / Release Manager
        - Verolop # subproject owner / Release Manager
        - xmudrii # Release Manager
        privacy: closed
        repos:
          release: triage
          sig-release: triage
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            maintainers:
            - palnabarun
            members:
            - cici37
            - cpanato
            - jeremyrickard
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - Verolop
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
            repos:
              kubernetes: admin
              release: write
              sig-release: write
      release-team:
        description: Members of the current Release Team and subproject owners.
        maintainers:
        - palnabarun # subproject owner (1.21 RT Lead)
        - Priyankasaggu11929 # subproject owner (1.29 RT Lead)
        members:
        - cpanato # subproject owner / Technical Lead
        - drewhagen # 1.31 Release Lead Shadow
        - fsmunoz # 1.31 Release Lead Shadow
        - gracenng # subproject owner (1.28 RT Lead)
        - jameslaverack # subproject owner (1.24 RT Lead)
        - jeremyrickard # subproject owner / Technical Lead
        - jimangel # 1.29 RT Branch Manager
        - justaugustus # subproject owner / Chair
        - katcosgrove # 1.30 RT Lead
        - leonardpahlke # subproject owner (1.26 RT Lead)
        - marosset # 1.29 RT Branch Manager Shadow
        - neoaggelos # 1.31 Release Lead
        - npolshakova # 1.31 Release Notes Lead
        - Princesso # 1.31 Docs Lead
        - puerco # subproject owner / Technical Lead
        - reylejano # subproject owner (1.23 RT Lead)
        - salaxander # subproject owner (1.27 RT Lead)
        - salehsedghpour # 1.31 Release Lead Shadow
        - sanchita-07 # 1.31 Release Lead Shadow
        - saschagrunert # subproject owner / Chair
        - savitharaghunathan # subproject owner (1.22 RT Lead)
        - sreeram-venkitesh # 1.31 Enhancements Lead
        - Verolop # Release Manager
        - Vyom-Yadav # 1.31 Release Signal Lead
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-team-release-signal:
            description: Members of the Release Signal team for the current release
              cycle.
            members:
            - AdminTurnedDevOps # 1.31 Release Signal Shadow
            - Atharva-Shinde # 1.31 Release Signal Shadow
            - SubhasmitaSw # 1.31 Release Signal Shadow
            - Vyom-Yadav # 1.31 Release Signal Lead
            - wendy-ha18 # 1.31 Release Signal Shadow
            privacy: closed
          release-team-docs:
            description: Members of the Docs team for the current release cycle.
            members:
            - chanieljdan # 1.31 Docs Shadow
            - hacktivist123 # 1.31 Docs Shadow
            - LaurentGoderre # 1.31 Docs Shadow
            - MaryamTavakkoli # 1.31 Docs Shadow
            - Princesso # 1.31 Docs Lead
            - salaxander # 1.31 Docs Shadow
            privacy: closed
          release-team-comms:
            description: Members of the Comms team for the current release cycle.
            members:
            - a-mccarthy # 1.31 Comms Lead
            - edithturn # 1.31 Comms Shadow
            - hailkomputer # 1.31 Comms Shadow
            - mbianchidev # 1.31 Comms Shadow
            - rashansmith # 1.31 Comms Shadow
            privacy: closed
          release-team-enhancements:
            description: Members of the Enhancments team for the current release
              cycle.
            members:
            - ArkaSaha30 # 1.31 Enhancements Shadow
            - dipesh-rawat # 1.31 Enhancements Shadow
            - mickeyboxell # 1.31 Enhancements Shadow
            - prianna # 1.31 Enhancements Shadow
            - sreeram-venkitesh # 1.31 Enhancements Lead
            - tjons # 1.31 Enhancements Shadow
            privacy: closed
          release-team-release-notes:
            description: Members of the Release Notes team for the current release
              cycle.
            members:
            - checksumz # 1.31 Release Notes Shadow
            - cloudmelon # 1.31 Release Notes Shadow
            - npolshakova # 1.31 Release Notes Lead
            - rayandas # 1.31 Release Notes Shadow
            - satyampsoni # 1.31 Release Notes Shadow
            - shecodesmagic # 1.31 Release Notes Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            maintainers:
            - Priyankasaggu11929 # 1.31 Release EA
            members:
            - drewhagen # 1.31 Release Lead Shadow
            - fsmunoz # 1.31 Release Lead Shadow
            - neoaggelos # 1.31 Release Lead
            - salehsedghpour # 1.31 Release Lead Shadow
            - sanchita-07 # 1.31 Release Lead Shadow
            privacy: closed
            repos:
              kubernetes: write
              release: triage
              sig-release: write
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
        repos:
          release: admin
          sig-release: admin
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Chair
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        - Verolop # Technical Lead
        privacy: closed
        repos:
          release: triage
          sig-release: maintain
