teams:
  kubernetes-milestone-maintainers:
    description: Team members can use `/milestone` or `/status` commands on issues/PRs
    maintainers:
    - calebamiles # Release / PM
    - cblecker # ContribEx
    - fejta # Testing
    - idvoretskyi # PM
    - justaugustus # Azure / PM / Release
    - tpepper # Release
    - spiffxp # 1.14 RT Lead / Testing
    members:
    - abgworrall # GCP
    - andrewsykim # Cloud Provider
    - BenTheElder # 1.14 RT Lead Shadow
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - bsalamat # Scheduling
    - carolynvs # Service Catalog
    - caseydavenport # Network
    - chenopis # Docs
    - childsb # Storage
    - csbell # Multicluster
    - d-nishi # AWS
    - danielromlein # UI
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery
    - derekwaynecarr # Node
    - directxman12 # Autoscaling
    - dims # Release
    - dklyle # OpenStack
    - dstrebel # Azure
    - duglin # Service Catalog
    - enj # Auth
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - hogepodge # Cloud Provider / OpenStack
    - jagosan # Cloud Provider
    - jdumars # Architecture
    - justinsb # AWS
    - k82cn # Scheduling
    - khenidak # Azure
    - kow3ns # Apps
    - kris-nova # AWS
    - lavalamp # API Machinery
    - liggitt # Release
    - liyinan926 # Big Data
    - luxas # Cluster Lifecycle
    - marpaia # 1.14 RT Lead Shadow
    - mattfarina # Apps / Architecture
    - michmike # Windows
    - mikedanese # Auth
    - mwielgus # Autoscaling
    - nikhita # ContribEx
    - parispittman # ContribEx
    - patricklang # Windows
    - phillels # ContribEx
    - piosz # Instrumentation
    - prydonius # Apps
    - pwittrock # CLI
    - quinton-hoole-2 # Multicluster
    - roberthbailey # Cluster Lifecycle
    - saad-ali # Storage
    - seans3 # CLI
    - shyamjvs # Scalability
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - wojtek-t # Scalability
    - zacharysarah # Docs
    privacy: closed
  kubernetes-release-managers:
    description: People actively working on next k8s minor release, or who are patch
      managers for any still-supported minor release. Gives admin access to repos
      where branches must be created, etc., and write access to ones where label/PR
      management is needed. Remove users who are not actively doing this job.
    maintainers:
    - calebamiles
    - justaugustus
    - tpepper # 1.13 PRM
    members:
    - aleksandra-malinowska # 1.13 PRM
    - feiskyer # 1.12 PRM
    - foxish # 1.11 PRM
    - hoegaarden # 1.14 Branch Manager
    - k8s-release-robot
    - maciekpytel # 1.10 PRM
    privacy: closed
  sig-release:
    description: SIG Release Members
    maintainers:
    - calebamiles
    - justaugustus
    - spiffxp
    - tpepper
    members:
    - abgworrall
    - AishSundar
    - aleksandra-malinowska
    - amwat
    - BenTheElder
    - Bradamant3
    - caesarxuchao
    - chenopis
    - cjwagner
    - claurence
    - dashpole
    - dchen1107
    - dims
    - dougm
    - dstrebel
    - enisoc
    - ethernetdan
    - feiskyer
    - foxish
    - guineveresaenger
    - hoegaarden
    - ixdy
    - jberkus
    - jdumars
    - jimangel
    - jpbetz
    - kacole2
    - kbarnard10
    - krzyzacy
    - liggitt
    - MaciekPytel
    - mariantalla
    - marpaia
    - marun
    - mbohlool
    - mistyhacks
    - mohammedzee1000
    - monopole
    - nickchase
    - nikopen
    - nwoods3
    - pwittrock
    - radhikapc
    - saad-ali
    - shyamjvs
    - steveperry-53
    - tfogo
    - wojtek-t
    - zacharysarah
    - zparnold
    privacy: closed
    teams:
      sig-release-admins:
        description: Admins for SIG Release repositories
        maintainers:
        - calebamiles
        - justaugustus
        - tpepper
        privacy: closed
