teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with
      access to publish packages (debs/rpms) on behalf of the Kubernetes
      project. This team is a notification-only group, which includes the SIG
      Release Chairs/TLs for continuity.
    members:
    - BenTheElder
    - cpanato
    - juanfescobar
    - justaugustus
    - MushuEE
    - puerco
    - saschagrunert
    - spiffxp
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on
      issues/PRs and have triage access to the kubernetes/enhancements repo
    maintainers:
    - ameukam # Release Manager Associate
    - cblecker # ContribEx
    - mrbobbytables # ContribEx
    - nikhita # ContribEx
    - palnabarun # Release Manager
    members:
    - abgworrall # GCP
    - adisky # OpenStack
    - ahg-g # Scheduling
    - alejandrox1 # Testing
    - andrewsykim # Cloud Provider
    - aojea # Testing / Network
    - Atharva-Shinde # 1.25 Enhancements Shadow
    - BenTheElder # Testing
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - cantbewong # VMware
    - caseydavenport # Network
    - cheftako # Cloud Provider
    - chrigl # OpenStack
    - cici37 # 1.25 Release Lead
    - claudiubelu # Windows
    - cpanato # Release Manager
    - craiglpeters # Azure
    - csantanapr # 1.25 Release Notes Lead
    - dashpole # Instrumentation
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery / Auth
    - derekwaynecarr # Architecture / Node
    - dims # Architecture / Release
    - eddiezane # CLI
    - ehashman # Instrumentation
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - fejta # Testing
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - gracenng # 1.25 RT Lead Shadow
    - harshitasao # 1.25 Bug Triage Shadow
    - helayoty # 1.25 Bug Triage Lead
    - hkamel # 1.25 Bug Triage Shadow
    - hpandeycodeit # Usability
    - Huang-Wei # Scheduling
    - janetkuo # Apps
    - jasonbraganza # 1.25 Enhancements Shadow
    - jayunit100 # Windows
    - jberkus # Release
    - jdumars # Architecture / PM
    - jeremyrickard # Release
    - jhvhs # Service Catalog
    - jimangel # Docs / Release Manager Associate
    - jlbutler # 1.25 RT Lead Shadow
    - johnbelamaric # Architecture
    - jrsapi # Release Manager Associate
    - jsafrane # Storage
    - jsturtevant # Windows
    - justaugustus # Release
    - justin-chizer # 1.25 Bug Triage Shadow
    - justinsb # AWS / Cluster Lifecycle
    - k8s-release-robot # Release
    - katcosgrove # 1.25 Comms Lead
    - kcmartin # 1.25 Docs Lead
    - khenidak # Azure
    - KnVerey # CLI
    - kow3ns # Apps
    - lavalamp # API Machinery
    - leonardpahlke # 1.25 RT Lead Shadow
    - liggitt # Auth / Release
    - lingxiankong # OpenStack
    - liyinan926 # Big Data
    - logicalhan # Instrumentation
    - luxas # Cluster Lifecycle
    - maciaszczykm # UI
    - markyjackson-taulia # 1.25 Bug Triage Shadow
    - marosset # 1.25 Enhancements Shadow
    - marosset # Windows
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - mikedanese # Auth
    - mkorbi # Release Manager Associate / 1.24 RT Lead Shadow
    - mm4tt # Scalability
    - msau42 # Storage
    - mwielgus # Autoscaling
    - nckturner # AWS
    - neolit123 # Cluster Lifecycle
    - onlydole # Release Manager Associate
    - oxddr # Scalability
    - parispittman # ContribEx
    - parul5sahoo # 1.25 Enhancements Shadow
    - phillels # ContribEx
    - pmorie # Multicluster
    - Priyankasaggu11929 # 1.25 Enhancements Lead
    - prydonius # Apps
    - puerco # Release Manager
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - RainbowMango # Instrumentation
    - rajakavitha1 # Usability
    - reylejano # 1.25 EA
    - rhockenbury # 1.25 Enhancements Shadow
    - RinkiyaKeDad # 1.25 CI Signal Lead
    - saad-ali # Storage
    - salaxander # 1.25 RT Lead Shadow
    - saschagrunert # Release
    - SataQiu # Cluster Lifecycle
    - seans3 # CLI
    - serathius # Instrumentation
    - sethmccombs # Release Manager Associate
    - shu-mutou # UI
    - shyamjvs # Scalability
    - soltysh # CLI
    - spiffxp # Testing
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - tashimi # Usability
    - thejoycekung # Release Manager Associate
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - Verolop # Release Manager
    - vllry # Usability
    - wilsonehusin # Release Manager Associate
    - wojtek-t # Scalability
    - xing-yang # Storage
    - xmudrii # Release Manager
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  publishing-bot-admins:
    description: Admin access to the publishing-bot repo
    maintainers:
    - nikhita
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    privacy: closed
    previously:
    - publishing-bot-reviewers
  publishing-bot-maintainers:
    description: Write access to the publishing-bot repo
    maintainers:
    - nikhita
    - palnabarun
    members:
    - cpanato
    - dims
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    - sttts
    - Verolop
    - xmudrii
    privacy: closed
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - fejta
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    privacy: closed
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    members:
    - BenTheElder
    - clarketm
    - cpanato
    - fejta
    - justaugustus
    - mikedanese
    - puerco
    - saschagrunert
    - Verolop
    - xmudrii
    privacy: closed
  sig-release:
    description: SIG Release members. Explicitly lists SIG Release Chairs,
      Technical Leads, Program Managers, and any active SIG contributors that
      are not already members of a nested team.
    maintainers:
    - mrbobbytables
    - nikhita
    - palnabarun
    members:
    - alenkacz
    - BenTheElder
    - castrojo
    - cpanato # Technical Lead
    - dims
    - ixdy
    - JamesLaverack
    - jberkus
    - jdumars
    - jeefy
    - jeremyrickard # Technical Lead
    - justaugustus # Chair
    - liggitt
    - mariantalla
    - nikopen
    - onyiny-ang
    - puerco # Technical Lead
    - rawkode
    - reylejano
    - saschagrunert # Chair
    - savitharaghunathan
    - soggiest
    - spiffxp
    - tpepper
    privacy: closed
    teams:
      release-engineering:
        description: Members of the Release Engineering subproject, including
          Release Managers, Release Manager Associates, and Build Admins.
        maintainers:
        - ameukam # Release Manager Associate
        - palnabarun # Release Manager
        members:
        - cpanato # subproject owner / Release Manager
        - jeremyrickard # Release Manager Associate
        - jimangel # Release Manager Associate
        - jrsapi # Release Manager Associate
        - justaugustus # subproject owner / Release Manager
        - mkorbi # Release Manager Associate
        - onlydole # Release Manager Associate
        - puerco # subproject owner / Release Manager
        - saschagrunert # subproject owner / Release Manager
        - sethmccombs # Release Manager Associate
        - thejoycekung # Release Manager Associate
        - Verolop # Release Manager
        - wilsonehusin # Release Manager Associate
        - xmudrii # Release Manager
        privacy: closed
        teams:
          release-managers:
            description: People actively pushing Kubernetes releases. Gives
              admin access to repos where branches must be created and write
              access to ones where label/PR management is needed. Remove users
              who are not actively doing this job.
            maintainers:
            - palnabarun
            members:
            - cpanato
            - justaugustus
            - k8s-release-robot
            - puerco
            - saschagrunert
            - Verolop
            - xmudrii
            privacy: closed
            previously:
            - kubernetes-release-managers
      release-team:
        description: Members of the current Release Team and subproject owners.
        maintainers:
        - palnabarun # subproject owner (1.21 RT Lead)
        members:
        - AnaMMedina21 # 1.25 Comms Shadow
        - Atharva-Shinde # 1.25 Enhancements Shadow
        - cathchu # 1.25 Docs Shadow
        - cici37 # 1.25 RT Lead
        - cpanato # subproject owner / Technical Lead
        - csantanapr # 1.25 Release Notes Lead
        - Debanitrkl # 1.25 Comms Shadow
        - didicodes # 1.25 Docs Shadow
        - DiptoChakrabarty # 1.25 Release Notes Shadow
        - Divya063 # 1.25 Release Notes Shadow
        - fsmunoz # 1.25 Comms Shadow
        - Garima-Negi # 1.25 Comms Shadow
        - gnoam # 1.25 CI Signal Shadow
        - gracenng # 1.25 RT Lead Shadow
        - harshitasao # 1.25 Bug Triage Shadow
        - helayoty # 1.25 Bug Triage Lead
        - hkamel # 1.25 Bug Triage Shadow
        - jameslaverack # subproject owner (1.24 RT Lead)
        - jasonbraganza # 1.25 Enhancements Shadow
        - jeremyrickard # subproject owner / Technical Lead
        - jlbutler # 1.25 RT Lead Shadow
        - justaugustus # subproject owner / Chair
        - justin-chizer # 1.25 Bug Triage Shadow
        - jyotimahapatra # 1.25 CI Signal Shadow
        - katcosgrove # 1.25 Comms Lead
        - kcmartin # 1.25 Docs Lead
        - krol3 # 1.25 Docs Shadow
        - leonardpahlke # 1.25 RT Lead Shadow
        - markyjackson-taulia # 1.25 Bug Triage Shadow
        - marosset # 1.25 Enhancements Shadow
        - mehabhalodiya # 1.24 Docs Shadow
        - Nivedita-coder # 1.25 CI Signal Shadow
        - onlydole # subproject owner (1.19 RT Lead)
        - orsenthil # 1.25 Release Notes Shadow
        - parul5sahoo # 1.25 Enhancements Shadow
        - Priyankasaggu11929 # 1.25 Enhancements Lead
        - puerco # subproject owner / Technical Lead
        - ramrodo # 1.25 Release Notes Shadow
        - reylejano # 1.25 EA
        - reylejano # subproject owner (1.23 RT Lead)
        - rhockenbury # 1.25 Enhancements Shadow
        - RinkiyaKeDad # 1.25 CI Signal Lead
        - salaxander # 1.25 RT Lead Shadow
        - saschagrunert # subproject owner / Chair
        - savitharaghunathan # subproject owner (1.22 RT Lead)
        - sethmccombs # 1.25 Docs Shadow
        - shuheiktgw # 1.25 CI Signal Shadow
        - Verolop # Release Manager
        - xmudrii # Release Manager
        privacy: closed
        teams:
          ci-signal:
            description: Members of the CI Signal team for the current release
              cycle.
            members:
            - gnoam # 1.25 CI Signal Shadow
            - jyotimahapatra # 1.25 CI Signal Shadow
            - Nivedita-coder # 1.25 CI Signal Shadow
            - RinkiyaKeDad # 1.25 CI Signal Lead
            - shuheiktgw # 1.25 CI Signal Shadow
            privacy: closed
          release-team-leads:
            description: Release Team Leads for the current Kubernetes release
              cycle. Grants write access to kubernetes/kubernetes,
              kubernetes/release, and kubernetes/sig-release, and can be used
              as a notification group. Remove org members who are not current
              Release Team Leads.
            members:
            - cici37 # 1.25 RT Lead
            - gracenng # 1.25 RT Lead Shadow
            - jlbutler # 1.25 RT Lead Shadow
            - leonardpahlke # 1.25 RT Lead Shadow
            - reylejano # 1.25 EA
            - salaxander # 1.25 RT Lead Shadow
            privacy: closed
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
      sig-release-leads:
        description: |
          Chairs, Technical Leads, and Program Managers for SIG Release
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
      sig-release-pms:
        description: |
          Grants access to maintain SIG Release project boards
        members:
        - cpanato # Technical Lead
        - jeremyrickard # Technical Lead
        - justaugustus # Chair
        - puerco # Technical Lead
        - saschagrunert # Chair
        privacy: closed
