teams:
  kubernetes-milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on issues/PRs.
      This team also grants write access to the kubernetes/enhancements repo to allow
      editing of descriptions for Enhancement tracking issues.
    maintainers:
    - calebamiles # Release / PM
    - cblecker # ContribEx
    - fejta # Testing
    - idvoretskyi # PM
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - alejandrox1 # 1.15 CI Signal
    - andrewsykim # Cloud Provider
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - bsalamat # Scheduling
    - bubblemelon # 1.15 Branch Manager
    - carolynvs # Service Catalog
    - caseydavenport # Network
    - castrojo # 1.15 Communications
    - chenopis # Docs
    - childsb # Storage
    - claurence # 1.15 Lead
    - craiglpeters # 1.15 Enhancements Shadow
    - csbell # Multicluster
    - d-nishi # AWS
    - danielromlein # UI
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery
    - derekwaynecarr # Node
    - dims # Release
    - directxman12 # Autoscaling
    - dklyle # OpenStack
    - dstrebel # Azure / 1.15 Bug Triage Shadow
    - duglin # Service Catalog
    - enj # Auth
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - hogepodge # Cloud Provider / OpenStack
    - imkin # 1.15 Test Infra
    - jagosan # Cloud Provider
    - jdumars # Architecture
    - jimangel # 1.15 CI Signal Shadow
    - justaugustus # Azure / PM / Release
    - justinsb # AWS
    - k82cn # Scheduling
    - k8s-release-robot # Release
    - kacole2 # 1.15 Enhancements
    - khenidak # Azure
    - kow3ns # Apps
    - kris-nova # AWS
    - lachie83 # 1.15 Lead Shadow
    - lavalamp # API Machinery
    - liggitt # Release
    - liyinan926 # Big Data
    - luxas # Cluster Lifecycle
    - MAKOSCAFEE # 1.15 Docs
    - mattfarina # Apps / Architecture
    - michmike # Windows
    - mikedanese # Auth
    - mrbobbytables # 1.15 Enhancements Shadow
    - mwielgus # Autoscaling
    - neolit123 # Cluster Lifecycle
    - nikopen # 1.15 Lead Shadow
    - onyiny-ang # 1.15 Release Notes
    - parispittman # ContribEx
    - patricklang # Windows
    - phillels # ContribEx
    - piosz # Instrumentation
    - prydonius # Apps
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - saad-ali # Storage
    - seans3 # CLI
    - shyamjvs # Scalability
    - smourapina # 1.15 CI Signal Shadow
    - soggiest # 1.15 Bug Triage
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - tpepper # 1.15 Lead Shadow / Release
    - wojtek-t # Scalability
    - xmudrii # 1.15 Bug Triage Shadow
    - zacharysarah # Docs
    privacy: closed
  kubernetes-release-managers:
    description: People actively working on next k8s minor release.  Gives admin access to repos
      where branches must be created, etc., and write access to ones where label/PR
      management is needed. Remove users who are not actively doing this job.
    members:
    - claurence # 1.15 RT Lead
    - k8s-release-robot
    - lachie83 # 1.15 RT Lead Shadow
    - nikopen # 1.15 RT Lead Shadow
    - tpepper # 1.15 RT Lead Shadow
    privacy: closed
    teams:
      patch-release-team:
        description: People managing patch releases of prior k8s minor release branches.
        maintainers:
        - justaugustus
        members:
        - aleksandra-malinowska
        - feiskyer
        - foxish
        - hoegaarden
        - tpepper
        privacy: closed
  sig-release:
    description: SIG Release Members
    maintainers:
    - calebamiles
    - spiffxp
    members:
    - abgworrall
    - AishSundar
    - aleksandra-malinowska
    - amwat
    - BenTheElder
    - Bradamant3
    - caesarxuchao
    - chenopis
    - cjwagner
    - claurence
    - craiglpeters
    - dashpole
    - dchen1107
    - dims
    - dougm
    - dstrebel
    - enisoc
    - ethernetdan
    - feiskyer
    - foxish
    - guineveresaenger
    - hoegaarden
    - idealhack
    - ixdy
    - jberkus
    - jdumars
    - jimangel
    - jpbetz
    - justaugustus
    - kacole2
    - kbarnard10
    - krzyzacy
    - liggitt
    - MaciekPytel
    - mariantalla
    - marpaia
    - marun
    - mbohlool
    - mistyhacks
    - mohammedzee1000
    - monopole
    - mrbobbytables
    - nickchase
    - nikopen
    - nwoods3
    - pwittrock
    - radhikapc
    - saad-ali
    - shyamjvs
    - steveperry-53
    - tfogo
    - tpepper
    - wojtek-t
    - zacharysarah
    - zparnold
    privacy: closed
    teams:
      sig-release-admins:
        description: Admins for SIG Release repositories
        maintainers:
        - calebamiles
        members:
        - justaugustus
        - tpepper
        privacy: closed
  publishing-bot-reviewers:
    description: Reviews for publishing-bot
    maintainers:
    - nikhita
    members:
    - caesarxuchao
    - dims
    - mfojtik
    - sttts
    privacy: closed
