teams:
  build-admins:
    description: Kubernetes Build Admins are the current set of Googlers with access to
      publish packages (debs/rpms) on behalf of the Kubernetes project. This team is a
      notification-only group, which includes the SIG Release Chairs for continuity.
    members:
    - aleksandra-malinowska
    - calebamiles
    - justaugustus
    - listx
    - sumitranr
    - tpepper
    privacy: closed
  licensing:
    description: Members of the Licensing subproject.
    maintainers:
    - nikhita # subproject owner
    members:
    - dims # subproject owner
    - justaugustus # subproject owner
    - swinslow # subproject owner
    privacy: closed
  milestone-maintainers:
    description: Contributors who can use `/milestone` or `/status` commands on issues/PRs.
      This team also grants write access to the kubernetes/enhancements repo to allow
      editing of descriptions for Enhancement tracking issues.
    maintainers:
    - cblecker # ContribEx
    - fejta # Testing
    - idvoretskyi # PM
    - mrbobbytables # 1.15 Enhancements Shadow
    - nikhita # ContribEx
    - spiffxp # Testing
    members:
    - abgworrall # GCP
    - alejandrox1 # 1.15 CI Signal
    - andrewsykim # Cloud Provider
    - bgrant0607 # Architecture
    - bradamant3 # Docs
    - brancz # Instrumentation
    - bsalamat # Scheduling
    - bubblemelon # 1.15 Branch Manager
    - calebamiles # Release / PM
    - carolynvs # Service Catalog
    - caseydavenport # Network
    - castrojo # 1.15 Communications
    - chenopis # Docs
    - childsb # Storage
    - claurence # 1.15 Lead
    - craiglpeters # 1.15 Enhancements Shadow
    - csbell # Multicluster
    - d-nishi # AWS
    - danielromlein # UI
    - dcbw # Network
    - dchen1107 # Node
    - deads2k # API Machinery
    - derekwaynecarr # Node
    - dims # Release
    - directxman12 # Autoscaling
    - dklyle # OpenStack
    - dstrebel # Azure / 1.15 Bug Triage Shadow
    - duglin # Service Catalog
    - enj # Auth
    - evillgenius75 # 1.16 Enhancements Shadow
    - fabriziopandini # Cluster Lifecycle
    - feiskyer # Azure
    - floreks # UI
    - foxish # Big Data
    - frapposelli # VMware
    - hogepodge # Cloud Provider / OpenStack
    - imkin # 1.15 Test Infra
    - jagosan # Cloud Provider
    - jberkus # Release
    - jdumars # Architecture
    - jimangel # 1.15 CI Signal Shadow
    - justaugustus # Azure / PM / Release
    - justinsb # AWS
    - k82cn # Scheduling
    - k8s-release-robot # Release
    - kacole2 # 1.16 Enhancement Lead
    - khenidak # Azure
    - kow3ns # Apps
    - kris-nova # AWS
    - lachie83 # 1.15 Lead Shadow
    - lavalamp # API Machinery
    - liggitt # Release
    - liyinan926 # Big Data
    - luxas # Cluster Lifecycle
    - MAKOSCAFEE # 1.15 Docs
    - mariantalla # 1.16 Enhancement Shadow
    - mattfarina # Apps / Architecture
    - mborsz # Scalability
    - michmike # Windows
    - mikedanese # Auth
    - mm4tt # Scalability
    - mwielgus # Autoscaling
    - neolit123 # Cluster Lifecycle
    - nikopen # 1.15 Lead Shadow
    - onyiny-ang # 1.15 Release Notes
    - parispittman # ContribEx
    - patricklang # Windows
    - phillels # ContribEx
    - piosz # Instrumentation
    - prydonius # Apps
    - pwittrock # CLI
    - quinton-hoole # Multicluster
    - rbitia # 1.16 Enhancements Shadow
    - saad-ali # Storage
    - seans3 # CLI
    - shyamjvs # Scalability
    - simplytunde # 1.16 Docs Lead
    - smourapina # 1.15 CI Signal Shadow
    - soggiest # 1.15 Bug Triage
    - soltysh # CLI
    - spzala # IBM Cloud
    - stevekuznetsov # Testing
    - tallclair # Auth
    - thockin # Network
    - timothysc # Cluster Lifecycle / Testing
    - tpepper # 1.15 Lead Shadow / Release
    - wojtek-t # Scalability
    - xmudrii # 1.15 Bug Triage Shadow
    - zacharysarah # Docs
    privacy: closed
    previously:
    - kubernetes-milestone-maintainers
  patch-release-team:
    description: People managing patch releases of prior k8s minor release
      branches. This team is used for notifications for all active patch
      managers, but does not give permissions.
    members:
    - aleksandra-malinowska
    - feiskyer
    - hoegaarden
    - tpepper
    privacy: closed
  publishing-bot-reviewers:
    description: Reviews for publishing-bot
    maintainers:
    - nikhita
    members:
    - caesarxuchao
    - dims
    - mfojtik
    - sttts
    privacy: closed
  release-engineering:
    description: Members of the Release Engineering subproject, including Build Admins,
      Patch Release Team, Branch Managers, and Release Manager Associates.
    maintainers:
    - nikhita # Release Manager Associate
    members:
    - aleksandra-malinowska # subproject owner / Build Admin / Patch Release Team
    - alexeldeib # Release Manager Associate
    - bubblemelon # Branch Manager
    - calebamiles # subproject owner / Build Admin
    - chrisz100 # Release Manager Associate
    - cpanato # Release Manager Associate
    - feiskyer # Patch Release Team
    - girikuncoro # Release Manager Associate
    - hoegaarden # subproject owner / Patch Release Team
    - idealhack # Branch Manager
    - imkin # Release Manager Associate
    - ixdy # subproject owner
    - javier-b-perez # Release Manager Associate
    - justaugustus # Release Manager Associate / Build Admin
    - k82cn # Release Manager Associate
    - listx # Build Admin
    - mcrute # Release Manager Associate
    - pswica # Release Manager Associate
    - slicknik # Release Manager Associate
    - sumitranr # Build Admin
    - tpepper # subproject owner / Build Admin / Patch Release Team
    privacy: closed
  release-managers:
    description: People actively pushing k8s releases. Gives admin access to
      repos where branches must be created, etc., and write access to ones where
      label/PR management is needed. Remove users who are not actively doing
      this job.
    maintainers:
    - nikhita # Branch Manager
    members:
    - aleksandra-malinowska # Patch Release Team
    - bubblemelon # Branch Manager
    - feiskyer # Patch Release Team
    - hoegaarden # Patch Release Team
    - idealhack # Branch Manager
    - justaugustus # Branch Manager
    - k8s-release-robot
    - tpepper # Patch Release Team
    privacy: closed
    previously:
    - kubernetes-release-managers
  release-team:
    description: Members of the current Release Team and subproject owners.
    maintainers:
    - mrbobbytables # 1.16 Enhancements Shadow
    - spiffxp # subproject owner
    members:
    - aishsundar # subproject owner
    - alejandrox1 # 1.16 CI Signal Lead
    - alenkacz # 1.15 CI Signal Shadow
    - bubblemelon # Branch Manager
    - castrojo # 1.15 Communications Lead
    - claurence # subproject owner
    - craiglpeters # 1.15 Enhancements Shadow
    - daminisatya # 1.15 Docs Shadow
    - dstrebel # 1.15 Bug Triage Shadow
    - evillgenius75 # 1.16 Enhancements Shadow
    - guineveresaenger # 1.16 RT Lead Shadow
    - idealhack # Branch Manager
    - imkin # 1.15 Test Infra Lead
    - jberkus # subproject owner
    - jeefy # 1.16 RT Lead Shadow
    - jimangel # 1.15 CI Signal Shadow
    - justaugustus # subproject owner
    - kacole2 # 1.16 Enhancements Lead
    - Katharine # 1.15 Test Infra Shadow
    - lachie83 # 1.15 RT Lead Shadow
    - MAKOSCAFEE # 1.15 Docs Lead
    - mariantalla # 1.16 Enhancements Shadow
    - nickchase # 1.15 Release Notes Shadow
    - nikopen # 1.16 RT Lead Shadow
    - onlydole # 1.16 Communications Lead
    - onyiny-ang # 1.15 Release Notes Lead
    - rbitia # 1.16 Enhancements Shadow
    - saschagrunert # 1.16 Release Notes Lead
    - simplytunde # 1.16 Docs Lead
    - slicknik # 1.15 Branch Manager Shadow
    - smourapina # 1.15 CI Signal Shadow
    - soggiest # 1.15 Bug Triage Lead
    - taragu # 1.15 Test Infra Shadow
    - tpepper # subproject owner
    - xmudrii # 1.16 Bug Triage Lead
    privacy: closed
    teams:
      release-team-leads:
        description: Release Team Leads for the current Kubernetes release cycle.
           Grants write access to kubernetes/kubernetes, kubernetes/release, and kubernetes/sig-release,
           and can be used as a notification group.
          Remove org members who are not current Release Team Leads.
        members:
        - guineveresaenger # 1.16 RT Lead Shadow
        - jeefy # 1.16 RT Lead Shadow
        - lachie83 # 1.16 RT Lead
        - nikopen # 1.16 RT Lead Shadow
        privacy: closed
  sig-release:
    description: SIG Release Members
    maintainers:
    - mrbobbytables
    - spiffxp
    members:
    - abgworrall
    - AishSundar
    - alejandrox1
    - aleksandra-malinowska
    - amwat
    - BenTheElder
    - Bradamant3
    - bubblemelon
    - caesarxuchao
    - calebamiles
    - castrojo
    - chenopis
    - cjwagner
    - claurence
    - craiglpeters
    - dashpole
    - dchen1107
    - dims
    - dougm
    - dstrebel
    - enisoc
    - ethernetdan
    - evillgenius75
    - feiskyer
    - foxish
    - guineveresaenger
    - hoegaarden
    - idealhack
    - imkin
    - ixdy
    - jberkus
    - jdumars
    - jeefy
    - jimangel
    - jpbetz
    - justaugustus
    - kacole2
    - Katharine
    - kbarnard10
    - krzyzacy
    - lachie83
    - liggitt
    - MaciekPytel
    - MAKOSCAFEE
    - mariantalla
    - marpaia
    - marun
    - mbohlool
    - mistyhacks
    - mohammedzee1000
    - monopole
    - nickchase
    - nikopen
    - nwoods3
    - onlydole
    - onyiny-ang
    - pwittrock
    - radhikapc
    - rbitia
    - saad-ali
    - saschagrunert
    - shyamjvs
    - simplytunde
    - soggiest
    - steveperry-53
    - tfogo
    - tpepper
    - wojtek-t
    - xmudrii
    - zacharysarah
    - zparnold
    privacy: closed
    teams:
      sig-release-admins:
        description: Admins for SIG Release repositories
        members:
        - calebamiles
        - justaugustus
        - tpepper
        privacy: closed
