teams:
  cluster-api-provider-ibmcloud-admins:
    description: Admin access to cluster-api-provider-ibmcloud repo
    members:
    - gyliu513
    privacy: closed
  cluster-api-provider-ibmcloud-maintainers:
    description: Write access to the cluster-api-provider-ibmcloud repo
    members:
    - gyliu513
    privacy: closed
