name: Kubernetes CSI
description: Kubernetes specific Container-Storage-Interface (CSI) components
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- 27149chen
- ameukam
- andrewsykim
- andyzhangx
- arahamad
- bertinatto
- boddumanohar
- bswartz
- calebamiles
- chakri-nelluri
- chrishenzie
- codenrhoden
- cofyc
- cwdsuzhou
- davidz627
- ddebroy
- dobsonj
- dvonthenen
- fengzixu
- ggriffiths
- gnufied
- grodrigues3
- hoyho
- huffmanca
- humblec
- idealhack
- irvifa
- j-griffith
- Jiawei0227
- jingxu97
- jsafrane
- justaugustus
- Kartik494
- kfox1111
- kkmsft
- ksubrmnn
- leakingtapan
- lizhuqi
- lpabon
- mattcary
- mauriciopoppe
- mayankshah1607
- misterikkit
- mlmhl
- msau42
- mucahitkurt
- nearora-msft
- NickrenREN
- nzoueidi
- palnabarun
- PatrickLang
- pohly
- prateekpandey14
- Priyankasaggu11929
- RaunakShah
- rlenferink
- rootfs
- saad-ali
- saikat-royc
- savitharaghunathan
- sbezverk
- verult
- vladimirvivien
- wk8
- wozniakjan
- xing-yang
- yuga711
- yuxiangqian
- ZeroMagic
- zhucan
teams:
  cluster-driver-registrar-admins:
    description: Admin access to cluster-driver-registrar repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  cluster-driver-registrar-maintainers:
    description: Write access to cluster-driver-registrar repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-host-path-admins:
    description: Admin access to csi-driver-host-path repo
    members:
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-host-path-maintainers:
    description: Write access to csi-driver-host-path repo
    members:
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - verult
    - xing-yang
    privacy: closed
  csi-driver-image-populator-admins:
    description: Admin access to csi-driver-image-populator repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-image-populator-maintainers:
    description: Write access to csi-driver-image-populator repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-iscsi-admins:
    description: Admin access to csi-driver-iscsi repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-iscsi-maintainers:
    description: Write access to csi-driver-iscsi repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-nfs-admins:
    description: Admin access to csi-driver-nfs repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-nfs-maintainers:
    description: Write access to csi-driver-nfs repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-smb-admins:
    description: Admin access to csi-driver-smb repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-driver-smb-maintainers:
    description: Write access to csi-driver-smb repo
    members:
    - andyzhangx
    - jingxu97
    - msau42
    privacy: closed
  csi-lib-fc-admins:
    description: Admin access to csi-lib-fc repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-lib-fc-maintainers:
    description: Write access to csi-lib-fc repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-lib-iscsi-admins:
    description: Admin access to csi-lib-iscsi repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-lib-iscsi-maintainers:
    description: Write access to csi-lib-iscsi repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-lib-utils-admins:
    description: Admin access to csi-lib-utils repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-lib-utils-maintainers:
    description: Write access to csi-lib-utils repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-misc:
    description: Miscellaneous Discussions for Kubernetes CSI Working Group
    members:
    - chakri-nelluri
    - davidz627
    - gnufied
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    - xing-yang
    privacy: closed
  csi-proxy-admins:
    description: Admin access to csi-proxy repo
    members:
    - andyzhangx
    - ddebroy
    - jsafrane
    - msau42
    - PatrickLang
    - saad-ali
    - xing-yang
    privacy: closed
  csi-proxy-maintainers:
    description: Write access to csi-proxy repo
    members:
    - andyzhangx
    - ddebroy
    - jsafrane
    - msau42
    - PatrickLang
    - saad-ali
    - xing-yang
    privacy: closed
  csi-release-tools-admins:
    description: Admin access to csi-release-tools repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-release-tools-maintainers:
    description: Write access to csi-release-tools repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  csi-test-admins:
    description: Admin access to csi-test repo
    members:
    - davidz627
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
  csi-test-maintainers:
    description: Write access to csi-test repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - sbezverk
    - xing-yang
    privacy: closed
  developers:
    description: ""
    members:
    - chakri-nelluri
    - davidz627
    - jsafrane
    - lpabon
    - msau42
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    - xing-yang
    privacy: closed
  docs-admins:
    description: Admin access to docs repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  docs-maintainers:
    description: Write access to docs repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  driver-registrar-admins:
    description: Admin access to driver-registrar repo
    members:
    - davidz627
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  driver-registrar-maintainers:
    description: Write access to driver-registrar repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-attacher-admins:
    description: Admin access to external-attacher repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-attacher-maintainers:
    description: Write access to external-attacher repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-health-monitor-admins:
    description: Admin access to external-health-monitor repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-health-monitor-maintainers:
    description: Write access to external-health-monitor repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - NickrenREN
    - saad-ali
    - xing-yang
    privacy: closed
  external-provisioner-admins:
    description: Admin access to external-provisioner repo
    members:
    - davidz627
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-provisioner-maintainers:
    description: Write access to external-provisioner repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-resizer-admins:
    description: Admin access to external-resizer repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-resizer-maintainers:
    description: Write access to external-resizer repo
    members:
    - chrishenzie
    - gnufied
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-snapshotter-admins:
    description: Admin access to external-snapshotter repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  external-snapshotter-maintainers:
    description: Write access to external-snapshotter repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  kubernetes-csi-github-io-admins:
    description: Admin access to kubernetes-csi.github.io repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  lib-volume-populator-admins:
    description: Admin access to lib-volume-populator repo
    members:
    - bswartz
    - saad-ali
    - xing-yang
    privacy: closed
  livenessprobe-admins:
    description: Admin access to livenessprobe repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  livenessprobe-maintainers:
    description: Write access to livenessprobe repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - msau42
    - saad-ali
    - sbezverk
    - verult
    - xing-yang
    privacy: closed
  node-driver-registrar-admins:
    description: Admin access to node-driver-registrar repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  node-driver-registrar-maintainers:
    description: Write access to node-driver-registrar repo
    members:
    - chrishenzie
    - Jiawei0227
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
  volume-data-source-validator-admins:
    description: Admin access to kubernetes-csi.github.io repo
    members:
    - bswartz
    - saad-ali
    - xing-yang
    privacy: closed
