name: Kubernetes CSI
description: Kubernetes specific Container-Storage-Interface (CSI) components
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- nikhita
- spiffxp
- thelinuxfoundation
members:
- andrewsykim
- bswartz
- chakri-nelluri
- childsb
- codenrhoden
- davidz627
- ddebroy
- gnufied
- grodrigues3
- j-griffith
- jsafrane
- justaugustus
- kfox1111
- leakingtapan
- lpabon
- mlmhl
- mrbobbytables
- msau42
- pohly
- rlenferink
- rootfs
- saad-ali
- sbezverk
- vladimirvivien
- xing-yang
teams:
  cluster-driver-registrar-admins:
    description: admin access to cluster-driver-registrar
    members:
    - lpabon
    - saad-ali
    privacy: closed
  cluster-driver-registrar-maintainers:
    description: write access to cluster-driver-registrar
    members:
    - lpabon
    - saad-ali
    privacy: closed
  csi-driver-fibre-channel-admins:
    description: admin access to csi-driver-fibre-channel
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-fibre-channel-maintainers:
    description: write access to csi-driver-fibre-channel
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-flex-admins:
    description: admin access to csi-driver-flex
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-flex-maintainers:
    description: write access to csi-driver-flex
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-host-path-admins:
    description: admin access to csi-driver-host-path
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-host-path-maintainers:
    description: write access to csi-driver-host-path
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-image-populator-admins:
    description: admin access to csi-driver-image-populator
    members:
      - msau42
      - saad-ali
    privacy: closed
  csi-driver-image-populator-maintainers:
    description: write access to csi-driver-image-populator
    members:
      - msau42
      - saad-ali
    privacy: closed
  csi-driver-iscsi-admins:
    description: admin access to csi-driver-iscsi
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-iscsi-maintainers:
    description: write access to csi-driver-iscsi
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-nfs-admins:
    description: admin access to csi-driver-nfs
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-nfs-maintainers:
    description: write access to csi-driver-nfs
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-fc-admins:
    description: admin access to csi-lib-fc
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-fc-maintainers:
    description: write access to csi-lib-fc
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-iscsi-admins:
    description: admin access to csi-lib-iscsi
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-iscsi-maintainers:
    description: write access to csi-lib-iscsi
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-utils-admins:
    description: admin access to csi-lib-utils
    members:
    - saad-ali
    privacy: closed
  csi-lib-utils-maintainers:
    description: write access to csi-lib-utils
    members:
    - saad-ali
    privacy: closed
  csi-misc:
    description: Miscellaneous Discussions for Kubernetes CSI Working Group
    members:
    - chakri-nelluri
    - childsb
    - davidz627
    - gnufied
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    - xing-yang
    privacy: closed
  csi-release-tools-admins:
    description: admin access to csi-release-tools
    members:
    - msau42
    - saad-ali
    privacy: closed
  csi-release-tools-maintainers:
    description: write access to csi-release-tools
    members:
    - msau42
    - saad-ali
    privacy: closed
  csi-test-admins:
    description: admin access to csi-test
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  csi-test-maintainers:
    description: write access to csi-test
    members:
    - childsb
    - saad-ali
    - sbezverk
    privacy: closed
  developers:
    description: ""
    members:
    - chakri-nelluri
    - childsb
    - davidz627
    - jsafrane
    - lpabon
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    privacy: closed
  docs-admins:
    description: admin access to docs
    members:
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  docs-maintainers:
    description: write access to docs
    members:
    - childsb
    - saad-ali
    privacy: closed
  driver-registrar-admins:
    description: admin access to driver-registrar
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  driver-registrar-maintainers:
    description: write access to driver-registrar
    members:
    - childsb
    - saad-ali
    privacy: closed
  drivers-admins:
    description: admin access to drivers
    members:
    - chakri-nelluri
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  drivers-maintainers:
    description: write access to drivers
    members:
    - childsb
    - saad-ali
    - sbezverk
    privacy: closed
  external-attacher-admins:
    description: admin access to external-attacher
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-attacher-maintainers:
    description: write access to external-attacher
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-provisioner-admins:
    description: admin access to external-provisioner
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  external-provisioner-maintainers:
    description: write access to external-provisioner
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-resizer-admins:
    description: admin access to external-resizer
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-resizer-maintainers:
    description: write access to external-resizer
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-snapshotter-admins:
    description: admin access to external-snapshotter
    members:
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  external-snapshotter-maintainers:
    description: write access to external-snapshotter
    members:
    - childsb
    - saad-ali
    privacy: closed
  kubernetes-csi-github-io-admins:
    description: admin access to kubernetes-csi.github.io
    members:
    - lpabon
    - saad-ali
    privacy: closed
  livenessprobe-admins:
    description: admin access to livenessprobe
    members:
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  livenessprobe-maintainers:
    description: write access to livenessprobe
    members:
    - childsb
    - saad-ali
    - sbezverk
    privacy: closed
  node-driver-registrar-admins:
    description: admnin access to node-driver-registrar
    members:
    - lpabon
    - saad-ali
    privacy: closed
  node-driver-registrar-maintainers:
    description: write access to node-driver-registrar
    members:
    - lpabon
    - saad-ali
    privacy: closed
