name: Kubernetes CSI
description: Kubernetes specific Container-Storage-Interface (CSI) components
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- grodrigues3
- idvoretskyi
- k8s-ci-robot
- spiffxp
- thelinuxfoundation
members:
- chakri-nelluri
- childsb
- davidz627
- jsafrane
- lpabon
- rootfs
- saad-ali
- sbezverk
- vladimirvivien
