name: Kubernetes CSI
description: Kubernetes specific Container-Storage-Interface (CSI) components
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- andrewsykim
- bertinatto
- bswartz
- calebamiles
- chakri-nelluri
- childsb
- codenrhoden
- cofyc
- cwdsuzhou
- davidz627
- ddebroy
- dvonthenen
- ggriffiths
- gnufied
- grodrigues3
- hoyho
- idealhack
- irvifa
- j-griffith
- jingxu97
- jsafrane
- justaugustus
- kfox1111
- leakingtapan
- lpabon
- misterikkit
- mlmhl
- msau42
- mucahitkurt
- nzoueidi
- PatrickLang
- pohly
- rlenferink
- rootfs
- saad-ali
- sbezverk
- verult
- vladimirvivien
- wk8
- xing-yang
- yuxiangqian
- zhucan
teams:
  cluster-driver-registrar-admins:
    description: Admin access to cluster-driver-registrar repo
    members:
    - lpabon
    - saad-ali
    privacy: closed
  cluster-driver-registrar-maintainers:
    description: Write access to cluster-driver-registrar repo
    members:
    - lpabon
    - saad-ali
    privacy: closed
  csi-driver-fibre-channel-admins:
    description: Admin access to csi-driver-fibre-channel repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-fibre-channel-maintainers:
    description: Write access to csi-driver-fibre-channel repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-flex-admins:
    description: Admin access to csi-driver-flex repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-flex-maintainers:
    description: Write access to csi-driver-flex repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-host-path-admins:
    description: Admin access to csi-driver-host-path repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-host-path-maintainers:
    description: Write access to csi-driver-host-path repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-image-populator-admins:
    description: Admin access to csi-driver-image-populator repo
    members:
      - msau42
      - saad-ali
    privacy: closed
  csi-driver-image-populator-maintainers:
    description: Write access to csi-driver-image-populator repo
    members:
      - msau42
      - saad-ali
    privacy: closed
  csi-driver-iscsi-admins:
    description: Admin access to csi-driver-iscsi repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-iscsi-maintainers:
    description: Write access to csi-driver-iscsi repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-nfs-admins:
    description: Admin access to csi-driver-nfs repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-driver-nfs-maintainers:
    description: Write access to csi-driver-nfs repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-fc-admins:
    description: Admin access to csi-lib-fc repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-fc-maintainers:
    description: Write access to csi-lib-fc repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-iscsi-admins:
    description: Admin access to csi-lib-iscsi repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-iscsi-maintainers:
    description: Write access to csi-lib-iscsi repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  csi-lib-utils-admins:
    description: Admin access to csi-lib-utils repo
    members:
    - saad-ali
    privacy: closed
  csi-lib-utils-maintainers:
    description: Write access to csi-lib-utils repo
    members:
    - saad-ali
    privacy: closed
  csi-misc:
    description: Miscellaneous Discussions for Kubernetes CSI Working Group
    members:
    - chakri-nelluri
    - childsb
    - davidz627
    - gnufied
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    - xing-yang
    privacy: closed
  csi-proxy-admins:
    description: Admin access to csi-proxy repo
    members:
    - ddebroy
    - msau42
    - PatrickLang
    privacy: closed
  csi-proxy-maintainers:
    description: Write access to csi-proxy repo
    members:
    - ddebroy
    - msau42
    - PatrickLang
    privacy: closed
  csi-release-tools-admins:
    description: Admin access to csi-release-tools repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  csi-release-tools-maintainers:
    description: Write access to csi-release-tools repo
    members:
    - msau42
    - saad-ali
    privacy: closed
  csi-test-admins:
    description: Admin access to csi-test repo
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  csi-test-maintainers:
    description: Write access to csi-test repo
    members:
    - childsb
    - pohly
    - saad-ali
    - sbezverk
    privacy: closed
  developers:
    description: ""
    members:
    - chakri-nelluri
    - childsb
    - davidz627
    - jsafrane
    - lpabon
    - rootfs
    - saad-ali
    - sbezverk
    - vladimirvivien
    privacy: closed
  docs-admins:
    description: Admin access to docs repo
    members:
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  docs-maintainers:
    description: Write access to docs repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  driver-registrar-admins:
    description: Admin access to driver-registrar repo
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  driver-registrar-maintainers:
    description: Write access to driver-registrar repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  drivers-admins:
    description: Admin access to drivers repo
    members:
    - chakri-nelluri
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  drivers-maintainers:
    description: Write access to drivers repo
    members:
    - childsb
    - saad-ali
    - sbezverk
    privacy: closed
  external-attacher-admins:
    description: Admin access to external-attacher repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-attacher-maintainers:
    description: Write access to external-attacher repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-provisioner-admins:
    description: Admin access to external-provisioner repo
    members:
    - childsb
    - davidz627
    - lpabon
    - saad-ali
    privacy: closed
  external-provisioner-maintainers:
    description: Write access to external-provisioner repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-resizer-admins:
    description: Admin access to external-resizer repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-resizer-maintainers:
    description: Write access to external-resizer repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  external-snapshotter-admins:
    description: Admin access to external-snapshotter repo
    members:
    - childsb
    - lpabon
    - saad-ali
    - xing-yang
    privacy: closed
  external-snapshotter-maintainers:
    description: Write access to external-snapshotter repo
    members:
    - childsb
    - saad-ali
    privacy: closed
  kubernetes-csi-github-io-admins:
    description: Admin access to kubernetes-csi.github.io repo
    members:
    - lpabon
    - saad-ali
    privacy: closed
  livenessprobe-admins:
    description: Admin access to livenessprobe repo
    members:
    - childsb
    - lpabon
    - saad-ali
    privacy: closed
  livenessprobe-maintainers:
    description: Write access to livenessprobe repo
    members:
    - childsb
    - saad-ali
    - sbezverk
    privacy: closed
  node-driver-registrar-admins:
    description: Admin access to node-driver-registrar repo
    members:
    - lpabon
    - saad-ali
    privacy: closed
  node-driver-registrar-maintainers:
    description: Write access to node-driver-registrar repo
    members:
    - lpabon
    - saad-ali
    privacy: closed
