admins:
- cblecker
- jasonbraganza
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: Kubernetes specific Container-Storage-Interface (CSI) components
has_organization_projects: true
has_repository_projects: true
members:
- adriananeci
- ameukam
- AndrewSirenko
- andrewsykim
- andyzhangx
- arahamad
- aramase
- astraw99
- bells17
- bertinatto
- bswartz
- carlbraganza
- carlory
- chrishenzie
- cofyc
- ConnorJC3
- coulof
- cvvz
- cwdsuzhou
- dannawang0221
- darshansreenivas
- deepakkinni
- dobsonj
- dulek
- ElijahQuinones
- EmilienM
- gnufied
- hairyhum
- hime
- humblec
- huntergregory
- huww98
- idvoretskyi
- irvifa
- jingxu97
- jsafrane
- justaugustus
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- kfox1111
- laozc
- leiyiz
- leonardoce
- lpabon
- Madhu-1
- MartinForReal
- mattcary
- mauriciopoppe
- mdzraf
- MeinhardZhou
- misterikkit
- mjudeikis
- mowangdk
- mpatlasov
- msau42
- nearora-msft
- nixpanic
- nnmin-aws
- Phaow
- pierreprinetti
- pohly
- Pradumnasaraf
- PrasadG193
- pwschuurman
- Rakshith-R
- RaunakShah
- rlenferink
- RomanBednar
- saad-ali
- saikat-royc
- savitharaghunathan
- smileusd
- Sneha-at
- sunnylovestiramisu
- torredil
- ttakahashi21
- tyuchn
- vladimirvivien
- wackxu
- xing-yang
- ydFu
- zhucan
members_can_create_repositories: false
name: Kubernetes CSI
teams:
  csi-driver-host-path-admins:
    description: Admin access to csi-driver-host-path repo
    members:
    - jingxu97
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-driver-host-path: admin
  csi-driver-host-path-maintainers:
    description: Write access to csi-driver-host-path repo
    members:
    - jingxu97
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-driver-host-path: write
  csi-driver-iscsi-admins:
    description: Admin access to csi-driver-iscsi repo
    members:
    - andyzhangx
    - humblec
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-driver-iscsi: admin
  csi-driver-iscsi-maintainers:
    description: Write access to csi-driver-iscsi repo
    members:
    - andyzhangx
    - humblec
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-driver-iscsi: write
  csi-driver-nfs-admins:
    description: Admin access to csi-driver-nfs repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-driver-nfs: admin
  csi-driver-nfs-maintainers:
    description: Write access to csi-driver-nfs repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-driver-nfs: write
  csi-driver-nvmf-admins:
    description: Admin access to csi-driver-nvmf repo
    members:
    - jsafrane
    - MeinhardZhou
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-driver-nvmf: admin
  csi-driver-nvmf-maintainers:
    description: Write access to csi-driver-nvmf repo
    members:
    - jsafrane
    - MeinhardZhou
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-driver-nvmf: write
  csi-driver-smb-admins:
    description: Admin access to csi-driver-smb repo
    members:
    - andyzhangx
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-driver-smb: admin
  csi-driver-smb-maintainers:
    description: Write access to csi-driver-smb repo
    members:
    - andyzhangx
    - jingxu97
    - msau42
    - sunnylovestiramisu
    privacy: closed
    repos:
      csi-driver-smb: write
  csi-lib-iscsi-admins:
    description: Admin access to csi-lib-iscsi repo
    members:
    - andyzhangx
    - humblec
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-lib-iscsi: admin
  csi-lib-iscsi-maintainers:
    description: Write access to csi-lib-iscsi repo
    members:
    - andyzhangx
    - humblec
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-lib-iscsi: write
  csi-lib-utils-admins:
    description: Admin access to csi-lib-utils repo
    members:
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-lib-utils: admin
  csi-lib-utils-maintainers:
    description: Write access to csi-lib-utils repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-lib-utils: write
  csi-misc:
    description: Miscellaneous Discussions for Kubernetes CSI Working Group
    members:
    - gnufied
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - saad-ali
    - vladimirvivien
    - xing-yang
    privacy: closed
  csi-proxy-admins:
    description: Admin access to csi-proxy repo
    members:
    - andyzhangx
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-proxy: admin
  csi-proxy-maintainers:
    description: Write access to csi-proxy repo
    members:
    - andyzhangx
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-proxy: write
  csi-release-tools-admins:
    description: Admin access to csi-release-tools repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-release-tools: admin
  csi-release-tools-maintainers:
    description: Write access to csi-release-tools repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-release-tools: write
  csi-test-admins:
    description: Admin access to csi-test repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      csi-test: admin
  csi-test-maintainers:
    description: Write access to csi-test repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      csi-test: write
  developers:
    description: ""
    members:
    - humblec
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - vladimirvivien
    - xing-yang
    privacy: closed
    repos:
      external-attacher: write
      external-provisioner: write
      livenessprobe: write
  docs-admins:
    description: Admin access to docs repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      docs: admin
  docs-maintainers:
    description: Write access to docs repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      docs: write
  external-attacher-admins:
    description: Admin access to external-attacher repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-attacher: admin
  external-attacher-maintainers:
    description: Write access to external-attacher repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      external-attacher: write
  external-health-monitor-admins:
    description: Admin access to external-health-monitor repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-health-monitor: admin
  external-health-monitor-maintainers:
    description: Write access to external-health-monitor repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      external-health-monitor: write
  external-provisioner-admins:
    description: Admin access to external-provisioner repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - pohly
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-provisioner: admin
  external-provisioner-maintainers:
    description: Write access to external-provisioner repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - pohly
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      external-provisioner: write
  external-resizer-admins:
    description: Admin access to external-resizer repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-resizer: admin
  external-resizer-maintainers:
    description: Write access to external-resizer repo
    members:
    - chrishenzie
    - gnufied
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      external-resizer: write
  external-snapshot-metadata-admins:
    description: Admin access to external-snapshot-metadata repo
    members:
    - carlbraganza
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-snapshot-metadata: admin
  external-snapshot-metadata-maintainers:
    description: Write access to external-snapshot-metadata repo
    members:
    - carlbraganza
    - hairyhum
    - jsafrane
    - msau42
    - PrasadG193
    - rakshith-r
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-snapshot-metadata: write
  external-snapshotter-admins:
    description: Admin access to external-snapshotter repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      external-snapshotter: admin
  external-snapshotter-maintainers:
    description: Write access to external-snapshotter repo
    members:
    - chrishenzie
    - jsafrane
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      external-snapshotter: write
  kubernetes-csi-github-io-admins:
    description: Admin access to kubernetes-csi.github.io repo
    members:
    - jsafrane
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      kubernetes-csi.github.io: admin
  lib-volume-populator-admins:
    description: Admin access to lib-volume-populator repo
    members:
    - bswartz
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      lib-volume-populator: admin
  livenessprobe-admins:
    description: Admin access to livenessprobe repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      livenessprobe: admin
  livenessprobe-maintainers:
    description: Write access to livenessprobe repo
    members:
    - chrishenzie
    - jsafrane
    - mauriciopoppe
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      livenessprobe: write
  node-driver-registrar-admins:
    description: Admin access to node-driver-registrar repo
    members:
    - jsafrane
    - lpabon
    - msau42
    - saad-ali
    - xing-yang
    privacy: closed
    repos:
      node-driver-registrar: admin
  node-driver-registrar-maintainers:
    description: Write access to node-driver-registrar repo
    members:
    - chrishenzie
    - jsafrane
    - lpabon
    - mauriciopoppe
    - msau42
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      node-driver-registrar: write
  volume-data-source-validator-admins:
    description: Admin access to kubernetes-csi.github.io repo
    members:
    - bswartz
    - saad-ali
    - sunnylovestiramisu
    - xing-yang
    privacy: closed
    repos:
      volume-data-source-validator: admin
