teams:
  downloadkubernetes-admins:
    description: admin access to downloadkubernetes
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - justaugustus # subproject owner
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  downloadkubernetes-maintainers:
    description: write access to downloadkubernetes
    members:
    - alejandrox1 # subproject owner
    - chuckha
    - hasheddan # subproject owner
    - justaugustus # subproject owner
    - mauilion
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  image-promoter-admins:
    description: admin access to k8s-container-image-promoter
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - justaugustus # subproject owner / maintainer
    - justinsb # maintainer
    - listx # maintainer
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
    previously:
    - k8s-container-image-promoter-admins
  image-promoter-maintainers:
    description: write access to k8s-container-image-promoter
    maintainers:
    - spiffxp # WG K8s Infra Lead
    members:
    - alejandrox1 # subproject owner
    - ameukam # WG K8s Infra Lead
    - dims # WG K8s Infra Lead
    - hasheddan # subproject owner
    - justaugustus # subproject owner / maintainer
    - justinsb # maintainer
    - listx # maintainer
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
    previously:
    - k8s-container-image-promoter-maintainers
  mdtoc-admins:
    description: admin access to mdtoc
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - justaugustus # subproject owner
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  release-engineering:
    description: Members of the Release Engineering subproject, including
      Release Managers and Release Manager Associates.
    members:
    - ameukam # Release Manager Associate
    - cpanato # Release Manager
    - hasheddan # subproject owner / Release Manager
    - jimangel # Release Manager Associate
    - justaugustus # subproject owner / Release Manager
    - mkorbi # Release Manager Associate
    - onlydole # Release Manager Associate
    - palnabarun # Release Manager Associate
    - puerco # Release Manager
    - saschagrunert # subproject owner / Release Manager
    - sethmccombs # Release Manager Associate
    - thejoycekung # Release Manager Associate
    - Verolop # Release Manager Associate
    - wilsonehusin # Release Manager Associate
    - xmudrii # Release Manager
    privacy: closed
  release-notes-admins:
    description: admin access to release-notes
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - jeefy
    - justaugustus # subproject owner
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  release-notes-maintainers:
    description: write access to release-notes
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - jeefy
    - justaugustus # subproject owner
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  release-sdk-admins:
    description: admin access to release-sdk
    members:
    - hasheddan
    - jeremyrickard
    - justaugustus
    - saschagrunert
    privacy: closed
  release-sdk-maintainers:
    description: write access to release-sdk
    members:
    - hasheddan
    - jeremyrickard
    - justaugustus
    - saschagrunert
    privacy: closed
  release-utils-admins:
    description: admin access to release-utils
    members:
    - hasheddan
    - jeremyrickard
    - justaugustus
    - saschagrunert
    privacy: closed
  release-utils-maintainers:
    description: write access to release-utils
    members:
    - hasheddan
    - jeremyrickard
    - justaugustus
    - saschagrunert
    privacy: closed
  zeitgeist-admins:
    description: admin access to zeitgeist
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - justaugustus # subproject owner
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
  zeitgeist-maintainers:
    description: write access to zeitgeist
    members:
    - alejandrox1 # subproject owner
    - hasheddan # subproject owner
    - justaugustus # subproject owner
    - n3wscott
    - Pluies
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    - yastij
    privacy: closed
