teams:
  k8s-container-image-promoter-admins:
    description: "admin access to k8s-container-image-promoter"
    members:
    - dims
    - hh
    - listx
    - tpepper
    privacy: closed
  k8s-container-image-promoter-maintainers:
    description: "write access to k8s-container-image-promoter"
    members:
    - dims
    - hh
    - listx
    - tpepper
    privacy: closed
  release-notes-admins:
    description: admin access to release-notes
    members:
    - jeefy
    - marpaia
    - onyiny-ang
    privacy: closed
  release-notes-maintainers:
    description: write access to release-notes
    members:
    - calebamiles
    - jeefy
    - justaugustus
    - marpaia
    - onyiny-ang
    - tpepper
    privacy: closed
