teams:
  bom-admins:
    description: admin access to the bom repo
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  bom-maintainers:
    description: write access to the bom repo
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  downloadkubernetes-admins:
    description: admin access to downloadkubernetes
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  downloadkubernetes-maintainers:
    description: write access to downloadkubernetes
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  mdtoc-admins:
    description: admin access to mdtoc
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  mdtoc-maintainers:
    description: write access to mdtoc
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  promo-tools-admins:
    description: admin access to promo-tools
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner / maintainer
    - listx # maintainer
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
    previously:
    - image-promoter-admins
    - k8s-container-image-promoter-admins
  promo-tools-maintainers:
    description: write access to promo-tools
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner / maintainer
    - listx # maintainer
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
    previously:
    - image-promoter-maintainers
    - k8s-container-image-promoter-maintainers
  release-engineering:
    description: Members of the Release Engineering subproject, including
      Release Managers and Release Manager Associates.
    maintainers:
    - ameukam # Release Manager Associate
    - palnabarun # Release Manager
    members:
    - cpanato # subproject owner / Release Manager
    - jeremyrickard # subproject owner
    - jimangel # Release Manager Associate
    - justaugustus # subproject owner / Release Manager
    - mkorbi # Release Manager Associate
    - onlydole # Release Manager Associate
    - puerco # subproject owner / Release Manager
    - saschagrunert # subproject owner / Release Manager
    - sethmccombs # Release Manager Associate
    - thejoycekung # Release Manager Associate
    - Verolop # Release Manager Associate
    - wilsonehusin # Release Manager Associate
    - xmudrii # Release Manager
    privacy: closed
  release-notes-admins:
    description: admin access to release-notes
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  release-notes-maintainers:
    description: write access to release-notes
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  release-sdk-admins:
    description: admin access to release-sdk
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  release-sdk-maintainers:
    description: write access to release-sdk
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  release-team-shadow-stats-admins:
    description: admin access to release-team-shadow-stats
    members:
    - cpanato
    - jeremyrickard
    - justaugustus
    - puerco
    - saschagrunert
    privacy: closed
  release-utils-admins:
    description: admin access to release-utils
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  release-utils-maintainers:
    description: write access to release-utils
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  zeitgeist-admins:
    description: admin access to zeitgeist
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
  zeitgeist-maintainers:
    description: write access to zeitgeist
    members:
    - cpanato # subproject owner
    - jeremyrickard # subproject owner
    - justaugustus # subproject owner
    - n3wscott
    - Pluies
    - puerco # subproject owner
    - saschagrunert # subproject owner
    privacy: closed
