teams:
  downloadkubernetes-admins:
    description: admin access to downloadkubernetes
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  downloadkubernetes-maintainers:
    description: write access to downloadkubernetes
    members:
    - alejandrox1
    - chuckha
    - justaugustus
    - mauilion
    - saschagrunert
    - tpepper
    privacy: closed
  image-promoter-admins:
    description: admin access to k8s-container-image-promoter
    members:
    - justaugustus # subproject owner / maintainer
    - justinsb # maintainer
    - listx # maintainer
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
    previously:
    - k8s-container-image-promoter-admins
  image-promoter-maintainers:
    description: write access to k8s-container-image-promoter
    maintainers:
    - spiffxp # WG K8s Infra Lead
    members:
    - bartsmykla # WG K8s Infra Lead
    - dims # WG K8s Infra Lead
    - justaugustus # subproject owner / maintainer
    - justinsb # maintainer
    - listx # maintainer
    - saschagrunert # subproject owner
    - tpepper # subproject owner
    privacy: closed
    previously:
    - k8s-container-image-promoter-maintainers
  mdtoc-admins:
    description: admin access to mdtoc
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  release-engineering:
    description: Members of the Release Engineering subproject, including
      Release Managers and Release Manager Associates.
    members:
    - cpanato # Release Manager
    - dougm # Release Manager
    - feiskyer # Release Manager
    - gianarb # Release Manager Associate
    - hasheddan # Release Manager
    - hoegaarden # Release Manager
    - idealhack # Release Manager
    - jimangel # Release Manager Associate
    - justaugustus # subproject owner / Release Manager
    - markyjackson-taulia # Release Manager Associate
    - mkorbi # Release Manager Associate
    - onlydole # Release Manager Associate
    - puerco # Release Manager Associate
    - saschagrunert # subproject owner / Release Manager
    - sethmccombs # Release Manager Associate
    - tpepper # subproject owner / Release Manager
    - Verolop # Release Manager Associate
    - xmudrii # Release Manager
    privacy: closed
  release-notes-admins:
    description: admin access to release-notes
    members:
    - jeefy
    - marpaia
    - onyiny-ang
    privacy: closed
  release-notes-maintainers:
    description: write access to release-notes
    members:
    - jeefy
    - justaugustus
    - marpaia
    - onyiny-ang
    - tpepper
    privacy: closed
  zeitgeist-admins:
    description: admin access to zeitgeist
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  zeitgeist-maintainers:
    description: write access to zeitgeist
    members:
    - alejandrox1
    - justaugustus
    - Pluies
    - saschagrunert
    - tpepper
    - yastij
    privacy: closed
