teams:
  downloadkubernetes-admins:
    description: admin access to downloadkubernetes
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  downloadkubernetes-maintainers:
    description: write access to downloadkubernetes
    members:
    - alejandrox1
    - chuckha
    - justaugustus
    - mauilion
    - saschagrunert
    - tpepper
    privacy: closed
  k8s-container-image-promoter-admins:
    description: admin access to k8s-container-image-promoter
    members:
    - dims
    - justaugustus
    - justinsb
    - listx
    - saschagrunert
    - tpepper
    privacy: closed
  k8s-container-image-promoter-maintainers:
    description: write access to k8s-container-image-promoter
    members:
    - dims
    - justaugustus
    - justinsb
    - listx
    - saschagrunert
    - tpepper
    privacy: closed
  mdtoc-admins:
    description: admin access to mdtoc
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  release-engineering:
    description: Members of the Release Engineering subproject, including
      Release Managers and Release Manager Associates.
    members:
    - calebamiles # subproject owner
    - cpanato # Release Manager
    - dougm # Release Manager
    - feiskyer # Release Manager
    - gianarb # Release Manager Associate
    - hasheddan # Release Manager
    - hoegaarden # subproject owner / Release Manager
    - idealhack # Release Manager
    - jimangel # Release Manager Associate
    - justaugustus # subproject owner / Build Admin / Release Manager
    - listx # Build Admin / Image promoter admin
    - markyjackson-taulia # Release Manager Associate
    - mkorbi # Release Manager Associate
    - onlydole # Release Manager Associate
    - puerco # Release Manager Associate
    - saschagrunert # Release Manager
    - sethmccombs # Release Manager Associate
    - tpepper # subproject owner / Build Admin / Release Manager
    - Verolop # Release Manager Associate
    - xmudrii # Release Manager
    - yodahekinsew # Image promoter contributor (ref: https://github.com/kubernetes/org/pull/1938)
    privacy: closed
  release-notes-admins:
    description: admin access to release-notes
    members:
    - jeefy
    - marpaia
    - onyiny-ang
    privacy: closed
  release-notes-maintainers:
    description: write access to release-notes
    members:
    - calebamiles
    - jeefy
    - justaugustus
    - marpaia
    - onyiny-ang
    - tpepper
    privacy: closed
  zeitgeist-admins:
    description: admin access to zeitgeist
    members:
    - alejandrox1
    - justaugustus
    - saschagrunert
    - tpepper
    privacy: closed
  zeitgeist-maintainers:
    description: write access to zeitgeist
    members:
    - alejandrox1
    - justaugustus
    - Pluies
    - saschagrunert
    - tpepper
    - yastij
    privacy: closed
