restrictions:
  - path: "kubernetes/org.yaml"
    allowedRepos:
    - "^api"
    - "^apiextensions-apiserver"
    - "^apimachinery"
    - "^apiserver"
    - "^autoscaler"
    - "^cli-runtime"
    - "^client-go"
    - "^cloud-provider"
    - "^cloud-provider-gcp"
    - "^cloud-provider-vsphere"
    - "^cluster-bootstrap"
    - "^code-generator"
    - "^component-base"
    - "^component-helpers"
    - "^controller-manager"
    - "^cri-api"
    - "^csi-api"
    - "^csi-translation-lib"
    - "^dashboard"
    - "^dns"
    - "^examples"
    - "^frakti"
    - "^funding"
    - "^gengo"
    - "^git-sync"
    - "^ingress-gce"
    - "^ingress-nginx"
    - "^klog"
    - "^kompose"
    - "^kube-aggregator"
    - "^kube-controller-manager"
    - "^kube-openapi"
    - "^kube-proxy"
    - "^kube-scheduler"
    - "^kube-state-metrics"
    - "^kubectl"
    - "^kubelet"
    - "^kubernetes"
    - "^kubernetes-template-project"
    - "^legacy-cloud-providers"
    - "^metrics"
    - "^mount-utils"
    - "^node-api"
    - "^node-problem-detector"
    - "^noderesourcetopology-api"
    - "^org"
    - "^perf-tests"
    - "^sample-apiserver"
    - "^sample-cli-plugin"
    - "^sample-controller"
    - "^security"
    - "^steering"
    - "^utils"
  - path: "kubernetes/provider-openstack/teams.yaml"
    allowedRepos:
    - "^cloud-provider-openstack"
  - path: "kubernetes/sig-apps/teams.yaml"
    allowedRepos:
    - "^kompose"
  - path: "kubernetes/sig-architecture/teams.yaml"
    allowedRepos:
    - "^enhancements"
  - path: "kubernetes/sig-cli/teams.yaml"
    allowedRepos:
    - "^kubectl"
  - path: "kubernetes/sig-cloud-provider/teams.yaml"
    allowedRepos:
    - "^cloud-provider"
    - "^cloud-provider-alibaba-cloud"
  - path: "kubernetes/sig-cluster-lifecycle/teams.yaml"
    allowedRepos:
    - "^kops"
    - "^kubeadm"
    - "^minikube"
    - "^system-validators"
  - path: "kubernetes/sig-contributor-experience/teams.yaml"
    allowedRepos:
    - "^community"
    - "^contributor-site"
  - path: "kubernetes/sig-docs/teams.yaml"
    allowedRepos:
    - "^website"
  - path: "kubernetes/sig-instrumentation/teams.yaml"
    allowedRepos:
    - "^kube-state-metrics"
    - "^klog"
    - "^metrics"
  - path: "kubernetes/sig-testing/teams.yaml"
    allowedRepos:
    - "^publishing-bot"
    - "^repo-infra"
    - "^test-infra"
  - path: "kubernetes/wg-k8s-infra/teams.yaml"
    allowedRepos:
    - "^k8s.io"
  - path: "kubernetes-sigs/org.yaml"
    allowedRepos:
    - "^application"
    - "^cri-tools"
    - "^dashboard-metrics-scraper"
    - "^gcp-filestore-csi-driver"
    - "^node-feature-discovery"
    - "^sig-storage-lib-external-provisioner"
    - "^sig-storage-local-static-provisioner"
  - path: "kubernetes-sigs/provider-azure/teams.yaml"
    allowedRepos:
    - "^azuredisk-csi-driver"
    - "^azurefile-csi-driver"
    - "^cloud-provider-azure"
  - path: "kubernetes-sigs/provider-vmware/teams.yaml"
    allowedRepos:
    - "^vsphere-csi-driver"
  - path: "kubernetes-sigs/sig-api-machinery/teams.yaml"
    allowedRepos:
    - "^apiserver-builder-alpha"
    - "^apiserver-runtime"
    - "^clientgofix"
    - "^controller-runtime"
    - "^controller-tools"
    - "^kubebuilder"
    - "^kubebuilder-declarative-pattern"
    - "^kubebuilder-release-tools"
    - "^kubectl-check-ownerreferences"
    - "^structured-merge-diff"
    - "^yaml"
  - path: "kubernetes-sigs/sig-apps/teams.yaml"
    allowedRepos:
    - "^execution-hook"
  - path: "kubernetes-sigs/sig-architecture/teams.yaml"
    allowedRepos:
    - "^depstat"
  - path: "kubernetes-sigs/sig-auth/teams.yaml"
    allowedRepos:
    - "^hierarchical-namespaces"
    - "^multi-tenancy"
    - "^secrets-store-csi-driver"
  - path: "kubernetes-sigs/sig-aws/teams.yaml"
    allowedRepos:
    - "^aws-ebs-csi-driver"
    - "^aws-efs-csi-driver"
    - "^aws-encryption-provider"
    - "^aws-fsx-csi-driver"
  - path: "kubernetes-sigs/sig-cli/teams.yaml"
    allowedRepos:
    - "^cli-experimental"
    - "^cli-utils"
    - "^krew"
    - "^krew-index"
    - "^kui"
    - "^kustomize"
  - path: "kubernetes-sigs/sig-cloud-provider/teams.yaml"
    allowedRepos:
    - "^alibaba-cloud-csi-driver"
    - "^apiserver-network-proxy"
    - "^aws-iam-authenticator"
    - "^blob-csi-driver"
    - "^cloud-provider-baiducloud"
    - "^cloud-provider-huaweicloud"
  - path: "kubernetes-sigs/sig-cluster-lifecycle/teams.yaml"
    allowedRepos:
    - "^bootkube"
    - "^cluster-addons"
    - "^cluster-api"
    - "^cluster-api-bootstrap-provider-kubeadm"
    - "^cluster-api-provider-aws"
    - "^cluster-api-provider-azure"
    - "^cluster-api-provider-digitalocean"
    - "^cluster-api-provider-docker"
    - "^cluster-api-provider-gcp"
    - "^cluster-api-provider-kubemark"
    - "^cluster-api-provider-nested"
    - "^cluster-api-provider-openstack"
    - "^cluster-api-provider-packet"
    - "^cluster-api-provider-vsphere"
    - "^etcdadm"
    - "^image-builder"
    - "^kubespray"
  - path: "kubernetes-sigs/sig-contributor-experience/teams.yaml"
    allowedRepos:
    - "^contributor-tweets"
    - "^discuss-theme"
    - "^slack-infra"
  - path: "kubernetes-sigs/sig-docs/teams.yaml"
    allowedRepos:
    - "^reference-docs"
  - path: "kubernetes/sig-release/teams.yaml"
    allowedRepos:
    - "^enhancements"
  - path: "kubernetes-sigs/sig-ibmcloud/teams.yaml"
    allowedRepos:
    - "^cluster-api-provider-ibmcloud"
  - path: "kubernetes-sigs/sig-instrumentation/teams.yaml"
    allowedRepos:
    - "^custom-metrics-apiserver"
    - "^instrumentation"
    - "^instrumentation-tools"
    - "^metrics-server"
    - "^prometheus-adapter"
  - path: "kubernetes-sigs/sig-k8s-infra/teams.yaml"
    allowedRepos:
    - "^community-images"
    - "^porche"
  - path: "kubernetes-sigs/sig-multicluster/teams.yaml"
    allowedRepos:
    - "^kubefed"
    - "^mcs-api"
    - "^work-api"
  - path: "kubernetes-sigs/sig-network/teams.yaml"
    allowedRepos:
    - "^cluster-proportional-autoscaler"
    - "^cluster-proportional-vertical-autoscaler"
    - "^external-dns"
    - "^gateway-api"
    - "^ingress-controller-conformance"
    - "^ip-masq-agent"
    - "^iptables-wrappers"
    - "^kpng"
  - path: "kubernetes-sigs/sig-node/teams.yaml"
    allowedRepos:
    - "^node-feature-discovery-operator"
    - "^security-profiles-operator"
  - path: "kubernetes-sigs/sig-release/teams.yaml"
    allowedRepos:
    - "^downloadkubernetes"
    - "^k8s-container-image-promoter"
    - "^mdtoc"
    - "^release-notes"
    - "^release-sdk"
    - "^release-utils"
    - "^zeitgeist"
  - path: "kubernetes-sigs/sig-scheduling/teams.yaml"
    allowedRepos:
    - "^cluster-capacity"
    - "^descheduler"
    - "^kube-batch"
    - "^poseidon"
    - "^scheduler-plugins"
  - path: "kubernetes-sigs/sig-service-catalog/teams.yaml"
    allowedRepos:
    - "^go-open-service-broker-client"
    - "^minibroker"
    - "^service-catalog"
  - path: "kubernetes-sigs/sig-storage/teams.yaml"
    allowedRepos:
    - "^container-object-storage-interface-api"
    - "^container-object-storage-interface-controller"
    - "^container-object-storage-interface-csi-adapter"
    - "^container-object-storage-interface-provisioner-sidecar"
    - "^container-object-storage-interface-spec"
    - "^gluster-block-external-provisioner"
    - "^gluster-file-external-provisioner"
    - "^nfs-ganesha-server-and-external-provisioner"
    - "^nfs-subdir-external-provisioner"
  - path: "kubernetes-sigs/sig-testing/teams.yaml"
    allowedRepos:
    - "^boskos"
    - "^cloud-provider-kind"
    - "^e2e-framework"
    - "^k8s-gsm-tools"
    - "^kind"
    - "^kubetest2"
  - path: "kubernetes-sigs/sig-usability/teams.yaml"
    allowedRepos:
    - "^sig-usability"
  - path: "kubernetes-sigs/sig-windows/teams.yaml"
    allowedRepos:
    - "^sig-windows-samples"
    - "^sig-windows-tools"
    - "^windows-gmsa"
    - "^windows-testing"
  - path: "kubernetes-sigs/wg-component-standard/teams.yaml"
    allowedRepos:
    - "^legacyflag"
  - path: "kubernetes-sigs/wg-policy/teams.yaml"
    allowedRepos:
    - "^wg-policy-prototypes"
  - path: "kubernetes-csi/org.yaml"
    allowedRepos:
    - "^cluster-driver-registrar"
    - "^csi-driver-host-path"
    - "^csi-driver-image-populator"
    - "^csi-driver-iscsi"
    - "^csi-driver-nfs"
    - "^csi-driver-smb"
    - "^csi-lib-fc"
    - "^csi-lib-iscsi"
    - "^csi-lib-utils"
    - "^csi-proxy"
    - "^csi-test"
    - "^docs"
    - "^driver-registrar"
    - "^external-attacher"
    - "^external-health-monitor"
    - "^external-provisioner"
    - "^external-resizer"
    - "^external-snapshotter"
    - "^kubernetes-csi.github.io"
    - "^lib-volume-populator"
    - "^livenessprobe"
    - "^node-driver-registrar"
    - "^volume-data-source-validator"
  - path: "kubernetes-client/org.yaml"
    allowedRepos:
    - "^c"
    - "^csharp"
    - "^gen"
    - "^go"
    - "^go-base"
    - "^haskell"
    - "^java"
    - "^javascript"
    - "^perl"
    - "^python"
    - "^python-base"
    - "^ruby"
  - path: "**/*" # prevent any other file from containing anything
