restrictions:
  - path: "kubernetes/org.yaml"
    allowedRepos:
    - "^api"
    - "^apiextensions-apiserver"
    - "^apimachinery"
    - "^apiserver"
    - "^cli-runtime"
    - "^client-go"
    - "^cloud-provider"
    - "^cluster-bootstrap"
    - "^code-generator"
    - "^component-base"
    - "^component-helpers"
    - "^controller-manager"
    - "^cri-api"
    - "^cri-client"
    - "^csi-translation-lib"
    - "^dynamic-resource-allocation"
    - "^endpointslice"
    - "^externaljwt"
    - "^kms"
    - "^kube-aggregator"
    - "^kube-controller-manager"
    - "^kube-proxy"
    - "^kube-scheduler"
    - "^kubectl"
    - "^kubelet"
    - "^legacy-cloud-providers"
    - "^metrics"
    - "^mount-utils"
    - "^node-api"
    - "^pod-security-admission"
    - "^sample-apiserver"
    - "^sample-cli-plugin"
    - "^sample-controller"
    - "^committee-security-response"
    - "^cloud-provider-gcp"
    - "^cloud-provider-vsphere"
    - "^dashboard"
    - "^dns"
    - "^examples"
    - "^gengo"
    - "^git-sync"
    - "^ingress-gce"
    - "^ingress-nginx"
    - "^kompose"
    - "^kube-openapi"
    - "^kubernetes"
    - "^kubernetes-template-project"
    - "^steering"
    - "^org"
    - "^perf-tests"
    - "^steering"
    - "^utils"
  - path: "kubernetes/provider-gcp/teams.yaml"
    allowedRepos:
    - "^cloud-provider-gcp"
  - path: "kubernetes/provider-openstack/teams.yaml"
    allowedRepos:
    - "^cloud-provider-openstack"
  - path: "kubernetes/sig-apps/teams.yaml"
    allowedRepos:
    - "^kompose"
  - path: "kubernetes/sig-api-machinery/teams.yaml"
    allowedRepos:
    - "^cel-admission-webhook"
  - path: "kubernetes/sig-architecture/teams.yaml"
    allowedRepos:
    - "^design-proposals-archive"
    - "^enhancements"
  - path: "kubernetes/sig-autoscaling/teams.yaml"
    allowedRepos:
    - "^autoscaler"
  - path: "kubernetes/sig-cli/teams.yaml"
    allowedRepos:
    - "^kubectl"
  - path: "kubernetes/sig-cloud-provider/teams.yaml"
    allowedRepos:
    - "^cloud-provider"
    - "^cloud-provider-sample"
    - "^cloud-provider-alibaba-cloud"
  - path: "kubernetes/sig-cluster-lifecycle/teams.yaml"
    allowedRepos:
    - "^kops"
    - "^kubeadm"
    - "^minikube"
    - "^system-validators"
  - path: "kubernetes/sig-contributor-experience/teams.yaml"
    allowedRepos:
    - "^community"
    - "^contributor-site"
  - path: "kubernetes/sig-docs/teams.yaml"
    allowedRepos:
    - "^website"
  - path: "kubernetes/sig-instrumentation/teams.yaml"
    allowedRepos:
    - "^kube-state-metrics"
    - "^klog"
    - "^metrics"
  - path: "kubernetes/sig-k8s-infra/teams.yaml"
    allowedRepos:
    - "^k8s.io"
    - "^registry.k8s.io"
  - path: "kubernetes/sig-node/teams.yaml"
    allowedRepos:
    - "^node-problem-detector"
  - path: "kubernetes/sig-security/teams.yaml"
    allowedRepos:
    - "^sig-security"
  - path: "kubernetes/sig-testing/teams.yaml"
    allowedRepos:
    - "^test-infra"
    - "^publishing-bot"
  - path: "kubernetes-sigs/org.yaml"
    allowedRepos:
    - "^application"
    - "^cri-tools"
    - "^dashboard-metrics-scraper"
    - "^node-feature-discovery"
  - path: "kubernetes-sigs/provider-azure/teams.yaml"
    allowedRepos:
    - "^cloud-provider-azure"
    - "^azuredisk-csi-driver"
    - "^azurefile-csi-driver"
    - "^azurelustre-csi-driver"
  - path: "kubernetes-sigs/provider-ibmcloud/teams.yaml"
    allowedRepos:
    - "^cluster-api-provider-ibmcloud"
    - "^ibm-vpc-block-csi-driver"
  - path: "kubernetes-sigs/provider-vmware/teams.yaml"
    allowedRepos:
    - "^vsphere-csi-driver"
  - path: "kubernetes-sigs/sig-api-machinery/teams.yaml"
    allowedRepos:
    - "^apiserver-builder-alpha"
    - "^apiserver-runtime"
    - "^clientgofix"
    - "^crdify"
    - "^controller-runtime"
    - "^controller-tools"
    - "^json"
    - "^kube-api-linter"
    - "^kubebuilder"
    - "^kubebuilder-declarative-pattern"
    - "^kubebuilder-release-tools"
    - "^kubectl-check-ownerreferences"
    - "^kube-storage-version-migrator"
    - "^structured-merge-diff"
    - "^yaml"
  - path: "kubernetes-sigs/sig-apps/teams.yaml"
    allowedRepos:
    - "^agent-sandbox"
    - "^execution-hook"
    - "^jobset"
    - "^kjob"
    - "^llm-instance-gateway$"
    - "^lws"
  - path: "kubernetes-sigs/sig-architecture/teams.yaml"
    allowedRepos:
    - "^apisnoop"
    - "^admission-policies"
    - "^depstat"
    - "^maintainer-tools"
    - "^verify-conformance"
    - "^wg-ai-conformance"
    - "^wg-device-management"
    - "^wg-serving"
  - path: "kubernetes-sigs/sig-auth/teams.yaml"
    allowedRepos:
    - "^referencegrant-poc"
    - "^secrets-store-csi-driver"
    - "^secrets-store-sync-controller"
    - "^sig-auth-tools"
  - path: "kubernetes-sigs/sig-autoscaling/teams.yaml"
    allowedRepos:
    - "^karpenter"
    - "^karpenter-provider-ibm-cloud"
  - path: "kubernetes-sigs/sig-aws/teams.yaml"
    allowedRepos:
    - "^aws-ebs-csi-driver"
    - "^aws-efs-csi-driver"
    - "^aws-encryption-provider"
    - "^aws-fsx-csi-driver"
  - path: "kubernetes-sigs/sig-cli/teams.yaml"
    allowedRepos:
    - "^cli-experimental"
    - "^cli-utils"
    - "^krew"
    - "^krew-index"
    - "^krm-functions-registry"
    - "^kubectl-validate"
    - "^kustomize"
  - path: "kubernetes-sigs/sig-cloud-provider/teams.yaml"
    allowedRepos:
    - "^apiserver-network-proxy"
    - "^alibaba-cloud-csi-driver"
    - "^aws-file-cache-csi-driver"
    - "^aws-fsx-openzfs-csi-driver"
    - "^aws-iam-authenticator"
    - "^blob-csi-driver"
    - "^cloud-pv-admission-labeler"
    - "^cloud-provider-baiducloud"
    - "^cloud-provider-equinix-metal"
    - "^cloud-provider-huaweicloud"
    - "^ibm-powervs-block-csi-driver"
    - "^kro"
    - "^provider-aws-test-infra"
    - "^provider-ibmcloud-test-infra"
  - path: "kubernetes-sigs/sig-cluster-lifecycle/teams.yaml"
    allowedRepos:
    - "^cluster-addons"
    - "^cluster-api-addon-provider-helm"
    - "^cluster-api"
    - "^cluster-api-operator"
    - "^cluster-api-provider-aws"
    - "^cluster-api-provider-azure"
    - "^cluster-api-provider-cloudstack"
    - "^cluster-api-provider-digitalocean"
    - "^cluster-api-provider-gcp"
    - "^cluster-api-provider-kubemark"
    - "^cluster-api-provider-kubevirt"
    - "^cluster-api-provider-openstack"
    - "^cluster-api-provider-packet"
    - "^cluster-api-provider-vsphere"
    - "^image-builder"
    - "^karpenter-provider-cluster-api"
    - "^kubespray"
    - "^logical-cluster"
    - "^minikube-gui"
    - "^minikube-os"
    - "^minikube-preloads"
  - path: "kubernetes-sigs/sig-contributor-experience/teams.yaml"
    allowedRepos:
    - "^contributor-tweets"
    - "^discuss-theme"
    - "^lwkd"
    - "^maintainers"
    - "^slack-infra"
  - path: "kubernetes-sigs/sig-docs/teams.yaml"
    allowedRepos:
    - "^reference-docs"
  - path: "kubernetes-sigs/sig-etcd/teams.yaml"
    allowedRepos:
    - "^etcd-manager"
  - path: "kubernetes/sig-release/teams.yaml"
    allowedRepos:
    - "^publishing-bot"
    - "^repo-infra"
    - "^enhancements"
  - path: "kubernetes-sigs/sig-instrumentation/teams.yaml"
    allowedRepos:
    - "^custom-metrics-apiserver"
    - "^instrumentation"
    - "^instrumentation-tools"
    - "^logtools"
    - "^metrics-server"
    - "^prometheus-adapter"
    - "^resource-state-metrics"
    - "^usage-metrics-collector"
  - path: "kubernetes-sigs/sig-k8s-infra/teams.yaml"
    allowedRepos:
    - "^community-images"
    - "^porche"
  - path: "kubernetes-sigs/sig-multicluster/teams.yaml"
    allowedRepos:
    - "^about-api"
    - "^cluster-inventory-api"
    - "^mcs-api"
    - "^multicluster-runtime"
    - "^sig-multicluster-site"
    - "^work-api"
  - path: "kubernetes-sigs/sig-network/teams.yaml"
    allowedRepos:
    - "^cluster-proportional-autoscaler"
    - "^cluster-proportional-vertical-autoscaler"
    - "^cni-dra-driver"
    - "^gwctl"
    - "^ip-masq-agent"
    - "^external-dns"
    - "^ingate"
    - "^ingress2gateway"
    - "^ingress-controller-conformance"
    - "^iptables-wrappers"
    - "^gateway-api"
    - "^knftables"
    - "^kube-network-policies"
    - "^multi-network"
    - "^multi-network-api"
    - "^nat64"
    - "^network-policy-api"
    - "^network-policy-finalizer"
    - "^node-ipam-controller"
    - "^wg-ai-gateway"
  - path: "kubernetes-sigs/sig-node/teams.yaml"
    allowedRepos:
    - "^dra-driver-cpu"
    - "^dra-example-driver"
    - "^kernel-module-management"
    - "^noderesourcetopology-api"
    - "^node-feature-discovery-operator"
    - "^security-profiles-operator"
  - path: "kubernetes-sigs/sig-release/teams.yaml"
    allowedRepos:
    - "^bom"
    - "^downloadkubernetes"
    - "^mdtoc"
    - "^obscli"
    - "^promo-tools"
    - "^release-actions"
    - "^release-notes"
    - "^release-sdk"
    - "^release-team-shadow-stats"
    - "^release-utils"
    - "^tejolote"
    - "^testgrid-json-exporter"
    - "^zeitgeist"
  - path: "kubernetes-sigs/sig-scalability/teams.yaml"
    allowedRepos:
    - "^inference-perf"
  - path: "kubernetes-sigs/sig-scheduling/teams.yaml"
    allowedRepos:
    - "^cluster-capacity"
    - "^descheduler"
    - "^kube-batch"
    - "^kube-scheduler-simulator"
    - "^kube-scheduler-wasm-extension"
    - "^kueue"
    - "^kwok"
    - "^scheduler-plugins"
  - path: "kubernetes-sigs/sig-storage/teams.yaml"
    allowedRepos:
    - "^container-object-storage-interface"
    - "^cosi-driver-sample"
    - "^gcp-compute-persistent-disk-csi-driver"
    - "^gcp-filestore-csi-driver"
    - "^gluster-block-external-provisioner"
    - "^gluster-file-external-provisioner"
    - "^nfs-subdir-external-provisioner"
    - "^nfs-ganesha-server-and-external-provisioner"
    - "^sig-storage-lib-external-provisioner"
    - "^sig-storage-local-static-provisioner"
  - path: "kubernetes-sigs/sig-testing/teams.yaml"
    allowedRepos:
    - "^boskos"
    - "^cloud-provider-kind"
    - "^e2e-framework"
    - "^hydrophone"
    - "^kind"
    - "^kubetest2"
    - "^prow"
    - "^randfill"
    - "^testgrid"
  - path: "kubernetes-sigs/sig-ui/teams.yaml"
    allowedRepos:
    - "^headlamp"
  - path: "kubernetes-sigs/sig-usability/teams.yaml"
    allowedRepos:
    - "^sig-usability"
  - path: "kubernetes-sigs/sig-windows/teams.yaml"
    allowedRepos:
    - "^windows-gmsa"
    - "^sig-windows-samples"
    - "^sig-windows-dev-tools"
    - "^sig-windows-tools"
    - "^windows-operational-readiness"
    - "^windows-service-proxy"
    - "^windows-testing"
  - path: "kubernetes-sigs/wg-component-standard/teams.yaml"
    allowedRepos:
    - "^legacyflag"
  - path: "kubernetes-csi/org.yaml"
    allowedRepos:
    - "^csi-driver-host-path"
    - "^csi-driver-iscsi"
    - "^csi-driver-nfs"
    - "^csi-driver-nvmf"
    - "^csi-driver-smb"
    - "^csi-lib-fc"
    - "^csi-lib-iscsi"
    - "^csi-lib-utils"
    - "^csi-proxy"
    - "^csi-release-tools"
    - "^csi-test"
    - "^docs"
    - "^external-attacher"
    - "^external-health-monitor"
    - "^external-provisioner"
    - "^external-resizer"
    - "^external-snapshot-metadata"
    - "^external-snapshotter"
    - "^kubernetes-csi.github.io"
    - "^lib-volume-populator"
    - "^livenessprobe"
    - "^node-driver-registrar"
    - "^volume-data-source-validator"
  - path: "kubernetes-client/org.yaml"
    allowedRepos:
    - "^c"
    - "^csharp"
    - "^gen"
    - "^go"
    - "^go-base"
    - "^haskell"
    - "^java"
    - "^javascript"
    - "^perl"
    - "^python"
    - "^python-base"
    - "^ruby"
  - path: "etcd-io/sig-etcd/teams.yaml"
    allowedRepos:
    - "^auger$"
    - "^bbolt$"
    - "^dbtester$"
    - "^discovery.etcd.io$"
    - "^discoveryserver$"
    - "^etcd$"
    - "^etcdlabs$"
    - "^etcd-operator$"
    - "^gofail$"
    - "^govanityurls$"
    - "^jetcd$"
    - "^protodoc$"
    - "^raft$"
    - "^website$"
  - path: "**/*" # prevent any other file from containing anything
