teams:
  cloud-provider-azure-admins:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - justaugustus
    - nilo19
    privacy: closed
  cloud-provider-azure-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - justaugustus
    - ritazh
    privacy: closed
  azuredisk-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
  azuredisk-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    privacy: closed
  azurefile-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
  azurefile-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    privacy: closed

