teams:
  cloud-provider-azure-admins:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - justaugustus
    privacy: closed
    repos:
      cloud-provider-azure: admin
  cloud-provider-azure-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - justaugustus
    - mainred
    - nilo19
    - ritazh
    privacy: closed
    repos:
      cloud-provider-azure: write
  azuredisk-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
    repos:
      azuredisk-csi-driver: admin
  azuredisk-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - landreasyan
    - nearora-msft
    privacy: closed
    repos:
      azuredisk-csi-driver: write
  azurefile-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
    repos:
      azurefile-csi-driver: admin
  azurefile-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    - feiskyer
    - landreasyan
    - nearora-msft
    privacy: closed
    repos:
      azurefile-csi-driver: write
  azurelustre-csi-driver-admins:
    description: "Admin access to the azurelustre-csi-driver repo"
    members:
    - andyzhangx
    privacy: closed
    repos:
      azurelustre-csi-driver: admin
  azurelustre-csi-driver-maintainers:
    description: "Write access to the azurelustre-csi-driver repo"
    members:
    - andyzhangx
    privacy: closed
    repos:
      azurelustre-csi-driver: write
