teams:
  sig-windows-bugs:
    description: For reporting and investigating bugs for sig-windows
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  sig-windows-feature-requests:
    description: Feature requests for sig-windows
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  sig-windows-leads:
    description: Special Interest Group Windows Leads
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
  sig-windows-misc:
    description: Special Interest Group Windows
    members:
    - claudiubelu
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
