teams:
  hierarchical-namespaces-admins:
    description: Admin access to hierarchical-namespaces repo
    members:
    - adrianludwin
    - rjbez17
    - srampal
    - tashimi
    privacy: closed
  hierarchical-namespaces-maintainers:
    description: Write access to hierarchical-namespaces repo
    members:
    - GinnyJI
    - yiqigao217
    privacy: closed
  multi-tenancy-admins:
    description: Admin access to multi-tenancy repo
    members:
    - davidopp
    - easeway
    - srampal
    - tashimi
    privacy: closed
  multi-tenancy-maintainers:
    description: Write access to multi-tenancy repo
    members:
    - adrianludwin
    - davidopp
    - easeway
    - rjbez17
    - srampal
    - tashimi
    - yiqigao217
    privacy: closed
  secrets-store-csi-driver-admins:
    description: Admin access to secrets-store-csi-driver repo
    members:
    - aramase
    - ritazh
    privacy: closed
  secrets-store-csi-driver-maintainers:
    description: Write access to secrets-store-csi-driver repo
    members:
    - aramase
    - ritazh
    - tam7t
    privacy: closed
