teams:
  multi-tenancy-admins:
    description: Admin access to multi-tenancy repo
    members:
    - davidopp
    - easeway
    - srampal
    - tashimi
    privacy: closed
  multi-tenancy-maintainers:
    description: Write access to multi-tenancy repo
    members:
    - davidopp
    - easeway
    - srampal
    - tashimi
    privacy: closed
