teams:
  secrets-store-csi-driver-admins:
    description: Admin access to secrets-store-csi-driver repo
    members:
    - aramase
    - enj
    - ritazh
    privacy: closed
    repos:
      secrets-store-csi-driver: admin
  secrets-store-csi-driver-maintainers:
    description: Write access to secrets-store-csi-driver repo
    members:
    - aramase
    - enj
    - ritazh
    privacy: closed
    repos:
      secrets-store-csi-driver: write
  referencegrant-poc-admins:
    description: Admin access to referencegrant-poc repo
    members:
    - enj
    - liggitt
    - robscott
    privacy: closed
    repos:
      referencegrant-poc: admin
  referencegrant-poc-maintainers:
    description: Write access to referencegrant-poc repo
    members:
    - LiorLieberman
    - robscott
    - stealthybox
    privacy: closed
    repos:
      referencegrant-poc: write
  secrets-store-sync-controller-admins:
    description: Admin access to secrets-store-sync-controller repo
    members:
    - aramase
    - enj
    privacy: closed
    repos:
      secrets-store-sync-controller: admin
  secrets-store-sync-controller-maintainers:
    description: Write access to secrets-store-sync-controller repo
    members:
    - aramase
    - enj
    - stlaz
    privacy: closed
    repos:
      secrets-store-sync-controller: write
  sig-auth-tools-admins:
    description: Admin access to sig-auth-tools repo
    members:
    - aramase
    - enj
    - ritazh
    privacy: closed
    repos:
      sig-auth-tools: admin
  sig-auth-tools-maintainers:
    description: Write access to sig-auth-tools repo
    members:
    - aramase
    - enj
    - ritazh
    privacy: closed
    repos:
      sig-auth-tools: write
