name: Kubernetes Incubator
description: Kubernetes Incubator
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
admins:
- calebamiles
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- nikhita
- spiffxp
- thelinuxfoundation
members:
- aaronlevy
- abhi
- adohe
- alex-mohr
- ant31
- aronchick
- arschles
- artmello
- Atoms
- aveshagarwal
- balajismaniam
- bgrant0607
- bmelville
- bogdando
- bowei
- Bradamant3
- bradtopol
- brancz
- bsalamat
- cab105
- caesarxuchao
- carolynvs
- cdrage
- chadswen
- chenopis
- childsb
- chrislovecnm
- cofyc
- colhom
- ConnorDoyle
- crassirostris
- cyphar
- davidopp
- dchen1107
- derekparker
- derekwaynecarr
- dhirajh
- dims
- DirectXMan12
- dnardo
- duglin
- elg0nz
- eparis
- eriknelson
- euank
- feiskyer
- fgrzadkowski
- flyingcougar
- foxish
- grodrigues3
- hjacobs
- hodovska
- hongchaodeng
- humblec
- ianchakeres
- ideahitme
- ingvagabund
- iterion
- janetkuo
- jberkhahn
- jboyd01
- jeremyrickard
- jimmidyson
- jinzhejz
- jpeeler
- jsafrane
- justaugustus
- justinsb
- k82cn
- kadel
- kawych
- kbarnard10
- kibbles-n-bytes
- kikisdeliveryservice
- krancour
- kris-nova
- krmayankk
- lavalamp
- linki
- loburm
- luksa
- luxas
- marquiz
- martinmaly
- mattf
- mattymo
- mbohlool
- MHBauer
- miaoyq
- mikebrow
- mirwan
- mistyhacks
- mrbobbytables
- MrHohn
- mrunalp
- msau42
- mtaufen
- mumoshu
- n3wscott
- nalind
- ncdc
- ngtuna
- nilebox
- njuettner
- onyiny-ang
- parispittman
- pbx0
- philips
- piosz
- pmorie
- procrypt
- pwittrock
- Raffo
- Rajakavitha1
- Random-Liu
- redbaron
- rhatdan
- riverzhang
- rlenferink
- roberthbailey
- rootfs
- rsmitty
- runcom
- ryanmcginnis
- sameo
- sarahnovotny
- sbezverk
- sebgoa
- service-catalog-jenkins
- shubheksha
- slack
- Smana
- smarterclayton
- spxtr
- squat
- staebler
- steveperry-53
- stewart-yu
- sttts
- surajssd
- taragu
- tengqm
- thockin
- timothysc
- tsmetana
- vaikas-google
- vishh
- warmchang
- wongma7
- woopstar
- x13n
- xiang90
- xiangpengzhao
- xlgao-zju
- yanxuean
- yifan-gu
- yliaog
- yue9944882
- yujuhong
- zacharysarah
- zhangxiaoyu-zidif
- zmerlynn
- zparnold
teams:
  admin-bootkube:
    description: ""
    maintainers:
    - aaronlevy
    members:
    - philips
    privacy: closed
  admin-cluster-capacity:
    description: ""
    members:
    - aveshagarwal
    - hodovska
    - ingvagabund
    - sarahnovotny
    privacy: closed
  admin-cri-containerd:
    description: administration of cri-containerd repo
    members:
    - dchen1107
    - Random-Liu
    - sarahnovotny
    privacy: closed
  admin-custom-metrics-apiserver:
    description: Admins for the custom-metrics-apiserver repo
    maintainers:
    - DirectXMan12
    members:
    - luxas
    - piosz
    privacy: closed
  admin-external-storage:
    description: administering the external-storage project
    members:
    - childsb
    - sarahnovotny
    privacy: closed
  admin-reference-docs:
    description: adminstration of reference-docs repo
    maintainers:
    - pwittrock
    members:
    - sarahnovotny
    privacy: closed
  admins-apiserver-builder:
    description: maintainers of the apiserver-builder repository with admin access
    maintainers:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
  admins-application-images:
    description: administrators of the application-images repository
    maintainers:
    - calebamiles
    - zmerlynn
    members:
    - mattf
    privacy: closed
  admins-client-python:
    description: admins of the client-python project
    maintainers:
    - mbohlool
    members:
    - sarahnovotny
    - smarterclayton
    - yliaog
    privacy: closed
  admins-cluster-proportional-autoscaler:
    description: administers of  the cluster-proportional-autoscaler repository
    maintainers:
    - bowei
    - calebamiles
    - MrHohn
    members:
    - philips
    privacy: closed
  admins-external-dns:
    description: ""
    maintainers:
    - calebamiles
    - justinsb
    members:
    - sarahnovotny
    privacy: closed
  admins-ip-masq-agent:
    description: ""
    maintainers:
    - dnardo
    - mtaufen
    - thockin
    members:
    - MrHohn
    privacy: closed
  admins-kargo:
    description: ""
    maintainers:
    - ant31
    - calebamiles
    members:
    - bogdando
    - mattymo
    - sarahnovotny
    - Smana
    privacy: closed
  admins-kompose:
    description: Admins for kompose
    maintainers:
    - sebgoa
    members:
    - bgrant0607
    - cdrage
    - janetkuo
    - kadel
    - ngtuna
    privacy: closed
  admins-kops:
    description: administrators of the kops repository
    maintainers:
    - calebamiles
    privacy: closed
  admins-kube-aws:
    description: kube-aws repository administrators
    maintainers:
    - calebamiles
    - colhom
    members:
    - mumoshu
    - philips
    privacy: closed
  admins-kube2consul:
    description: administrators of the kube2consul repository
    maintainers:
    - calebamiles
    - elg0nz
    members:
    - bgrant0607
    privacy: closed
  admins-metrics-server:
    description: ""
    members:
    - piosz
    - thockin
    privacy: closed
  admins-node-feature-discovery:
    description: Administrators of node-feature-discovery
    maintainers:
    - balajismaniam
    members:
    - ConnorDoyle
    - davidopp
    - philips
    privacy: closed
  admins-rktlet:
    description: administrators of the rktlet repository
    maintainers:
    - calebamiles
    - euank
    - yifan-gu
    members:
    - dchen1107
    privacy: closed
  admins-service-catalog:
    description: administrators for the service catalog project
    maintainers:
    - carolynvs
    - duglin
    - pmorie
    members:
    - kibbles-n-bytes
    - sarahnovotny
    privacy: closed
  descheduler-admins:
    description: Admin permission for descheduler repo
    maintainers:
    - aveshagarwal
    privacy: closed
  descheduler-maintainers:
    description: Write permission for descheduler repo
    maintainers:
    - aveshagarwal
    privacy: closed
  descheduler-reviewers:
    description: Read permission for descheduler repo
    maintainers:
    - aveshagarwal
    privacy: closed
  design-reviewer-kube-arbitrator:
    description: The design reviewer of kube-arbitrator
    maintainers:
    - k82cn
    members:
    - bsalamat
    - davidopp
    - foxish
    - timothysc
    privacy: closed
  external-storage-community:
    description: the extended external storage community
    maintainers:
    - childsb
    members:
    - ianchakeres
    - jsafrane
    - msau42
    - wongma7
    privacy: closed
  incubator-admin:
    description: ""
    members:
    - philips
    privacy: closed
  incubator-admins:
    description: ""
    privacy: closed
  kompose-contributors:
    description: Contributors to kompose repo (read access)
    maintainers:
    - sebgoa
    members:
    - bgrant0607
    - cdrage
    - ngtuna
    - procrypt
    privacy: closed
  maintainers-apiserver-builder:
    description: maintainers of apiserver-builder with write access on the repository
    maintainers:
    - DirectXMan12
    - pwittrock
    - yue9944882
    privacy: closed
  maintainers-application-images:
    description: contributors to the application-images repository
    maintainers:
    - calebamiles
    - zmerlynn
    members:
    - mattf
    privacy: closed
  maintainers-bootkube:
    description: ""
    members:
    - aaronlevy
    - derekparker
    - pbx0
    - philips
    privacy: closed
  maintainers-client-python:
    description: maintainers of the client-python project
    maintainers:
    - mbohlool
    members:
    - caesarxuchao
    - dims
    - lavalamp
    - sarahnovotny
    - yliaog
    privacy: closed
  maintainers-cluster-capacity:
    description: ""
    members:
    - aveshagarwal
    - hodovska
    - ingvagabund
    - sarahnovotny
    privacy: closed
  maintainers-cluster-proportional-autoscaler:
    description: contributors to the cluster-proportional-autoscaler repository
    maintainers:
    - calebamiles
    - MrHohn
    members:
    - philips
    privacy: closed
  maintainers-cluster-proportional-vertical-autoscaler:
    description: ""
    members:
    - dnardo
    - thockin
    privacy: closed
  maintainers-cri-containerd:
    description: maintainers of cri-containerd repo
    maintainers:
    - Random-Liu
    members:
    - abhi
    - dchen1107
    - mikebrow
    - sarahnovotny
    - yujuhong
    privacy: closed
  maintainers-external-dns:
    description: ""
    maintainers:
    - justinsb
    members:
    - chrislovecnm
    - hjacobs
    - ideahitme
    - iterion
    - kris-nova
    - linki
    - njuettner
    - Raffo
    - sarahnovotny
    privacy: closed
  maintainers-external-storage:
    description: maintainers of the external-storage project
    members:
    - childsb
    - humblec
    - ianchakeres
    - jsafrane
    - rootfs
    - sarahnovotny
    - sbezverk
    - tsmetana
    - wongma7
    privacy: closed
  maintainers-ip-masq-agent:
    description: ""
    members:
    - dnardo
    - mtaufen
    - thockin
    privacy: closed
  maintainers-kargo:
    description: ""
    maintainers:
    - ant31
    - calebamiles
    members:
    - bogdando
    - mattymo
    - rsmitty
    privacy: closed
  maintainers-kompose:
    description: Write access for kompose
    maintainers:
    - sebgoa
    members:
    - bgrant0607
    - cab105
    - cdrage
    - janetkuo
    - kadel
    - surajssd
    privacy: closed
  maintainers-kops:
    description: contributors to the kops repository
    maintainers:
    - calebamiles
    privacy: closed
  maintainers-kube-aws:
    description: maintainers for kube-aws
    maintainers:
    - calebamiles
    - colhom
    members:
    - mumoshu
    - pbx0
    - philips
    - redbaron
    privacy: closed
  maintainers-kube2consul:
    description: contributors to the kube2consul repository
    maintainers:
    - calebamiles
    - elg0nz
    members:
    - bgrant0607
    privacy: closed
  maintainers-metrics-server:
    description: ""
    members:
    - crassirostris
    - DirectXMan12
    - fgrzadkowski
    - kawych
    - loburm
    - ncdc
    - piosz
    - sttts
    - thockin
    - x13n
    privacy: closed
  maintainers-node-feature-discovery:
    description: Maintainers of the node-feature-discovery repo.
    maintainers:
    - balajismaniam
    members:
    - ConnorDoyle
    - davidopp
    - flyingcougar
    - marquiz
    - philips
    privacy: closed
  maintainers-reference-docs:
    description: maintainers of the reference-docs repo
    maintainers:
    - pwittrock
    members:
    - sarahnovotny
    - tengqm
    privacy: closed
  maintainers-rktlet:
    description: contributors to the rktlet repository
    maintainers:
    - calebamiles
    - euank
    - yifan-gu
    members:
    - dchen1107
    privacy: closed
  maintainers-service-catalog:
    description: maintainers of the service catalog project
    maintainers:
    - carolynvs
    - duglin
    - pmorie
    members:
    - arschles
    - bgrant0607
    - eriknelson
    - jberkhahn
    - jboyd01
    - jeremyrickard
    - jpeeler
    - kibbles-n-bytes
    - luksa
    - martinmaly
    - MHBauer
    - n3wscott
    - nilebox
    - service-catalog-jenkins
    - slack
    - staebler
    - vaikas-google
    privacy: closed
  maintainers-spartakus:
    description: People who maintain spartakus
    maintainers:
    - grodrigues3
    members:
    - aronchick
    - squat
    - thockin
    privacy: closed
  reviewers-cri-containerd:
    description: reviewers of cri-containerd repo
    maintainers:
    - Random-Liu
    members:
    - abhi
    - miaoyq
    - mikebrow
    - yanxuean
    privacy: closed
  temporary-admin-transfers:
    description: For transferring repos into incubator.
    members:
    - mbohlool
    - philips
    privacy: closed
