name: Kubernetes Clients
description: This organization hosts Kubernetes API client libraries.
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- akshaymankar
- arschles
- bgrant0607
- brejoc
- brendandburns
- caesarxuchao
- calebamiles
- codevulture
- dims
- dmyerscough
- drubin
- fabianvf
- grodrigues3
- iamneha
- idealhack
- irvifa
- ityuhui
- jonschoning
- justaugustus
- krabhishek8260
- lavalamp
- lwander
- mbohlool
- micw523
- MoShitrit
- nzoueidi
- oz123
- palnabarun
- pokoli
- rlenferink
- roycaihw
- sebgoa
- SEJeff
- skuda
- strigazi
- tg123
- tomplus
- webwurst
- yliaog
- yue9944882
teams:
  Reviewers:
    description: ""
    members:
    - arschles
    - krabhishek8260
    - lwander
    - mbohlool
    privacy: closed
  c-admins:
    description: Admin access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
  c-maintainers:
    description: Write access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
  csharp-admins:
    description: Admin access to csharp repo
    members:
    - brendandburns
    - krabhishek8260
    privacy: closed
  gen-admins:
    description: Admin access to gen repo
    members:
    - brendandburns
    - mbohlool
    - roycaihw
    privacy: closed
  go-admins:
    description: Admin access to go repo
    members:
    - brendandburns
    - roycaihw
    privacy: closed
  go-base-admins:
    description: Admin access to go-base repo
    members:
    - brendandburns
    - roycaihw
    privacy: closed
  haskell-admins:
    description: Admin access to haskell repo
    members:
    - brendandburns
    - mbohlool
    privacy: closed
  java-admins:
    description: Admin access to java repo
    members:
    - brendandburns
    - mbohlool
    - yue9944882
    privacy: closed
  javascript-admins:
    description: Admin access to javascript repo
    members:
    - brendandburns
    - mbohlool
    privacy: closed
  perl-admins:
    description: Admin access to perl repo
    members:
    - brendandburns
    - mbohlool
    - yue9944882
    privacy: closed
  perl-maintainers:
    description: Write access to perl repo
    members:
    - brendandburns
    - mbohlool
    - yue9944882
    privacy: closed
  python-admins:
    description: Admin access to python repo
    members:
    - brendandburns
    - mbohlool
    - roycaihw
    - yliaog
    privacy: closed
  python-base-admins:
    description: Admin access to python-base repo
    members:
    - brendandburns
    - mbohlool
    - roycaihw
    - yliaog
    privacy: closed
  ruby-admins:
    description: Admin access to ruby repo
    members:
    - brendandburns
    - mbohlool
    privacy: closed
