admins:
- cblecker
- jasonbraganza
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: This organization hosts Kubernetes API client libraries.
has_organization_projects: true
has_repository_projects: true
members:
- adriananeci
- akshaymankar
- ambiknai
- ameukam
- arahamad
- bgrant0607
- brendandburns
- carlossg
- cjihrig
- davidgamero
- dims
- dulek
- EmilienM
- fabianvf
- Hii-Arpit
- huntergregory
- idvoretskyi
- irvifa
- ityuhui
- jonschoning
- justaugustus
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- longwuyuan
- mjudeikis
- moshevayner
- mstruebing
- nnmin-aws
- Pradumnasaraf
- prateekgogia
- rlenferink
- roycaihw
- savitharaghunathan
- tg123
- tomplus
- vrutkovs
- webwurst
- ydFu
- yliaog
- yue9944882
- zqzten
members_can_create_repositories: false
name: Kubernetes Clients
teams:
  c-admins:
    description: Admin access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
    repos:
      c: admin
  c-maintainers:
    description: Write access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
    repos:
      c: write
  csharp-admins:
    description: Admin access to csharp repo
    members:
    - brendandburns
    - tg123
    privacy: closed
    repos:
      csharp: admin
  gen-admins:
    description: Admin access to gen repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    - yue9944882
    privacy: closed
    repos:
      gen: admin
  go-admins:
    description: Admin access to go repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
    repos:
      go: admin
  go-base-admins:
    description: Admin access to go-base repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
    repos:
      go-base: admin
  haskell-admins:
    description: Admin access to haskell repo
    members:
    - brendandburns
    privacy: closed
    repos:
      haskell: admin
  java-admins:
    description: Admin access to java repo
    members:
    - brendandburns
    - yliaog
    - yue9944882
    privacy: closed
    repos:
      java: admin
  javascript-admins:
    description: Admin access to javascript repo
    members:
    - brendandburns
    - cjihrig
    - mstruebing
    privacy: closed
    repos:
      javascript: admin
  perl-admins:
    description: Admin access to perl repo
    members:
    - brendandburns
    - yue9944882
    privacy: closed
    repos:
      perl: admin
  perl-maintainers:
    description: Write access to perl repo
    members:
    - brendandburns
    - yue9944882
    privacy: closed
    repos:
      perl: write
  python-admins:
    description: Admin access to python repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
    repos:
      python: admin
  python-base-admins:
    description: Admin access to python-base repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
    repos:
      python-base: admin
  ruby-admins:
    description: Admin access to ruby repo
    members:
    - brendandburns
    privacy: closed
    repos:
      ruby: admin
