admins:
- ameukam
- cblecker
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- palnabarun
- thelinuxfoundation
billing_email: github@kubernetes.io
default_repository_permission: read
description: This organization hosts Kubernetes API client libraries.
has_organization_projects: true
has_repository_projects: true
members:
- akshaymankar
- alberthuang24
- ambiknai
- arahamad
- Arhell
- bgrant0607
- brendandburns
- caesarxuchao
- calebamiles
- dims
- drubin
- fabianvf
- fejta
- fengshunli
- grodrigues3
- iamneha
- idealhack
- irvifa
- ityuhui
- jlsong01
- jonschoning
- justaugustus
- k8s-infra-cherrypick-robot
- k8s-infra-ci-robot
- krabhishek8260
- lavalamp
- longwuyuan
- micw523
- moshevayner
- nnmin-aws
- nzoueidi
- oz123
- rlenferink
- roycaihw
- savitharaghunathan
- sebgoa
- SEJeff
- simrangupta234
- spiffxp
- strigazi
- tg123
- tomplus
- webwurst
- yliaog
- yue9944882
- zqzten
members_can_create_repositories: false
name: Kubernetes Clients
teams:
  Reviewers:
    description: ""
    members:
    - krabhishek8260
    privacy: closed
  c-admins:
    description: Admin access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
  c-maintainers:
    description: Write access to the c repo
    members:
    - brendandburns
    - ityuhui
    privacy: closed
  csharp-admins:
    description: Admin access to csharp repo
    members:
    - brendandburns
    - tg123
    privacy: closed
  gen-admins:
    description: Admin access to gen repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    - yue9944882
    privacy: closed
  go-admins:
    description: Admin access to go repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
  go-base-admins:
    description: Admin access to go-base repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
  haskell-admins:
    description: Admin access to haskell repo
    members:
    - brendandburns
    privacy: closed
  java-admins:
    description: Admin access to java repo
    members:
    - brendandburns
    - yliaog
    - yue9944882
    privacy: closed
  javascript-admins:
    description: Admin access to javascript repo
    members:
    - brendandburns
    privacy: closed
  perl-admins:
    description: Admin access to perl repo
    members:
    - brendandburns
    - yue9944882
    privacy: closed
  perl-maintainers:
    description: Write access to perl repo
    members:
    - brendandburns
    - yue9944882
    privacy: closed
  python-admins:
    description: Admin access to python repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
  python-base-admins:
    description: Admin access to python-base repo
    members:
    - brendandburns
    - roycaihw
    - yliaog
    privacy: closed
  ruby-admins:
    description: Admin access to ruby repo
    members:
    - brendandburns
    privacy: closed
