teams:
  apiserver-network-proxy-admins:
    description: admin access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - cheftako
    - mcrute
    privacy: closed
  apiserver-network-proxy-maintainers:
    description: write access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - cheftako
    - mcrute
    privacy: closed
  alibaba-cloud-csi-driver-admins:
   description: Admin access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - xianlubird
   privacy: closed
  alibaba-cloud-csi-driver-maintainers:
   description: Write access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - xianlubird
   privacy: closed
  aws-iam-authenticator-admins:
   description: Admin access to the aws-iam-authenticator repo
   members:
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
  aws-iam-authenticator-maintainers:
   description: Write access to the aws-iam-authenticator repo
   members:
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
  blobfuse-csi-driver-admins:
   description: Admin access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - brendandburns
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
  blobfuse-csi-driver-maintainers:
   description: Write access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - brendandburns
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
