teams:
  apiserver-network-proxy-admins:
    description: admin access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - cheftako
    - jkh52
    - nckturner
    privacy: closed
  apiserver-network-proxy-maintainers:
    description: write access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - cheftako
    - jkh52
    privacy: closed
  alibaba-cloud-csi-driver-admins:
   description: Admin access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - JiaoDean
   - xianlubird
   privacy: closed
  alibaba-cloud-csi-driver-maintainers:
   description: Write access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - JiaoDean
   - xianlubird
   privacy: closed
  aws-file-cache-csi-driver-admins:
    description: Admin access to the aws-file-cache-csi-driver repo
    members:
      - jacobwolfaws
      - khoang98
      - nckturner
    privacy: closed
  aws-file-cache-csi-driver-maintainers:
    description: Write access to the aws-file-cache-csi-driver repo
    members:
      - jacobwolfaws
      - khoang98
      - nckturner
    privacy: closed
  aws-fsx-openzfs-csi-driver-admins:
    description: Admin access to the aws-fsx-openzfs-csi-driver repo
    members:
      - jacobwolfaws
      - nckturner
    privacy: closed
  aws-fsx-openzfs-csi-driver-maintainers:
    description: Write access to the aws-fsx-openzfs-csi-driver repo
    members:
      - jacobwolfaws
      - nckturner
    privacy: closed
  aws-iam-authenticator-admins:
   description: Admin access to the aws-iam-authenticator repo
   members:
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
  aws-iam-authenticator-maintainers:
   description: Write access to the aws-iam-authenticator repo
   members:
   - jyotimahapatra
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
  blobfuse-csi-driver-admins:
   description: Admin access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
  blobfuse-csi-driver-maintainers:
   description: Write access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
  cloud-provider-baiducloud-admins:
   description: Admin access to the cloud-provider-baiducloud repo
   members:
   - hello2mao
   - tizhou86
   - ZP-AlwaysWin
   privacy: closed
  cloud-provider-baiducloud-maintainers:
   description: Write access to the cloud-provider-baiducloud repo
   members:
   - hello2mao
   - tizhou86
   - ZP-AlwaysWin
   privacy: closed
  cloud-provider-huaweicloud-admins:
   description: Admin access to the cloud-provider-huaweicloud repo
   members:
   - chengxiangdong
   - kevin-wangzefeng
   - niuzhenguo
   - RainbowMango
   privacy: closed
  cloud-provider-huaweicloud-maintainers:
   description: Write access to the cloud-provider-huaweicloud repo
   members:
   - chengxiangdong
   - kevin-wangzefeng
   - niuzhenguo
   - RainbowMango
   privacy: closed
  ibm-powervs-block-csi-driver-admins:
    description: Admin access to the ibm-powervs-block-csi-driver
    members:
    - mkumatag
    privacy: closed
  ibm-powervs-block-csi-driver-maintainers:
    description: Write access to the ibm-powervs-block-csi-driver
    members:
    - mkumatag
    privacy: closed
  provider-aws-test-infra-admins:
   description: Admin access to the provider-aws-test-infra repo
   members:
   - nckturner
   - wongma7
   privacy: closed
