teams:
  mcs-api-admins:
    description: Admin access to the mcs-api repo
    members:
    - JeremyOT
    - pmorie
    privacy: closed
  service-catalog-admins:
    description: Admin access to the service-catalog repo
    members:
    - jberkhahn
    - mszostok
    privacy: closed
  service-catalog-maintainers:
    description: Write access to the service-catalog repo
    members:
    - carolynvs
    - jberkhahn
    - jhvhs
    - mhbauer
    - mszostok
    - piotrmiskiewicz
    privacy: closed
  minibroker-admins:
    description: Admin access to the minibroker repo
    members:
    - carolynvs
    - f0rmiga
    privacy: closed
