teams:
  service-catalog-admins:
    description: Admin access to the service-catalog repo
    members:
    - jberkhahn
    - jhvhs
    privacy: closed
  service-catalog-maintainers:
    description: Write access to the service-catalog repo
    members:
    - carolynvs
    - jberkhahn
    - jhvhs
    - mhbauer
    - piotrmiskiewicz
    privacy: closed
  minibroker-admins:
    description: Admin access to the minibroker repo
    members:
    - carolynvs
    - f0rmiga
    privacy: closed
