teams:
  ingress-gce-admins:
    description: Admin access to the ingress-gce repo
    members:
    - aojea
    - bowei
    - thockin
    privacy: closed
    repos:
      ingress-gce: admin
  ingress-gce-maintainers:
    description: Write access to the ingress-gce repo
    members:
    - aojea
    - bowei
    - DamianSawicki
    - kl52752
    - mmamczur
    - MrHohn
    - swetharepakula
    - thockin
    - TortillaZHawaii
    privacy: closed
    repos:
      ingress-gce: write
  sig-network-api-reviews:
    description: ""
    members:
    - caseydavenport
    - shaneutt
    - thockin
    privacy: closed
  sig-network-bugs:
    description: ""
    members:
    - caseydavenport
    - shaneutt
    - thockin
    privacy: closed
  sig-network-feature-requests:
    description: ""
    members:
    - caseydavenport
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-misc:
    description: Network SIG
    members:
    - aanm
    - bowei
    - caseydavenport
    - danwinship
    - feiskyer
    - MrHohn
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-pr-reviews:
    description: ""
    members:
    - bowei
    - caseydavenport
    - feiskyer
    - shaneutt
    - thockin
    privacy: closed
  sig-network-proposals:
    description: ""
    members:
    - caseydavenport
    - feiskyer
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-test-failures:
    description: ""
    members:
    - caseydavenport
    - shaneutt
    - thockin
    privacy: closed
  sig-network-leads:
    description: ""
    members:
    - aojea
    - danwinship
    - MikeZappa87
    - shaneutt
    - thockin
    privacy: closed
