teams:
  sig-network-api-reviews:
    description: ""
    members:
    - caseydavenport
    - davidopp
    - shaneutt
    - thockin
    privacy: closed
  sig-network-bugs:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - shaneutt
    - thockin
    privacy: closed
  sig-network-feature-requests:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - davidopp
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-misc:
    description: Network SIG
    members:
    - aanm
    - bowei
    - caseydavenport
    - danwinship
    - davidopp
    - dcbw
    - eparis
    - feiskyer
    - freehan
    - jeremyeder
    - MrHohn
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-pr-reviews:
    description: ""
    members:
    - bowei
    - caseydavenport
    - cmluciano
    - dcbw
    - feiskyer
    - shaneutt
    - thockin
    privacy: closed
  sig-network-proposals:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - davidopp
    - dcbw
    - feiskyer
    - shaneutt
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-test-failures:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - shaneutt
    - thockin
    privacy: closed
  sig-network-leads:
    description: ""
    members:
    - dcbw
    - shaneutt
    - thockin
    privacy: closed
