teams:
  sig-network-api-reviews:
    description: ""
    members:
    - caseydavenport
    - davidopp
    - thockin
    privacy: closed
  sig-network-bugs:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - thockin
    privacy: closed
  sig-network-feature-requests:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - davidopp
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-misc:
    description: Network SIG
    maintainers:
    - dcbw
    members:
    - aanm
    - bowei
    - bprashanth
    - caseydavenport
    - danwinship
    - davidopp
    - dnardo
    - eghobo
    - eparis
    - feiskyer
    - freehan
    - gsasha
    - jeremyeder
    - MrHohn
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-pr-reviews:
    description: ""
    members:
    - bowei
    - caseydavenport
    - cmluciano
    - dcbw
    - feiskyer
    - m1093782566
    - thockin
    privacy: closed
  sig-network-proposals:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - davidopp
    - dcbw
    - feiskyer
    - smarterclayton
    - thockin
    privacy: closed
  sig-network-test-failures:
    description: ""
    members:
    - caseydavenport
    - cmluciano
    - thockin
    privacy: closed
