teams:
  discuss-theme-admins:
    description: admin access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
    repos:
      discuss-theme: admin
  discuss-theme-maintainers:
    description: write access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
    repos:
      discuss-theme: write
  lwkd-admins:
    description: admin access to the lwkd repo
    members:
    - coderanger
    - jberkus
    - mfahlandt
    - sreeram-venkitesh
    - Hii-Arpit
    privacy: closed
    repos:
      lwkd: admin
  lwkd-maintainers:
    description: write access to the lwkd repo
    members:
    - coderanger
    - jberkus
    privacy: closed
    repos:
      lwkd: write
  maintainers-admins:
    description: admin access to the maintainers repo
    maintainers:
    - nikhita
    members:
    - dims
    privacy: closed
    repos:
      maintainers: admin
  maintainers-maintainers:
    description: write access to the maintainers repo
    maintainers:
    - MadhavJivrajani
    - mrbobbytables
    - nikhita
    - palnabarun
    members:
    - dims
    privacy: closed
    repos:
      maintainers: write
  sig-contributor-experience:
    description: Improve contributor productivity
    maintainers:
    - cblecker
    - MadhavJivrajani
    - mrbobbytables
    - nikhita
    - palnabarun
    - Priyankasaggu11929
    members:
    - castrojo
    - dims
    - idvoretskyi
    - kaslin
    - mfahlandt
    - parispittman
    - pwittrock
    - thockin
    privacy: closed
    teams:
      sig-contributor-experience-leads:
        description: Chairs and Technical Leads for SIG Contributor Experience
        maintainers:
        - MadhavJivrajani
        - palnabarun
        - Priyankasaggu11929
        members:
        - kaslin
        - mfahlandt
        privacy: closed
      sig-contributor-experience-pr-reviews:
        description: PR reviews for contributor-experience infrastructure, such as the
          PR bot, etc.
        maintainers:
        - MadhavJivrajani
        - palnabarun
        - Priyankasaggu11929
        members:
        - kaslin
        - mfahlandt
        privacy: closed
  slack-infra-admins:
    description: admin access to slack-infra
    members:
    - jeefy
    - Katharine
    privacy: closed
    repos:
      slack-infra: admin
