teams:
  sig-testing:
    description: sig-testing
    maintainers:
    - cblecker
    members:
    - akutz
    - BenTheElder
    - bowei
    - chases2
    - cjwagner
    - clarketm
    - fejta
    - ixdy
    - jayunit100
    - jdef
    - justaugustus
    - justinsb
    - Katharine
    - marun
    - michelle192837
    - mkumatag
    - pigmej
    - stevekuznetsov
    - timothysc
    - xiangpengzhao
    - xmcqueen
    privacy: closed
    teams:
      sig-testing-leads:
        description: sig-testing chairs and technical leads
        members:
        - aojea
        - BenTheElder
        - michelle192837
        - pohly
        - stevekuznetsov
        - xmcqueen
        privacy: closed
      sig-testing-pr-reviews:
        description: sig-testing PR reviews
        members:
        - akutz
        - amwat
        - BenTheElder
        - chases2
        - cjwagner
        - clarketm
        - fejta
        - ixdy
        - Katharine
        - krzyzacy
        - michelle192837
        - mkumatag
        - stevekuznetsov
        - xmcqueen
        privacy: closed
  test-infra-admins:
    description: admin access to test-infra
    members:
    - BenTheElder
    - chaodaiG
    - chases2
    - cjwagner
    - fejta
    - k8s-infra-ci-robot
    - listx
    - michelle192837
    - mpherman2
    - spiffxp
    - stevekuznetsov
    - sultan-duisenbay
    privacy: closed
  test-infra-maintainers:
    description: write access to test-infra
    members:
    - amwat
    - BenTheElder
    - cjwagner
    - fejta
    - ixdy
    - krzyzacy
    - michelle192837
    - spiffxp
    - stevekuznetsov
    privacy: closed
  sig-testing-dummy-project-team:
    description: dummy team to test prow project plugin; no acl
    members:
    - taragu
    privacy: closed
