teams:
  sig-testing:
    description: sig-testing
    maintainers:
    - cblecker
    - fejta
    - spiffxp
    members:
    - akutz
    - BenTheElder
    - bowei
    - chases2
    - cjwagner
    - clarketm
    - ixdy
    - jayunit100
    - jdef
    - justaugustus
    - justinsb
    - Katharine
    - marun
    - michelle192837
    - mkumatag
    - pigmej
    - stevekuznetsov
    - timothysc
    - xiangpengzhao
    privacy: closed
    teams:
      sig-testing-leads:
        description: sig-testing chairs and technical leads
        maintainers:
        - spiffxp
        members:
        - BenTheElder
        - stevekuznetsov
        privacy: closed
      sig-testing-pr-reviews:
        description: sig-testing PR reviews
        maintainers:
        - fejta
        - spiffxp
        members:
        - akutz
        - amwat
        - BenTheElder
        - chases2
        - cjwagner
        - clarketm
        - ixdy
        - Katharine
        - krzyzacy
        - michelle192837
        - mkumatag
        - stevekuznetsov
        privacy: closed
  test-infra-admins:
    description: admin access to test-infra
    maintainers:
    - fejta
    - spiffxp
    members:
    - BenTheElder
    - chaodaiG
    - chases2
    - cjwagner
    - e-blackwelder
    - listx
    - michelle192837
    - mpherman2
    - stevekuznetsov
    privacy: closed
  test-infra-maintainers:
    description: write access to test-infra
    maintainers:
    - fejta
    - spiffxp
    members:
    - amwat
    - BenTheElder
    - cjwagner
    - ixdy
    - krzyzacy
    - michelle192837
    - stevekuznetsov
    privacy: closed
  sig-testing-dummy-project-team:
    description: dummy team to test prow project plugin; no acl
    members:
    - taragu
    privacy: closed
