teams:
  sig-testing:
    description: sig-testing
    maintainers:
    - cblecker
    members:
    - akutz
    - BenTheElder
    - bowei
    - chases2
    - cjwagner
    - clarketm
    - fejta
    - ixdy
    - jayunit100
    - jbpratt
    - jdef
    - justaugustus
    - justinsb
    - Katharine
    - marun
    - michelle192837
    - mkumatag
    - pigmej
    - stevekuznetsov
    - timothysc
    - xiangpengzhao
    - xmcqueen
    privacy: closed
    teams:
      sig-testing-leads:
        description: sig-testing chairs and technical leads
        members:
        - aojea
        - BenTheElder
        - cjwagner
        - jbpratt
        - michelle192837
        - pohly
        - xmcqueen
        privacy: closed
        repos:
          sig-testing: admin
      sig-testing-pr-reviews:
        description: sig-testing PR reviews
        members:
        - akutz
        - BenTheElder
        - chases2
        - cjwagner
        - clarketm
        - fejta
        - ixdy
        - Katharine
        - krzyzacy
        - michelle192837
        - mkumatag
        - stevekuznetsov
        - xmcqueen
        privacy: closed
  test-infra-admins:
    description: admin access to test-infra
    members:
    - alvaroaleman
    - ameukam    # k8s-infra-oncall
    - aojea
    - BenTheElder
    - chaodaiG   # test-infra-oncall
    - chases2    # test-infra-oncall
    - cjwagner
    - dims       # k8s-infra-oncall
    - k8s-infra-ci-robot
    - michelle192837
    - mpherman2  # test-infra-oncall
    - pohly
    - stevekuznetsov
    - thockin    # k8s-infra-oncall
    - upodroid    # k8s-infra-oncall
    privacy: closed
    repos:
      publishing-bot: admin
      test-infra: admin
  test-infra-maintainers:
    description: write access to test-infra
    members:
    - alvaroaleman
    - aojea
    - BenTheElder
    - cjwagner
    - k8s-infra-ci-robot
    - michelle192837
    - pohly
    - stevekuznetsov
    privacy: closed
    repos:
      publishing-bot: write
      test-infra: write
  sig-testing-dummy-project-team:
    description: dummy team to test prow project plugin; no acl
    members:
    - taragu
    privacy: closed
