teams:
  sig-testing:
    description: sig-testing
    maintainers:
    - cblecker
    - fejta
    - spiffxp
    members:
    - akutz
    - BenTheElder
    - bowei
    - chases2
    - cjwagner
    - clarketm
    - ixdy
    - jayunit100
    - jdef
    - justaugustus
    - justinsb
    - Katharine
    - marun
    - michelle192837
    - mithrav
    - mkumatag
    - pigmej
    - pskrzyns
    - stevekuznetsov
    - timothysc
    - xiangpengzhao
    privacy: closed
  sig-testing-pr-reviews:
    description: sig-testing PR reviews
    maintainers:
    - fejta
    - spiffxp
    members:
    - akutz
    - amwat
    - BenTheElder
    - chases2
    - cjwagner
    - clarketm
    - ixdy
    - Katharine
    - krzyzacy
    - michelle192837
    - mithrav
    - mkumatag
    - stevekuznetsov
    privacy: closed
  test-infra-admins:
    description: admin access to test-infra
    maintainers:
    - fejta
    - spiffxp
    members:
    - BenTheElder
    - chaodaiG
    - chases2
    - cjwagner
    - Katharine
    - michelle192837
    - stevekuznetsov
    privacy: closed
  test-infra-maintainers:
    description: write access to test-infra
    maintainers:
    - fejta
    - spiffxp
    members:
    - amwat
    - BenTheElder
    - cjwagner
    - ixdy
    - Katharine
    - krzyzacy
    - michelle192837
    - stevekuznetsov
    privacy: closed
  sig-testing-dummy-project-team:
    description: dummy team to test prow project plugin; no acl
    members:
    - taragu
    privacy: closed
  repo-infra-admins:
    description: Admin access to the repo-infra repo
    maintainers:
    - fejta
    members:
    - BenTheElder
    - clarketm
    - justaugustus
    - mikedanese
    privacy: closed
  repo-infra-maintainers:
    description: Write access to the repo-infra repo
    maintainers:
    - fejta
    members:
    - BenTheElder
    - clarketm
    - justaugustus
    - mikedanese
    privacy: closed
