teams:
  cluster-addons-admins:
    description: admin access to cluster-addons
    members:
    - justinsb
    - luxas
    privacy: closed
    previously:
    - addon-operators-admins
    repos:
      cluster-addons: admin
  cluster-addons-maintainers:
    description: write access to cluster-addons
    members:
    - justinsb
    - stealthybox
    privacy: closed
    previously:
    - addon-operators-maintainers
    repos:
      cluster-addons: write
  cluster-api-addon-provider-helm-admins:
    description:  Admin access to cluster-api-addon-provider-helm repo
    members:
    - fabriziopandini
    - jackfrancis
    - Jont828
    - mboersma
    privacy: closed
    repos:
      cluster-api-addon-provider-helm: admin
  cluster-api-addon-provider-helm-maintainers:
    description: Write access to cluster-api-addon-provider-helm repo
    members:
    - fabriziopandini
    - jackfrancis
    - Jont828
    - mboersma
    privacy: closed
    repos:
      cluster-api-addon-provider-helm: write
  cluster-api-admins:
    description: ""
    members:
    - fabriziopandini
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      cluster-api: admin
  cluster-api-maintainers:
    description: ""
    members:
    - chrischdi
    - enxebre
    - fabriziopandini
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      cluster-api: write
  cluster-api-ipam-provider-in-cluster-admins:
    description: "admin access to cluster-api-ipam-provider-in-cluster"
    members:
    - fabriziopandini
    - schrej
    privacy: closed
    repos:
      cluster-api-ipam-provider-in-cluster: admin
  cluster-api-ipam-provider-in-cluster-maintainers:
    description: "write access to cluster-api-ipam-provider-in-cluster"
    members:
    - mcbenjemaa
    privacy: closed
    repos:
      cluster-api-ipam-provider-in-cluster: write
  cluster-api-operator-admins:
    description: "admin access to cluster-api-operator"
    members:
    - alexander-demicev
    - damdo
    - Danil-Grigorev
    - Fedosin
    - furkatgofurov7
    - JoelSpeed
    privacy: closed
    repos:
      cluster-api-operator: admin
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-aws: admin
  cluster-api-provider-aws-maintainers:
    description: maintain access to cluster-api-provider-aws
    members:
    - AndiDog
    - damdo
    - dlipovetsky
    - nrb
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-aws: maintain
  cluster-api-provider-aws-release-team:
    description: write access to cluster-api-provider-aws. maintainers are implied members of release team.
    members:
    - damdo
    privacy: closed
    repos:
      cluster-api-provider-aws: write
  cluster-api-provider-azure-admins:
    description: ""
    members:
    - jackfrancis
    - Jont828
    - mboersma
    - nawazkh
    - nojnhuh
    - willie-yao
    privacy: closed
    repos:
      cluster-api-provider-azure: admin
  cluster-api-provider-azure-maintainers:
    description: ""
    members:
    - jackfrancis
    - Jont828
    - mboersma
    - nawazkh
    - nojnhuh
    - willie-yao
    privacy: closed
    repos:
      cluster-api-provider-azure: write
  cluster-api-provider-azure-pms:
    description: ""
    members:
    - devigned
    - dtzar
    - jackfrancis
    - Jont828
    - jsturtevant
    - marosset
    - mboersma
    - nawazkh
    - nojnhuh
    - willie-yao
    privacy: closed
    repos:
      cluster-api-provider-azure: triage
  cluster-api-provider-cloudstack-admins:
    description: ""
    members:
    - davidjumani
    - dims
    - g-gaston
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-admins
    repos:
      cluster-api-provider-cloudstack: admin
  cluster-api-provider-cloudstack-maintainers:
    description: ""
    members:
    - davidjumani
    - dims
    - g-gaston
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-maintainers
    repos:
      cluster-api-provider-cloudstack: write
  cluster-api-provider-digitalocean-admins:
    description: Admin access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - gottwald
    - luxas
    - timoreimann
    privacy: closed
    repos:
      cluster-api-provider-digitalocean: admin
  cluster-api-provider-digitalocean-maintainers:
    description: Write access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - gottwald
    - MorrisLaw
    - timoreimann
    privacy: closed
    repos:
      cluster-api-provider-digitalocean: write
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - cpanato
    - dims
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-gcp: admin
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - cpanato
    - damdo
    - dims
    - richardcase
    - salasberryfin
    privacy: closed
    repos:
      cluster-api-provider-gcp: write
  cluster-api-provider-kubemark-admins:
    description: admin access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    - justinsb
    - neolit123
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-kubemark: admin
  cluster-api-provider-kubemark-maintainers:
    description: write access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    privacy: closed
    repos:
      cluster-api-provider-kubemark: write
  cluster-api-provider-kubevirt-admins:
    description: admin access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - davidvossel
    - justinsb
    - neolit123
    - nunnatsa
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-kubevirt: admin
  cluster-api-provider-kubevirt-maintainers:
    description: write access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - davidvossel
    - nunnatsa
    privacy: closed
    repos:
      cluster-api-provider-kubevirt: write
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - EmilienM
    - lentzi90
    privacy: closed
    repos:
      cluster-api-provider-openstack: admin
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - EmilienM
    - lentzi90
    privacy: closed
    repos:
      cluster-api-provider-openstack: write
  cluster-api-provider-vsphere-admins:
    description: Admin access to the cluster-api-provider-vsphere repo
    members:
    - chrischdi
    - fabriziopandini
    - gab-satchi
    - randomvariable
    - sbueringer
    - srm09
    - yastij
    privacy: closed
    repos:
      cluster-api-provider-vsphere: admin
  cluster-api-provider-vsphere-maintainers:
    description: Write access to the cluster-api-provider-vsphere repo
    members:
    - chrischdi
    - fabriziopandini
    - gab-satchi
    - randomvariable
    - sbueringer
    - srm09
    - yastij
    privacy: closed
    repos:
      cluster-api-provider-vsphere: write
  cluster-api-release-team:
    description: Release team of Cluster API
    members:
    - adilGhaffarDev
    - chandankumar4
    - chiukapoor
    - cprivitere
    - hackeramitkumar
    - mboersma
    - shecodesmagic
    - tsuzu
    privacy: closed
  image-builder-admins:
    description: admin access to image-builder
    members:
    - AverageMarcus
    - drew-viles
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
    repos:
      image-builder: admin
  image-builder-maintainers:
    description: write access to image-builder
    members:
    - AverageMarcus
    - drew-viles
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
    repos:
      image-builder: write
  karpenter-provider-cluster-api-admins:
    description: Admin access to the karpenter-provider-cluster-api repo
    members:
    - elmiko
    - fabriziopandini
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      karpenter-provider-cluster-api: admin
  karpenter-provider-cluster-api-maintainers:
    description: Write access to the karpenter-provider-cluster-api repo
    members:
    - chrischdi
    - elmiko
    - enxebre
    - fabriziopandini
    - mtulio
    - sbueringer
    - vincepri
    - vrabbi
    privacy: closed
    repos:
      karpenter-provider-cluster-api: write
  kubespray-admins:
    description: Admin access to the kubespray repo
    members:
    - ant31
    - chadswen
    - floryut
    privacy: closed
    repos:
      kubespray: admin
  kubespray-maintainers:
    description: Write access to the kubespray repo
    members:
    - ant31
    - chadswen
    - floryut
    - mzaian
    - oomichi
    - tico88612
    - VannTen
    - yankay
    privacy: closed
    repos:
      kubespray: write
  logical-cluster-admins:
    description: Admin access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
    repos:
      logical-cluster: admin
  logical-cluster-maintainers:
    description: Write access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
    repos:
      logical-cluster: write
  minikube-gui-admins:
    description: Admin access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
    repos:
      minikube-gui: admin
  minikube-gui-maintainers:
    description: Write access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
    repos:
      minikube-gui: write
  minikube-os-admins:
    description: Admin access to the minikube-os repo
    members:
    - medyagh
    privacy: closed
    repos:
      minikube-os: admin
  minikube-os-maintainers:
    description: Write access to the minikube-os repo
    members:
    - medyagh
    privacy: closed
    repos:
      minikube-os: write
  minikube-preloads-admins:
    description: Admin access to the minikube-preloads repo
    members:
    - medyagh
    privacy: closed
    repos:
      minikube-preloads: admin
  minikube-preloads-maintainers:
    description: Write access to the minikube-preloads repo
    members:
    - medyagh
    privacy: closed
    repos:
      minikube-preloads: write
