teams:
  cluster-addons-admins:
    description: admin access to cluster-addons
    members:
    - justinsb
    - luxas
    - roberthbailey
    - timothysc
    privacy: closed
    previously:
    - addon-operators-admins
  cluster-addons-maintainers:
    description: write access to cluster-addons
    members:
    - dholbach
    - justinsb
    - stealthybox
    privacy: closed
    previously:
    - addon-operators-maintainers
  cluster-api-admins:
    description: ""
    members:
    - CecileRobertMichon
    - vincepri
    privacy: closed
  cluster-api-maintainers:
    description: ""
    members:
    - CecileRobertMichon
    - fabriziopandini
    - vincepri
    privacy: closed
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - detiber
    - justinsb
    - luxas
    - randomvariable
    - richardcase
    - sedefsavas
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-aws-maintainers:
    description: write access to cluster-api-provider-aws
    members:
    - chuckha
    - davidewatson
    - detiber
    - ingvagabund
    - randomvariable
    - richardcase
    - sedefsavas
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-azure-admins:
    description: ""
    members:
    - alexeldeib
    - CecileRobertMichon
    - devigned
    - nader-ziada
    privacy: closed
  cluster-api-provider-azure-maintainers:
    description: ""
    members:
    - alexeldeib
    - CecileRobertMichon
    - devigned
    - nader-ziada
    privacy: closed
  cluster-api-provider-azure-pms:
    description: ""
    members:
    - alexeldeib
    - CecileRobertMichon
    - cpanato
    - devigned
    - juan-lee
    - mboersma
    - nader-ziada
    - shysank
    privacy: closed
  cluster-api-provider-digitalocean-admins:
    description: Admin access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - luxas
    - roberthbailey
    - timoreimann
    - timothysc
    privacy: closed
  cluster-api-provider-digitalocean-maintainers:
    description: Write access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - MorrisLaw
    - prksu
    - timoreimann
    - timothysc
    privacy: closed
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - cpanato
    - justinsb
    - luxas
    - roberthbailey
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - cpanato
    - detiber
    - justinsb
    - krousey
    - vincepri
    privacy: closed
  cluster-api-provider-kubemark-admins:
    description: admin access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-kubemark-maintainers:
    description: write access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    privacy: closed
  cluster-api-provider-kubevirt-admins:
    description: admin access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-kubevirt-maintainers:
    description: write access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    privacy: closed
  cluster-api-provider-nested-admins:
    description: admin access to cluster-api-provider-nested
    members:
    - christopherhein
    - fabriziopandini
    - Fei-Guo
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-nested-maintainers:
    description: write access to cluster-api-provider-nested
    members:
    - christopherhein
    - Fei-Guo
    - resouer
    - zhuangqh
    privacy: closed
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - dims
    - luxas
    - roberthbailey
    - sbueringer
    - timothysc
    privacy: closed
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - chrigl
    - dims
    - jichenjc
    - sbueringer
    privacy: closed
  cluster-api-provider-packet-admins:
    description: Admin access to cluster-api-provider-packet repo
    members:
    - deitch
    - detiber
    - mrmrcoleman
    - thebsdbox
    privacy: closed
  cluster-api-provider-packet-maintainers:
    description: Write access to the cluster-api-provider-packet repo
    members:
    - deitch
    - detiber
    - gianarb
    - jacobsmith928
    - mrmrcoleman
    - thebsdbox
    privacy: closed
  cluster-api-provider-vsphere-admins:
    description: Admin access to the cluster-api-provider-vsphere repo
    members:
    - akutz
    - andrewsykim
    - frapposelli
    - yastij
    privacy: closed
  cluster-api-provider-vsphere-maintainers:
    description: Write access to the cluster-api-provider-vsphere repo
    members:
    - akutz
    - andrewsykim
    - detiber
    - figo
    - frapposelli
    - randomvariable
    - sidharthsurana
    - vincepri
    - yastij
    privacy: closed
  etcdadm-admins:
    description: Admin access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  etcdadm-maintainers:
    description: Write access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
  image-builder-admins:
    description: admin access to image-builder
    members:
    - codenrhoden
    - justinsb
    - luxas
    - timothysc
    privacy: closed
  image-builder-maintainers:
    description: write access to image-builder
    members:
    - codenrhoden
    - justinsb
    - luxas
    - moshloop
    - timothysc
    privacy: closed
  kubespray-admins:
    description: Admin access to the kubespray repo
    members:
    - ant31
    - chadswen
    - mattymo
    privacy: closed
  kubespray-maintainers:
    description: Write access to the kubespray repo
    members:
    - ant31
    - Atoms
    - chadswen
    - floryut
    - mattymo
    - miouge1
    - mirwan
    - riverzhang
    - woopstar
    privacy: closed
