teams:
  cluster-addons-admins:
    description: admin access to cluster-addons
    members:
    - justinsb
    - luxas
    - timothysc
    privacy: closed
    previously:
    - addon-operators-admins
    repos:
      cluster-addons: admin
  cluster-addons-maintainers:
    description: write access to cluster-addons
    members:
    - justinsb
    - stealthybox
    privacy: closed
    previously:
    - addon-operators-maintainers
    repos:
      cluster-addons: write
  cluster-api-addon-provider-helm-admins:
    description:  Admin access to cluster-api-addon-provider-helm repo
    members:
    - fabriziopandini
    - jackfrancis
    - Jont828
    - mboersma
    privacy: closed
    repos:
      cluster-api-addon-provider-helm: admin
  cluster-api-addon-provider-helm-maintainers:
    description: Write access to cluster-api-addon-provider-helm repo
    members:
    - fabriziopandini
    - jackfrancis
    - Jont828
    - mboersma
    privacy: closed
    repos:
      cluster-api-addon-provider-helm: write
  cluster-api-admins:
    description: ""
    members:
    - fabriziopandini
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      cluster-api: admin
  cluster-api-maintainers:
    description: ""
    members:
    - chrischdi
    - enxebre
    - fabriziopandini
    - killianmuldoon
    - sbueringer
    - vincepri
    privacy: closed
    repos:
      cluster-api: write
  cluster-api-ipam-provider-in-cluster-admins:
    description: "admin access to cluster-api-ipam-provider-in-cluster"
    members:
    - fabriziopandini
    - schrej
    privacy: closed
    repos:
      cluster-api-ipam-provider-in-cluster: admin
  cluster-api-operator-admins:
    description: "admin access to cluster-api-operator"
    members:
    - alexander-demicev
    - damdo
    - Danil-Grigorev
    - Fedosin
    - JoelSpeed
    privacy: closed
    repos:
      cluster-api-operator: admin
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-aws: admin
  cluster-api-provider-aws-maintainers:
    description: maintain access to cluster-api-provider-aws
    members:
    - Ankitasw
    - dlipovetsky
    - richardcase
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-aws: maintain
  cluster-api-provider-aws-release-team:
    description: write access to cluster-api-provider-aws. maintainers are implied members of release team.
    members:
    - damdo
    - nrb
    privacy: closed
    repos:
      cluster-api-provider-aws: write
  cluster-api-provider-azure-admins:
    description: ""
    members:
    - jackfrancis
    - mboersma
    - nojnhuh
    privacy: closed
    repos:
      cluster-api-provider-azure: admin
  cluster-api-provider-azure-maintainers:
    description: ""
    members:
    - jackfrancis
    - mboersma
    - nojnhuh
    privacy: closed
    repos:
      cluster-api-provider-azure: write
  cluster-api-provider-azure-pms:
    description: ""
    members:
    - devigned
    - dtzar
    - jackfrancis
    - Jont828
    - jsturtevant
    - marosset
    - mboersma
    - nawazkh
    - nojnhuh
    - willie-yao
    privacy: closed
    repos:
      cluster-api-provider-azure: triage
  cluster-api-provider-cloudstack-admins:
    description: ""
    members:
    - davidjumani
    - dims
    - g-gaston
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-admins
    repos:
      cluster-api-provider-cloudstack: admin
  cluster-api-provider-cloudstack-maintainers:
    description: ""
    members:
    - davidjumani
    - dims
    - g-gaston
    - jweite-amazon
    - rohityadavcloud
    privacy: closed
    previously:
    - cluster-api-cloudstack-maintainers
    repos:
      cluster-api-provider-cloudstack: write
  cluster-api-provider-digitalocean-admins:
    description: Admin access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - luxas
    - timoreimann
    - timothysc
    privacy: closed
    repos:
      cluster-api-provider-digitalocean: admin
  cluster-api-provider-digitalocean-maintainers:
    description: Write access to the cluster-api-provider-digitalocean repo
    members:
    - cpanato
    - MorrisLaw
    - timoreimann
    - timothysc
    privacy: closed
    repos:
      cluster-api-provider-digitalocean: write
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - cpanato
    - dims
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-gcp: admin
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - cpanato
    - dims
    - richardcase
    privacy: closed
    repos:
      cluster-api-provider-gcp: write
  cluster-api-provider-kubemark-admins:
    description: admin access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-kubemark: admin
  cluster-api-provider-kubemark-maintainers:
    description: write access to cluster-api-provider-kubemark
    members:
    - benmoss
    - elmiko
    privacy: closed
    repos:
      cluster-api-provider-kubemark: write
  cluster-api-provider-kubevirt-admins:
    description: admin access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    - davidvossel
    - justinsb
    - neolit123
    - nunnatsa
    - timothysc
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-kubevirt: admin
  cluster-api-provider-kubevirt-maintainers:
    description: write access to cluster-api-provider-kubevirt
    members:
    - agradouski
    - cchengleo
    - davidvossel
    - nunnatsa
    privacy: closed
    repos:
      cluster-api-provider-kubevirt: write
  cluster-api-provider-nested-admins:
    description: admin access to cluster-api-provider-nested
    members:
    - christopherhein
    - fabriziopandini
    - Fei-Guo
    - justinsb
    - neolit123
    - timothysc
    - vincepri
    privacy: closed
    repos:
      cluster-api-provider-nested: admin
  cluster-api-provider-nested-maintainers:
    description: write access to cluster-api-provider-nested
    members:
    - christopherhein
    - Fei-Guo
    privacy: closed
    repos:
      cluster-api-provider-nested: write
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - jichenjc
    - lentzi90
    - mdbooth
    - seanschneeweiss
    - tobiasgiese
    privacy: closed
    repos:
      cluster-api-provider-openstack: admin
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - jichenjc
    - lentzi90
    - mdbooth
    - seanschneeweiss
    - tobiasgiese
    privacy: closed
    repos:
      cluster-api-provider-openstack: write
  cluster-api-provider-packet-admins:
    description: Admin access to cluster-api-provider-packet repo
    members:
    - cprivitere
    - deitch
    - detiber
    - displague
    privacy: closed
    repos:
      cluster-api-provider-packet: admin
  cluster-api-provider-packet-maintainers:
    description: Write access to the cluster-api-provider-packet repo
    members:
    - cprivitere
    - deitch
    - detiber
    - displague
    privacy: closed
    repos:
      cluster-api-provider-packet: write
  cluster-api-provider-vsphere-admins:
    description: Admin access to the cluster-api-provider-vsphere repo
    members:
    - chrischdi
    - fabriziopandini
    - gab-satchi
    - killianmuldoon
    - randomvariable
    - sbueringer
    - srm09
    - yastij
    privacy: closed
    repos:
      cluster-api-provider-vsphere: admin
  cluster-api-provider-vsphere-maintainers:
    description: Write access to the cluster-api-provider-vsphere repo
    members:
    - chrischdi
    - fabriziopandini
    - gab-satchi
    - killianmuldoon
    - randomvariable
    - sbueringer
    - srm09
    - yastij
    privacy: closed
    repos:
      cluster-api-provider-vsphere: write
  cluster-api-release-team:
    description: Release team of Cluster API
    members:
    # members added in commented lines have a pending membership
    # and will be added back once it is acquired.
    - adilGhaffarDev
    # - chandankumar4
    - chiukapoor
    # - dhij
    - hackeramitkumar
    - jayesh-srivastava
    # - kperath
    # - meatballhat
    # - Nivedita-coder
    - pravarag
    # - rajankumary2k
    # - shipra101
    # - smoshiur1237
    # - Sunnatillo
    - troy0820
    - vishalanarase
    - willie-yao
    privacy: closed
  etcdadm-admins:
    description: Admin access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
    repos:
      etcdadm: admin
  etcdadm-maintainers:
    description: Write access to the etcdadm repo
    members:
    - dlipovetsky
    - justinsb
    privacy: closed
    repos:
      etcdadm: write
  image-builder-admins:
    description: admin access to image-builder
    members:
    - AverageMarcus
    - drew-viles
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
    repos:
      image-builder: admin
  image-builder-maintainers:
    description: write access to image-builder
    members:
    - AverageMarcus
    - drew-viles
    - jsturtevant
    - kkeshavamurthy
    - mboersma
    privacy: closed
    repos:
      image-builder: write
  kubespray-admins:
    description: Admin access to the kubespray repo
    members:
    - ant31
    - chadswen
    - floryut
    privacy: closed
    repos:
      kubespray: admin
  kubespray-maintainers:
    description: Write access to the kubespray repo
    members:
    - ant31
    - chadswen
    - cristicalin
    - floryut
    - mzaian
    - oomichi
    - yankay
    privacy: closed
    repos:
      kubespray: write
  logical-cluster-admins:
    description: Admin access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
    repos:
      logical-cluster: admin
  logical-cluster-maintainers:
    description: Write access to the logical-cluster repo
    members:
    - fabriziopandini
    - vincepri
    privacy: closed
    repos:
      logical-cluster: write
  minikube-gui-admins:
    description: Admin access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
    repos:
      minikube-gui: admin
  minikube-gui-maintainers:
    description: Write access to the minikube-gui repo
    members:
    - medyagh
    - spowelljr
    privacy: closed
    repos:
      minikube-gui: write
