teams:
  addon-operators-admins:
    description: admin access to addon-operators
    members:
    - justinsb
    - luxas
    - roberthbailey
    - timothysc
    privacy: closed
  addon-operators-maintainers:
    description: write access to addon-operators
    members:
    - dholbach
    - justinsb
    - stealthybox
    privacy: closed
  bootkube-admins:
    description: admin access to bootkube repo
    members:
    - aaronlevy
    privacy: closed
  bootkube-maintainers:
    description: write access to bootkube repo
    members:
    - aaronlevy
    privacy: closed
  cluster-api-admins:
    description: ""
    members:
    - davidewatson
    - detiber
    - justinsb
    - luxas
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-maintainers:
    description: ""
    members:
    - chuckha
    - davidewatson
    - detiber
    - ncdc
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-bootstrap-provider-kubeadm-admins:
    descrption: admin acccess to cluster-api-bootstrap-provider-kubeadm
    members:
    - chuckha
    - justinsb
    - luxas
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-bootstrap-provider-kubeadm-maintainers:
    descrption: write acccess to cluster-api-bootstrap-provider-kubeadm
    members:
    - chuckha
    - detiber
    - justinsb
    - luxas
    - ncdc
    - SataQiu
    - timothysc
    privacy: closed
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - detiber
    - justinsb
    - luxas
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-aws-maintainers:
    description: write access to cluster-api-provider-aws
    members:
    - chuckha
    - davidewatson
    - detiber
    - ingvagabund
    - ncdc
    - randomvariable
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-digitalocean-admins:
    description: ""
    members:
    - luxas
    - roberthbailey
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-digitalocean-maintainers:
    description: ""
    maintainers:
    - nikhita
    members:
    - alvaroaleman
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-docker-admins:
    description: admin access to cluster-api-provider-docker repo
    members:
    - chuckha
    - justinsb
    - luxas
    - timothysc
    privacy: closed
  cluster-api-provider-docker-maintainers:
    description: write access to cluster-api-provider-docker repo
    members:
    - chuckha
    - justinsb
    - luxas
    - ncdc
    - timothysc
    privacy: closed
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - justinsb
    - luxas
    - roberthbailey
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - detiber
    - justinsb
    - krousey
    - maisem
    - vincepri
    privacy: closed
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - dims
    - luxas
    - roberthbailey
    - timothysc
    privacy: closed
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - chrigl
    - dims
    - jichenjc
    - sbueringer
    privacy: closed
  image-builder-admins:
    description: admin access to image-builder
    members:
    - justinsb
    - luxas
    - timothysc
    privacy: closed
  image-builder-maintainers:
    description: write access to image-builder
    members:
    - justinsb
    - luxas
    - moshloop
    - timothysc
    privacy: closed
