teams:
  addon-operators-admins:
    description: admin access to addon-operators
    members:
    - justinsb
    privacy: closed
  addon-operators-maintainers:
    description: write access to addon-operators
    members:
    - justinsb
    privacy: closed
  cluster-api-admins:
    description: ""
    members:
    - kris-nova
    - krousey
    - timothysc
    privacy: closed
  cluster-api-maintainers:
    description: ""
    members:
    - davidewatson
    - detiber
    - ncdc
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-aws-admins:
    description: admin access to cluster-api-provider-aws
    members:
    - detiber
    privacy: closed
  cluster-api-provider-aws-maintainers:
    description: write access to cluster-api-provider-aws
    members:
    - chuckha
    - davidewatson
    - detiber
    - ingvagabund
    - ncdc
    - randomvariable
    - timothysc
    - vincepri
    privacy: closed
  cluster-api-provider-digitalocean-admins:
    description: ""
    members:
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-digitalocean-maintainers:
    description: ""
    maintainers:
    - nikhita
    members:
    - alvaroaleman
    - timothysc
    - xmudrii
    privacy: closed
  cluster-api-provider-gcp-admins:
    description: admin access to cluster-api-provider-gcp
    members:
    - justinsb
    privacy: closed
  cluster-api-provider-gcp-maintainers:
    description: write access to cluster-api-provider-gcp-maintainers
    members:
    - justinsb
    privacy: closed
  cluster-api-provider-openstack-admins:
    description: admin access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - dims
    privacy: closed
  cluster-api-provider-openstack-maintainers:
    description: write access to cluster-api-provider-openstack
    members:
    - chaosaffe
    - dims
    privacy: closed
