teams:
  k8s.io-admins:
    description: Admin access to kubernetes/k8s.io
    members:
      - ameukam
      - GenPage
      - hakman
      - k8s-infra-ci-robot
      - upodroid
      - xmudrii
    privacy: closed
    repos:
      k8s.io: admin
  sig-k8s-infra:
    description: sig-k8s-infra members
    maintainers:
      - cblecker
      - nikhita
    members:
      - ameukam
      - GenPage
      - hakman
      - upodroid
      - xmudrii
    privacy: closed
    teams:
      sig-k8s-infra-leads:
        description: sig-k8s-infra chairs and technical leads
        members:
          - ameukam
          - GenPage
          - hakman
          - upodroid
          - xmudrii
        privacy: closed
      k8s-infra-gcp-org-admins:
        description: granted owner access to the k8s-infra GCP org
        members:
          - ameukam
          - GenPage
          - hakman
          - upodroid
          - xmudrii
        privacy: closed
      k8s-infra-group-admins:
        description: granted run access to kubernetes.io groups reconciler
        maintainers:
          - cblecker
        members:
          - ameukam
          - GenPage
          - hakman
          - upodroid
          - xmudrii
        privacy: closed
      sig-k8s-infra-dns-admins:
        description: sig-k8s-infra dns admins
        maintainers:
          - cblecker
        members:
          - BenTheElder
        privacy: closed
      registry.k8s.io-admins:
        description: Admin access to kubernetes/registry.k8s.io
        members:
          - ameukam
          - GenPage
          - hakman
          - upodroid
          - xmudrii
        privacy: closed
        repos:
          registry.k8s.io: admin
      registry.k8s.io-maintainers:
        description: Write access to kubernetes/registry.k8s.io
        members:
          - ameukam
          - GenPage
          - hakman
          - upodroid
          - xmudrii
        privacy: closed
        repos:
          registry.k8s.io: write
