teams:
  sig-cloud-provider:
    description: Parent Team for SIG Cloud Provider
    members:
    - andrewsykim
    - calebamiles
    - cheftako
    - hogepodge
    - jagosan
    - jhorwit2
    - justaugustus
    - mcrute
    - nckturner
    - Rajakavitha1
    - yastij
    privacy: closed
    teams:
      cloud-provider-sample-admins:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - cheftako
        - mcrute
        privacy: closed
      cloud-provider-sample-maintainers:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - cheftako
        - mcrute
        privacy: closed
      sig-cloud-provider-alibaba-admins:
        description: ""
        members:
        - aoxn
        - cheyang
        - gujingit
        - xlgao-zju
        privacy: closed
      sig-cloud-provider-aws-admins:
        description: "Admin access to k8s.io/cloud-provider-aws"
        members:
        - andrewsykim
        - justinsb
        - nckturner
        privacy: closed
      sig-cloud-provider-aws-maintainers:
        description: "Write access to k8s.io/cloud-provider-aws"
        members:
        - andrewsykim
        - justinsb
        - nckturner
        privacy: closed
      sig-cloud-provider-api-reviews:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
      sig-cloud-provider-bugs:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
      sig-cloud-provider-feature-requests:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
      sig-cloud-provider-misc:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
      sig-cloud-provider-pr-reviews:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        - nckturner
        - Rajakavitha1
        privacy: closed
      sig-cloud-provider-proposals:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
      sig-cloud-provider-test-failures:
        description: ""
        members:
        - andrewsykim
        - calebamiles
        - hogepodge
        - jagosan
        privacy: closed
  sig-cloud-provider-admins:
    description: ""
    members:
    - andrewsykim
    - calebamiles
    privacy: closed
