teams:
  boskos-admins:
    description: admin access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: admin
  boskos-maintainers:
    description: write access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: write
  cloud-provider-kind-admins:
    description: Admin access to the cloud-provider-kind repo
    members:
    - aojea
    - BenTheElder
    privacy: closed
    repos:
      cloud-provider-kind: admin
  cloud-provider-kind-maintainers:
    description: Write access to the cloud-provider-kind repo
    members:
    - aojea
    - BenTheElder
    privacy: closed
    repos:
      cloud-provider-kind: write
  e2e-framework-admins:
    description: admin access to e2e-framework
    members:
    - cpanato
    - harshanarayana
    - ShwethaKumbla
    - vladimirvivien
    privacy: closed
    repos:
      e2e-framework: admin
  e2e-framework-maintainers:
    description: write access to e2e-framework
    members:
    - cpanato
    - harshanarayana
    - ShwethaKumbla
    - vladimirvivien
    privacy: closed
    repos:
      e2e-framework: write
  hydrophone-admins:
    description: admin access to hydrophone
    members:
    - dims
    - rjsadow
    privacy: closed
    repos:
      hydrophone: admin
  hydrophone-maintainers:
    description: write access to hydrophone
    members:
    - dims
    - rjsadow
    privacy: closed
    repos:
      hydrophone: write
  kind-admins:
    description: Admin access to the kind repo
    members:
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: admin
  kind-maintainers:
    description: Write access to the kind repo
    members:
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: write
  kubetest2-admins:
    description: Admin access to kubetest2
    members:
    - MushuEE
    privacy: closed
    repos:
      kubetest2: admin
  kubetest2-maintainers:
    description: Write access to kubetest2
    members:
    - MushuEE
    privacy: closed
    repos:
      kubetest2: write
  prow-admins:
    description: Admin access to prow
    maintainers:
    - cblecker
    members:
    - alvaroaleman
    - cjwagner
    - petr-muller
    - stevekuznetsov
    privacy: closed
    repos:
      prow: admin
  prow-maintainers:
    description: Write access to prow
    maintainers:
    - cblecker
    members:
    - alvaroaleman
    - cjwagner
    - petr-muller
    - stevekuznetsov
    privacy: closed
    repos:
      prow: write
  testgrid-admins:
    description: Admin access to testgrid
    members:
    - chases2
    - michelle192837
    privacy: closed
    repos:
      testgrid: admin
  testgrid-maintainers:
    description: Write access to testgrid
    members:
    - chases2
    - michelle192837
    privacy: closed
    repos:
      testgrid: write
