teams:
  boskos-admins:
    description: admin access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: admin
  boskos-maintainers:
    description: write access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: write
  cloud-provider-kind-admins:
    description: Admin access to the cloud-provider-kind repo
    members:
    - aojea
    - BenTheElder
    privacy: closed
    repos:
      cloud-provider-kind: admin
  cloud-provider-kind-maintainers:
    description: Write access to the cloud-provider-kind repo
    members:
    - aojea
    - BenTheElder
    privacy: closed
    repos:
      cloud-provider-kind: write
  e2e-framework-admins:
    description: admin access to e2e-framework
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    - spiffxp
    - vladimirvivien
    privacy: closed
    repos:
      e2e-framework: admin
  e2e-framework-maintainers:
    description: write access to e2e-framework
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    - spiffxp
    privacy: closed
    repos:
      e2e-framework: write
  kind-admins:
    description: Admin access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: admin
  kind-maintainers:
    description: Write access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: write
  kubetest2-admins:
    description: Admin access to kubetest2
    members:
    - MushuEE
    - spiffxp
    privacy: closed
    repos:
      kubetest2: admin
  kubetest2-maintainers:
    description: Write access to kubetest2
    members:
    - MushuEE
    - spiffxp
    privacy: closed
    repos:
      kubetest2: write
  prow-admins:
    description: Admin access to prow
    maintainers:
    - cblecker
    members:
    - alvaroaleman
    - cjwagner
    - fejta
    - petr-muller
    - stevekuznetsov
    privacy: closed
    repos:
      prow: admin
  prow-maintainers:
    description: Write access to prow
    maintainers:
    - cblecker
    members:
    - alvaroaleman
    - cjwagner
    - fejta
    - petr-muller
    - stevekuznetsov
    privacy: closed
    repos:
      prow: write
