teams:
  boskos-admins:
    description: admin access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
  boskos-maintainers:
    description: write access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
  e2e-framework-admins:
    description: admin access to e2e-framework
    maintainers:
    - spiffxp
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    - vladimirvivien
    privacy: closed
  e2e-framework-maintainers:
    description: write access to e2e-framework
    maintainers:
    - spiffxp
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    privacy: closed
  kind-admins:
    description: Admin access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
  kind-maintainers:
    description: Write access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
  kubetest2-admins:
    description: Admin access to kubetest2
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    privacy: closed
  kubetest2-maintainers:
    description: Write access to kubetest2
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    privacy: closed
  k8s-gsm-tools-admins:
    description: Admin access to k8s-gsm-tools
    maintainers:
    - spiffxp
    members:
    - BenTheElder
    privacy: closed
    previously:
    - secret-sync-rotation-admins
  k8s-gsm-tools-maintainers:
    description: Write access to k8s-gsm-tools
    maintainers:
    - spiffxp
    members:
    - BenTheElder
    privacy: closed
    previously:
    - secret-sync-rotation-maintainers
