teams:
  kompose-admins:
    description: Admin access to the kompose repo
    members:
    - cdrage
    - janetkuo
    - kadel
    - TessaIO
    privacy: closed
    repos:
      kompose: admin
  kompose-maintainers:
    description: Write access to the kompose repo
    members:
    - cdrage
    - janetkuo
    - kadel
    - TessaIO
    privacy: closed
    repos:
      kompose: write
  sig-apps-api-reviews:
    description: ""
    members:
    - davidopp
    - dixudx
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    - zouyee
    privacy: closed
  sig-apps-bugs:
    description: ""
    members:
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-feature-requests:
    description: ""
    members:
    - ant31
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-misc:
    description: Use only if you can't figure out a better category
    members:
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-pr-reviews:
    description: ""
    members:
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-proposals:
    description: ""
    members:
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-test-failures:
    description: ""
    members:
    - davidopp
    - enisoc
    - janetkuo
    - kow3ns
    - mfojtik
    - mimowo
    - smarterclayton
    - soltysh
    privacy: closed
  sig-apps-leads:
    description: ""
    members:
    - janetkuo
    - kow3ns
    - soltysh
    privacy: closed
