teams:
  about-api-admins:
    description: admin access for the about-api repo
    members:
    - jeremyot
    - pmorie
    privacy: closed
    repos:
      about-api: admin
  federation-wg:
    description: Individuals who are part of sig-multicluster and working as federation
      workgroup.
    members:
    - font
    - gyliu513
    - hectorj2f
    - irfanurrehman
    - jimmidyson
    - onyiny-ang
    - pmorie
    - quinton-hoole
    - shashidharatd
    privacy: closed
  mcs-api-admins:
    description: Admin access to the mcs-api repo
    members:
    - JeremyOT
    - pmorie
    privacy: closed
    repos:
      mcs-api: admin
  sig-multicluster-site-admins:
    description: Admin access to the sig-multicluster-site repo
    members:
    - jeremyot
    - lauralorenz
    - pmorie
    privacy: closed
    repos:
      sig-multicluster-site: admin
  sig-multicluster-site-maintainers:
    description: Write access to the sig-multicluster-site repo
    members:
    - jeremyot
    - lauralorenz
    - pmorie
    privacy: closed
    repos:
      sig-multicluster-site: write
  work-api-admins:
    description: Admin access for the work-api repo
    members:
    - jeremyot
    - pmorie
    privacy: closed
    repos:
      work-api: admin
