teams:
  about-api-admins:
    description: admin access for the about-api repo
    members:
    - jeremyot
    - pmorie
    privacy: closed
  kubefed-admins:
    description: admin access for the kubefed repo
    members:
    - font
    - hectorj2f
    - irfanurrehman
    - jimmidyson
    - pmorie
    - shashidharatd
    privacy: closed
    previously:
    - federation-v2-admins
  kubefed-maintainers:
    description: write access to the kubefed repo
    members:
    - font
    - hectorj2f
    - irfanurrehman
    - jimmidyson
    - shashidharatd
    privacy: closed
    previously:
    - federation-v2-maintainers
  federation-wg:
    description: Individuals who are part of sig-multicluster and working as federation
      workgroup.
    members:
    - font
    - gyliu513
    - hectorj2f
    - irfanurrehman
    - jimmidyson
    - onyiny-ang
    - pmorie
    - quinton-hoole
    - shashidharatd
    privacy: closed
  mcs-api-admins:
    description: Admin access to the mcs-api repo
    members:
    - JeremyOT
    - pmorie
    privacy: closed
  work-api-admins:
    description: Admin access for the work-api repo
    members:
    - jeremyot
    - pmorie
    privacy: closed
