teams:
  sig-node-api-reviews:
    description: API Reviews for Kubernetes Node Special-Interest-Group
    members:
    - ConnorDoyle
    - davidopp
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - resouer
    - tallclair
    - vikaschoudhary16
    - vishh
    - yujuhong
    privacy: closed
  sig-node-bugs:
    description: Bugs for Kubernetes Node Special-Interest-Group
    members:
    - ConnorDoyle
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - resouer
    - tallclair
    - vikaschoudhary16
    - vishh
    - yguo0905
    - yujuhong
    privacy: closed
  sig-node-feature-requests:
    description: Feature Requests for Kubernetes Node Special-Interest-Group
    members:
    - ConnorDoyle
    - davidopp
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - Random-Liu
    - resouer
    - smarterclayton
    - tallclair
    - vikaschoudhary16
    - vishh
    - yguo0905
    - yujuhong
    privacy: closed
  sig-node-pr-reviews:
    description: PR Reviews for Kubernetes Node Special-Interest-Group
    members:
    - ConnorDoyle
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - resouer
    - tallclair
    - vikaschoudhary16
    - vishh
    - yujuhong
    privacy: closed
  sig-node-proposals:
    description: Proposals for Kubernetes Node Special-Interest-Group
    members:
    - ConnorDoyle
    - dashpole
    - davidopp
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - mtaufen
    - Random-Liu
    - resouer
    - smarterclayton
    - tallclair
    - vikaschoudhary16
    - vishh
    - yujuhong
    privacy: closed
  sig-node-test-failures:
    description: Test Failures for Kubernetes Node Special-Interest-Group
    members:
    - alejandrox1
    - bobbypage
    - bsdnet
    - ConnorDoyle
    - dashpole
    - dchen1107
    - derekwaynecarr
    - feiskyer
    - karan
    - MHBauer
    - mtaufen
    - Random-Liu
    - resouer
    - sjenning
    - tallclair
    - vikaschoudhary16
    - vishh
    - vpickard
    - yguo0905
    - yujuhong
    privacy: closed
