teams:
  sig-node-api-reviews:
    description: API Reviews for Kubernetes Node Special-Interest-Group
    members:
    - dchen1107
    - derekwaynecarr
    - smarterclayton
    - tallclair
    - thockin
    - yujuhong
    privacy: closed
  sig-node-leads:
    description: Chairs and Technical Leads for SIG Node
    members:
    - dchen1107
    - derekwaynecarr
    - mrunalp
    - SergeyKanzhelev
    privacy: closed
  sig-node-bugs:
    description: Bugs for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    - yujuhong
    privacy: closed
  sig-node-feature-requests:
    description: Feature Requests for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    - yujuhong
    privacy: closed
  sig-node-pr-reviews:
    description: PR Reviews for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    - yujuhong
    privacy: closed
  sig-node-proposals:
    description: Proposals for Kubernetes Node Special-Interest-Group
    members:
    - andrewsykim
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - dims
    - endocrimes
    - feiskyer
    - harche
    - klueska
    - krmayankk
    - matthyx
    - mrunalp
    - mtaufen
    - odinuge
    - pacoxu
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - wzshiming
    - yujuhong
    privacy: closed
  sig-node-test-failures:
    description: Test Failures for Kubernetes Node Special-Interest-Group
    members:
    - bart0sh
    - bobbypage
    - dchen1107
    - derekwaynecarr
    - endocrimes
    - harche
    - klueska
    - mrunalp
    - Random-Liu
    - saschagrunert
    - SergeyKanzhelev
    - sjenning
    - yujuhong
    privacy: closed
