teams:
  sig-scheduling-api-reviews:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - resouer
    - rrati
    - SrinivasChilveri
    - timothysc
    - vishh
    - xiang90
    privacy: closed
  sig-scheduling-bugs:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - ravisantoshgudimetla
    - resouer
    - rrati
    - SrinivasChilveri
    - timothysc
    - vikaschoudhary16
    - vishh
    - wanghaoran1988
    - xiang90
    privacy: closed
  sig-scheduling-feature-requests:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - ravisantoshgudimetla
    - resouer
    - rrati
    - smarterclayton
    - SrinivasChilveri
    - timothysc
    - vikaschoudhary16
    - vishh
    - xiang90
    - yastij
    privacy: closed
  sig-scheduling-misc:
    description: Scheduling algorithms, scheduling/scheduler architecture and extensibility,
      rescheduling/continuous re-optimization, cluster-level resource allocation and
      resource management
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - ravisantoshgudimetla
    - resouer
    - rrati
    - smarterclayton
    - SrinivasChilveri
    - timothysc
    - wanghaoran1988
    - xiang90
    privacy: closed
  sig-scheduling-pr-reviews:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - ravisantoshgudimetla
    - resouer
    - rrati
    - SrinivasChilveri
    - timothysc
    - vikaschoudhary16
    - vishh
    - wanghaoran1988
    - xiang90
    - yastij
    privacy: closed
  sig-scheduling-proposals:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - resouer
    - rrati
    - smarterclayton
    - SrinivasChilveri
    - timothysc
    - vikaschoudhary16
    - vishh
    - xiang90
    privacy: closed
  sig-scheduling-test-failures:
    description: ""
    members:
    - aveshagarwal
    - balajismaniam
    - bsalamat
    - ConnorDoyle
    - davidopp
    - derekwaynecarr
    - gyliu513
    - hongchaodeng
    - ingvagabund
    - jayunit100
    - k82cn
    - kevin-wangzefeng
    - pigmej
    - quinton-hoole
    - ravisantoshgudimetla
    - resouer
    - rrati
    - SrinivasChilveri
    - timothysc
    - xiang90
    privacy: closed
