teams:
  sig-scheduling-misc:
    description: Scheduling algorithms, scheduling/scheduler architecture and extensibility,
      rescheduling/continuous re-optimization, cluster-level resource allocation and
      resource management
    members:
    - ahg-g
    - alculquicondor
    - AxeZhan
    - damemi
    - denkensk
    - dom4ha
    - Huang-Wei
    - kerthcet
    - macsko
    - sanposhiho
    privacy: closed
  sig-scheduling-approvers:
    description: ""
    members:
    - ahg-g
    - alculquicondor
    - Huang-Wei
    - kerthcet
    - sanposhiho
    privacy: closed
  sig-scheduling-leads:
    description: ""
    members:
    - ahg-g
    - alculquicondor
    - Huang-Wei
    privacy: closed
