teams:
  sig-scalability:
    description: SIG Scalability
    members:
    - alejandrox1 # SIG Release Technical Lead
    - hasheddan # 1.19 CI Signal Lead / Release Manager
    - jkaniuk
    - jprzychodzen
    - justaugustus # SIG Release Chair / Release Manager
    - krzysied
    - mborsz
    - mm4tt
    - onlydole # 1.19 Release Team Lead
    - oxddr
    - saschagrunert # SIG Release Technical Lead / Release Manager
    - shyamjvs
    - tosi3k
    - tpepper # SIG Release Chair / Release Manager
    - wojtek-t
    privacy: closed
    teams:
      sig-scalability-leads:
        description: Chairs and Technical Leads for SIG Scalability
        members:
        - mm4tt
        - shyamjvs
        - wojtek-t
        privacy: closed
      sig-scalability-pr-reviews:
        description: PR reviews for SIG Scalability
        members:
        - jkaniuk
        - jprzychodzen
        - mborsz
        - mm4tt
        - shyamjvs
        - tosi3k
        - wojtek-t
        privacy: closed
