name: Kubernetes Nightly
description: Org for Kubernetes publishing-bot work
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- cpanato
- dims
- jasonbraganza
- jeremyrickard
- justaugustus
- k8s-ci-robot
- k8s-github-robot
- MadhavJivrajani
- mrbobbytables
- nikhita
- palnabarun
- Priyankasaggu11929
- puerco
- saschagrunert
- sttts
- thelinuxfoundation
members:
- ameukam
- idvoretskyi
- k8s-publishing-bot
- savitharaghunathan
- Verolop
- xmudrii
teams:
  bots:
    description: Bot service accounts in the kubernetes-nightly org
    maintainers:
    - k8s-ci-robot
    - k8s-github-robot
    - thelinuxfoundation
    members:
    - k8s-publishing-bot
    privacy: closed
