teams:
  etcd-admins:
    description: Admin access to etcd repo
    members:
    - ahrtr
    - fuweid
    - jmhbnz
    - serathius
    - siyuanfoundation
    - spzala
    privacy: closed
    repos:
      etcd: admin
  etcd-operator-admins:
    description: Admin access to etcd-operator repo
    members:
    - ahrtr
    - hakman
    - jberkus
    - jmhbnz
    - justinsb
    privacy: closed
    repos:
      etcd-operator: admin
  etcd-operator-maintainers:
    description: Write access to etcd-operator repo
    members:
    - ahrtr
    - hakman
    - ivanvc
    - jberkus
    - jmhbnz
    - justinsb
    privacy: closed
    repos:
      etcd-operator: write
  maintainers-auger:
    description: Granted write access to auger
    members:
    - jmhbnz
    - siyuanfoundation
    - wenjiaswe
    privacy: closed
    repos:
      auger: admin
  maintainers-bbolt:
    description: Granted write access to bbolt
    members:
    - ahrtr
    - serathius
    privacy: closed
    repos:
      bbolt: maintain
  maintainers-discovery:
    description: discovery.etcd.io maintainers
    members:
    - eduartua
    - idvoretskyi
    - victortrac
    privacy: closed
    repos:
      discovery.etcd.io: maintain
      discoveryserver: maintain
  maintainers-etcd:
    description: Granted write access to etcd
    members:
    - ahrtr
    - fuweid
    - jmhbnz
    - serathius
    - siyuanfoundation
    - spzala
    privacy: closed
    repos:
      dbtester: maintain
      etcd: maintain
      gofail: maintain
  maintainers-jetcd:
    description: Granted write access to jetcd
    members:
    - lburgazzoli
    - vorburger
    privacy: closed
    repos:
      jetcd: maintain
  maintainers-raft:
    description: raft maintainers
    members:
    - ahrtr
    - serathius
    - spzala
    privacy: closed
    repos:
      raft: maintain
  maintainers-website:
    description: Granted write access to website
    members:
    - ahrtr
    - chalin
    - ivanvc
    - jberkus
    - jmhbnz
    - nate-double-u
    - serathius
    - siyuanfoundation
    - spzala
    privacy: closed
    repos:
      website: admin
      protodoc: admin
  maintainers-labs:
    description: Granted write access to etcdlabs
    members:
    - ahrtr
    - jmhbnz
    - serathius
    - siyuanfoundation
    - spzala
    privacy: closed
    repos:
      etcdlabs: admin
  members:
    description: ""
    members:
    - ArkaSaha30
    - chaochn47
    - elbehery
    - fuweid
    - ghouscht
    - henrybear327
    - hwdef
    - ivanvc
    - jmhbnz
    - joshjms
    - lavacat
    - logicalhan
    - moficodes
    - pav-kv
    - siyuanfoundation
    - thedtripp
    - tjungblu
    privacy: closed
    repos:
      bbolt: triage
      dbtester: triage
      etcd: triage
      etcd-operator: triage
      gofail: triage
      raft: triage
      website: triage
    teams:
      reviewers-etcd:
        description: ""
        members:
        - fuweid
        - ivanvc
        - jmhbnz
        - siyuanfoundation
        privacy: closed
        repos:
          auger: triage
          bbolt: triage
          dbtester: triage
          etcd: triage
          gofail: triage
          raft: triage
          website: triage
  release-etcd:
    description: Granted permission to release etcd-io/etcd
    # The member list is intentionally empty. It should only include the release
    # lead during release windows.
    members:
    - ivanvc
    - joshjms
    privacy: closed
    repos:
      etcd: maintain
